# KBStats last-five average points × odds × lineup score

Creates an optimizer-ready full KBStats score file from the newest matchday-qualified last-five-average-points analysis, expected match points from odds, configurable-weight LigaInsider, Kickbase, Kicker, and RotoWire starting chances, and geometric alternative decay for LigaInsider/Kickbase/Kicker slots. Kickbase and Kicker display labels resolve automatically to a unique same-team KBStats last name, then first name; shared-name or no-match candidates are prompted only at 50% similarity or higher and persist to `data/reference/kickbase_player_name_cross_references.csv` with a provider scope. A Kickbase label therefore cannot override a Kicker label for the same player, or vice versa. The last-five average already excludes unplayed slots from its denominator. Players not present in the qualified analysis receive a metric and score of zero; valid negative KBStats averages are retained and can yield negative scores.

In [1]:
import importlib
import sys
from pathlib import Path

QUESTIONABLE_INJURY_STARTING_CHANCE_PENALTY = 0.15
# Each rank is 45% of the preceding alternative before its slot is normalized.
ALTERNATIVE_STARTING_CHANCE_DECAY = 0.45
# Relative trust weights for active lineup sources; use 0 to disable one.
LINEUP_SOURCE_WEIGHTS = {'ligainsider': 4.0, 'kickbase': 3.0, 'kicker': 2.0, 'rotowire': 1.0}
# You will confirm whether each source is current for the selected matchday.


def locate_project_root() -> Path:
    starts = [Path.cwd().resolve()]
    notebook_path = globals().get('__vsc_ipynb_file__')
    if isinstance(notebook_path, str) and notebook_path.strip():
        starts.insert(0, Path(notebook_path).expanduser().resolve().parent)
    for start in starts:
        for candidate in (start, *start.parents):
            if (candidate / 'project_paths.py').is_file():
                return candidate
    raise FileNotFoundError('Could not locate project_paths.py.')


PROJECT_ROOT = locate_project_root()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import kbstats_points_odds_lineup_score

kbstats_points_odds_lineup_score = importlib.reload(
    kbstats_points_odds_lineup_score
)

result = kbstats_points_odds_lineup_score.run_score_creation(
    'last5_average',
    questionable_injury_starting_chance_penalty=QUESTIONABLE_INJURY_STARTING_CHANCE_PENALTY,
    alternative_starting_chance_decay=ALTERNATIVE_STARTING_CHANCE_DECAY,
    lineup_source_weights=LINEUP_SOURCE_WEIGHTS,
)

Matchday for odds and lineups:  1

No exact match for rotowire lineup for Marco Grüll (bremen)
  1. Marco Friedl (ID 23443, similarity 67%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Joël Schmied (koeln)
  1. Waldschmidt (displayed name, similarity 64%)
  2. SCHWÄBE (displayed name, similarity 44%)
  3. ACHE (displayed name, similarity 40%)
  4. JÓHANNESSON (displayed name, similarity 36%)
  5. LOCHOSHVILI (displayed name, similarity 36%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Kim Minjae (bayern)
  1. KIMMICH (displayed name, similarity 62%)
  2. KANE (displayed name, similarity 46%)
  3. LAIMER (displayed name, similarity 40%)
  4. DÍAZ (displayed name, similarity 31%)
  5. NEUER (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Daniel Elfadli (hamburg)
  1. Daniel Heuer Fernandes (ID 6379, similarity 61%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Daniel Elfadli (hamburg)
  1. Daniel Heuer Fernandes (ID 21877, similarity 61%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Kevin Stöger (gladbach)
  1. Kevin Diks (ID 21650, similarity 60%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Mads Pedersen (augsburg)
  1. MASSENGO (displayed name, similarity 60%)
  2. RIEDER (displayed name, similarity 44%)
  3. BEHRENS (displayed name, similarity 42%)
  4. KADE (displayed name, similarity 38%)
  5. DAHMEN (displayed name, similarity 33%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Nico Elvedi (gladbach)
  1. NICOLAS (displayed name, similarity 59%)
  2. Leopold (displayed name, similarity 35%)
  3. DIKS (displayed name, similarity 29%)
  4. KLEINDIENST (displayed name, similarity 29%)
  5. SANDER (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Tim Lemperle (hoffenheim)
  1. Wimmer (displayed name, similarity 59%)
  2. Moerstedt (displayed name, similarity 40%)
  3. CONTÉ (displayed name, similarity 25%)
  4. Prass (displayed name, similarity 25%)
  5. BURGER (displayed name, similarity 24%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Oliver Burke (union)
  1. Livan Burcu (ID 36114, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Oliver Burke (union)
  1. Livan Burcu (ID 43803, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Marius Bülter (koeln)
  1. Marvin Schwabe (ID 34845, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Christian Günter (freiburg)
  1. Matthias Ginter (ID 17592, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Salim Amani Musah (bremen)
  1. Samuel Mbangula (ID 38382, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Said El Mala (koeln)
  1. Jan Thielmann (ID 30688, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Frederik Rönnow (union)
  1. Derrick Koehn (ID 14385, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Joël Schmied (koeln)
  1. Luca Waldschmidt (ID 2594, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Joël Schmied (koeln)
  1. Luca Waldschmidt (ID 19652, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Frederik Rönnow (union)
  1. Rønnow (displayed name, similarity 53%)
  2. Friedrich (displayed name, similarity 52%)
  3. KEMLEIN (displayed name, similarity 38%)
  4. Jeong (displayed name, similarity 32%)
  5. KHEDIRA (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Paul Nebel (mainz)
  1. Jaesung Lee (ID 21202, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Sander Tangvik (hamburg)
  1. Stange (displayed name, similarity 53%)
  2. ADELINE (displayed name, similarity 40%)
  3. JATTA (displayed name, similarity 33%)
  4. OMARI (displayed name, similarity 33%)
  5. SAMBI LOKONGA (displayed name, similarity 32%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Danny Da Costa (mainz)
  1. Anthony Caci (ID 25792, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Janik Haberer (union)
  1. Rani Khedira (ID 2122, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Jovan Milosevic (stuttgart)
  1. Demirović (displayed name, similarity 52%)
  2. Pejčinović (displayed name, similarity 42%)
  3. JELTSCH (displayed name, similarity 38%)
  4. El Khannouss (displayed name, similarity 32%)
  5. MITTELSTÄDT (displayed name, similarity 32%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jovan Milosevic (stuttgart)
  1. Jamie Leweling (ID 21336, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Jovan Milosevic (stuttgart)
  1. Jamie Leweling (ID 35268, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Ramy Bensebaini (dortmund)
  1. Samuele Inacio (ID 47795, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Adam Daghim (hoffenheim)
  1. Adam Hlozek (ID 33675, similarity 50%)
  2. Andrej Kramaric (ID 18613, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Andrej Kramarić (hoffenheim)
  1. Adam Daghim (ID 37622, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Chema Andrés (stuttgart)
  1. Ramon Hendriks (ID 23957, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Chema Andrés (stuttgart)
  1. Ramon Hendriks (ID 29953, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Cyriaque Irié (freiburg)
  1. Christian Guenter (ID 2153, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Derrick Köhn (union)
  1. Friedrich (displayed name, similarity 50%)
  2. Jeong (displayed name, similarity 38%)
  3. VAN DEN BOSCH (displayed name, similarity 36%)
  4. KEMLEIN (displayed name, similarity 33%)
  5. JURANOVIĆ (displayed name, similarity 30%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Eren Sami Dinkçi (bremen)
  1. Erebenagie (displayed name, similarity 50%)
  2. HEIN (displayed name, similarity 33%)
  3. Reis (displayed name, similarity 33%)
  4. SCHMETGENS (displayed name, similarity 33%)
  5. NJINMAH (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jamal Musiala (bayern)
  1. Luis Diaz (ID 22566, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Janis Blaswich (leverkusen)
  1. QUANSAH (displayed name, similarity 50%)
  2. TAPSOBA (displayed name, similarity 40%)
  3. Palacios (displayed name, similarity 38%)
  4. GARCÍA (displayed name, similarity 32%)
  5. SCHICK (displayed name, similarity 32%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Montrell Culbreath (leverkusen)
  1. MOREIRA (displayed name, similarity 50%)
  2. Tella (displayed name, similarity 45%)
  3. GARCÍA (displayed name, similarity 26%)
  4. Kofane (displayed name, similarity 26%)
  5. Medina (displayed name, similarity 26%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Niklas Stark (bremen)
  1. Jens Stage (ID 22538, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Niklas Stark (bremen)
  1. Jens Stage (ID 30066, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Paul Nebel (mainz)
  1. LEE (displayed name, similarity 50%)
  2. GRUBER (displayed name, similarity 40%)
  3. SANO (displayed name, similarity 31%)
  4. MWENE (displayed name, similarity 29%)
  5. BECKER (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Tim Lemperle (hoffenheim)
  1. Patrick Wimmer (ID 26236, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Andrej Ilic (union)
  1. VAN DEN BOSCH (displayed name, similarity 48%)
  2. Friedrich (displayed name, similarity 42%)
  3. JURANOVIĆ (displayed name, similarity 42%)
  4. LATTE LATH (displayed name, similarity 32%)
  5. ANSAH (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Andrej Kramarić (hoffenheim)
  1. HAJDARI (displayed name, similarity 48%)
  2. BURGER (displayed name, similarity 30%)
  3. Asllani (displayed name, similarity 29%)
  4. Bernardo (displayed name, similarity 27%)
  5. AVDULLAHU (displayed name, similarity 26%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Daniel Batz (gladbach)
  1. NICOLAS (displayed name, similarity 47%)
  2. KLEINDIENST (displayed name, similarity 38%)
  3. SANDER (displayed name, similarity 38%)
  4. HONORAT (displayed name, similarity 35%)
  5. HASHIOKA (displayed name, similarity 33%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Love Arrhov (frankfurt)
  1. LARSSON (displayed name, similarity 47%)
  2. ONYEDIKA (displayed name, similarity 33%)
  3. DOAN (displayed name, similarity 29%)
  4. KOCH (displayed name, similarity 29%)
  5. THEATE (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Malik Tillman (leverkusen)
  1. Tella (displayed name, similarity 47%)
  2. MAZA (displayed name, similarity 38%)
  3. GARCÍA (displayed name, similarity 33%)
  4. Kofane (displayed name, similarity 33%)
  5. FLEKKEN (displayed name, similarity 32%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Samuele Inácio (dortmund)
  1. KONSTANTELIAS (displayed name, similarity 46%)
  2. BENSEBAINI (displayed name, similarity 43%)
  3. Svensson (displayed name, similarity 38%)
  4. ANTON (displayed name, similarity 33%)
  5. Sabitzer (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Robert Andrich (leverkusen)
  1. FERNÁNDEZ (displayed name, similarity 45%)
  2. MOREIRA (displayed name, similarity 40%)
  3. Kofane (displayed name, similarity 32%)
  4. QUANSAH (displayed name, similarity 30%)
  5. TAPSOBA (displayed name, similarity 30%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Jens Castrop (gladbach)
  1. NICOLAS (displayed name, similarity 44%)
  2. KLEINDIENST (displayed name, similarity 36%)
  3. STÖGER (displayed name, similarity 35%)
  4. HONORAT (displayed name, similarity 33%)
  5. Leopold (displayed name, similarity 33%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Jonas Hofmann (leverkusen)
  1. Kofane (displayed name, similarity 44%)
  2. FERNÁNDEZ (displayed name, similarity 29%)
  3. MAZA (displayed name, similarity 25%)
  4. GARCÍA (displayed name, similarity 22%)
  5. Medina (displayed name, similarity 22%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Maximilian Wöber (schalke)
  1. Schallenberg (displayed name, similarity 44%)
  2. DINA EBIMBE (displayed name, similarity 40%)
  3. Ayhan (displayed name, similarity 30%)
  4. KARAMAN (displayed name, similarity 27%)
  5. T. BECKER (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Carney Chukwuemeka (dortmund)
  1. NMECHA (displayed name, similarity 43%)
  2. KARETSAS (displayed name, similarity 32%)
  3. KONSTANTELIAS (displayed name, similarity 27%)
  4. ANTON (displayed name, similarity 18%)
  5. GADOU (displayed name, similarity 18%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Dmytro Bogdanov (union)
  1. JURANOVIĆ (displayed name, similarity 43%)
  2. Rønnow (displayed name, similarity 32%)
  3. KHEDIRA (displayed name, similarity 29%)
  4. VAN DEN BOSCH (displayed name, similarity 24%)
  5. RAAB (displayed name, similarity 22%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Josha Vagnoman (stuttgart)
  1. Tiago Tomás (displayed name, similarity 43%)
  2. El Khannouss (displayed name, similarity 33%)
  3. CHABOT (displayed name, similarity 32%)
  4. JELTSCH (displayed name, similarity 30%)
  5. Pejčinović (displayed name, similarity 26%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Stanley Nsoki (union)
  1. VAN DEN BOSCH (displayed name, similarity 43%)
  2. JURANOVIĆ (displayed name, similarity 38%)
  3. ANSAH (displayed name, similarity 35%)
  4. Rønnow (displayed name, similarity 35%)
  5. KEMLEIN (displayed name, similarity 32%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Janik Haberer (union)
  1. SCHÄFER (displayed name, similarity 42%)
  2. JURANOVIĆ (displayed name, similarity 38%)
  3. RAAB (displayed name, similarity 38%)
  4. ANSAH (displayed name, similarity 35%)
  5. KHEDIRA (displayed name, similarity 32%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Lucas Höler (freiburg)
  1. Scherhant (displayed name, similarity 42%)
  2. Günter (displayed name, similarity 38%)
  3. LIENHART (displayed name, similarity 33%)
  4. ENGELHARDT (displayed name, similarity 30%)
  5. BESTE (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Noah Atubolu (freiburg)
  1. BACKHAUS (displayed name, similarity 42%)
  2. LIENHART (displayed name, similarity 42%)
  3. ENGELHARDT (displayed name, similarity 38%)
  4. Scherhant (displayed name, similarity 30%)
  5. TREU (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Shuto Machino (gladbach)
  1. HONORAT (displayed name, similarity 42%)
  2. HASHIOKA (displayed name, similarity 40%)
  3. Hack (displayed name, similarity 38%)
  4. BOLIN (displayed name, similarity 35%)
  5. SANDER (displayed name, similarity 33%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Badredine Bouanani (stuttgart)
  1. BREDLOW (displayed name, similarity 42%)
  2. Pejčinović (displayed name, similarity 37%)
  3. Andrés (displayed name, similarity 35%)
  4. El Khannouss (displayed name, similarity 29%)
  5. CHABOT (displayed name, similarity 26%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Arijon Ibrahimović (bayern)
  1. PAVLOVIĆ (displayed name, similarity 40%)
  2. Stanišić (displayed name, similarity 40%)
  3. KIMMICH (displayed name, similarity 33%)
  4. BROWN (displayed name, similarity 27%)
  5. Davies (displayed name, similarity 26%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Daniel Elfadli (hamburg)
  1. ADELINE (displayed name, similarity 40%)
  2. DAKA (displayed name, similarity 35%)
  3. Stange (displayed name, similarity 32%)
  4. TORUNARIGHA (displayed name, similarity 25%)
  5. SAMBI LOKONGA (displayed name, similarity 24%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Jeanuël Belocian (leverkusen)
  1. Tella (displayed name, similarity 40%)
  2. GARCÍA (displayed name, similarity 38%)
  3. Palacios (displayed name, similarity 35%)
  4. FERNÁNDEZ (displayed name, similarity 33%)
  5. Kofane (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Jonas Urbig (bayern)
  1. NEUER (displayed name, similarity 40%)
  2. Saibari (displayed name, similarity 35%)
  3. Stanišić (displayed name, similarity 33%)
  4. BROWN (displayed name, similarity 27%)
  5. OLISE (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Luca Reggiani (dortmund)
  1. KARETSAS (displayed name, similarity 40%)
  2. BENSEBAINI (displayed name, similarity 36%)
  3. RYERSON (displayed name, similarity 32%)
  4. KONSTANTELIAS (displayed name, similarity 24%)
  5. ANTON (displayed name, similarity 24%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Rayan Philippe (hamburg)
  1. ADELINE (displayed name, similarity 40%)
  2. Stange (displayed name, similarity 32%)
  3. CAPALDO (displayed name, similarity 30%)
  4. HEUER FERNANDES (displayed name, similarity 30%)
  5. TORUNARIGHA (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Sebastian Sebulonsen (koeln)
  1. CASTRO-MONTES (displayed name, similarity 39%)
  2. JÓHANNESSON (displayed name, similarity 33%)
  3. BÜLTER (displayed name, similarity 32%)
  4. Thielmann (displayed name, similarity 29%)
  5. MAINA (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Lukas Klostermann (leipzig)
  1. CASTELLO JR. (displayed name, similarity 38%)
  2. ORBÁN (displayed name, similarity 38%)
  3. BAKAYOKO (displayed name, similarity 33%)
  4. Estève (displayed name, similarity 27%)
  5. RÔMULO (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Youssoupha Niang (koeln)
  1. JÓHANNESSON (displayed name, similarity 38%)
  2. Thielmann (displayed name, similarity 33%)
  3. LOCHOSHVILI (displayed name, similarity 31%)
  4. MAINA (displayed name, similarity 30%)
  5. KRAUSS (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Bara Sapoko Ndiaye (bayern)
  1. BROWN (displayed name, similarity 38%)
  2. Saibari (displayed name, similarity 35%)
  3. DÍAZ (displayed name, similarity 30%)
  4. KANE (displayed name, similarity 30%)
  5. BISCHOF (displayed name, similarity 26%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Dan-Axel Zagadou (stuttgart)
  1. Karazor (displayed name, similarity 38%)
  2. El Khannouss (displayed name, similarity 32%)
  3. MITTELSTÄDT (displayed name, similarity 32%)
  4. Andrés (displayed name, similarity 30%)
  5. NARTEY (displayed name, similarity 30%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Kacper Potulski (mainz)
  1. Da Costa (displayed name, similarity 38%)
  2. CACI (displayed name, similarity 33%)
  3. AMIRI (displayed name, similarity 32%)
  4. POSCH (displayed name, similarity 32%)
  5. BECKER (displayed name, similarity 30%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Lennard Maloney (mainz)
  1. ZENTNER (displayed name, similarity 38%)
  2. LEE (displayed name, similarity 35%)
  3. MWENE (displayed name, similarity 32%)
  4. SANO (displayed name, similarity 22%)
  5. AMIRI (displayed name, similarity 21%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Michael Zetterer (frankfurt)
  1. THEATE (displayed name, similarity 38%)
  2. KOCH (displayed name, similarity 21%)
  3. Højlund (displayed name, similarity 19%)
  4. LARSSON (displayed name, similarity 18%)
  5. BURKARDT (displayed name, similarity 17%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Timothy Chandler (frankfurt)
  1. THEATE (displayed name, similarity 38%)
  2. DOAN (displayed name, similarity 32%)
  3. KOCH (displayed name, similarity 32%)
  4. Højlund (displayed name, similarity 29%)
  5. Collins (displayed name, similarity 18%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Arthur Chaves (hoffenheim)
  1. ROTS (displayed name, similarity 38%)
  2. BURGER (displayed name, similarity 33%)
  3. BAUMANN (displayed name, similarity 32%)
  4. AVDULLAHU (displayed name, similarity 29%)
  5. Moerstedt (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Hiroki Ito (bayern)
  1. KIMMICH (displayed name, similarity 38%)
  2. Saibari (displayed name, similarity 38%)
  3. BROWN (displayed name, similarity 29%)
  4. LAIMER (displayed name, similarity 27%)
  5. BISCHOF (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Mario Götze (frankfurt)
  1. THEATE (displayed name, similarity 38%)
  2. LARSSON (displayed name, similarity 35%)
  3. BURKARDT (displayed name, similarity 33%)
  4. EBNOUTALIB (displayed name, similarity 20%)
  5. KAUÃ SANTOS (displayed name, similarity 20%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Mert Kömür (augsburg)
  1. MATSIMA (displayed name, similarity 38%)
  2. Ribeiro (displayed name, similarity 38%)
  3. MASSENGO (displayed name, similarity 35%)
  4. GREGORITSCH (displayed name, similarity 30%)
  5. CLAUDE-MAURICE (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Niklas Stark (bremen)
  1. STAGE (displayed name, similarity 38%)
  2. NJINMAH (displayed name, similarity 33%)
  3. MBANGULA (displayed name, similarity 32%)
  4. Reis (displayed name, similarity 27%)
  5. FRIEDL (displayed name, similarity 24%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Oliver Burke (union)
  1. BURCU (displayed name, similarity 38%)
  2. QUERFELD (displayed name, similarity 32%)
  3. Friedrich (displayed name, similarity 30%)
  4. RAAB (displayed name, similarity 27%)
  5. Klaus (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Tim Skarke (union)
  1. SCHÄFER (displayed name, similarity 38%)
  2. ANSAH (displayed name, similarity 29%)
  3. ROTHE (displayed name, similarity 29%)
  4. KEMLEIN (displayed name, similarity 25%)
  5. KHEDIRA (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Assan Ouédraogo (leipzig)
  1. BAKAYOKO (displayed name, similarity 36%)
  2. CASTELLO JR. (displayed name, similarity 33%)
  3. VANDEVOORT (displayed name, similarity 33%)
  4. RÔMULO (displayed name, similarity 30%)
  5. BANZUZI (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Conrad Harder (leipzig)
  1. VANDEVOORT (displayed name, similarity 36%)
  2. Henrichs (displayed name, similarity 30%)
  3. CASTELLO JR. (displayed name, similarity 27%)
  4. NUSA (displayed name, similarity 25%)
  5. RAUM (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Fabio Chiarodia (gladbach)
  1. HASHIOKA (displayed name, similarity 36%)
  2. Leopold (displayed name, similarity 29%)
  3. ULLRICH (displayed name, similarity 29%)
  4. KLEINDIENST (displayed name, similarity 24%)
  5. DIKS (displayed name, similarity 22%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Jean-Mattéo Bahoya (frankfurt)
  1. THEATE (displayed name, similarity 36%)
  2. KAUÃ SANTOS (displayed name, similarity 31%)
  3. EBNOUTALIB (displayed name, similarity 23%)
  4. BAUM (displayed name, similarity 20%)
  5. DOAN (displayed name, similarity 20%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Leonidas Stergiou (stuttgart)
  1. NARTEY (displayed name, similarity 36%)
  2. HENDRIKS (displayed name, similarity 33%)
  3. LEWELING (displayed name, similarity 33%)
  4. El Khannouss (displayed name, similarity 30%)
  5. UNDAV (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Lorenz Assignon (stuttgart)
  1. LEWELING (displayed name, similarity 36%)
  2. Pejčinović (displayed name, similarity 33%)
  3. El Khannouss (displayed name, similarity 32%)
  4. Andrés (displayed name, similarity 30%)
  5. HENDRIKS (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Abdoul-Karim Coulibaly (bremen)
  1. FÜLLKRUG (displayed name, similarity 36%)
  2. MBANGULA (displayed name, similarity 29%)
  3. CHUKI (displayed name, similarity 24%)
  4. Grüll (displayed name, similarity 24%)
  5. FRIEDL (displayed name, similarity 23%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Joseph Scally (gladbach)
  1. MOHYA (displayed name, similarity 35%)
  2. Leopold (displayed name, similarity 32%)
  3. Hack (displayed name, similarity 25%)
  4. BOLIN (displayed name, similarity 24%)
  5. SANDER (displayed name, similarity 22%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Lennart Karl (bayern)
  1. LAIMER (displayed name, similarity 35%)
  2. KANE (displayed name, similarity 27%)
  3. NEUER (displayed name, similarity 25%)
  4. OLISE (displayed name, similarity 25%)
  5. Musiala (displayed name, similarity 22%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Luca Jaquez (stuttgart)
  1. Karazor (displayed name, similarity 35%)
  2. UNDAV (displayed name, similarity 27%)
  3. Andrés (displayed name, similarity 25%)
  4. CHABOT (displayed name, similarity 25%)
  5. NARTEY (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Lukas Kübler (freiburg)
  1. Günter (displayed name, similarity 35%)
  2. LIENHART (displayed name, similarity 32%)
  3. Scherhant (displayed name, similarity 30%)
  4. ENGELHARDT (displayed name, similarity 29%)
  5. BESTE (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Max Finkgräfe (leipzig)
  1. GRUDA (displayed name, similarity 35%)
  2. BAKAYOKO (displayed name, similarity 30%)
  3. Maksimovic (displayed name, similarity 27%)
  4. VANDEVOORT (displayed name, similarity 27%)
  5. BAKU (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for William Bøving (mainz)
  1. AMIRI (displayed name, similarity 35%)
  2. SANO (displayed name, similarity 25%)
  3. MWENE (displayed name, similarity 24%)
  4. LEE (displayed name, similarity 13%)
  5. CACI (displayed name, similarity 12%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Yannik Keitel (augsburg)
  1. Banks (displayed name, similarity 35%)
  2. RIEDER (displayed name, similarity 33%)
  3. Ribeiro (displayed name, similarity 32%)
  4. Brackelmann (displayed name, similarity 26%)
  5. GREGORITSCH (displayed name, similarity 26%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Christopher Trimmel (union)
  1. ROTHE (displayed name, similarity 35%)
  2. SCHÄFER (displayed name, similarity 32%)
  3. QUERFELD (displayed name, similarity 31%)
  4. LATTE LATH (displayed name, similarity 30%)
  5. KHEDIRA (displayed name, similarity 24%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Silvan Dominic Widmer (mainz)
  1. SANO (displayed name, similarity 35%)
  2. AMIRI (displayed name, similarity 33%)
  3. ZENTNER (displayed name, similarity 31%)
  4. BECKER (displayed name, similarity 24%)
  5. LEE (displayed name, similarity 18%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Anthony Jung (freiburg)
  1. MAKENGO (displayed name, similarity 33%)
  2. BACKHAUS (displayed name, similarity 32%)
  3. MATANOVIĆ (displayed name, similarity 30%)
  4. Scherhant (displayed name, similarity 30%)
  5. TREU (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Arthur (leverkusen)
  1. GARCÍA (displayed name, similarity 33%)
  2. QUANSAH (displayed name, similarity 31%)
  3. GUTIÉRREZ (displayed name, similarity 27%)
  4. BADÉ (displayed name, similarity 20%)
  5. MAZA (displayed name, similarity 20%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Bruno Ogbus (freiburg)
  1. BACKHAUS (displayed name, similarity 33%)
  2. TREU (displayed name, similarity 29%)
  3. BESTE (displayed name, similarity 27%)
  4. GRIFO (displayed name, similarity 27%)
  5. Günter (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Christoph Baumgartner (leipzig)
  1. CASTELLO JR. (displayed name, similarity 33%)
  2. RAUM (displayed name, similarity 33%)
  3. ORBÁN (displayed name, similarity 32%)
  4. BAKU (displayed name, similarity 25%)
  5. Reitz (displayed name, similarity 24%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Cyriaque Irié (freiburg)
  1. Yilmaz (displayed name, similarity 33%)
  2. BACKHAUS (displayed name, similarity 30%)
  3. Scherhant (displayed name, similarity 29%)
  4. TREU (displayed name, similarity 25%)
  5. BESTE (displayed name, similarity 24%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Farès Chaïbi (frankfurt)
  1. LARSSON (displayed name, similarity 33%)
  2. EBNOUTALIB (displayed name, similarity 29%)
  3. KAUÃ SANTOS (displayed name, similarity 29%)
  4. KOCH (displayed name, similarity 27%)
  5. KOSUGI (displayed name, similarity 24%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Fábio Silva (dortmund)
  1. KARETSAS (displayed name, similarity 33%)
  2. Sabitzer (displayed name, similarity 33%)
  3. BENSEBAINI (displayed name, similarity 30%)
  4. ANTON (displayed name, similarity 27%)
  5. BEIER (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Nico Schlotterbeck (dortmund)
  1. KONSTANTELIAS (displayed name, similarity 33%)
  2. Sabitzer (displayed name, similarity 32%)
  3. BEIER (displayed name, similarity 27%)
  4. KOBEL (displayed name, similarity 27%)
  5. NMECHA (displayed name, similarity 26%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Patrice Covic (bremen)
  1. FRIEDL (displayed name, similarity 33%)
  2. Erebenagie (displayed name, similarity 27%)
  3. Reis (displayed name, similarity 25%)
  4. Itten (displayed name, similarity 24%)
  5. STAGE (displayed name, similarity 24%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Robin Hranác (hoffenheim)
  1. BAUMANN (displayed name, similarity 33%)
  2. Bernardo (displayed name, similarity 32%)
  3. ROTS (displayed name, similarity 27%)
  4. CONTÉ (displayed name, similarity 25%)
  5. KABAK (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Uchenna Ogundu (augsburg)
  1. Brackelmann (displayed name, similarity 33%)
  2. DAHMEN (displayed name, similarity 32%)
  3. BEHRENS (displayed name, similarity 30%)
  4. MASSENGO (displayed name, similarity 29%)
  5. GOUWELEEUW (displayed name, similarity 26%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Kristijan Jakić (augsburg)
  1. GREGORITSCH (displayed name, similarity 32%)
  2. Banks (displayed name, similarity 32%)
  3. Ribeiro (displayed name, similarity 29%)
  4. Brackelmann (displayed name, similarity 24%)
  5. CLAUDE-MAURICE (displayed name, similarity 22%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Ayoube Amaimouni (frankfurt)
  1. BAUM (displayed name, similarity 32%)
  2. UZUN (displayed name, similarity 32%)
  3. KOSUGI (displayed name, similarity 29%)
  4. Collins (displayed name, similarity 27%)
  5. LARSSON (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Ellyes Skhiri (frankfurt)
  1. Collins (displayed name, similarity 32%)
  2. LARSSON (displayed name, similarity 32%)
  3. ONYEDIKA (displayed name, similarity 30%)
  4. EBNOUTALIB (displayed name, similarity 27%)
  5. KOCH (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Lucas Vázquez (leverkusen)
  1. TAPSOBA (displayed name, similarity 32%)
  2. Palacios (displayed name, similarity 30%)
  3. FERNÁNDEZ (displayed name, similarity 29%)
  4. GUTIÉRREZ (displayed name, similarity 29%)
  5. BADÉ (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Eric Martel (mainz)
  1. LEE (displayed name, similarity 31%)
  2. AMIRI (displayed name, similarity 27%)
  3. MWENE (displayed name, similarity 27%)
  4. TIETZ (displayed name, similarity 27%)
  5. BECKER (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for El Chadaille Bitshiabu (leipzig)
  1. Henrichs (displayed name, similarity 29%)
  2. Reitz (displayed name, similarity 24%)
  3. SEIWALD (displayed name, similarity 22%)
  4. CASTELLO JR. (displayed name, similarity 20%)
  5. BAKU (displayed name, similarity 17%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Ransford Königsdörffer (mainz)
  1. ZENTNER (displayed name, similarity 29%)
  2. KOHR (displayed name, similarity 24%)
  3. SANO (displayed name, similarity 24%)
  4. BECKER (displayed name, similarity 22%)
  5. GRUBER (displayed name, similarity 22%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Eliesse Ben Seghir (leverkusen)
  1. Medina (displayed name, similarity 27%)
  2. SCHICK (displayed name, similarity 27%)
  3. FLEKKEN (displayed name, similarity 26%)
  4. MOREIRA (displayed name, similarity 26%)
  5. QUANSAH (displayed name, similarity 26%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Yussuf Poulsen (hamburg)
  1. SAMBI LOKONGA (displayed name, similarity 24%)
  2. Lemke (displayed name, similarity 22%)
  3. MUHEIM (displayed name, similarity 21%)
  4. Stange (displayed name, similarity 21%)
  5. ADELINE (displayed name, similarity 20%)

Choose a candidate number, or press Enter to skip (score 0):

Input summary
  Matchday: 1; derived metric: kbstats_matchday_qualified_last_5_average_players_20260819_091529_+0200.json
  KBStats source CSV: kbstats_players_20260818_204143_+0200.csv
  Ligainsider (weight 4): ligainsider_bundesliga_lineups_20260819_095720.json
  Kickbase (weight 3): kickbase_bundesliga_lineups_20260819_125416.json
  Rotowire (weight 1): rotowire_bundesliga_lineups_20260819_095810.json
  Alternative starting-chance decay: 0.45
  Questionable-injury starting-chance penalty: 0.15
  Output: C:\kickbase project\outputs\expected_points\expected_points_20260818_204143_+0200_kbstats_last_5_average_odds_lineup_20260819_141710_+0200.csv

Team odds and expected match points

,team,provider,win_probability,draw_probability,loss_probability,expected_match_points
0,augsburg,FotMob,0.439632,0.255462,0.304906,1.574358
1,bayern,FotMob,0.746846,0.141566,0.111588,2.382105
2,bremen,FotMob,0.270567,0.255941,0.473492,1.067642
3,dortmund,FotMob,0.728590,0.166170,0.105241,2.351939
4,elversberg,FotMob,0.182306,0.206085,0.611608,0.753004
5,frankfurt,FotMob,0.364604,0.256208,0.379188,1.350020
6,freiburg,FotMob,0.473492,0.255941,0.270567,1.676417
7,gladbach,FotMob,0.178859,0.197490,0.623652,0.734066
8,hamburg,FotMob,0.105241,0.166170,0.728590,0.481892
9,hoffenheim,FotMob,0.421053,0.263158,0.315789,1.526316
10,koeln,FotMob,0.315789,0.263158,0.421053,1.210526
11,leipzig,FotMob,0.623652,0.197490,0.178859,2.068445
12,leverkusen,FotMob,0.611608,0.206085,0.182306,2.040910
13,mainz,FotMob,0.567332,0.231084,0.201584,1.933080
14,paderborn,FotMob,0.201584,0.231084,0.567332,0.835836
15,schalke,FotMob,0.304906,0.255462,0.439632,1.170180
16,stuttgart,FotMob,0.111588,0.141566,0.746846,0.476329
17,union,FotMob,0.379188,0.256208,0.364604,1.393772

Player score review (not qualified, missing metric, or non-positive score)

,name,team,metric_status,metric,lineup_status,expected_match_points,ligainsider_starting_chance,kickbase_starting_chance,rotowire_starting_chance,questionable_injury_penalty,starting_chance,score
2,Sven Ulreich,bayern,not_qualified,0.0,not_evaluated_missing_metric,2.382105,0.0,0.0,0.0,0.0,0.0,0.0
4,Serge Gnabry,bayern,qualified_without_last_five_average,0.0,not_evaluated_missing_metric,2.382105,0.0,0.0,0.0,0.0,0.0,0.0
10,Jonas Urbig,bayern,qualified,132.4,ligainsider:missing; kickbase:missing; rotowir...,2.382105,0.0,0.0,0.0,0.0,0.0,0.0
11,Hiroki Ito,bayern,qualified,136.0,ligainsider:missing; kickbase:missing; rotowir...,2.382105,0.0,0.0,0.0,0.0,0.0,0.0
13,Arijon Ibrahimović,bayern,qualified,95.2,ligainsider:missing; kickbase:missing; rotowir...,2.382105,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
463,Christian Gomis,schalke,not_qualified,0.0,not_evaluated_missing_metric,1.170180,0.0,0.0,0.0,0.0,0.0,0.0
464,Luca Vozar,schalke,not_qualified,0.0,not_evaluated_missing_metric,1.170180,0.0,0.0,0.0,0.0,0.0,0.0
465,Satoshi Tanaka,schalke,not_qualified,0.0,not_evaluated_missing_metric,1.170180,0.0,0.0,0.0,0.0,0.0,0.0
466,Johannes Simon Siebeking,schalke,not_qualified,0.0,not_evaluated_missing_metric,1.170180,0.0,0.0,0.0,0.0,0.0,0.0
467,Adil Aouchiche,schalke,not_qualified,0.0,not_evaluated_missing_metric,1.170180,0.0,0.0,0.0,0.0,0.0,0.0