# KBStats average points × odds × lineup score

Creates an optimizer-ready full KBStats score file from the newest matchday-qualified season-average-points analysis, expected match points from odds, configurable-weight LigaInsider, Kickbase, and RotoWire starting chances, and geometric alternative decay for LigaInsider/Kickbase slots. Kicker is reserved until its parser exists. Kickbase display labels resolve automatically to a unique same-team KBStats last name, then first name; shared-name or no-match candidates are prompted only at 50% similarity or higher and persist to `data/reference/kickbase_player_name_cross_references.csv`. Lower-similarity cases leave Kickbase at zero. Players not present in the qualified analysis receive a metric and score of zero; valid negative KBStats averages are retained and can yield negative scores.

In [1]:
import importlib
import sys
from pathlib import Path

QUESTIONABLE_INJURY_STARTING_CHANCE_PENALTY = 0.15
# Each rank is 45% of the preceding alternative before its slot is normalized.
ALTERNATIVE_STARTING_CHANCE_DECAY = 0.45
# Relative trust weights for active lineup sources; use 0 to disable one.
LINEUP_SOURCE_WEIGHTS = {'ligainsider': 4.0, 'kickbase': 3.0, 'rotowire': 1.0}


def locate_project_root() -> Path:
    starts = [Path.cwd().resolve()]
    notebook_path = globals().get('__vsc_ipynb_file__')
    if isinstance(notebook_path, str) and notebook_path.strip():
        starts.insert(0, Path(notebook_path).expanduser().resolve().parent)
    for start in starts:
        for candidate in (start, *start.parents):
            if (candidate / 'project_paths.py').is_file():
                return candidate
    raise FileNotFoundError('Could not locate project_paths.py.')


PROJECT_ROOT = locate_project_root()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import kbstats_points_odds_lineup_score

kbstats_points_odds_lineup_score = importlib.reload(
    kbstats_points_odds_lineup_score
)

result = kbstats_points_odds_lineup_score.run_score_creation(
    'season_average',
    questionable_injury_starting_chance_penalty=QUESTIONABLE_INJURY_STARTING_CHANCE_PENALTY,
    alternative_starting_chance_decay=ALTERNATIVE_STARTING_CHANCE_DECAY,
    lineup_source_weights=LINEUP_SOURCE_WEIGHTS,
)

Matchday for odds and lineups:  1

No exact match for rotowire lineup for Marco Grüll (bremen)
  1. Marco Friedl (ID 23443, similarity 67%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Joël Schmied (koeln)
  1. Waldschmidt (displayed name, similarity 64%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Kim Minjae (bayern)
  1. KIMMICH (displayed name, similarity 62%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Emre Can (dortmund)
  1. NMECHA (displayed name, similarity 62%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Daniel Elfadli (hamburg)
  1. Daniel Heuer Fernandes (ID 6379, similarity 61%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Daniel Elfadli (hamburg)
  1. Daniel Heuer Fernandes (ID 21877, similarity 61%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Kevin Stöger (gladbach)
  1. Kevin Diks (ID 21650, similarity 60%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Mads Pedersen (augsburg)
  1. MASSENGO (displayed name, similarity 60%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Nico Elvedi (gladbach)
  1. NICOLAS (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Tim Lemperle (hoffenheim)
  1. Wimmer (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Tim Oermann (leverkusen)
  1. MOREIRA (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Junior Adamu (schalke)
  1. Eric Junior (ID 27879, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Oliver Burke (union)
  1. Livan Burcu (ID 36114, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Oliver Burke (union)
  1. Livan Burcu (ID 43803, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Stefan Bell (mainz)
  1. Stefan Posch (ID 12798, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Stefan Bell (mainz)
  1. Stefan Posch (ID 23594, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Marius Bülter (koeln)
  1. Marvin Schwabe (ID 34845, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Emre Can (dortmund)
  1. Felix Nmecha (ID 25090, similarity 56%)
  2. Waldemar Anton (ID 5837, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Emre Can (dortmund)
  1. Felix Nmecha (ID 27147, similarity 56%)
  2. Waldemar Anton (ID 20160, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Christian Günter (freiburg)
  1. Matthias Ginter (ID 17592, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Salim Amani Musah (bremen)
  1. Samuel Mbangula (ID 38382, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Martin Terrier (leverkusen)
  1. GUTIÉRREZ (displayed name, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Said El Mala (koeln)
  1. Jan Thielmann (ID 30688, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Frederik Rönnow (union)
  1. Derrick Koehn (ID 14385, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Joël Schmied (koeln)
  1. Luca Waldschmidt (ID 2594, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Joël Schmied (koeln)
  1. Luca Waldschmidt (ID 19652, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Frederik Rönnow (union)
  1. Rønnow (displayed name, similarity 53%)
  2. Friedrich (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Paul Nebel (mainz)
  1. Jaesung Lee (ID 21202, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Sander Tangvik (hamburg)
  1. Stange (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Danny Da Costa (mainz)
  1. Anthony Caci (ID 25792, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Janik Haberer (union)
  1. Rani Khedira (ID 2122, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Jovan Milosevic (stuttgart)
  1. Demirović (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jovan Milosevic (stuttgart)
  1. Jamie Leweling (ID 21336, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Jovan Milosevic (stuttgart)
  1. Jamie Leweling (ID 35268, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Ramy Bensebaini (dortmund)
  1. Samuele Inacio (ID 47795, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Adam Daghim (hoffenheim)
  1. Adam Hlozek (ID 33675, similarity 50%)
  2. Andrej Kramaric (ID 18613, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Andrej Kramarić (hoffenheim)
  1. Adam Daghim (ID 37622, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Chema Andrés (stuttgart)
  1. Ramon Hendriks (ID 23957, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Chema Andrés (stuttgart)
  1. Ramon Hendriks (ID 29953, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Cyriaque Irié (freiburg)
  1. Christian Guenter (ID 2153, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Derrick Köhn (union)
  1. Friedrich (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Eren Sami Dinkçi (bremen)
  1. Erebenagie (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jamal Musiala (bayern)
  1. Luis Diaz (ID 22566, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Janis Blaswich (leverkusen)
  1. QUANSAH (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Lazar Jovanovic (stuttgart)
  1. Pejčinović (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Martin Terrier (leverkusen)
  1. Miguel Gutierrez (ID 24219, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Martin Terrier (leverkusen)
  1. Miguel Gutierrez (ID 32495, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Mick Schmetgens (bremen)
  1. Mitchell Weiser (ID 18200, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Montrell Culbreath (leverkusen)
  1. MOREIRA (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Niklas Stark (bremen)
  1. Jens Stage (ID 22538, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Niklas Stark (bremen)
  1. Jens Stage (ID 30066, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Paul Nebel (mainz)
  1. LEE (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Sacha Boey (bayern)
  1. BISCHOF (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Tim Lemperle (hoffenheim)
  1. Patrick Wimmer (ID 26236, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

Input summary
  Matchday: 1; derived metric: kbstats_matchday_qualified_average_players_20260819_091135_+0200.json
  KBStats source CSV: kbstats_players_20260818_204143_+0200.csv
  Ligainsider (weight 4): ligainsider_bundesliga_lineups_20260819_095720.json
  Kickbase (weight 3): kickbase_bundesliga_lineups_20260819_125416.json
  Rotowire (weight 1): rotowire_bundesliga_lineups_20260819_095810.json
  Alternative starting-chance decay: 0.45
  Questionable-injury starting-chance penalty: 0.15
  Output: C:\kickbase project\outputs\expected_points\expected_points_20260818_204143_+0200_kbstats_season_average_odds_lineup_20260819_153815_+0200.csv

Team odds and expected match points

,team,provider,win_probability,draw_probability,loss_probability,expected_match_points
0,augsburg,FotMob,0.439632,0.255462,0.304906,1.574358
1,bayern,FotMob,0.746846,0.141566,0.111588,2.382105
2,bremen,FotMob,0.270567,0.255941,0.473492,1.067642
3,dortmund,FotMob,0.728590,0.166170,0.105241,2.351939
4,elversberg,FotMob,0.182306,0.206085,0.611608,0.753004
5,frankfurt,FotMob,0.364604,0.256208,0.379188,1.350020
6,freiburg,FotMob,0.473492,0.255941,0.270567,1.676417
7,gladbach,FotMob,0.178859,0.197490,0.623652,0.734066
8,hamburg,FotMob,0.105241,0.166170,0.728590,0.481892
9,hoffenheim,FotMob,0.421053,0.263158,0.315789,1.526316
10,koeln,FotMob,0.315789,0.263158,0.421053,1.210526
11,leipzig,FotMob,0.623652,0.197490,0.178859,2.068445
12,leverkusen,FotMob,0.611608,0.206085,0.182306,2.040910
13,mainz,FotMob,0.567332,0.231084,0.201584,1.933080
14,paderborn,FotMob,0.201584,0.231084,0.567332,0.835836
15,schalke,FotMob,0.304906,0.255462,0.439632,1.170180
16,stuttgart,FotMob,0.111588,0.141566,0.746846,0.476329
17,union,FotMob,0.379188,0.256208,0.364604,1.393772

Player score review (not qualified, missing metric, or non-positive score)

,name,team,metric_status,metric,lineup_status,expected_match_points,ligainsider_starting_chance,kickbase_starting_chance,rotowire_starting_chance,questionable_injury_penalty,starting_chance,score
2,Sven Ulreich,bayern,not_qualified,0.0,not_evaluated_missing_metric,2.382105,0.0,0.0,0.0,0.0,0.0,0.0
4,Serge Gnabry,bayern,qualified,142.0,ligainsider:missing; kickbase:missing; rotowir...,2.382105,0.0,0.0,0.0,0.0,0.0,0.0
10,Jonas Urbig,bayern,qualified,114.0,ligainsider:missing; kickbase:missing; rotowir...,2.382105,0.0,0.0,0.0,0.0,0.0,0.0
11,Hiroki Ito,bayern,qualified,103.0,ligainsider:missing; kickbase:missing; rotowir...,2.382105,0.0,0.0,0.0,0.0,0.0,0.0
13,Arijon Ibrahimović,bayern,qualified,57.0,ligainsider:missing; kickbase:missing; rotowir...,2.382105,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
463,Christian Gomis,schalke,not_qualified,0.0,not_evaluated_missing_metric,1.170180,0.0,0.0,0.0,0.0,0.0,0.0
464,Luca Vozar,schalke,not_qualified,0.0,not_evaluated_missing_metric,1.170180,0.0,0.0,0.0,0.0,0.0,0.0
465,Satoshi Tanaka,schalke,not_qualified,0.0,not_evaluated_missing_metric,1.170180,0.0,0.0,0.0,0.0,0.0,0.0
466,Johannes Simon Siebeking,schalke,not_qualified,0.0,not_evaluated_missing_metric,1.170180,0.0,0.0,0.0,0.0,0.0,0.0
467,Adil Aouchiche,schalke,not_qualified,0.0,not_evaluated_missing_metric,1.170180,0.0,0.0,0.0,0.0,0.0,0.0