# SofaScore Bundesliga rating × odds × lineup score

Creates optimizer-ready scores from Bundesliga average ratings, expected match points from odds, and configurable-weight LigaInsider, Kickbase, and RotoWire starting chances. LigaInsider and Kickbase alternatives use configurable geometric decay before slot normalization; Kicker remains reserved until its parser exists. The exported CSV includes the provider-specific chances, the injury penalty, and the final `score` column.

Confirmed SofaScore, LigaInsider, and RotoWire name matches are stored with Transfermarkt mappings in `data/reference/player_name_cross_references.csv`. Kickbase display names resolve to a unique same-team KBStats last name, then first name; only shared-name or no-match candidates at 50% similarity or higher are shown for notebook confirmation and stored separately in `data/reference/kickbase_player_name_cross_references.csv`. Lower-similarity cases record `kickbase:missing`.

Set the notebook's QUES penalty, alternative-decay, and source-weight variables to tune scoring. A provider-level QUES reduction is applied before LigaInsider or Kickbase formation-slot alternatives are normalized.

In [1]:









import sys
from pathlib import Path

# Absolute starting-chance reduction for a `QUES` injury flag from a lineup source.
QUESTIONABLE_INJURY_STARTING_CHANCE_PENALTY = 0.15
# Each rank is 45% of the preceding alternative before its slot is normalized.
ALTERNATIVE_STARTING_CHANCE_DECAY = 0.45
# Relative trust weights for active lineup sources; use 0 to disable one.
LINEUP_SOURCE_WEIGHTS = {'ligainsider': 4.0, 'kickbase': 3.0, 'rotowire': 1.0}

def locate_project_root() -> Path:
    starts = [Path.cwd().resolve()]
    notebook_path = globals().get('__vsc_ipynb_file__')
    if isinstance(notebook_path, str) and notebook_path.strip():
        starts.insert(0, Path(notebook_path).expanduser().resolve().parent)
    for start in starts:
        for candidate in (start, *start.parents):
            if (candidate / 'project_paths.py').is_file():
                return candidate
    raise FileNotFoundError('Could not locate project_paths.py.')

PROJECT_ROOT = locate_project_root()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from sofascore_rating_odds_lineup_score import run_score_creation
result = run_score_creation(
    'bundesliga',
    questionable_injury_starting_chance_penalty=QUESTIONABLE_INJURY_STARTING_CHANCE_PENALTY,
    alternative_starting_chance_decay=ALTERNATIVE_STARTING_CHANCE_DECAY,
    lineup_source_weights=LINEUP_SOURCE_WEIGHTS,
)

Matchday for odds and lineups:  1

No exact match for SofaScore rating for Alexander Schlager
  1. Xaver Schlager (ID 791079, similarity 80%)
  2. András Schäfer (ID 877302, similarity 67%)
  3. Tom Alexander Rothe (ID 1210666, similarity 65%)
  4. Alexander Nübel (ID 584722, similarity 65%)
  5. Alexander Prass (ID 978062, similarity 65%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Keven Schlotterbeck
  1. Nico Schlotterbeck (ID 940871, similarity 80%)
  2. Kevin Stöger (ID 95381, similarity 55%)
  3. Xaver Schlager (ID 791079, similarity 52%)
  4. Sheraldo Becker (ID 352544, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nicholas Mickelson
  1. Nicolas Jackson (ID 1085381, similarity 77%)
  2. Nicolás Capaldo (ID 973564, similarity 65%)
  3. Nicolas Seiwald (ID 976575, similarity 58%)
  4. Hugo Larsson (ID 1142211, similarity 57%)
  5. Nicolas Höfler (ID 49639, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Mitchell Weiser
  1. Michael Olise (ID 978838, similarity 77%)
  2. Michael Zetterer (ID 190161, similarity 62%)
  3. Michael Gregoritsch (ID 111483, similarity 56%)
  4. Nelson Weiper (ID 1152505, similarity 54%)
  5. Jamie Leweling (ID 990201, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Aleksa Damjanovic
  1. Aleksandar Pavlović (ID 1142251, similarity 76%)
  2. Andrej Kramarić (ID 67647, similarity 53%)
  3. Josip Juranović (ID 791642, similarity 53%)
  4. Alexis Claude-Maurice (ID 822877, similarity 51%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Luka Duric
  1. Lukas Ullrich (ID 1083382, similarity 76%)
  2. Luka Vušković (ID 1405212, similarity 67%)
  3. Laurin Curda (ID 981788, similarity 60%)
  4. Lukas Kübler (ID 142525, similarity 60%)
  5. Livan Burcu (ID 1513469, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Maximilian Rohr
  1. Maximilian Beier (ID 980628, similarity 76%)
  2. Maximilian Wöber (ID 794962, similarity 76%)
  3. Maximilian Philipp (ID 171927, similarity 71%)
  4. Maximilian Eggestein (ID 569784, similarity 61%)
  5. Maximilian Mittelstädt (ID 788949, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kevin Müller
  1. Ruben Müller (ID 1864750, similarity 73%)
  2. Kevin Stöger (ID 95381, similarity 64%)
  3. Angelo Stiller (ID 901882, similarity 50%)
  4. Kevin Akpoguma (ID 187423, similarity 50%)
  5. Kevin Diks (ID 583806, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nathan De Cat
  1. Nathan Tella (ID 920379, similarity 73%)
  2. Jonathan Tah (ID 227672, similarity 64%)
  3. Jonathan Burkardt (ID 939830, similarity 59%)
  4. Nathaniel Brown (ID 1159759, similarity 56%)
  5. Anthony Caci (ID 846471, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Fabian Bredlow
  1. Fabian Rieder (ID 929620, similarity 72%)
  2. Fabio Baldé (ID 1546267, similarity 52%)
  3. Fabio Chiarodia (ID 1130067, similarity 52%)
  4. Nathaniel Brown (ID 1159759, similarity 52%)
  5. Damion Downs (ID 1146091, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Alexander Meyer
  1. Alexander Nübel (ID 584722, similarity 71%)
  2. Alexander Prass (ID 978062, similarity 71%)
  3. Tom Alexander Rothe (ID 1210666, similarity 65%)
  4. Alexis Claude-Maurice (ID 822877, similarity 55%)
  5. Julian Ryerson (ID 800951, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nicolas Kristof
  1. Nicolas Jackson (ID 1085381, similarity 71%)
  2. Nicolas Höfler (ID 49639, similarity 67%)
  3. Nikolas Nartey (ID 861981, similarity 59%)
  4. Nicolas Seiwald (ID 976575, similarity 57%)
  5. Nicolás Capaldo (ID 973564, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Raphael Obermair
  1. Raphaël Guerreiro (ID 246999, similarity 71%)
  2. Janik Haberer (ID 168985, similarity 52%)
  3. Robert Andrich (ID 168903, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kauã Santos
  1. Kaishu Sano (ID 1028307, similarity 70%)
  2. Tom Krauß (ID 930272, similarity 53%)
  3. Waldemar Anton (ID 799046, similarity 52%)
  4. Bazoumana Touré (ID 1568123, similarity 50%)
  5. Dayot Upamecano (ID 798583, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Marius Funk
  1. Marius Wolf (ID 254119, similarity 70%)
  2. Marius Bülter (ID 378340, similarity 64%)
  3. Kaishu Sano (ID 1028307, similarity 50%)
  4. Kristoffer Lund (ID 963043, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Vitalie Becker (schalke)
  1. T. BECKER (displayed name, similarity 70%)
  2. Schallenberg (displayed name, similarity 48%)
  3. DINA EBIMBE (displayed name, similarity 43%)
  4. TANAKA (displayed name, similarity 32%)
  5. Ljubičić (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Laurin Ulrich (paderborn)
  1. Laurin Curda (ID 48704, similarity 70%)
  2. Luka Duric (ID 45012, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Laurin Ulrich
  1. Laurin Curda (ID 981788, similarity 70%)
  2. Lukas Ullrich (ID 1083382, similarity 67%)
  3. Chris Führich (ID 891510, similarity 58%)
  4. Benjamin Henrichs (ID 319857, similarity 50%)
  5. Luca Reggiani (ID 1937833, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Christian Gomis
  1. Christian Günter (ID 142231, similarity 69%)
  2. Christian Kofane (ID 2029648, similarity 69%)
  3. Tidiam Gomis (ID 1426577, similarity 64%)
  4. Tiago Tomás (ID 983540, similarity 58%)
  5. Kristijan Jakić (ID 796206, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Matthias Köbbing
  1. Matthias Ginter (ID 142259, similarity 69%)
  2. Mattes Hansen (ID 1083387, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Cédric Itten
  1. Cedric Zesiger (ID 798926, similarity 67%)
  2. Eric Martel (ID 988639, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Fabio Gruber
  1. Fabio Baldé (ID 1546267, similarity 67%)
  2. Fabian Rieder (ID 929620, similarity 61%)
  3. Fábio Vieira (ID 904835, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Felix Agu
  1. Felix Götze (ID 844131, similarity 67%)
  2. Felix Nmecha (ID 907463, similarity 63%)
  3. Felipe Chávez (ID 1482457, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Filippo Mane
  1. Philipp Sander (ID 939880, similarity 67%)
  2. Phillipp Mwene (ID 138126, similarity 67%)
  3. Willi Orbán (ID 136924, similarity 57%)
  4. Linton Maina (ID 921033, similarity 55%)
  5. Philipp Treu (ID 979820, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Florian Müller
  1. Ruben Müller (ID 1864750, similarity 67%)
  2. Angelo Stiller (ID 901882, similarity 54%)
  3. Livan Burcu (ID 1513469, similarity 52%)
  4. Christian Günter (ID 142231, similarity 50%)
  5. Felix Nmecha (ID 907463, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Jason Ceka (elversberg)
  1. ONYEKA (displayed name, similarity 67%)
  2. GYAMERAH (displayed name, similarity 35%)
  3. PINCKERT (displayed name, similarity 35%)
  4. Sirch (displayed name, similarity 29%)
  5. Zimmerschied (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Justin Diehl
  1. Justin Njinmah (ID 1005343, similarity 67%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Justin Lerma
  1. Justin Njinmah (ID 1005343, similarity 67%)
  2. Jan Uwe Thielmann (ID 1010726, similarity 54%)
  3. Jamal Musiala (ID 1010231, similarity 52%)
  4. Angelo Stiller (ID 901882, similarity 50%)
  5. Julian Ryerson (ID 800951, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Leopold Zingerle
  1. Leopold Querfeld (ID 1086547, similarity 67%)
  2. Tim Lemperle (ID 1014290, similarity 54%)
  3. Cedric Zesiger (ID 798926, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Luca Philipp
  1. Rayan Philippe (ID 991824, similarity 67%)
  2. Maximilian Philipp (ID 171927, similarity 64%)
  3. Philipp Treu (ID 979820, similarity 64%)
  4. Philipp Sander (ID 939880, similarity 58%)
  5. Phillipp Mwene (ID 138126, similarity 58%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Luca Schnellbacher
  1. Lucas Höler (ID 280009, similarity 67%)
  2. Tjark Lasse Scheller (ID 1137717, similarity 57%)
  3. Xaver Schlager (ID 791079, similarity 53%)
  4. Castello Lukeba (ID 976421, similarity 52%)
  5. Lukas Kübler (ID 142525, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Luca Sirch
  1. Lukas Ullrich (ID 1083382, similarity 67%)
  2. Lucas Höler (ID 280009, similarity 63%)
  3. Luca Waldschmidt (ID 319861, similarity 58%)
  4. Lukas Kübler (ID 142525, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lukas Klostermann
  1. Lukas Kübler (ID 142525, similarity 67%)
  2. Lucas Höler (ID 280009, similarity 54%)
  3. Jonas Hofmann (ID 142390, similarity 50%)
  4. Luka Vušković (ID 1405212, similarity 50%)
  5. Lukas Ullrich (ID 1083382, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lukas Pinckert
  1. Lukas Kübler (ID 142525, similarity 67%)
  2. Luka Vušković (ID 1405212, similarity 56%)
  3. Lukas Ullrich (ID 1083382, similarity 56%)
  4. Amos Pieper (ID 851254, similarity 52%)
  5. Lucas Höler (ID 280009, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Malik Pimpong
  1. Malik Tillman (ID 975798, similarity 67%)
  2. Jahmai Simpson-Pusey (ID 1402924, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Marco Grüll (bremen)
  1. Marco Friedl (ID 23443, similarity 67%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Markus Kolke
  1. Marius Wolf (ID 254119, similarity 67%)
  2. Mark Flekken (ID 171919, similarity 64%)
  3. Marius Bülter (ID 378340, similarity 61%)
  4. Carl Klaus (ID 148167, similarity 50%)
  5. Tim Skarke (ID 800252, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Maxime Estève
  1. Max Moerstedt (ID 1418703, similarity 67%)
  2. Maximilian Eggestein (ID 569784, similarity 65%)
  3. Maximilian Beier (ID 980628, similarity 52%)
  4. Michael Zetterer (ID 190161, similarity 52%)
  5. Mads Pedersen (ID 809219, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nikola Katic
  1. Nikolas Nartey (ID 861981, similarity 67%)
  2. Nikolas Veratschnig (ID 1138150, similarity 62%)
  3. Cenk Özkaçar (ID 953097, similarity 55%)
  4. Niklas Stark (ID 229544, similarity 55%)
  5. Noahkai Banks (ID 1597260, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sven Ulreich
  1. Sven Michel (ID 246431, similarity 67%)
  2. Lukas Ullrich (ID 1083382, similarity 61%)
  3. Chris Führich (ID 891510, similarity 52%)
  4. Robert Andrich (ID 168903, similarity 50%)
  5. Samuele Inacio (ID 1861666, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Alexander Røssing-Lelesiit
  1. Alexander Nübel (ID 584722, similarity 65%)
  2. Alexander Prass (ID 978062, similarity 65%)
  3. Tom Alexander Rothe (ID 1210666, similarity 55%)
  4. Alejandro Grimaldo (ID 177177, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Alexander Schwolow
  1. Alexander Nübel (ID 584722, similarity 65%)
  2. Alexander Prass (ID 978062, similarity 65%)
  3. Alejandro Grimaldo (ID 177177, similarity 59%)
  4. Tom Alexander Rothe (ID 1210666, similarity 59%)
  5. Xaver Schlager (ID 791079, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Andrija Maksimovic
  1. Andrej Kramarić (ID 67647, similarity 65%)
  2. Haris Tabaković (ID 259803, similarity 65%)
  3. Andrej Ilić (ID 953767, similarity 52%)
  4. Kristijan Jakić (ID 796206, similarity 52%)
  5. Aleksandar Pavlović (ID 1142251, similarity 51%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Nicholas Mickelson (elversberg)
  1. Nicolas Kristof (ID 26473, similarity 65%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Nicholas Mickelson (elversberg)
  1. Nicolas Kristof (ID 48713, similarity 65%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Alessandro Vogt
  1. Assan Ouédraogo (ID 1418623, similarity 64%)
  2. Aleksandar Pavlović (ID 1142251, similarity 62%)
  3. Alessio Castro-Montes (ID 839898, similarity 61%)
  4. Alejandro Grimaldo (ID 177177, similarity 58%)
  5. Tom Alexander Rothe (ID 1210666, similarity 58%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Daniel Elfadli
  1. Daniel Fernandes (ID 113442, similarity 64%)
  2. Daniel Batz (ID 94312, similarity 61%)
  3. Nico Elvedi (ID 282229, similarity 61%)
  4. Jamie Leweling (ID 990201, similarity 54%)
  5. Daniel Svensson (ID 1021272, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lazar Jovanovic
  1. Jovan Milošević (ID 1154491, similarity 64%)
  2. Josip Juranović (ID 791642, similarity 57%)
  3. Aleksandar Pavlović (ID 1142251, similarity 56%)
  4. Luka Vušković (ID 1405212, similarity 54%)
  5. Igor Matanović (ID 1019321, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Ron-Robert Zieler
  1. Robert Glatzel (ID 168987, similarity 64%)
  2. Gregor Kobel (ID 556866, similarity 54%)
  3. Robert Andrich (ID 168903, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tom Rothe
  1. Tom Alexander Rothe (ID 1210666, similarity 64%)
  2. Timothy Chandler (ID 40239, similarity 52%)
  3. Arthur Theate (ID 965778, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Anton Donkor
  1. Antonio Nusa (ID 1121923, similarity 64%)
  2. Anton Kade (ID 1129365, similarity 60%)
  3. Anthony Jung (ID 103442, similarity 55%)
  4. Damion Downs (ID 1146091, similarity 55%)
  5. Dominik Kohr (ID 152206, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jason Ceka (elversberg)
  1. Francis Onyeka (ID 36948, similarity 64%)
  2. Jan Gyamerah (ID 5825, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Jason Ceka (elversberg)
  1. Francis Onyeka (ID 40979, similarity 64%)
  2. Jan Gyamerah (ID 48720, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Joël Schmied (koeln)
  1. Waldschmidt (displayed name, similarity 64%)
  2. SCHWÄBE (displayed name, similarity 44%)
  3. ACHE (displayed name, similarity 40%)
  4. JÓHANNESSON (displayed name, similarity 36%)
  5. LOCHOSHVILI (displayed name, similarity 36%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Albert Frank Millgramm
  1. Albert Sambi Lokonga (ID 901892, similarity 63%)
  2. Albert Grønbæk (ID 1000263, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for David Mokwa
  1. David Raum (ID 856076, similarity 63%)
  2. Damion Downs (ID 1146091, similarity 57%)
  3. Danilho Doekhi (ID 830803, similarity 52%)
  4. Adam Hložek (ID 963801, similarity 50%)
  5. Said El Mala (ID 1800475, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Luca Vozar
  1. Lucas Höler (ID 280009, similarity 63%)
  2. Lucas Vázquez (ID 255239, similarity 57%)
  3. Luca Jaquez (ID 1127823, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Patson Daka
  1. Anton Kade (ID 1129365, similarity 63%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Kim Minjae (bayern)
  1. KIMMICH (displayed name, similarity 62%)
  2. KANE (displayed name, similarity 46%)
  3. LAIMER (displayed name, similarity 40%)
  4. DÍAZ (displayed name, similarity 31%)
  5. NEUER (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Sima Suso (augsburg)
  1. MASSENGO (displayed name, similarity 62%)
  2. MATSIMA (displayed name, similarity 53%)
  3. CLAUDE-MAURICE (displayed name, similarity 29%)
  4. Ribeiro (displayed name, similarity 27%)
  5. FELLHAUER (displayed name, similarity 24%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Marcel Hoffmeier
  1. Marcel Sabitzer (ID 133908, similarity 62%)
  2. Marco Friedl (ID 825771, similarity 62%)
  3. Manuel Neuer (ID 8959, similarity 54%)
  4. Nelson Weiper (ID 1152505, similarity 52%)
  5. András Schäfer (ID 877302, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Emre Can (dortmund)
  1. NMECHA (displayed name, similarity 62%)
  2. BENSEBAINI (displayed name, similarity 47%)
  3. RYERSON (displayed name, similarity 43%)
  4. KARETSAS (displayed name, similarity 40%)
  5. ANTON (displayed name, similarity 33%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Francis Onyeka
  1. Franck Honorat (ID 280453, similarity 62%)
  2. Anton Kade (ID 1129365, similarity 55%)
  3. Anthony Caci (ID 846471, similarity 50%)
  4. Rani Khedira (ID 149479, similarity 50%)
  5. Yan Diomande (ID 2087085, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Julián Malatini
  1. Julian Brandt (ID 226978, similarity 62%)
  2. Linton Maina (ID 921033, similarity 56%)
  3. Albian Hajdari (ID 1000269, similarity 52%)
  4. Jakub Kamiński (ID 801263, similarity 52%)
  5. Johan Manzambi (ID 1518931, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kenan Karaman
  1. Lennard Maloney (ID 893962, similarity 62%)
  2. Atakan Karazor (ID 801030, similarity 56%)
  3. Kevin Akpoguma (ID 187423, similarity 56%)
  4. Andrej Kramarić (ID 67647, similarity 54%)
  5. Lennart Karl (ID 1861975, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lúkas Petersson
  1. Mads Pedersen (ID 809219, similarity 62%)
  2. Hugo Larsson (ID 1142211, similarity 56%)
  3. Lukas Kübler (ID 142525, similarity 56%)
  4. Julian Ryerson (ID 800951, similarity 52%)
  5. Amos Pieper (ID 851254, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Markus Schubert
  1. Marius Bülter (ID 378340, similarity 62%)
  2. András Schäfer (ID 877302, similarity 59%)
  3. Marvin Schwäbe (ID 187185, similarity 59%)
  4. Tjark Lasse Scheller (ID 1137717, similarity 56%)
  5. Xaver Schlager (ID 791079, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Marvin Friedrich
  1. Marco Friedl (ID 825771, similarity 62%)
  2. Fabian Rieder (ID 929620, similarity 59%)
  3. Marvin Schwäbe (ID 187185, similarity 57%)
  4. Benjamin Henrichs (ID 319857, similarity 52%)
  5. Robert Andrich (ID 168903, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Robin Zentner
  1. Robin Fellhauer (ID 860461, similarity 62%)
  2. Robin Hranáč (ID 957615, similarity 52%)
  3. Ruben Müller (ID 1864750, similarity 52%)
  4. Christian Günter (ID 142231, similarity 52%)
  5. Fabian Rieder (ID 929620, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tom Zimmerschied
  1. Joel Schmied (ID 965950, similarity 62%)
  2. Tom Bischof (ID 1129935, similarity 56%)
  3. Tim Lemperle (ID 1014290, similarity 54%)
  4. Romano Schmid (ID 830127, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Amara Condé
  1. Waldemar Anton (ID 799046, similarity 61%)
  2. Chema Andrés (ID 1464641, similarity 57%)
  3. Marco Friedl (ID 825771, similarity 57%)
  4. Yan Diomande (ID 2087085, similarity 57%)
  5. Bara Sapoko Ndiaye (ID 2427970, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Bilal Nadir
  1. Albian Hajdari (ID 1000269, similarity 61%)
  2. Fabian Rieder (ID 929620, similarity 55%)
  3. Silvan Widmer (ID 157377, similarity 55%)
  4. Nikolas Nartey (ID 861981, similarity 52%)
  5. Philipp Sander (ID 939880, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Finn Porath
  1. Franck Honorat (ID 280453, similarity 61%)
  2. Finn Dahmen (ID 822564, similarity 60%)
  3. Finn Jeltsch (ID 1418649, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jeremy Arévalo
  1. Eric Martel (ID 988639, similarity 61%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Julian Pauli
  1. Julian Brandt (ID 226978, similarity 61%)
  2. Albian Hajdari (ID 1000269, similarity 50%)
  3. Julian Ryerson (ID 800951, similarity 50%)
  4. Maximilian Philipp (ID 171927, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Koki Machida
  1. Romano Schmid (ID 830127, similarity 61%)
  2. Cenk Özkaçar (ID 953097, similarity 55%)
  3. Isaac Schmidt (ID 1015164, similarity 52%)
  4. Shuto Machino (ID 925910, similarity 52%)
  5. Joshua Kimmich (ID 259117, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Linus Güther
  1. Marius Bülter (ID 378340, similarity 61%)
  2. Lucas Höler (ID 280009, similarity 57%)
  3. Kevin Stöger (ID 95381, similarity 55%)
  4. Lukas Kübler (ID 142525, similarity 55%)
  5. Christian Günter (ID 142231, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Noël Aséko
  1. Nicolas Jackson (ID 1085381, similarity 61%)
  2. Nicolas Höfler (ID 49639, similarity 55%)
  3. Nikolas Nartey (ID 861981, similarity 55%)
  4. Nico Elvedi (ID 282229, similarity 53%)
  5. Niklas Mohr (ID 2076815, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tim Binder
  1. Tim Kleindienst (ID 228981, similarity 61%)
  2. Timothy Chandler (ID 40239, similarity 58%)
  3. Fabian Rieder (ID 929620, similarity 57%)
  4. Kim Min-jae (ID 896569, similarity 56%)
  5. Philipp Sander (ID 939880, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tim Oermann
  1. Oliver Baumann (ID 40244, similarity 61%)
  2. Jan Uwe Thielmann (ID 1010726, similarity 56%)
  3. Olivier Deman (ID 960114, similarity 55%)
  4. Igor Matanović (ID 1019321, similarity 52%)
  5. Tiago Tomás (ID 983540, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Daniel Elfadli (hamburg)
  1. Daniel Heuer Fernandes (ID 6379, similarity 61%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Daniel Elfadli (hamburg)
  1. Daniel Heuer Fernandes (ID 21877, similarity 61%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Andreas Hanche-Olsen
  1. Mattes Hansen (ID 1083387, similarity 60%)
  2. András Schäfer (ID 877302, similarity 58%)
  3. Andrej Kramarić (ID 67647, similarity 50%)
  4. Tjark Lasse Scheller (ID 1137717, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for David Herold
  1. David Raum (ID 856076, similarity 60%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Janik Bachmann
  1. Calvin Brackelmann (ID 1128792, similarity 60%)
  2. Jan Uwe Thielmann (ID 1010726, similarity 57%)
  3. Jonas Hofmann (ID 142390, similarity 56%)
  4. Oliver Baumann (ID 40244, similarity 54%)
  5. Han-Noah Massengo (ID 927340, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Kevin Stöger (gladbach)
  1. Kevin Diks (ID 21650, similarity 60%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Mads Pedersen (augsburg)
  1. MASSENGO (displayed name, similarity 60%)
  2. RIEDER (displayed name, similarity 44%)
  3. BEHRENS (displayed name, similarity 42%)
  4. KADE (displayed name, similarity 38%)
  5. DAHMEN (displayed name, similarity 33%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Robin Gosens
  1. Robin Koch (ID 581302, similarity 60%)
  2. Armindo Sieb (ID 1005834, similarity 55%)
  3. Robin Hranáč (ID 957615, similarity 55%)
  4. Ramon Hendriks (ID 916943, similarity 50%)
  5. Robin Hack (ID 876858, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Satoshi Tanaka
  1. Santiago Castañeda (ID 1199101, similarity 60%)
  2. Sebastian Klaas (ID 878628, similarity 59%)
  3. Anton Kade (ID 1129365, similarity 55%)
  4. Johan Bakayoko (ID 1088896, similarity 54%)
  5. Otto Stange (ID 1568535, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Arthur Vermeeren
  1. Arthur Chaves (ID 1122806, similarity 59%)
  2. Arthur Theate (ID 965778, similarity 59%)
  3. Arthur (ID 1174761, similarity 57%)
  4. Aurèle Amenda (ID 999276, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Ismael Saibari
  1. Marcel Sabitzer (ID 133908, similarity 59%)
  2. Nadiem Amiri (ID 327755, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jan Olschowsky (gladbach)
  1. Jan Leszczynski (ID 38925, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Markus Schubert (paderborn)
  1. Tjark Scheller (ID 36890, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Markus Schubert (paderborn)
  1. Tjark Scheller (ID 48700, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Martin Terrier
  1. Matthias Ginter (ID 142259, similarity 59%)
  2. Maximilian Beier (ID 980628, similarity 57%)
  3. Michael Zetterer (ID 190161, similarity 57%)
  4. Fabian Rieder (ID 929620, similarity 56%)
  5. Marius Bülter (ID 378340, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Rav van den Berg
  1. Alexander Nübel (ID 584722, similarity 59%)
  2. Manuel Neuer (ID 8959, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Vitalie Becker
  1. Sheraldo Becker (ID 352544, similarity 59%)
  2. Nicolai Remberg (ID 1064305, similarity 52%)
  3. Maximilian Beier (ID 980628, similarity 50%)
  4. Oliver Burke (ID 608362, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Elias Baum
  1. Mika Baur (ID 1172815, similarity 59%)
  2. Oliver Baumann (ID 40244, similarity 55%)
  3. Livan Burcu (ID 1513469, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Faik Sakar
  1. Mika Baur (ID 1172815, similarity 59%)
  2. Tim Skarke (ID 800252, similarity 56%)
  3. Fábio Silva (ID 954076, similarity 53%)
  4. Niklas Stark (ID 229544, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Isac Lidberg (gladbach)
  1. SANDER (displayed name, similarity 59%)
  2. STÖGER (displayed name, similarity 35%)
  3. DIKS (displayed name, similarity 27%)
  4. Hack (displayed name, similarity 27%)
  5. BOLIN (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Nico Elvedi (gladbach)
  1. NICOLAS (displayed name, similarity 59%)
  2. Leopold (displayed name, similarity 35%)
  3. DIKS (displayed name, similarity 29%)
  4. KLEINDIENST (displayed name, similarity 29%)
  5. SANDER (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Tim Lemperle (hoffenheim)
  1. Wimmer (displayed name, similarity 59%)
  2. Moerstedt (displayed name, similarity 40%)
  3. CONTÉ (displayed name, similarity 25%)
  4. Prass (displayed name, similarity 25%)
  5. BURGER (displayed name, similarity 24%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Tim Oermann (leverkusen)
  1. MOREIRA (displayed name, similarity 59%)
  2. FERNÁNDEZ (displayed name, similarity 42%)
  3. GUTIÉRREZ (displayed name, similarity 42%)
  4. Tella (displayed name, similarity 40%)
  5. Kofane (displayed name, similarity 38%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tom Baack
  1. Robin Hack (ID 876858, similarity 59%)
  2. Tom Bischof (ID 1129935, similarity 56%)
  3. Linton Maina (ID 921033, similarity 53%)
  4. Mio Backhaus (ID 1083390, similarity 53%)
  5. Robin Hranáč (ID 957615, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Deniz Zeitler
  1. Dennis Seimen (ID 1195736, similarity 58%)
  2. Cedric Zesiger (ID 798926, similarity 56%)
  3. Diogo Leite (ID 855663, similarity 55%)
  4. Nelson Weiper (ID 1152505, similarity 50%)
  5. Yannik Keitel (ID 877842, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Jannik Huth (freiburg)
  1. Jan-Niklas Beste (ID 26591, similarity 58%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jannik Huth
  1. Jan-Niklas Beste (ID 836711, similarity 58%)
  2. Janik Haberer (ID 168985, similarity 55%)
  3. Yannik Keitel (ID 877842, similarity 55%)
  4. Yannick Engelhardt (ID 990209, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Keita Kosugi
  1. Kevin Akpoguma (ID 187423, similarity 58%)
  2. Kevin Stöger (ID 95381, similarity 55%)
  3. Yuito Suzuki (ID 1020422, similarity 55%)
  4. Kevin Diks (ID 583806, similarity 50%)
  5. Mert Kömür (ID 1390682, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Martin Adeline
  1. Manuel Neuer (ID 8959, similarity 58%)
  2. Karim Adeyemi (ID 940054, similarity 56%)
  3. Arnaud Kalimuendo (ID 954061, similarity 55%)
  4. Anton Kade (ID 1129365, similarity 55%)
  5. Marvin Schwäbe (ID 187185, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Paul Erevbenagie
  1. Paul Nebel (ID 980621, similarity 58%)
  2. Aurèle Amenda (ID 999276, similarity 52%)
  3. Eliesse Ben Seghir (ID 1394353, similarity 52%)
  4. Samuele Inacio (ID 1861666, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sani Suleiman
  1. Dennis Seimen (ID 1195736, similarity 58%)
  2. Samuele Inacio (ID 1861666, similarity 56%)
  3. Said El Mala (ID 1800475, similarity 55%)
  4. Salim Musah (ID 1864786, similarity 55%)
  5. Rani Khedira (ID 149479, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Timo Becker
  1. Sheraldo Becker (ID 352544, similarity 58%)
  2. Tim Lemperle (ID 1014290, similarity 57%)
  3. Timothy Chandler (ID 40239, similarity 56%)
  4. Tim Skarke (ID 800252, similarity 53%)
  5. Amos Pieper (ID 851254, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Arijon Ibrahimović
  1. Haris Tabaković (ID 259803, similarity 58%)
  2. Josip Juranović (ID 791642, similarity 58%)
  3. Ermedin Demirović (ID 878081, similarity 55%)
  4. Jovan Milošević (ID 1154491, similarity 52%)
  5. Ibrahim Maza (ID 1407524, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Oliver Batista Meier
  1. Oliver Baumann (ID 40244, similarity 58%)
  2. Oliver Burke (ID 608362, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Eren Sami Dinkçi
  1. Ramy Bensebaini (ID 577726, similarity 57%)
  2. Samuele Inacio (ID 1861666, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Felix Keidel
  1. Felix Götze (ID 844131, similarity 57%)
  2. Felix Nmecha (ID 907463, similarity 55%)
  3. Felipe Chávez (ID 1482457, similarity 52%)
  4. Yannik Keitel (ID 877842, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Frederik Schmahl
  1. Frederik Rønnow (ID 137692, similarity 57%)
  2. Eric Martel (ID 988639, similarity 56%)
  3. Farès Chaïbi (ID 1192318, similarity 54%)
  4. Grischa Prömel (ID 253993, similarity 50%)
  5. Ramon Hendriks (ID 916943, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jeanuël Belocian
  1. Jamie Leweling (ID 990201, similarity 57%)
  2. Jan Uwe Thielmann (ID 1010726, similarity 53%)
  3. Jean-Mattéo Bahoya (ID 1146148, similarity 52%)
  4. Samuele Inacio (ID 1861666, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Junior Adamu (schalke)
  1. Eric Junior (ID 27879, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Luka Lochoshvili
  1. Giorgi Gocholeishvili (ID 1035752, similarity 57%)
  2. Luka Vušković (ID 1405212, similarity 52%)
  3. Lukas Ullrich (ID 1083382, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Max Grüger
  1. Marius Bülter (ID 378340, similarity 57%)
  2. Max Finkgräfe (ID 1146250, similarity 57%)
  3. Arthur (ID 1174761, similarity 53%)
  4. Marco Grüll (ID 815612, similarity 53%)
  5. Manuel Neuer (ID 8959, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nahuel Noll
  1. Nathan Tella (ID 920379, similarity 57%)
  2. Noah Atubolu (ID 980626, similarity 57%)
  3. Angelo Stiller (ID 901882, similarity 52%)
  4. Samuele Inacio (ID 1861666, similarity 52%)
  5. Finn Dahmen (ID 822564, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Oliver Burke (union)
  1. Livan Burcu (ID 36114, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Oliver Burke (union)
  1. Livan Burcu (ID 43803, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Raphael Onyedika
  1. Ramon Hendriks (ID 916943, similarity 57%)
  2. Rani Khedira (ID 149479, similarity 54%)
  3. Raphaël Guerreiro (ID 246999, similarity 52%)
  4. Wael Mohya (ID 1995809, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Ron Schallenberg
  1. Marvin Schwäbe (ID 187185, similarity 57%)
  2. Aljoscha Kemlein (ID 1198074, similarity 53%)
  3. András Schäfer (ID 877302, similarity 50%)
  4. Joe Scally (ID 1002920, similarity 50%)
  5. Nico Schlotterbeck (ID 940871, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Stefan Bell (mainz)
  1. Stefan Posch (ID 12798, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Stefan Bell (mainz)
  1. Stefan Posch (ID 23594, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Stefan Bell
  1. Nathan Tella (ID 920379, similarity 57%)
  2. Stefan Posch (ID 355486, similarity 57%)
  3. Cole Campbell (ID 1134578, similarity 55%)
  4. Stefano Marino (ID 1167764, similarity 52%)
  5. Steffen Tigges (ID 826884, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Ezechiel Banzuzi
  1. Ezequiel Fernández (ID 1003012, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Daiki Hashioka
  1. Patrik Schick (ID 280609, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Edin Džeko
  1. Ermedin Demirović (ID 878081, similarity 56%)
  2. Kevin Diks (ID 583806, similarity 56%)
  3. Damion Downs (ID 1146091, similarity 50%)
  4. Dominik Kohr (ID 152206, similarity 50%)
  5. Yan Diomande (ID 2087085, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Florian Neuhaus
  1. Felix Nmecha (ID 907463, similarity 56%)
  2. Livan Burcu (ID 1513469, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Frank Lehmann
  1. Franck Honorat (ID 280453, similarity 56%)
  2. Calvin Brackelmann (ID 1128792, similarity 55%)
  3. Rani Khedira (ID 149479, similarity 52%)
  4. Jan Uwe Thielmann (ID 1010726, similarity 52%)
  5. Bilal El Khannouss (ID 1126569, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Isac Lidberg
  1. Nicolai Remberg (ID 1064305, similarity 56%)
  2. Sheraldo Becker (ID 352544, similarity 56%)
  3. Albert Grønbæk (ID 1000263, similarity 55%)
  4. Fabian Rieder (ID 929620, similarity 52%)
  5. Isaac Schmidt (ID 1015164, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Janik Bachmann (schalke)
  1. Kenan Karaman (ID 2676, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Janik Bachmann (schalke)
  1. Kenan Karaman (ID 20178, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Marius Bülter (koeln)
  1. Marvin Schwabe (ID 34845, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nnamdi Collins
  1. Michael Olise (ID 978838, similarity 56%)
  2. Jamie Leweling (ID 990201, similarity 54%)
  3. Nico Elvedi (ID 282229, similarity 52%)
  4. Damion Downs (ID 1146091, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Patrick Drewes
  1. Patrice Čović (ID 1596105, similarity 56%)
  2. Patrik Schick (ID 280609, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Patrick Wimmer
  1. Patrice Čović (ID 1596105, similarity 56%)
  2. Patrik Schick (ID 280609, similarity 56%)
  3. Tim Lemperle (ID 1014290, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Paul Okon-Engstler
  1. Paul Nebel (ID 980621, similarity 56%)
  2. Angelo Stiller (ID 901882, similarity 55%)
  3. Manuel Neuer (ID 8959, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Timo Hübers
  1. Timothy Chandler (ID 40239, similarity 56%)
  2. Ramon Hendriks (ID 916943, similarity 52%)
  3. Arthur (ID 1174761, similarity 50%)
  4. Niklas Mohr (ID 2076815, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Emre Can (dortmund)
  1. Felix Nmecha (ID 25090, similarity 56%)
  2. Waldemar Anton (ID 5837, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Emre Can (dortmund)
  1. Felix Nmecha (ID 27147, similarity 56%)
  2. Waldemar Anton (ID 20160, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Emre Can
  1. Felix Nmecha (ID 907463, similarity 56%)
  2. Waldemar Anton (ID 799046, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jason Ceka
  1. Anton Kade (ID 1129365, similarity 56%)
  2. Jae-sung Lee (ID 537552, similarity 53%)
  3. Anthony Caci (ID 846471, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jens Grahl
  1. Jens Stage (ID 830142, similarity 56%)
  2. Joe Scally (ID 1002920, similarity 56%)
  3. Jarell Quansah (ID 1003339, similarity 55%)
  4. Jae-sung Lee (ID 537552, similarity 53%)
  5. Brajan Gruda (ID 1198075, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Mats Rots
  1. Mario Götze (ID 66518, similarity 56%)
  2. Mads Pedersen (ID 809219, similarity 50%)
  3. Mattes Hansen (ID 1083387, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Nick Bätzner (paderborn)
  1. STICKER (displayed name, similarity 56%)
  2. CASTAÑEDA (displayed name, similarity 50%)
  3. Zeitler (displayed name, similarity 44%)
  4. BATISTA MEIER (displayed name, similarity 43%)
  5. Götze (displayed name, similarity 38%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Sima Suso (augsburg)
  1. Marius Wolf (ID 5670, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sima Suso
  1. Marius Wolf (ID 254119, similarity 56%)
  2. Salim Musah (ID 1864786, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Sven Michel (paderborn)
  1. SCHELLER (displayed name, similarity 56%)
  2. STICKER (displayed name, similarity 47%)
  3. ULRICH (displayed name, similarity 38%)
  4. BATISTA MEIER (displayed name, similarity 36%)
  5. Zeitler (displayed name, similarity 35%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tim Boss
  1. Tidiam Gomis (ID 1426577, similarity 56%)
  2. Tim Skarke (ID 800252, similarity 50%)
  3. Tom Krauß (ID 930272, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Zento Uno
  1. Ernest Poku (ID 1119502, similarity 56%)
  2. Anthony Jung (ID 103442, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Christian Günter (freiburg)
  1. Matthias Ginter (ID 17592, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Dariusz Stalmach
  1. Haris Tabaković (ID 259803, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Salim Amani Musah (bremen)
  1. Samuel Mbangula (ID 38382, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Adrian Gantenbein
  1. Badredine Bouanani (ID 1153265, similarity 55%)
  2. Christian Günter (ID 142231, similarity 52%)
  3. Maximilian Eggestein (ID 569784, similarity 51%)
  4. Rasmus Kristensen (ID 921789, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Dmytro Bogdanov
  1. Dimitrios Giannoulis (ID 354878, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Emmanuel Latte Lath
  1. Jean-Mattéo Bahoya (ID 1146148, similarity 55%)
  2. Montrell Culbreath (ID 1568522, similarity 53%)
  3. Manuel Neuer (ID 8959, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Florian Pruhs
  1. Livan Burcu (ID 1513469, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Joane Gadou
  1. Jordy Makengo (ID 1131339, similarity 55%)
  2. Johan Bakayoko (ID 1088896, similarity 52%)
  3. Alejandro Grimaldo (ID 177177, similarity 52%)
  4. Bazoumana Touré (ID 1568123, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jonah Sticker
  1. Jonas Urbig (ID 1130647, similarity 55%)
  2. Jens Castrop (ID 1019312, similarity 52%)
  3. Jonathan Tah (ID 227672, similarity 52%)
  4. Nick Bätzner (ID 959635, similarity 52%)
  5. Conrad Harder (ID 1494826, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kauã Prates
  1. Arthur Theate (ID 965778, similarity 55%)
  2. Nikolas Nartey (ID 861981, similarity 52%)
  3. Alexander Prass (ID 978062, similarity 50%)
  4. Bazoumana Touré (ID 1568123, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Keisuke Goto
  1. Kevin Stöger (ID 95381, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Kenny Quetant (bremen)
  1. Senne Lynen (ID 35359, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Kenny Quetant (bremen)
  1. Senne Lynen (ID 37714, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kenny Quetant
  1. Senne Lynen (ID 826171, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lasse Günther
  1. Lucas Höler (ID 280009, similarity 55%)
  2. Matthias Ginter (ID 142259, similarity 54%)
  3. Tjark Lasse Scheller (ID 1137717, similarity 53%)
  4. Lukas Kübler (ID 142525, similarity 52%)
  5. Niklas Stark (ID 229544, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Luca Pfeiffer
  1. Lucas Höler (ID 280009, similarity 55%)
  2. Luca Reggiani (ID 1937833, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Luca Sirch (elversberg)
  1. Lukas Pinckert (ID 38539, similarity 55%)
  2. Luca Schnellbacher (ID 6495, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Luca Sirch (elversberg)
  1. Lukas Pinckert (ID 48715, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lukasz Poreba
  1. Lucas Höler (ID 280009, similarity 55%)
  2. Lukas Kübler (ID 142525, similarity 52%)
  3. Luca Reggiani (ID 1937833, similarity 50%)
  4. Lucas Vázquez (ID 255239, similarity 50%)
  5. Luka Vušković (ID 1405212, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Martin Terrier (leverkusen)
  1. GUTIÉRREZ (displayed name, similarity 55%)
  2. GARCÍA (displayed name, similarity 32%)
  3. Kofane (displayed name, similarity 32%)
  4. Medina (displayed name, similarity 32%)
  5. FERNÁNDEZ (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Noah Darvich
  1. Nadiem Amiri (ID 327755, similarity 55%)
  2. Noahkai Banks (ID 1597260, similarity 52%)
  3. Benjamin Henrichs (ID 319857, similarity 52%)
  4. Albian Hajdari (ID 1000269, similarity 50%)
  5. Marvin Schwäbe (ID 187185, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sacha Boey
  1. Grischa Prömel (ID 253993, similarity 55%)
  2. Marvin Schwäbe (ID 187185, similarity 55%)
  3. Jeff Chabot (ID 863271, similarity 53%)
  4. Farès Chaïbi (ID 1192318, similarity 50%)
  5. Noah Atubolu (ID 980626, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Said El Mala (koeln)
  1. Jan Thielmann (ID 30688, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Örjan Nyland
  1. Oscar Højlund (ID 1149113, similarity 55%)
  2. Julian Brandt (ID 226978, similarity 52%)
  3. Anton Kade (ID 1129365, similarity 50%)
  4. Giovanni Reyna (ID 989056, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Ameen Al Dakhil
  1. Samuele Inacio (ID 1861666, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Dzenan Pejcinovic
  1. Andrej Ilić (ID 953767, similarity 54%)
  2. Dennis Seimen (ID 1195736, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Enzo Leopold
  1. Leopold Querfeld (ID 1086547, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Facundo Medina
  1. Stefano Marino (ID 1167764, similarity 54%)
  2. Finn Dahmen (ID 822564, similarity 52%)
  3. Fabio Chiarodia (ID 1130067, similarity 52%)
  4. Fábio Vieira (ID 904835, similarity 50%)
  5. Rani Khedira (ID 149479, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Frederik Rönnow (union)
  1. Derrick Koehn (ID 14385, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Hasan Kuruçay
  1. Assan Ouédraogo (ID 1418623, similarity 54%)
  2. Brajan Gruda (ID 1198075, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Janis Blaswich
  1. Josip Stanišić (ID 927407, similarity 54%)
  2. Andrej Ilić (ID 953767, similarity 52%)
  3. Niklas Mohr (ID 2076815, similarity 52%)
  4. Haris Tabaković (ID 259803, similarity 52%)
  5. Jan-Niklas Beste (ID 836711, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jannik Huth (freiburg)
  1. Yannik Engelhardt (ID 20278, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Joël Schmied (koeln)
  1. Luca Waldschmidt (ID 2594, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Joël Schmied (koeln)
  1. Luca Waldschmidt (ID 19652, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Matheo Raab
  1. Jean-Mattéo Bahoya (ID 1146148, similarity 54%)
  2. Arthur (ID 1174761, similarity 50%)
  3. Matthias Ginter (ID 142259, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Mick Schmetgens
  1. Isaac Schmidt (ID 1015164, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Miguel Gutiérrez
  1. Manuel Neuer (ID 8959, similarity 54%)
  2. Michael Zetterer (ID 190161, similarity 53%)
  3. Marius Bülter (ID 378340, similarity 52%)
  4. Raphaël Guerreiro (ID 246999, similarity 52%)
  5. Angelo Stiller (ID 901882, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Patrick Osterhage
  1. Otto Stange (ID 1568535, similarity 54%)
  2. Arthur Chaves (ID 1122806, similarity 50%)
  3. Marius Bülter (ID 378340, similarity 50%)
  4. Mattes Hansen (ID 1083387, similarity 50%)
  5. Patrice Čović (ID 1596105, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Stanley Nsoki
  1. Daniel Svensson (ID 1021272, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Zeno Van den Bosch
  1. Stefan Posch (ID 355486, similarity 54%)
  2. Romano Schmid (ID 830127, similarity 52%)
  3. Benjamin Henrichs (ID 319857, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Leonidas Stergiou
  1. Lorenz Assignon (ID 1009334, similarity 53%)
  2. Jens Castrop (ID 1019312, similarity 52%)
  3. Niklas Stark (ID 229544, similarity 52%)
  4. Dennis Seimen (ID 1195736, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lukas Emanuel Petkov
  1. Luka Vušković (ID 1405212, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nediljko Labrović
  1. Andrej Kramarić (ID 67647, similarity 53%)
  2. Ermedin Demirović (ID 878081, similarity 50%)
  3. Luka Vušković (ID 1405212, similarity 50%)
  4. William Bøving (ID 1021075, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Silas
  1. Fábio Silva (ID 954076, similarity 53%)
  2. Ilyas Ansah (ID 1462742, similarity 53%)
  3. Niklas Mohr (ID 2076815, similarity 53%)
  4. Said El Mala (ID 1800475, similarity 53%)
  5. Sebastian Klaas (ID 878628, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Tim Binder (bayern)
  1. LAIMER (displayed name, similarity 53%)
  2. NEUER (displayed name, similarity 43%)
  3. KIMMICH (displayed name, similarity 38%)
  4. Saibari (displayed name, similarity 38%)
  5. Stanišić (displayed name, similarity 35%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Maurice Krattenmacher
  1. Marcel Sabitzer (ID 133908, similarity 53%)
  2. Nick Bätzner (ID 959635, similarity 52%)
  3. Michael Zetterer (ID 190161, similarity 51%)
  4. Aurèle Amenda (ID 999276, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Abdoul Koné
  1. Paul Nebel (ID 980621, similarity 53%)
  2. Lennard Maloney (ID 893962, similarity 50%)
  3. Rômulo (ID 1133743, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Frederik Rönnow (union)
  1. Rønnow (displayed name, similarity 53%)
  2. Friedrich (displayed name, similarity 52%)
  3. KEMLEIN (displayed name, similarity 38%)
  4. Jeong (displayed name, similarity 32%)
  5. KHEDIRA (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Karl Hein
  1. Mark Flekken (ID 171919, similarity 53%)
  2. Aurèle Amenda (ID 999276, similarity 50%)
  3. Karim Adeyemi (ID 940054, similarity 50%)
  4. Luca Reggiani (ID 1937833, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Leo Sauer
  1. Manuel Neuer (ID 8959, similarity 53%)
  2. Leopold Querfeld (ID 1086547, similarity 52%)
  3. Alexis Claude-Maurice (ID 822877, similarity 52%)
  4. Lucas Vázquez (ID 255239, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Otávio
  1. Igor Matanović (ID 1019321, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Paul Nebel (mainz)
  1. Jaesung Lee (ID 21202, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Raif Adam
  1. Brajan Gruda (ID 1198075, similarity 53%)
  2. Ibrahim Maza (ID 1407524, similarity 53%)
  3. Karim Adeyemi (ID 940054, similarity 50%)
  4. Shafiq Nandja (ID 2204961, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Robert Skov
  1. Mert Kömür (ID 1390682, similarity 53%)
  2. Robin Koch (ID 581302, similarity 53%)
  3. Robert Andrich (ID 168903, similarity 52%)
  4. Robert Glatzel (ID 168987, similarity 52%)
  5. Albert Sambi Lokonga (ID 901892, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Ruben Müller (paderborn)
  1. SCHELLER (displayed name, similarity 53%)
  2. Zeitler (displayed name, similarity 44%)
  3. OBERMAIR (displayed name, similarity 42%)
  4. MILLGRAMM (displayed name, similarity 40%)
  5. NOLL (displayed name, similarity 40%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Sander Tangvik (hamburg)
  1. Stange (displayed name, similarity 53%)
  2. ADELINE (displayed name, similarity 40%)
  3. JATTA (displayed name, similarity 33%)
  4. OMARI (displayed name, similarity 33%)
  5. SAMBI LOKONGA (displayed name, similarity 32%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Serge Gnabry
  1. Bernardo (ID 828571, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Adil Aouchiche
  1. Andrej Ilić (ID 953767, similarity 52%)
  2. Alexis Claude-Maurice (ID 822877, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Amara Condé (elversberg)
  1. Francis Onyeka (ID 36948, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Cajetan Lenz
  1. Mattes Hansen (ID 1083387, similarity 52%)
  2. Jens Stage (ID 830142, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Danny Da Costa (mainz)
  1. Anthony Caci (ID 25792, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Dejan Ljubičić
  1. Andrej Ilić (ID 953767, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Gideon Mensah
  1. Linton Maina (ID 921033, similarity 52%)
  2. Dennis Seimen (ID 1195736, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Hennes Behrens
  1. Senne Lynen (ID 826171, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jan Gyamerah
  1. Ansgar Knauff (ID 997012, similarity 52%)
  2. Janik Haberer (ID 168985, similarity 52%)
  3. Julian Ryerson (ID 800951, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Janik Haberer (union)
  1. Rani Khedira (ID 2122, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jean-Luc Dompé
  1. Yan Diomande (ID 2087085, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Jovan Milosevic (stuttgart)
  1. Demirović (displayed name, similarity 52%)
  2. Pejčinović (displayed name, similarity 42%)
  3. JELTSCH (displayed name, similarity 38%)
  4. El Khannouss (displayed name, similarity 32%)
  5. MITTELSTÄDT (displayed name, similarity 32%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Junior Adamu
  1. Julian Brandt (ID 226978, similarity 52%)
  2. Konrad Laimer (ID 355492, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Moussa Sylla
  1. Jamal Musiala (ID 1010231, similarity 52%)
  2. Fisnik Asllani (ID 1010117, similarity 50%)
  3. Joe Scally (ID 1002920, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Nick Bätzner (paderborn)
  1. Jonah Sticker (ID 38855, similarity 52%)
  2. Santiago Castaneda (ID 37450, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Ragnar Ache
  1. Robert Andrich (ID 168903, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Sebastian Klaas (paderborn)
  1. CASTAÑEDA (displayed name, similarity 52%)
  2. Baack (displayed name, similarity 42%)
  3. BATISTA MEIER (displayed name, similarity 38%)
  4. STICKER (displayed name, similarity 38%)
  5. MARINO (displayed name, similarity 30%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Alexander Meyer (dortmund)
  1. Julian Ryerson (ID 18478, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Alexander Meyer (dortmund)
  1. Julian Ryerson (ID 28864, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Cyriaque Irié
  1. Christian Günter (ID 142231, similarity 52%)
  2. Chris Führich (ID 891510, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Florian Le Joncour
  1. Laurin Curda (ID 981788, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jovan Milosevic (stuttgart)
  1. Jamie Leweling (ID 21336, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Jovan Milosevic (stuttgart)
  1. Jamie Leweling (ID 35268, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Ramy Bensebaini (dortmund)
  1. Samuele Inacio (ID 47795, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Benedict Hollerbach
  1. Nicolas Höfler (ID 49639, similarity 52%)
  2. Nikolas Veratschnig (ID 1138150, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Younes Ebnoutalib
  1. Youssoupha Niang (ID 2197599, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Johannes Simon Siebeking
  1. Jamie Leweling (ID 990201, similarity 51%)
  2. Jahmai Simpson-Pusey (ID 1402924, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Abdoul Koné (leipzig)
  1. RÔMULO (displayed name, similarity 50%)
  2. BAKAYOKO (displayed name, similarity 44%)
  3. VANDEVOORT (displayed name, similarity 40%)
  4. BAKU (displayed name, similarity 29%)
  5. RAUM (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Abdoul Koné (leipzig)
  1. Romulo (ID 46816, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Adam Daghim (hoffenheim)
  1. Adam Hlozek (ID 33675, similarity 50%)
  2. Andrej Kramaric (ID 18613, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Adam Daghim
  1. Adam Hložek (ID 963801, similarity 50%)
  2. Andrej Kramarić (ID 67647, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Afonso Moreira
  1. Fábio Vieira (ID 904835, similarity 50%)
  2. Rani Khedira (ID 149479, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Andrej Kramarić (hoffenheim)
  1. Adam Daghim (ID 37622, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Axel Tape
  1. Aurèle Amenda (ID 999276, similarity 50%)
  2. Max Moerstedt (ID 1418703, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Bambasé Conté
  1. Bara Sapoko Ndiaye (ID 2427970, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Chema Andrés (stuttgart)
  1. Ramon Hendriks (ID 23957, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Chema Andrés (stuttgart)
  1. Ramon Hendriks (ID 29953, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Clemens Lippmann
  1. Calvin Brackelmann (ID 1128792, similarity 50%)
  2. Phillipp Mwene (ID 138126, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Cyriaque Irié (freiburg)
  1. Christian Guenter (ID 2153, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Dan-Axel Zagadou
  1. Daniel Batz (ID 94312, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Deniz Zeitler (paderborn)
  1. Ruben Mueller (ID 37563, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Derrick Köhn (union)
  1. Friedrich (displayed name, similarity 50%)
  2. Jeong (displayed name, similarity 38%)
  3. VAN DEN BOSCH (displayed name, similarity 36%)
  4. KEMLEIN (displayed name, similarity 33%)
  5. JURANOVIĆ (displayed name, similarity 30%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Eren Sami Dinkçi (bremen)
  1. Erebenagie (displayed name, similarity 50%)
  2. HEIN (displayed name, similarity 33%)
  3. Reis (displayed name, similarity 33%)
  4. SCHMETGENS (displayed name, similarity 33%)
  5. NJINMAH (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Florian Pruhs (paderborn)
  1. Laurin Ulrich (ID 27568, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Isac Lidberg (gladbach)
  1. Philipp Sander (ID 43368, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jamal Musiala (bayern)
  1. Luis Diaz (ID 22566, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jan Olschowsky
  1. Joel Schmied (ID 965950, similarity 50%)
  2. Stefan Posch (ID 355486, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Janik Bachmann (schalke)
  1. KARAMAN (displayed name, similarity 50%)
  2. TANAKA (displayed name, similarity 42%)
  3. ADAMU (displayed name, similarity 33%)
  4. KATIĆ (displayed name, similarity 33%)
  5. Schallenberg (displayed name, similarity 32%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Janis Blaswich (leverkusen)
  1. QUANSAH (displayed name, similarity 50%)
  2. TAPSOBA (displayed name, similarity 40%)
  3. Palacios (displayed name, similarity 38%)
  4. GARCÍA (displayed name, similarity 32%)
  5. SCHICK (displayed name, similarity 32%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jano ter Horst
  1. Benjamin Henrichs (ID 319857, similarity 50%)
  2. Janik Haberer (ID 168985, similarity 50%)
  3. Jean-Mattéo Bahoya (ID 1146148, similarity 50%)
  4. Max Moerstedt (ID 1418703, similarity 50%)
  5. Yan Couto (ID 1002813, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Justin Lerma (dortmund)
  1. Julian Ryerson (ID 18478, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Justin Lerma (dortmund)
  1. Julian Ryerson (ID 28864, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kennedy Okpala
  1. Cenk Özkaçar (ID 953097, similarity 50%)
  2. Lennart Karl (ID 1861975, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kennet Eichhorn
  1. Senne Lynen (ID 826171, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Konstantinos Karetsas
  1. Jonathan Burkardt (ID 939830, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Lazar Jovanovic (stuttgart)
  1. Pejčinović (displayed name, similarity 50%)
  2. Demirović (displayed name, similarity 43%)
  3. El Khannouss (displayed name, similarity 32%)
  4. FÜHRICH (displayed name, similarity 29%)
  5. Karazor (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Loris Karius
  1. Tim Skarke (ID 800252, similarity 50%)
  2. Tom Krauß (ID 930272, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Martin Terrier (leverkusen)
  1. Miguel Gutierrez (ID 24219, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Martin Terrier (leverkusen)
  1. Miguel Gutierrez (ID 32495, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Michy Batshuayi
  1. Michael Gregoritsch (ID 111483, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Mick Schmetgens (bremen)
  1. Mitchell Weiser (ID 18200, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Mitchell Weiser (bremen)
  1. Mick Schmetgens (ID 37129, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Montrell Culbreath (leverkusen)
  1. MOREIRA (displayed name, similarity 50%)
  2. Tella (displayed name, similarity 45%)
  3. GARCÍA (displayed name, similarity 26%)
  4. Kofane (displayed name, similarity 26%)
  5. Medina (displayed name, similarity 26%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Nick Bätzner (paderborn)
  1. Santiago Castaneda (ID 48702, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Niklas Stark (bremen)
  1. Jens Stage (ID 22538, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Niklas Stark (bremen)
  1. Jens Stage (ID 30066, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Noel Futkeu
  1. Nico Elvedi (ID 282229, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Noël Aséko (frankfurt)
  1. LARSSON (displayed name, similarity 50%)
  2. THEATE (displayed name, similarity 40%)
  3. ONYEDIKA (displayed name, similarity 35%)
  4. EBNOUTALIB (displayed name, similarity 32%)
  5. KAUÃ SANTOS (displayed name, similarity 32%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Noël Aséko (frankfurt)
  1. Hugo Larsson (ID 35384, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Oskar Wójcik
  1. Tim Skarke (ID 800252, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Otávio (frankfurt)
  1. EBNOUTALIB (displayed name, similarity 50%)
  2. DOAN (displayed name, similarity 40%)
  3. KOSUGI (displayed name, similarity 33%)
  4. THEATE (displayed name, similarity 33%)
  5. Collins (displayed name, similarity 31%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Paul Nebel (mainz)
  1. LEE (displayed name, similarity 50%)
  2. GRUBER (displayed name, similarity 40%)
  3. SANO (displayed name, similarity 31%)
  4. MWENE (displayed name, similarity 29%)
  5. BECKER (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Ruben Müller (paderborn)
  1. Tjark Scheller (ID 48700, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Sacha Boey (bayern)
  1. BISCHOF (displayed name, similarity 50%)
  2. UPAMECANO (displayed name, similarity 44%)
  3. Musiala (displayed name, similarity 38%)
  4. Saibari (displayed name, similarity 38%)
  5. Stanišić (displayed name, similarity 35%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sota Kawasaki
  1. Noahkai Banks (ID 1597260, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Tim Lemperle (hoffenheim)
  1. Patrick Wimmer (ID 26236, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Timur Gayret
  1. Tim Skarke (ID 800252, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Valentin Gendrey
  1. Giovanni Reyna (ID 989056, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Éric Dina Ebimbe
  1. Eric Martel (ID 988639, similarity 50%)
  2. Nicolai Remberg (ID 1064305, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Örjan Nyland (leipzig)
  1. ORBÁN (displayed name, similarity 50%)
  2. SEIWALD (displayed name, similarity 33%)
  3. VANDEVOORT (displayed name, similarity 29%)
  4. RAUM (displayed name, similarity 27%)
  5. GRUDA (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Andrej Ilic (union)
  1. VAN DEN BOSCH (displayed name, similarity 48%)
  2. Friedrich (displayed name, similarity 42%)
  3. JURANOVIĆ (displayed name, similarity 42%)
  4. LATTE LATH (displayed name, similarity 32%)
  5. ANSAH (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Andrej Kramarić (hoffenheim)
  1. HAJDARI (displayed name, similarity 48%)
  2. BURGER (displayed name, similarity 30%)
  3. Asllani (displayed name, similarity 29%)
  4. Bernardo (displayed name, similarity 27%)
  5. AVDULLAHU (displayed name, similarity 26%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Julián Malatini (bremen)
  1. NJINMAH (displayed name, similarity 48%)
  2. Grüll (displayed name, similarity 32%)
  3. LYNEN (displayed name, similarity 32%)
  4. FÜLLKRUG (displayed name, similarity 27%)
  5. MBANGULA (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Mattes Hansen (paderborn)
  1. CASTAÑEDA (displayed name, similarity 48%)
  2. BATISTA MEIER (displayed name, similarity 42%)
  3. MARINO (displayed name, similarity 33%)
  4. TER HORST (displayed name, similarity 30%)
  5. Hoffmeier (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Daniel Batz (gladbach)
  1. NICOLAS (displayed name, similarity 47%)
  2. KLEINDIENST (displayed name, similarity 38%)
  3. SANDER (displayed name, similarity 38%)
  4. HONORAT (displayed name, similarity 35%)
  5. HASHIOKA (displayed name, similarity 33%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Malik Tillman (leverkusen)
  1. Tella (displayed name, similarity 47%)
  2. MAZA (displayed name, similarity 38%)
  3. GARCÍA (displayed name, similarity 33%)
  4. Kofane (displayed name, similarity 33%)
  5. FLEKKEN (displayed name, similarity 32%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Axel Tape (leverkusen)
  1. Tella (displayed name, similarity 46%)
  2. TAPSOBA (displayed name, similarity 40%)
  3. Palacios (displayed name, similarity 38%)
  4. BADÉ (displayed name, similarity 33%)
  5. MAZA (displayed name, similarity 33%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Samuele Inácio (dortmund)
  1. KONSTANTELIAS (displayed name, similarity 46%)
  2. BENSEBAINI (displayed name, similarity 43%)
  3. Svensson (displayed name, similarity 38%)
  4. ANTON (displayed name, similarity 33%)
  5. Sabitzer (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Markus Schubert (paderborn)
  1. SCHELLER (displayed name, similarity 45%)
  2. MARINO (displayed name, similarity 30%)
  3. ULRICH (displayed name, similarity 30%)
  4. STICKER (displayed name, similarity 29%)
  5. OBERMAIR (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Paul Okon-Engstler (koeln)
  1. BÜLTER (displayed name, similarity 45%)
  2. CASTRO-MONTES (displayed name, similarity 43%)
  3. LOCHOSHVILI (displayed name, similarity 37%)
  4. Waldschmidt (displayed name, similarity 30%)
  5. SIMPSON-PUSEY (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Robert Andrich (leverkusen)
  1. FERNÁNDEZ (displayed name, similarity 45%)
  2. MOREIRA (displayed name, similarity 40%)
  3. Kofane (displayed name, similarity 32%)
  4. QUANSAH (displayed name, similarity 30%)
  5. TAPSOBA (displayed name, similarity 30%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Steffen Tigges (paderborn)
  1. Hoffmeier (displayed name, similarity 45%)
  2. BATISTA MEIER (displayed name, similarity 32%)
  3. STICKER (displayed name, similarity 30%)
  4. SCHELLER (displayed name, similarity 29%)
  5. CASTAÑEDA (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Timo Hübers (koeln)
  1. CASTRO-MONTES (displayed name, similarity 45%)
  2. SIMPSON-PUSEY (displayed name, similarity 45%)
  3. JÓHANNESSON (displayed name, similarity 38%)
  4. BÜLTER (displayed name, similarity 38%)
  5. SCHWÄBE (displayed name, similarity 35%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Amara Condé (elversberg)
  1. GYAMERAH (displayed name, similarity 44%)
  2. ONYEKA (displayed name, similarity 38%)
  3. Zimmerschied (displayed name, similarity 36%)
  4. Darvich (displayed name, similarity 35%)
  5. CAMPBELL (displayed name, similarity 33%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Cajetan Lenz (hoffenheim)
  1. BAUMANN (displayed name, similarity 44%)
  2. DE CAT (displayed name, similarity 38%)
  3. COUFAL (displayed name, similarity 35%)
  4. Asllani (displayed name, similarity 33%)
  5. HAJDARI (displayed name, similarity 33%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for David Herold (gladbach)
  1. Leopold (displayed name, similarity 44%)
  2. SANDER (displayed name, similarity 35%)
  3. NICOLAS (displayed name, similarity 33%)
  4. HASHIOKA (displayed name, similarity 32%)
  5. KLEINDIENST (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Florian Pruhs (paderborn)
  1. ULRICH (displayed name, similarity 44%)
  2. OBERMAIR (displayed name, similarity 40%)
  3. MARINO (displayed name, similarity 33%)
  4. TER HORST (displayed name, similarity 30%)
  5. MILLGRAMM (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Jannik Huth (freiburg)
  1. BACKHAUS (displayed name, similarity 44%)
  2. MATANOVIĆ (displayed name, similarity 32%)
  3. Scherhant (displayed name, similarity 32%)
  4. GINTER (displayed name, similarity 25%)
  5. Günter (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Jens Castrop (gladbach)
  1. NICOLAS (displayed name, similarity 44%)
  2. KLEINDIENST (displayed name, similarity 36%)
  3. STÖGER (displayed name, similarity 35%)
  4. HONORAT (displayed name, similarity 33%)
  5. Leopold (displayed name, similarity 33%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Jonas Hofmann (leverkusen)
  1. Kofane (displayed name, similarity 44%)
  2. FERNÁNDEZ (displayed name, similarity 29%)
  3. MAZA (displayed name, similarity 25%)
  4. GARCÍA (displayed name, similarity 22%)
  5. Medina (displayed name, similarity 22%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Justin Diehl (stuttgart)
  1. STILLER (displayed name, similarity 44%)
  2. Pejčinović (displayed name, similarity 38%)
  3. UNDAV (displayed name, similarity 38%)
  4. Andrés (displayed name, similarity 35%)
  5. FÜHRICH (displayed name, similarity 33%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Kauã Prates (dortmund)
  1. GUIRASSY (displayed name, similarity 44%)
  2. KARETSAS (displayed name, similarity 44%)
  3. KONSTANTELIAS (displayed name, similarity 43%)
  4. RYERSON (displayed name, similarity 35%)
  5. ANTON (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Keisuke Goto (freiburg)
  1. MAKENGO (displayed name, similarity 44%)
  2. BESTE (displayed name, similarity 38%)
  3. SUZUKI (displayed name, similarity 35%)
  4. ENGELHARDT (displayed name, similarity 29%)
  5. TREU (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Linus Güther (union)
  1. SCHÄFER (displayed name, similarity 44%)
  2. ANSAH (displayed name, similarity 38%)
  3. Klaus (displayed name, similarity 38%)
  4. ROTHE (displayed name, similarity 38%)
  5. KEMLEIN (displayed name, similarity 33%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Maximilian Wöber (schalke)
  1. Schallenberg (displayed name, similarity 44%)
  2. DINA EBIMBE (displayed name, similarity 40%)
  3. Ayhan (displayed name, similarity 30%)
  4. KARAMAN (displayed name, similarity 27%)
  5. T. BECKER (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Silas (mainz)
  1. SANO (displayed name, similarity 44%)
  2. Da Costa (displayed name, similarity 33%)
  3. LEE (displayed name, similarity 25%)
  4. CACI (displayed name, similarity 22%)
  5. AMIRI (displayed name, similarity 20%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Carney Chukwuemeka (dortmund)
  1. NMECHA (displayed name, similarity 43%)
  2. KARETSAS (displayed name, similarity 32%)
  3. KONSTANTELIAS (displayed name, similarity 27%)
  4. ANTON (displayed name, similarity 18%)
  5. GADOU (displayed name, similarity 18%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Dennis Seimen (stuttgart)
  1. El Khannouss (displayed name, similarity 43%)
  2. HENDRIKS (displayed name, similarity 40%)
  3. Demirović (displayed name, similarity 38%)
  4. Andrés (displayed name, similarity 33%)
  5. Pejčinović (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Dmytro Bogdanov (union)
  1. JURANOVIĆ (displayed name, similarity 43%)
  2. Rønnow (displayed name, similarity 32%)
  3. KHEDIRA (displayed name, similarity 29%)
  4. VAN DEN BOSCH (displayed name, similarity 24%)
  5. RAAB (displayed name, similarity 22%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Josha Vagnoman (stuttgart)
  1. Tiago Tomás (displayed name, similarity 43%)
  2. El Khannouss (displayed name, similarity 33%)
  3. CHABOT (displayed name, similarity 32%)
  4. JELTSCH (displayed name, similarity 30%)
  5. Pejčinović (displayed name, similarity 26%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Stanley Nsoki (union)
  1. VAN DEN BOSCH (displayed name, similarity 43%)
  2. JURANOVIĆ (displayed name, similarity 38%)
  3. ANSAH (displayed name, similarity 35%)
  4. Rønnow (displayed name, similarity 35%)
  5. KEMLEIN (displayed name, similarity 32%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Faik Sakar (augsburg)
  1. Banks (displayed name, similarity 43%)
  2. MATSIMA (displayed name, similarity 38%)
  3. FELLHAUER (displayed name, similarity 33%)
  4. KADE (displayed name, similarity 31%)
  5. Brackelmann (displayed name, similarity 30%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Felix Agu (bremen)
  1. FRIEDL (displayed name, similarity 43%)
  2. FÜLLKRUG (displayed name, similarity 38%)
  3. MBANGULA (displayed name, similarity 38%)
  4. Erebenagie (displayed name, similarity 33%)
  5. HEIN (displayed name, similarity 33%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Stefan Bell (mainz)
  1. SANO (displayed name, similarity 43%)
  2. MWENE (displayed name, similarity 40%)
  3. Da Costa (displayed name, similarity 35%)
  4. LEE (displayed name, similarity 31%)
  5. TIETZ (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Edin Džeko (schalke)
  1. DINA EBIMBE (displayed name, similarity 42%)
  2. Schallenberg (displayed name, similarity 29%)
  3. GOSENS (displayed name, similarity 27%)
  4. TANAKA (displayed name, similarity 27%)
  5. T. BECKER (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Florian Müller (freiburg)
  1. GINTER (displayed name, similarity 42%)
  2. Günter (displayed name, similarity 32%)
  3. Scherhant (displayed name, similarity 27%)
  4. TREU (displayed name, similarity 24%)
  5. GRIFO (displayed name, similarity 22%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Janik Haberer (union)
  1. SCHÄFER (displayed name, similarity 42%)
  2. JURANOVIĆ (displayed name, similarity 38%)
  3. RAAB (displayed name, similarity 38%)
  4. ANSAH (displayed name, similarity 35%)
  5. KHEDIRA (displayed name, similarity 32%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Jean-Luc Dompé (hamburg)
  1. CAPALDO (displayed name, similarity 42%)
  2. HEUER FERNANDES (displayed name, similarity 38%)
  3. Lemke (displayed name, similarity 35%)
  4. Stange (displayed name, similarity 33%)
  5. ADELINE (displayed name, similarity 32%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Jens Grahl (frankfurt)
  1. EBNOUTALIB (displayed name, similarity 42%)
  2. Højlund (displayed name, similarity 27%)
  3. Knauff (displayed name, similarity 27%)
  4. KOSUGI (displayed name, similarity 27%)
  5. THEATE (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Justin Lerma (dortmund)
  1. Sabitzer (displayed name, similarity 42%)
  2. BEIER (displayed name, similarity 38%)
  3. NMECHA (displayed name, similarity 35%)
  4. KONSTANTELIAS (displayed name, similarity 33%)
  5. BELLINGHAM (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Lucas Höler (freiburg)
  1. Scherhant (displayed name, similarity 42%)
  2. Günter (displayed name, similarity 38%)
  3. LIENHART (displayed name, similarity 33%)
  4. ENGELHARDT (displayed name, similarity 30%)
  5. BESTE (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Markus Kolke (bremen)
  1. MBANGULA (displayed name, similarity 42%)
  2. Grüll (displayed name, similarity 38%)
  3. Musah (displayed name, similarity 38%)
  4. FÜLLKRUG (displayed name, similarity 32%)
  5. Reis (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Noah Atubolu (freiburg)
  1. BACKHAUS (displayed name, similarity 42%)
  2. LIENHART (displayed name, similarity 42%)
  3. ENGELHARDT (displayed name, similarity 38%)
  4. Scherhant (displayed name, similarity 30%)
  5. TREU (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Sani Suleiman (leipzig)
  1. SEIWALD (displayed name, similarity 42%)
  2. RAUM (displayed name, similarity 38%)
  3. BANZUZI (displayed name, similarity 32%)
  4. Maksimovic (displayed name, similarity 27%)
  5. VANDEVOORT (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Shuto Machino (gladbach)
  1. HONORAT (displayed name, similarity 42%)
  2. HASHIOKA (displayed name, similarity 40%)
  3. Hack (displayed name, similarity 38%)
  4. BOLIN (displayed name, similarity 35%)
  5. SANDER (displayed name, similarity 33%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Sven Ulreich (bayern)
  1. PAVLOVIĆ (displayed name, similarity 42%)
  2. Stanišić (displayed name, similarity 42%)
  3. NEUER (displayed name, similarity 38%)
  4. BISCHOF (displayed name, similarity 33%)
  5. KIMMICH (displayed name, similarity 33%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Timur Gayret (paderborn)
  1. TER HORST (displayed name, similarity 42%)
  2. CURDA (displayed name, similarity 38%)
  3. BATISTA MEIER (displayed name, similarity 35%)
  4. STICKER (displayed name, similarity 33%)
  5. CASTAÑEDA (displayed name, similarity 30%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Badredine Bouanani (stuttgart)
  1. BREDLOW (displayed name, similarity 42%)
  2. Pejčinović (displayed name, similarity 37%)
  3. Andrés (displayed name, similarity 35%)
  4. El Khannouss (displayed name, similarity 29%)
  5. CHABOT (displayed name, similarity 26%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Benedict Hollerbach (mainz)
  1. BECKER (displayed name, similarity 42%)
  2. ZENTNER (displayed name, similarity 40%)
  3. CACI (displayed name, similarity 27%)
  4. MWENE (displayed name, similarity 26%)
  5. POSCH (displayed name, similarity 26%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Luca Schnellbacher (elversberg)
  1. GÜNTHER (displayed name, similarity 42%)
  2. CAMPBELL (displayed name, similarity 40%)
  3. Zimmerschied (displayed name, similarity 28%)
  4. Sirch (displayed name, similarity 27%)
  5. POREBA (displayed name, similarity 26%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Matthias Köbbing (koeln)
  1. Thielmann (displayed name, similarity 42%)
  2. MAINA (displayed name, similarity 40%)
  3. JÓHANNESSON (displayed name, similarity 31%)
  4. CASTRO-MONTES (displayed name, similarity 30%)
  5. SIMPSON-PUSEY (displayed name, similarity 30%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Mitchell Weiser (bremen)
  1. SCHMETGENS (displayed name, similarity 42%)
  2. PIEPER (displayed name, similarity 40%)
  3. HEIN (displayed name, similarity 33%)
  4. Reis (displayed name, similarity 33%)
  5. CHUKI (displayed name, similarity 32%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Patrick Osterhage (freiburg)
  1. BACKHAUS (displayed name, similarity 42%)
  2. Scherhant (displayed name, similarity 40%)
  3. GINTER (displayed name, similarity 36%)
  4. LIENHART (displayed name, similarity 33%)
  5. MATANOVIĆ (displayed name, similarity 32%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Alexander Røssing-Lelesiit (hamburg)
  1. ADELINE (displayed name, similarity 40%)
  2. HEUER FERNANDES (displayed name, similarity 32%)
  3. REMBERG (displayed name, similarity 27%)
  4. SAMBI LOKONGA (displayed name, similarity 23%)
  5. Lemke (displayed name, similarity 21%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Arijon Ibrahimović (bayern)
  1. PAVLOVIĆ (displayed name, similarity 40%)
  2. Stanišić (displayed name, similarity 40%)
  3. KIMMICH (displayed name, similarity 33%)
  4. BROWN (displayed name, similarity 27%)
  5. Davies (displayed name, similarity 26%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Daniel Elfadli (hamburg)
  1. ADELINE (displayed name, similarity 40%)
  2. DAKA (displayed name, similarity 35%)
  3. Stange (displayed name, similarity 32%)
  4. TORUNARIGHA (displayed name, similarity 25%)
  5. SAMBI LOKONGA (displayed name, similarity 24%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Dariusz Stalmach (bremen)
  1. Musah (displayed name, similarity 40%)
  2. NJINMAH (displayed name, similarity 36%)
  3. Reis (displayed name, similarity 32%)
  4. DEMAN (displayed name, similarity 30%)
  5. Grüll (displayed name, similarity 30%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Florian Neuhaus (gladbach)
  1. KLEINDIENST (displayed name, similarity 40%)
  2. ULLRICH (displayed name, similarity 38%)
  3. BOLIN (displayed name, similarity 32%)
  4. SANDER (displayed name, similarity 30%)
  5. HONORAT (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Jan Olschowsky (gladbach)
  1. NICOLAS (displayed name, similarity 40%)
  2. Hack (displayed name, similarity 35%)
  3. ULLRICH (displayed name, similarity 30%)
  4. HASHIOKA (displayed name, similarity 29%)
  5. LESZCZYŃSKI (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Jeanuël Belocian (leverkusen)
  1. Tella (displayed name, similarity 40%)
  2. GARCÍA (displayed name, similarity 38%)
  3. Palacios (displayed name, similarity 35%)
  4. FERNÁNDEZ (displayed name, similarity 33%)
  5. Kofane (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Jeremy Arévalo (stuttgart)
  1. BREDLOW (displayed name, similarity 40%)
  2. Karazor (displayed name, similarity 40%)
  3. Demirović (displayed name, similarity 36%)
  4. NARTEY (displayed name, similarity 32%)
  5. JELTSCH (displayed name, similarity 30%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Jonas Urbig (bayern)
  1. NEUER (displayed name, similarity 40%)
  2. Saibari (displayed name, similarity 35%)
  3. Stanišić (displayed name, similarity 33%)
  4. BROWN (displayed name, similarity 27%)
  5. OLISE (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Leo Sauer (stuttgart)
  1. STILLER (displayed name, similarity 40%)
  2. LEWELING (displayed name, similarity 38%)
  3. El Khannouss (displayed name, similarity 32%)
  4. MITTELSTÄDT (displayed name, similarity 32%)
  5. Andrés (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Luca Pfeiffer (elversberg)
  1. CAMPBELL (displayed name, similarity 40%)
  2. KEIDEL (displayed name, similarity 33%)
  3. GÜNTHER (displayed name, similarity 32%)
  4. GYAMERAH (displayed name, similarity 30%)
  5. PINCKERT (displayed name, similarity 30%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Luca Reggiani (dortmund)
  1. KARETSAS (displayed name, similarity 40%)
  2. BENSEBAINI (displayed name, similarity 36%)
  3. RYERSON (displayed name, similarity 32%)
  4. KONSTANTELIAS (displayed name, similarity 24%)
  5. ANTON (displayed name, similarity 24%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Max Grüger (schalke)
  1. KARIUS (displayed name, similarity 40%)
  2. AOUCHICHE (displayed name, similarity 33%)
  3. ADAMU (displayed name, similarity 29%)
  4. Schallenberg (displayed name, similarity 29%)
  5. GOSENS (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Nediljko Labrović (augsburg)
  1. FELLHAUER (displayed name, similarity 40%)
  2. Ribeiro (displayed name, similarity 35%)
  3. CLAUDE-MAURICE (displayed name, similarity 34%)
  4. RIEDER (displayed name, similarity 27%)
  5. Brackelmann (displayed name, similarity 22%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Nicholas Mickelson (elversberg)
  1. CAMPBELL (displayed name, similarity 40%)
  2. Zimmerschied (displayed name, similarity 34%)
  3. PINCKERT (displayed name, similarity 32%)
  4. Sirch (displayed name, similarity 27%)
  5. KEIDEL (displayed name, similarity 26%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Raif Adam (elversberg)
  1. KRISTOF (displayed name, similarity 40%)
  2. Zimmerschied (displayed name, similarity 30%)
  3. KEIDEL (displayed name, similarity 29%)
  4. POREBA (displayed name, similarity 29%)
  5. Darvich (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Rayan Philippe (hamburg)
  1. ADELINE (displayed name, similarity 40%)
  2. Stange (displayed name, similarity 32%)
  3. CAPALDO (displayed name, similarity 30%)
  4. HEUER FERNANDES (displayed name, similarity 30%)
  5. TORUNARIGHA (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Robert Skov (union)
  1. ROTHE (displayed name, similarity 40%)
  2. Friedrich (displayed name, similarity 32%)
  3. JURANOVIĆ (displayed name, similarity 32%)
  4. RAAB (displayed name, similarity 29%)
  5. Rønnow (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Zento Uno (gladbach)
  1. HONORAT (displayed name, similarity 40%)
  2. Leopold (displayed name, similarity 40%)
  3. KLEINDIENST (displayed name, similarity 32%)
  4. STÖGER (displayed name, similarity 29%)
  5. NICOLAS (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Sebastian Sebulonsen (koeln)
  1. CASTRO-MONTES (displayed name, similarity 39%)
  2. JÓHANNESSON (displayed name, similarity 33%)
  3. BÜLTER (displayed name, similarity 32%)
  4. Thielmann (displayed name, similarity 29%)
  5. MAINA (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Lukas Klostermann (leipzig)
  1. CASTELLO JR. (displayed name, similarity 38%)
  2. ORBÁN (displayed name, similarity 38%)
  3. BAKAYOKO (displayed name, similarity 33%)
  4. Estève (displayed name, similarity 27%)
  5. RÔMULO (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Youssoupha Niang (koeln)
  1. JÓHANNESSON (displayed name, similarity 38%)
  2. Thielmann (displayed name, similarity 33%)
  3. LOCHOSHVILI (displayed name, similarity 31%)
  4. MAINA (displayed name, similarity 30%)
  5. KRAUSS (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Alessandro Vogt (hoffenheim)
  1. Asllani (displayed name, similarity 38%)
  2. Moerstedt (displayed name, similarity 35%)
  3. ROTS (displayed name, similarity 33%)
  4. Prass (displayed name, similarity 32%)
  5. BAUMANN (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Alexander Meyer (dortmund)
  1. RYERSON (displayed name, similarity 38%)
  2. BEIER (displayed name, similarity 32%)
  3. NMECHA (displayed name, similarity 30%)
  4. KARETSAS (displayed name, similarity 27%)
  5. Sabitzer (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Ameen Al Dakhil (stuttgart)
  1. HENDRIKS (displayed name, similarity 38%)
  2. El Khannouss (displayed name, similarity 33%)
  3. UNDAV (displayed name, similarity 33%)
  4. PRÖMEL (displayed name, similarity 32%)
  5. JELTSCH (displayed name, similarity 30%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Bara Sapoko Ndiaye (bayern)
  1. BROWN (displayed name, similarity 38%)
  2. Saibari (displayed name, similarity 35%)
  3. DÍAZ (displayed name, similarity 30%)
  4. KANE (displayed name, similarity 30%)
  5. BISCHOF (displayed name, similarity 26%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Dan-Axel Zagadou (stuttgart)
  1. Karazor (displayed name, similarity 38%)
  2. El Khannouss (displayed name, similarity 32%)
  3. MITTELSTÄDT (displayed name, similarity 32%)
  4. Andrés (displayed name, similarity 30%)
  5. NARTEY (displayed name, similarity 30%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Frederik Schmahl (elversberg)
  1. KEIDEL (displayed name, similarity 38%)
  2. Zimmerschied (displayed name, similarity 37%)
  3. Darvich (displayed name, similarity 36%)
  4. GYAMERAH (displayed name, similarity 35%)
  5. Sirch (displayed name, similarity 30%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Kacper Potulski (mainz)
  1. Da Costa (displayed name, similarity 38%)
  2. CACI (displayed name, similarity 33%)
  3. AMIRI (displayed name, similarity 32%)
  4. POSCH (displayed name, similarity 32%)
  5. BECKER (displayed name, similarity 30%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Kevin Müller (schalke)
  1. DINA EBIMBE (displayed name, similarity 38%)
  2. KARIUS (displayed name, similarity 35%)
  3. Schallenberg (displayed name, similarity 35%)
  4. KURUÇAY (displayed name, similarity 33%)
  5. T. BECKER (displayed name, similarity 33%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Lennard Maloney (mainz)
  1. ZENTNER (displayed name, similarity 38%)
  2. LEE (displayed name, similarity 35%)
  3. MWENE (displayed name, similarity 32%)
  4. SANO (displayed name, similarity 22%)
  5. AMIRI (displayed name, similarity 21%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Michael Zetterer (frankfurt)
  1. THEATE (displayed name, similarity 38%)
  2. KOCH (displayed name, similarity 21%)
  3. Højlund (displayed name, similarity 19%)
  4. LARSSON (displayed name, similarity 18%)
  5. BURKARDT (displayed name, similarity 17%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Patrick Drewes (dortmund)
  1. KARETSAS (displayed name, similarity 38%)
  2. KONSTANTELIAS (displayed name, similarity 31%)
  3. RYERSON (displayed name, similarity 30%)
  4. Sabitzer (displayed name, similarity 29%)
  5. ANTON (displayed name, similarity 22%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Timothy Chandler (frankfurt)
  1. THEATE (displayed name, similarity 38%)
  2. DOAN (displayed name, similarity 32%)
  3. KOCH (displayed name, similarity 32%)
  4. Højlund (displayed name, similarity 29%)
  5. Collins (displayed name, similarity 18%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Arthur Chaves (hoffenheim)
  1. ROTS (displayed name, similarity 38%)
  2. BURGER (displayed name, similarity 33%)
  3. BAUMANN (displayed name, similarity 32%)
  4. AVDULLAHU (displayed name, similarity 29%)
  5. Moerstedt (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Hiroki Ito (bayern)
  1. KIMMICH (displayed name, similarity 38%)
  2. Saibari (displayed name, similarity 38%)
  3. BROWN (displayed name, similarity 29%)
  4. LAIMER (displayed name, similarity 27%)
  5. BISCHOF (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Johannes Simon Siebeking (schalke)
  1. DINA EBIMBE (displayed name, similarity 38%)
  2. Schallenberg (displayed name, similarity 35%)
  3. GOSENS (displayed name, similarity 29%)
  4. Ayhan (displayed name, similarity 22%)
  5. TANAKA (displayed name, similarity 21%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Luca Vozar (schalke)
  1. KURUÇAY (displayed name, similarity 38%)
  2. EL FAOUZI (displayed name, similarity 35%)
  3. Ljubičić (displayed name, similarity 35%)
  4. Ayhan (displayed name, similarity 29%)
  5. Sylla (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Mario Götze (frankfurt)
  1. THEATE (displayed name, similarity 38%)
  2. LARSSON (displayed name, similarity 35%)
  3. BURKARDT (displayed name, similarity 33%)
  4. EBNOUTALIB (displayed name, similarity 20%)
  5. KAUÃ SANTOS (displayed name, similarity 20%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Marius Funk (stuttgart)
  1. Andrés (displayed name, similarity 38%)
  2. HENDRIKS (displayed name, similarity 33%)
  3. Demirović (displayed name, similarity 32%)
  4. Tiago Tomás (displayed name, similarity 30%)
  5. El Khannouss (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Mert Kömür (augsburg)
  1. MATSIMA (displayed name, similarity 38%)
  2. Ribeiro (displayed name, similarity 38%)
  3. MASSENGO (displayed name, similarity 35%)
  4. GREGORITSCH (displayed name, similarity 30%)
  5. CLAUDE-MAURICE (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Niklas Stark (bremen)
  1. STAGE (displayed name, similarity 38%)
  2. NJINMAH (displayed name, similarity 33%)
  3. MBANGULA (displayed name, similarity 32%)
  4. Reis (displayed name, similarity 27%)
  5. FRIEDL (displayed name, similarity 24%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Oliver Burke (union)
  1. BURCU (displayed name, similarity 38%)
  2. QUERFELD (displayed name, similarity 32%)
  3. Friedrich (displayed name, similarity 30%)
  4. RAAB (displayed name, similarity 27%)
  5. Klaus (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Tim Skarke (union)
  1. SCHÄFER (displayed name, similarity 38%)
  2. ANSAH (displayed name, similarity 29%)
  3. ROTHE (displayed name, similarity 29%)
  4. KEMLEIN (displayed name, similarity 25%)
  5. KHEDIRA (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Alexander Schlager (bremen)
  1. Erebenagie (displayed name, similarity 37%)
  2. SCHMETGENS (displayed name, similarity 37%)
  3. STAGE (displayed name, similarity 36%)
  4. MBANGULA (displayed name, similarity 32%)
  5. DEMAN (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Maurice Krattenmacher (elversberg)
  1. Darvich (displayed name, similarity 37%)
  2. GÜNTHER (displayed name, similarity 37%)
  3. GYAMERAH (displayed name, similarity 36%)
  4. PINCKERT (displayed name, similarity 36%)
  5. Zimmerschied (displayed name, similarity 31%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Assan Ouédraogo (leipzig)
  1. BAKAYOKO (displayed name, similarity 36%)
  2. CASTELLO JR. (displayed name, similarity 33%)
  3. VANDEVOORT (displayed name, similarity 33%)
  4. RÔMULO (displayed name, similarity 30%)
  5. BANZUZI (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Bilal Nadir (hamburg)
  1. SAMBI LOKONGA (displayed name, similarity 36%)
  2. ADELINE (displayed name, similarity 35%)
  3. CAPALDO (displayed name, similarity 35%)
  4. DAKA (displayed name, similarity 29%)
  5. TORUNARIGHA (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Conrad Harder (leipzig)
  1. VANDEVOORT (displayed name, similarity 36%)
  2. Henrichs (displayed name, similarity 30%)
  3. CASTELLO JR. (displayed name, similarity 27%)
  4. NUSA (displayed name, similarity 25%)
  5. RAUM (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Fabio Chiarodia (gladbach)
  1. HASHIOKA (displayed name, similarity 36%)
  2. Leopold (displayed name, similarity 29%)
  3. ULLRICH (displayed name, similarity 29%)
  4. KLEINDIENST (displayed name, similarity 24%)
  5. DIKS (displayed name, similarity 22%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Jean-Mattéo Bahoya (frankfurt)
  1. THEATE (displayed name, similarity 36%)
  2. KAUÃ SANTOS (displayed name, similarity 31%)
  3. EBNOUTALIB (displayed name, similarity 23%)
  4. BAUM (displayed name, similarity 20%)
  5. DOAN (displayed name, similarity 20%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Kennedy Okpala (paderborn)
  1. CASTAÑEDA (displayed name, similarity 36%)
  2. NOLL (displayed name, similarity 35%)
  3. CURDA (displayed name, similarity 22%)
  4. MARINO (displayed name, similarity 21%)
  5. STICKER (displayed name, similarity 20%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Leonidas Stergiou (stuttgart)
  1. NARTEY (displayed name, similarity 36%)
  2. HENDRIKS (displayed name, similarity 33%)
  3. LEWELING (displayed name, similarity 33%)
  4. El Khannouss (displayed name, similarity 30%)
  5. UNDAV (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Lorenz Assignon (stuttgart)
  1. LEWELING (displayed name, similarity 36%)
  2. Pejčinović (displayed name, similarity 33%)
  3. El Khannouss (displayed name, similarity 32%)
  4. Andrés (displayed name, similarity 30%)
  5. HENDRIKS (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Valentin Gendrey (hoffenheim)
  1. Asllani (displayed name, similarity 36%)
  2. Moerstedt (displayed name, similarity 33%)
  3. CONTÉ (displayed name, similarity 30%)
  4. BURGER (displayed name, similarity 29%)
  5. BAUMANN (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Abdoul-Karim Coulibaly (bremen)
  1. FÜLLKRUG (displayed name, similarity 36%)
  2. MBANGULA (displayed name, similarity 29%)
  3. CHUKI (displayed name, similarity 24%)
  4. Grüll (displayed name, similarity 24%)
  5. FRIEDL (displayed name, similarity 23%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Adrian Gantenbein (schalke)
  1. Schallenberg (displayed name, similarity 36%)
  2. KARAMAN (displayed name, similarity 35%)
  3. DINA EBIMBE (displayed name, similarity 31%)
  4. ADAMU (displayed name, similarity 29%)
  5. Ayhan (displayed name, similarity 29%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Anton Donkor (schalke)
  1. TANAKA (displayed name, similarity 35%)
  2. T. BECKER (displayed name, similarity 33%)
  3. Schallenberg (displayed name, similarity 26%)
  4. ADAMU (displayed name, similarity 25%)
  5. Ayhan (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Joseph Scally (gladbach)
  1. MOHYA (displayed name, similarity 35%)
  2. Leopold (displayed name, similarity 32%)
  3. Hack (displayed name, similarity 25%)
  4. BOLIN (displayed name, similarity 24%)
  5. SANDER (displayed name, similarity 22%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Julian Pauli (koeln)
  1. EL MALA (displayed name, similarity 35%)
  2. SIMPSON-PUSEY (displayed name, similarity 35%)
  3. Thielmann (displayed name, similarity 30%)
  4. JÓHANNESSON (displayed name, similarity 27%)
  5. MAINA (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Kenny Quetant (bremen)
  1. DEMAN (displayed name, similarity 35%)
  2. NJINMAH (displayed name, similarity 32%)
  3. Erebenagie (displayed name, similarity 27%)
  4. HEIN (displayed name, similarity 25%)
  5. Itten (displayed name, similarity 24%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Lennart Karl (bayern)
  1. LAIMER (displayed name, similarity 35%)
  2. KANE (displayed name, similarity 27%)
  3. NEUER (displayed name, similarity 25%)
  4. OLISE (displayed name, similarity 25%)
  5. Musiala (displayed name, similarity 22%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Luca Jaquez (stuttgart)
  1. Karazor (displayed name, similarity 35%)
  2. UNDAV (displayed name, similarity 27%)
  3. Andrés (displayed name, similarity 25%)
  4. CHABOT (displayed name, similarity 25%)
  5. NARTEY (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Luca Philipp (hoffenheim)
  1. DAGHIM (displayed name, similarity 35%)
  2. Asllani (displayed name, similarity 33%)
  3. DE CAT (displayed name, similarity 25%)
  4. BAUMANN (displayed name, similarity 22%)
  5. HAJDARI (displayed name, similarity 22%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Lukas Kübler (freiburg)
  1. Günter (displayed name, similarity 35%)
  2. LIENHART (displayed name, similarity 32%)
  3. Scherhant (displayed name, similarity 30%)
  4. ENGELHARDT (displayed name, similarity 29%)
  5. BESTE (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Max Finkgräfe (leipzig)
  1. GRUDA (displayed name, similarity 35%)
  2. BAKAYOKO (displayed name, similarity 30%)
  3. Maksimovic (displayed name, similarity 27%)
  4. VANDEVOORT (displayed name, similarity 27%)
  5. BAKU (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for William Bøving (mainz)
  1. AMIRI (displayed name, similarity 35%)
  2. SANO (displayed name, similarity 25%)
  3. MWENE (displayed name, similarity 24%)
  4. LEE (displayed name, similarity 13%)
  5. CACI (displayed name, similarity 12%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Yannik Keitel (augsburg)
  1. Banks (displayed name, similarity 35%)
  2. RIEDER (displayed name, similarity 33%)
  3. Ribeiro (displayed name, similarity 32%)
  4. Brackelmann (displayed name, similarity 26%)
  5. GREGORITSCH (displayed name, similarity 26%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Aleksa Damjanovic (leverkusen)
  1. FLEKKEN (displayed name, similarity 35%)
  2. Kofane (displayed name, similarity 27%)
  3. SCHICK (displayed name, similarity 27%)
  4. QUANSAH (displayed name, similarity 26%)
  5. TAPSOBA (displayed name, similarity 26%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Christopher Trimmel (union)
  1. ROTHE (displayed name, similarity 35%)
  2. SCHÄFER (displayed name, similarity 32%)
  3. QUERFELD (displayed name, similarity 31%)
  4. LATTE LATH (displayed name, similarity 30%)
  5. KHEDIRA (displayed name, similarity 24%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Silvan Dominic Widmer (mainz)
  1. SANO (displayed name, similarity 35%)
  2. AMIRI (displayed name, similarity 33%)
  3. ZENTNER (displayed name, similarity 31%)
  4. BECKER (displayed name, similarity 24%)
  5. LEE (displayed name, similarity 18%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Alexander Schwolow (mainz)
  1. ZENTNER (displayed name, similarity 33%)
  2. LEE (displayed name, similarity 30%)
  3. SANO (displayed name, similarity 29%)
  4. MWENE (displayed name, similarity 27%)
  5. POSCH (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Anthony Jung (freiburg)
  1. MAKENGO (displayed name, similarity 33%)
  2. BACKHAUS (displayed name, similarity 32%)
  3. MATANOVIĆ (displayed name, similarity 30%)
  4. Scherhant (displayed name, similarity 30%)
  5. TREU (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Arthur (leverkusen)
  1. GARCÍA (displayed name, similarity 33%)
  2. QUANSAH (displayed name, similarity 31%)
  3. GUTIÉRREZ (displayed name, similarity 27%)
  4. BADÉ (displayed name, similarity 20%)
  5. MAZA (displayed name, similarity 20%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Bruno Ogbus (freiburg)
  1. BACKHAUS (displayed name, similarity 33%)
  2. TREU (displayed name, similarity 29%)
  3. BESTE (displayed name, similarity 27%)
  4. GRIFO (displayed name, similarity 27%)
  5. Günter (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Christoph Baumgartner (leipzig)
  1. CASTELLO JR. (displayed name, similarity 33%)
  2. RAUM (displayed name, similarity 33%)
  3. ORBÁN (displayed name, similarity 32%)
  4. BAKU (displayed name, similarity 25%)
  5. Reitz (displayed name, similarity 24%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Clemens Lippmann (paderborn)
  1. CASTAÑEDA (displayed name, similarity 33%)
  2. MARINO (displayed name, similarity 29%)
  3. OBERMAIR (displayed name, similarity 26%)
  4. SCHELLER (displayed name, similarity 26%)
  5. Hoffmeier (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Cyriaque Irié (freiburg)
  1. Yilmaz (displayed name, similarity 33%)
  2. BACKHAUS (displayed name, similarity 30%)
  3. Scherhant (displayed name, similarity 29%)
  4. TREU (displayed name, similarity 25%)
  5. BESTE (displayed name, similarity 24%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Farès Chaïbi (frankfurt)
  1. LARSSON (displayed name, similarity 33%)
  2. EBNOUTALIB (displayed name, similarity 29%)
  3. KAUÃ SANTOS (displayed name, similarity 29%)
  4. KOCH (displayed name, similarity 27%)
  5. KOSUGI (displayed name, similarity 24%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Florian Le Joncour (elversberg)
  1. PINCKERT (displayed name, similarity 33%)
  2. Futkeu (displayed name, similarity 27%)
  3. POREBA (displayed name, similarity 27%)
  4. Darvich (displayed name, similarity 26%)
  5. KRISTOF (displayed name, similarity 26%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Frank Lehmann (elversberg)
  1. Futkeu (displayed name, similarity 33%)
  2. GYAMERAH (displayed name, similarity 30%)
  3. ROHR (displayed name, similarity 25%)
  4. Sirch (displayed name, similarity 24%)
  5. KEIDEL (displayed name, similarity 22%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Fábio Silva (dortmund)
  1. KARETSAS (displayed name, similarity 33%)
  2. Sabitzer (displayed name, similarity 33%)
  3. BENSEBAINI (displayed name, similarity 30%)
  4. ANTON (displayed name, similarity 27%)
  5. BEIER (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Koki Machida (hoffenheim)
  1. HAJDARI (displayed name, similarity 33%)
  2. KABAK (displayed name, similarity 25%)
  3. COUFAL (displayed name, similarity 24%)
  4. DAGHIM (displayed name, similarity 24%)
  5. Wimmer (displayed name, similarity 24%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Michy Batshuayi (frankfurt)
  1. BAUM (displayed name, similarity 33%)
  2. THEATE (displayed name, similarity 30%)
  3. BURKARDT (displayed name, similarity 27%)
  4. KAUÃ SANTOS (displayed name, similarity 25%)
  5. KOCH (displayed name, similarity 22%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Nico Schlotterbeck (dortmund)
  1. KONSTANTELIAS (displayed name, similarity 33%)
  2. Sabitzer (displayed name, similarity 32%)
  3. BEIER (displayed name, similarity 27%)
  4. KOBEL (displayed name, similarity 27%)
  5. NMECHA (displayed name, similarity 26%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Patrice Covic (bremen)
  1. FRIEDL (displayed name, similarity 33%)
  2. Erebenagie (displayed name, similarity 27%)
  3. Reis (displayed name, similarity 25%)
  4. Itten (displayed name, similarity 24%)
  5. STAGE (displayed name, similarity 24%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Rav van den Berg (koeln)
  1. JÓHANNESSON (displayed name, similarity 33%)
  2. BÜLTER (displayed name, similarity 32%)
  3. SCHWÄBE (displayed name, similarity 30%)
  4. Thielmann (displayed name, similarity 27%)
  5. CASTRO-MONTES (displayed name, similarity 24%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Robin Hranác (hoffenheim)
  1. BAUMANN (displayed name, similarity 33%)
  2. Bernardo (displayed name, similarity 32%)
  3. ROTS (displayed name, similarity 27%)
  4. CONTÉ (displayed name, similarity 25%)
  5. KABAK (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Ron-Robert Zieler (koeln)
  1. Thielmann (displayed name, similarity 33%)
  2. LOCHOSHVILI (displayed name, similarity 31%)
  3. CASTRO-MONTES (displayed name, similarity 30%)
  4. BÜLTER (displayed name, similarity 29%)
  5. SIMPSON-PUSEY (displayed name, similarity 22%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Tim Boss (elversberg)
  1. MOKWA (displayed name, similarity 33%)
  2. Zimmerschied (displayed name, similarity 32%)
  3. PETKOV (displayed name, similarity 31%)
  4. KRISTOF (displayed name, similarity 29%)
  5. CAMPBELL (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Uchenna Ogundu (augsburg)
  1. Brackelmann (displayed name, similarity 33%)
  2. DAHMEN (displayed name, similarity 32%)
  3. BEHRENS (displayed name, similarity 30%)
  4. MASSENGO (displayed name, similarity 29%)
  5. GOUWELEEUW (displayed name, similarity 26%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Kristijan Jakić (augsburg)
  1. GREGORITSCH (displayed name, similarity 32%)
  2. Banks (displayed name, similarity 32%)
  3. Ribeiro (displayed name, similarity 29%)
  4. Brackelmann (displayed name, similarity 24%)
  5. CLAUDE-MAURICE (displayed name, similarity 22%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Leopold Zingerle (leipzig)
  1. VANDEVOORT (displayed name, similarity 32%)
  2. Estève (displayed name, similarity 29%)
  3. SEIWALD (displayed name, similarity 27%)
  4. CASTELLO JR. (displayed name, similarity 24%)
  5. Gomis (displayed name, similarity 20%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Arthur Vermeeren (leipzig)
  1. RAUM (displayed name, similarity 32%)
  2. Estève (displayed name, similarity 29%)
  3. Henrichs (displayed name, similarity 26%)
  4. VANDEVOORT (displayed name, similarity 24%)
  5. BAKU (displayed name, similarity 21%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Ayoube Amaimouni (frankfurt)
  1. BAUM (displayed name, similarity 32%)
  2. UZUN (displayed name, similarity 32%)
  3. KOSUGI (displayed name, similarity 29%)
  4. Collins (displayed name, similarity 27%)
  5. LARSSON (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Christian Gomis (schalke)
  1. Ayhan (displayed name, similarity 32%)
  2. Schallenberg (displayed name, similarity 31%)
  3. GOSENS (displayed name, similarity 30%)
  4. KARIUS (displayed name, similarity 30%)
  5. TANAKA (displayed name, similarity 30%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Ellyes Skhiri (frankfurt)
  1. Collins (displayed name, similarity 32%)
  2. LARSSON (displayed name, similarity 32%)
  3. ONYEDIKA (displayed name, similarity 30%)
  4. EBNOUTALIB (displayed name, similarity 27%)
  5. KOCH (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Lucas Vázquez (leverkusen)
  1. TAPSOBA (displayed name, similarity 32%)
  2. Palacios (displayed name, similarity 30%)
  3. FERNÁNDEZ (displayed name, similarity 29%)
  4. GUTIÉRREZ (displayed name, similarity 29%)
  5. BADÉ (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Lúkas Petersson (hoffenheim)
  1. Prass (displayed name, similarity 32%)
  2. BURGER (displayed name, similarity 30%)
  3. Asllani (displayed name, similarity 29%)
  4. BAUMANN (displayed name, similarity 29%)
  5. Bernardo (displayed name, similarity 27%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Malik Pimpong (frankfurt)
  1. Collins (displayed name, similarity 32%)
  2. LARSSON (displayed name, similarity 32%)
  3. EBNOUTALIB (displayed name, similarity 27%)
  4. DOAN (displayed name, similarity 25%)
  5. KOCH (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Sota Kawasaki (mainz)
  1. Da Costa (displayed name, similarity 32%)
  2. CACI (displayed name, similarity 25%)
  3. SANO (displayed name, similarity 25%)
  4. AMIRI (displayed name, similarity 24%)
  5. TIETZ (displayed name, similarity 24%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Eric Martel (mainz)
  1. LEE (displayed name, similarity 31%)
  2. AMIRI (displayed name, similarity 27%)
  3. MWENE (displayed name, similarity 27%)
  4. TIETZ (displayed name, similarity 27%)
  5. BECKER (displayed name, similarity 25%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Finn Porath (schalke)
  1. DINA EBIMBE (displayed name, similarity 30%)
  2. KATIĆ (displayed name, similarity 27%)
  3. TANAKA (displayed name, similarity 25%)
  4. KARAMAN (displayed name, similarity 24%)
  5. KURUÇAY (displayed name, similarity 24%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Kennet Eichhorn (leverkusen)
  1. Kofane (displayed name, similarity 30%)
  2. FLEKKEN (displayed name, similarity 29%)
  3. MOREIRA (displayed name, similarity 29%)
  4. FERNÁNDEZ (displayed name, similarity 26%)
  5. Tella (displayed name, similarity 21%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for El Chadaille Bitshiabu (leipzig)
  1. Henrichs (displayed name, similarity 29%)
  2. Reitz (displayed name, similarity 24%)
  3. SEIWALD (displayed name, similarity 22%)
  4. CASTELLO JR. (displayed name, similarity 20%)
  5. BAKU (displayed name, similarity 17%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Filippo Mane (dortmund)
  1. BELLINGHAM (displayed name, similarity 29%)
  2. ANTON (displayed name, similarity 25%)
  3. BEIER (displayed name, similarity 25%)
  4. KONSTANTELIAS (displayed name, similarity 25%)
  5. NMECHA (displayed name, similarity 24%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Ransford Königsdörffer (mainz)
  1. ZENTNER (displayed name, similarity 29%)
  2. KOHR (displayed name, similarity 24%)
  3. SANO (displayed name, similarity 24%)
  4. BECKER (displayed name, similarity 22%)
  5. GRUBER (displayed name, similarity 22%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Andreas Hanche-Olsen (mainz)
  1. SANO (displayed name, similarity 27%)
  2. POSCH (displayed name, similarity 26%)
  3. LEE (displayed name, similarity 19%)
  4. CACI (displayed name, similarity 18%)
  5. AMIRI (displayed name, similarity 17%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Eliesse Ben Seghir (leverkusen)
  1. Medina (displayed name, similarity 27%)
  2. SCHICK (displayed name, similarity 27%)
  3. FLEKKEN (displayed name, similarity 26%)
  4. MOREIRA (displayed name, similarity 26%)
  5. QUANSAH (displayed name, similarity 26%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Oskar Wójcik (bremen)
  1. CHUKI (displayed name, similarity 25%)
  2. Musah (displayed name, similarity 25%)
  3. STAGE (displayed name, similarity 25%)
  4. FRIEDL (displayed name, similarity 24%)
  5. FÜLLKRUG (displayed name, similarity 21%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Serge Gnabry (bayern)
  1. BROWN (displayed name, similarity 25%)
  2. NEUER (displayed name, similarity 25%)
  3. OLISE (displayed name, similarity 25%)
  4. LAIMER (displayed name, similarity 24%)
  5. Musiala (displayed name, similarity 22%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Yussuf Poulsen (hamburg)
  1. SAMBI LOKONGA (displayed name, similarity 24%)
  2. Lemke (displayed name, similarity 22%)
  3. MUHEIM (displayed name, similarity 21%)
  4. Stange (displayed name, similarity 21%)
  5. ADELINE (displayed name, similarity 20%)

Choose a candidate number, or press Enter to skip (score 0):

Input summary
  Matchday: 1; ratings: team_player_average_ratings_2026-08-19_10-00-09_511464+0200.csv
  Ligainsider (weight 4): ligainsider_bundesliga_lineups_20260819_095720.json
  Kickbase (weight 3): kickbase_bundesliga_lineups_20260819_125416.json
  Rotowire (weight 1): rotowire_bundesliga_lineups_20260819_095810.json
  Alternative starting-chance decay: 0.45
  Questionable-injury starting-chance penalty: 0.15
  Output: C:\kickbase project\outputs\expected_points\expected_points_20260818_204143_+0200_sofascore_bundesliga_rating_odds_lineup_20260819_141302_+0200.csv

Team odds and expected match points

,team,provider,win_probability,draw_probability,loss_probability,expected_match_points
0,augsburg,FotMob,0.439632,0.255462,0.304906,1.574358
1,bayern,FotMob,0.746846,0.141566,0.111588,2.382105
2,bremen,FotMob,0.270567,0.255941,0.473492,1.067642
3,dortmund,FotMob,0.728590,0.166170,0.105241,2.351939
4,elversberg,FotMob,0.182306,0.206085,0.611608,0.753004
5,frankfurt,FotMob,0.364604,0.256208,0.379188,1.350020
6,freiburg,FotMob,0.473492,0.255941,0.270567,1.676417
7,gladbach,FotMob,0.178859,0.197490,0.623652,0.734066
8,hamburg,FotMob,0.105241,0.166170,0.728590,0.481892
9,hoffenheim,FotMob,0.421053,0.263158,0.315789,1.526316
10,koeln,FotMob,0.315789,0.263158,0.421053,1.210526
11,leipzig,FotMob,0.623652,0.197490,0.178859,2.068445
12,leverkusen,FotMob,0.611608,0.206085,0.182306,2.040910
13,mainz,FotMob,0.567332,0.231084,0.201584,1.933080
14,paderborn,FotMob,0.201584,0.231084,0.567332,0.835836
15,schalke,FotMob,0.304906,0.255462,0.439632,1.170180
16,stuttgart,FotMob,0.111588,0.141566,0.746846,0.476329
17,union,FotMob,0.379188,0.256208,0.364604,1.393772

Player score review (non-positive or non-exact ratings)

,name,team,rating_status,lineup_status,rating,expected_match_points,ligainsider_starting_chance,kickbase_starting_chance,rotowire_starting_chance,questionable_injury_penalty,starting_chance,score
2,Sven Ulreich,bayern,missing_rating,not_evaluated_missing_rating,0.00,2.382105,0.000000,0.0,0.0,0.0,0.000000,0.000000
4,Serge Gnabry,bayern,missing_rating,not_evaluated_missing_rating,0.00,2.382105,0.000000,0.0,0.0,0.0,0.000000,0.000000
5,Dayotchanculle Upamecano,bayern,override,ligainsider:override; kickbase:exact; rotowire...,7.30,2.382105,0.310345,1.0,1.0,0.0,0.655172,11.393031
10,Jonas Urbig,bayern,exact,ligainsider:missing; kickbase:missing; rotowir...,7.28,2.382105,0.000000,0.0,0.0,0.0,0.000000,0.000000
11,Hiroki Ito,bayern,exact,ligainsider:missing; kickbase:missing; rotowir...,6.85,2.382105,0.000000,0.0,0.0,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
463,Christian Gomis,schalke,missing_rating,not_evaluated_missing_rating,0.00,1.170180,0.000000,0.0,0.0,0.0,0.000000,0.000000
464,Luca Vozar,schalke,missing_rating,not_evaluated_missing_rating,0.00,1.170180,0.000000,0.0,0.0,0.0,0.000000,0.000000
465,Satoshi Tanaka,schalke,missing_rating,not_evaluated_missing_rating,0.00,1.170180,0.000000,0.0,0.0,0.0,0.000000,0.000000
466,Johannes Simon Siebeking,schalke,missing_rating,not_evaluated_missing_rating,0.00,1.170180,0.000000,0.0,0.0,0.0,0.000000,0.000000
467,Adil Aouchiche,schalke,missing_rating,not_evaluated_missing_rating,0.00,1.170180,0.000000,0.0,0.0,0.0,0.000000,0.000000