# SofaScore overall rating × odds × lineup score

Creates optimizer-ready scores from recency-weighted overall ratings, expected match points from odds, and configurable-weight LigaInsider, Kickbase, Kicker, and RotoWire starting chances. LigaInsider and Kicker alternatives use configurable geometric per-slot decay; repeated Kickbase alternatives are pooled as team-level evidence and normalized to an expected XI while remaining below displayed starters. The final score is `score multiplier × rating × expected match points × starting chance`; the exported CSV records the provider-specific chances, the injury penalty, multiplier, and final `score` column.

Confirmed SofaScore, LigaInsider, and RotoWire name matches are stored with Transfermarkt mappings in `data/reference/player_name_cross_references.csv`. Kickbase and Kicker display names resolve to a unique same-team KBStats last name, then first name; only shared-name or no-match candidates at 50% similarity or higher are shown for notebook confirmation and stored separately in `data/reference/kickbase_player_name_cross_references.csv`. Those mappings are scoped by provider, team, and KBStats player, so one provider's display label cannot override the other.

Overall ratings use team-match weights 28%, 24%, 20%, 16%, and 12% from newest to oldest, equally for good and bad performances. Missing ratings are excluded and remaining weights normalized without shifting match slots. The matching ratings JSON and its referenced team-form snapshot are required. The exported `sofascore_average_rating` is the weighted rating rounded half-up to two decimals. Bundesliga and standalone average-rating calculators retain their existing averages.

Set the notebook's QUES penalty, alternative-decay, source-weight, and score-multiplier variables to tune scoring. A provider-level QUES reduction is applied before LigaInsider or Kickbase formation-slot alternatives are normalized.

In [1]:
import sys
from pathlib import Path

# Absolute starting-chance reduction for a `QUES` injury flag from a lineup source.
QUESTIONABLE_INJURY_STARTING_CHANCE_PENALTY = 0.15
# Each rank is 45% of the preceding alternative before its slot is normalized.
ALTERNATIVE_STARTING_CHANCE_DECAY = 0.45
# Relative trust weights for active lineup sources; use 0 to disable one.
LINEUP_SOURCE_WEIGHTS = {'ligainsider': 4.0, 'kickbase': 3.0, 'kicker': 2.0, 'rotowire': 1.0}
# You will confirm whether each source is current for the selected matchday.
# Average of the previous multiplier and the new fitted scale.
SCORE_MULTIPLIER = (9.4739 + 10.5385) / 2  # 10.0062

def locate_project_root() -> Path:
    starts = [Path.cwd().resolve()]
    notebook_path = globals().get('__vsc_ipynb_file__')
    if isinstance(notebook_path, str) and notebook_path.strip():
        starts.insert(0, Path(notebook_path).expanduser().resolve().parent)
    for start in starts:
        for candidate in (start, *start.parents):
            if (candidate / 'project_paths.py').is_file():
                return candidate
    raise FileNotFoundError('Could not locate project_paths.py.')

PROJECT_ROOT = locate_project_root()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import importlib
import sofascore_rating_odds_lineup_score as score_creation
importlib.reload(score_creation)  # pick up local score-formula changes without restarting the kernel
from sofascore_rating_odds_lineup_score import run_score_creation
result = run_score_creation(
    'overall',
    questionable_injury_starting_chance_penalty=QUESTIONABLE_INJURY_STARTING_CHANCE_PENALTY,
    alternative_starting_chance_decay=ALTERNATIVE_STARTING_CHANCE_DECAY,
    lineup_source_weights=LINEUP_SOURCE_WEIGHTS,
    score_multiplier=SCORE_MULTIPLIER,
)

Matchday for odds and lineups:  3
Is the Ligainsider predicted lineup snapshot (ligainsider_bundesliga_lineups_20260911_094158.json) accurate for matchday 3, or from the previous matchday? [a]ccurate/[p]revious:  a
Is the Kickbase predicted lineup snapshot (kickbase_bundesliga_lineups_20260911_095348.json) accurate for matchday 3, or from the previous matchday? [a]ccurate/[p]revious:  a
Is the Kicker predicted lineup snapshot (kicker_bundesliga_lineups_20260911_094243.json) accurate for matchday 3, or from the previous matchday? [a]ccurate/[p]revious:  a
Is the Rotowire predicted lineup snapshot (rotowire_bundesliga_lineups_20260911_094138.json) accurate for matchday 3, or from the previous matchday? [a]ccurate/[p]revious:  a

No exact match for kickbase lineup for Nicolas Kühn (gladbach)
  1. NICOLAS (displayed name, similarity 78%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Nicolas Kühn (gladbach)
  1. Nicolas (displayed name, similarity 78%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Vitalie Becker (schalke)
  1. T. BECKER (displayed name, similarity 70%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Vitalie Becker (schalke)
  1. T. Becker (displayed name, similarity 70%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Nicholas Mickelson (elversberg)
  1. Kristof (displayed name, similarity 65%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Nicholas Mickelson (elversberg)
  1. Nicolas Kristof (ID 26473, similarity 65%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Nicholas Mickelson (elversberg)
  1. Nicolas Kristof (ID 48713, similarity 65%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Lucas Höler (freiburg)
  1. Lukas Kuebler (ID 1935, similarity 64%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Sima Suso (augsburg)
  1. MASSENGO (displayed name, similarity 62%)
  2. MATSIMA (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Sima Suso (augsburg)
  1. Massengo (displayed name, similarity 62%)
  2. M. Wolf (displayed name, similarity 56%)
  3. Matsima (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Emre Can (dortmund)
  1. NMECHA (displayed name, similarity 62%)
  2. Veerman (displayed name, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Vitalie Becker (schalke)
  1. Timo Becker (ID 11068, similarity 61%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Vitalie Becker (schalke)
  1. Timo Becker (ID 30648, similarity 61%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Kevin Stöger (gladbach)
  1. Diks (displayed name, similarity 60%)
  2. Kleindienst (displayed name, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Kevin Stöger (gladbach)
  1. Kevin Diks (ID 21650, similarity 60%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Luka Duric (paderborn)
  1. Curda (displayed name, similarity 60%)
  2. Ulrich (displayed name, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Luka Duric (paderborn)
  1. Laurin Curda (ID 36261, similarity 60%)
  2. Laurin Ulrich (ID 27568, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Luka Duric (paderborn)
  1. Laurin Curda (ID 48704, similarity 60%)
  2. Laurin Ulrich (ID 37153, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Christoph Baumgartner (leipzig)
  1. Nkunku (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Christoph Baumgartner (leipzig)
  1. Christopher Nkunku (ID 12446, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Christoph Baumgartner (leipzig)
  1. Christopher Nkunku (ID 20544, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jan Olschowsky (gladbach)
  1. Jan Leszczynski (ID 38925, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Junior Adamu (schalke)
  1. Junior Dina Ebimbe (ID 26881, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Markus Schubert (paderborn)
  1. Scheller (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Markus Schubert (paderborn)
  1. Tjark Scheller (ID 36890, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Markus Schubert (paderborn)
  1. Tjark Scheller (ID 48700, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Isac Lidberg (gladbach)
  1. SANDER (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Isac Lidberg (gladbach)
  1. Sander (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Otávio (frankfurt)
  1. M. Götze (displayed name, similarity 59%)
  2. Ebnoutalib (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Tim Oermann (leverkusen)
  1. MOREIRA (displayed name, similarity 59%)
  2. Tillman (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Tim Oermann (leverkusen)
  1. Tillman (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Jannik Huth (freiburg)
  1. Beste (displayed name, similarity 58%)
  2. Engelhardt (displayed name, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Jannik Huth (freiburg)
  1. Jan-Niklas Beste (ID 26591, similarity 58%)
  2. Yannik Engelhardt (ID 36578, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Mert Can Ayhan (schalke)
  1. Kurucay (displayed name, similarity 58%)
  2. Tanaka (displayed name, similarity 56%)
  3. Karaman (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Nicolas Kühn (gladbach)
  1. Moritz Nicolas (ID 6295, similarity 58%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Nicolas Kühn (gladbach)
  1. Moritz Nicolas (ID 25259, similarity 58%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Cédric Itten (bremen)
  1. Dinkci (displayed name, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Ezechiel Banzuzi (leipzig)
  1. El Aynaoui (displayed name, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Felix Nmecha (dortmund)
  1. Bellingham (displayed name, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Junior Adamu (schalke)
  1. Eric Junior (ID 27879, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Luca Pfeiffer (elversberg)
  1. Luca Sirch (ID 26346, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Noah Darvich (elversberg)
  1. Mokwa (displayed name, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Oliver Burke (union)
  1. Livan Burcu (ID 36114, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Oliver Burke (union)
  1. Livan Burcu (ID 43803, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Stefan Bell (mainz)
  1. Posch (displayed name, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Stefan Bell (mainz)
  1. Stefan Posch (ID 12798, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Stefan Bell (mainz)
  1. Stefan Posch (ID 23594, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Janik Bachmann (schalke)
  1. Karaman (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Janik Bachmann (schalke)
  1. Kenan Karaman (ID 2676, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Jonathan Tah (bayern)
  1. Brown (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Marius Bülter (koeln)
  1. Marvin Schwabe (ID 34845, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Borna Sosa (koeln)
  1. Krauß (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Borna Sosa (koeln)
  1. Tom Krauss (ID 20244, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Borna Sosa (koeln)
  1. Tom Krauss (ID 29789, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Emre Can (dortmund)
  1. Felix Nmecha (ID 25090, similarity 56%)
  2. Waldemar Anton (ID 5837, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Mert Can Ayhan (schalke)
  1. TANAKA (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Robert Skov (union)
  1. Rothe (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Sima Suso (augsburg)
  1. Marius Wolf (ID 5670, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Sima Suso (augsburg)
  1. Marius Wolf (ID 21031, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Sven Michel (paderborn)
  1. SCHELLER (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Sven Michel (paderborn)
  1. Scheller (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Tiago Tomás (stuttgart)
  1. VAGNOMAN (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Tiago Tomás (stuttgart)
  1. Vagnoman (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Tim Binder (bayern)
  1. M.-J. Kim (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Tim Binder (bayern)
  1. Kim Min-Jae (ID 34953, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Christian Günter (freiburg)
  1. Ginter (displayed name, similarity 55%)
  2. Scherhant (displayed name, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Christian Günter (freiburg)
  1. Matthias Ginter (ID 17592, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for András Schäfer (union)
  1. Aebischer (displayed name, similarity 55%)
  2. van den Bosch (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Jan Thielmann (koeln)
  1. S. El Mala (displayed name, similarity 55%)
  2. Johannesson (displayed name, similarity 51%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jan Thielmann (koeln)
  1. Said El Mala (ID 38546, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Jan Thielmann (koeln)
  1. Said El Mala (ID 46716, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Luca Sirch (elversberg)
  1. Pinckert (displayed name, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Luca Sirch (elversberg)
  1. Lukas Pinckert (ID 48715, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Martin Terrier (leverkusen)
  1. GUTIÉRREZ (displayed name, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Reigan Heskey (koeln)
  1. Moore (displayed name, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Afonso Moreira (leverkusen)
  1. Medina (displayed name, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Ermedin Demirović (stuttgart)
  1. Pejcinovic (displayed name, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jannik Huth (freiburg)
  1. Yannik Engelhardt (ID 20278, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Luca Schnellbacher (elversberg)
  1. Luca Sirch (ID 26346, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Luca Waldschmidt (koeln)
  1. Joel Schmied (ID 38328, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Marius Bülter (koeln)
  1. Schwäbe (displayed name, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Borna Sosa (koeln)
  1. KRAUSS (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Emre Can (dortmund)
  1. J. Veerman (displayed name, similarity 53%)
  2. Anton (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Guéla Doué (leverkusen)
  1. Miguel (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Luka Duric (paderborn)
  1. ULRICH (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Marvin Friedrich (union)
  1. Rönnow (displayed name, similarity 53%)
  2. Ljubicic (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Tim Binder (bayern)
  1. Laimer (displayed name, similarity 53%)
  2. MINJAE (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Bambasé Conté (hoffenheim)
  1. Baumann (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Justin Lerma (dortmund)
  1. J. Veerman (displayed name, similarity 53%)
  2. Anton (displayed name, similarity 50%)
  3. Ryerson (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Paul Nebel (mainz)
  1. J.-S. Lee (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Paul Nebel (mainz)
  1. Jaesung Lee (ID 21202, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Ruben Müller (paderborn)
  1. SCHELLER (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Ruben Müller (paderborn)
  1. Scheller (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Amara Condé (elversberg)
  1. Onyeka (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Amara Condé (elversberg)
  1. Francis Onyeka (ID 36948, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Amara Condé (elversberg)
  1. Francis Onyeka (ID 40979, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Daniel Batz (gladbach)
  1. Nicolas (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Danny Da Costa (mainz)
  1. Caci (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Danny Da Costa (mainz)
  1. Anthony Caci (ID 26102, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Danny Da Costa (mainz)
  1. Anthony Caci (ID 25792, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Janik Haberer (union)
  1. R. Khedira (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Janik Haberer (union)
  1. Rani Khedira (ID 2122, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Janik Haberer (union)
  1. Rani Khedira (ID 21666, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Sebastian Klaas (paderborn)
  1. CASTAÑEDA (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Sebastian Klaas (paderborn)
  1. Castaneda (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Alexander Meyer (dortmund)
  1. Ryerson (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Alexander Meyer (dortmund)
  1. Julian Ryerson (ID 18478, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Alexander Meyer (dortmund)
  1. Julian Ryerson (ID 28864, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Nediljko Labrović (augsburg)
  1. IBRAHIMOVIĆ (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Nediljko Labrović (augsburg)
  1. Ibrahimovic (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Ron-Robert Zieler (koeln)
  1. Okon-Engstler (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Samuele Inácio (dortmund)
  1. Bensebaini (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Samuele Inácio (dortmund)
  1. Ramy Bensebaini (ID 7791, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Samuele Inácio (dortmund)
  1. Ramy Bensebaini (ID 20296, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Junior Adamu (schalke)
  1. Dina Ebimbe (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Andrej Kramarić (hoffenheim)
  1. Daghim (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Andrej Kramarić (hoffenheim)
  1. Adam Daghim (ID 44189, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Christian Günter (freiburg)
  1. SCHERHANT (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Elias Baum (frankfurt)
  1. Kosugi (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Emre Can (dortmund)
  1. Waldemar Anton (ID 20160, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Florian Pruhs (paderborn)
  1. Ulrich (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Florian Pruhs (paderborn)
  1. Laurin Ulrich (ID 27568, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Florian Pruhs (paderborn)
  1. Laurin Ulrich (ID 37153, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Frank Lehmann (elversberg)
  1. Florian Le Joncour (ID 37052, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Guéla Doué (leverkusen)
  1. Miguel Gutierrez (ID 24219, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Guéla Doué (leverkusen)
  1. Miguel Gutierrez (ID 32495, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Isac Lidberg (gladbach)
  1. Philipp Sander (ID 18612, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Isac Lidberg (gladbach)
  1. Philipp Sander (ID 43368, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Jamal Musiala (bayern)
  1. Luis Diaz (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Janik Bachmann (schalke)
  1. Karaman (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Janis Blaswich (leverkusen)
  1. QUANSAH (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Janis Blaswich (leverkusen)
  1. Quansah (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jens Castrop (gladbach)
  1. Joe Scally (ID 23700, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Jens Castrop (gladbach)
  1. Joe Scally (ID 26680, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Jens Grahl (frankfurt)
  1. Maluze (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jens Grahl (frankfurt)
  1. Jeremiaha Maluze (ID 38581, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Justin Diehl (stuttgart)
  1. Stiller (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Justin Lerma (dortmund)
  1. Silva (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Justin Lerma (dortmund)
  1. Julian Ryerson (ID 18478, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Justin Lerma (dortmund)
  1. Julian Ryerson (ID 28864, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Linus Güther (union)
  1. AEBISCHER (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Linus Güther (union)
  1. Aebischer (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Marcel Hoffmeier (paderborn)
  1. Scheller (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Marcel Hoffmeier (paderborn)
  1. Tjark Scheller (ID 36890, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Marcel Hoffmeier (paderborn)
  1. Tjark Scheller (ID 48700, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Martin Adeline (hamburg)
  1. El Ouahdi (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Martin Adeline (hamburg)
  1. Zakaria El Ouahdi (ID 38592, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Martin Adeline (hamburg)
  1. Zakaria El Ouahdi (ID 43675, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Martin Terrier (leverkusen)
  1. Miguel (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Martin Terrier (leverkusen)
  1. Miguel Gutierrez (ID 24219, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Martin Terrier (leverkusen)
  1. Miguel Gutierrez (ID 32495, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Marvin Friedrich (union)
  1. Marin Ljubicic (ID 36465, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Marvin Friedrich (union)
  1. Marin Ljubicic (ID 40575, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Matthias Köbbing (koeln)
  1. Thijs Dallinga (ID 36506, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Mert Can Ayhan (schalke)
  1. Kenan Karaman (ID 2676, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Montrell Culbreath (leverkusen)
  1. MOREIRA (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Otávio (frankfurt)
  1. EBNOUTALIB (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Paul Nebel (mainz)
  1. LEE (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Ruben Müller (paderborn)
  1. Tjark Scheller (ID 48700, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Sota Kawasaki (mainz)
  1. POTULSKI (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Sota Kawasaki (mainz)
  1. Potulski (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Stefano Marino (paderborn)
  1. Pieringer (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Örjan Nyland (leipzig)
  1. ORBÁN (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Örjan Nyland (leipzig)
  1. Orban (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Moussa Ndiaye
  1. Moussa Diaby (ID 855817, similarity 87%)
  2. Moussa Sylla (ID 861980, similarity 61%)
  3. Luis Díaz (ID 883537, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Luca Jaquez
  1. Lucas Vázquez (ID 255239, similarity 82%)
  2. Cajetan Lenz (ID 2077300, similarity 57%)
  3. Luca Vozar (ID 2255221, similarity 53%)
  4. Lucas Höler (ID 280009, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nicolas Kühn
  1. Nicolas-Gerrit Kühn (ID 877835, similarity 79%)
  2. Nicholas Mickelson (ID 900264, similarity 64%)
  3. Niclas Füllkrug (ID 132645, similarity 64%)
  4. Nicolas Kristof (ID 1131080, similarity 64%)
  5. Moritz Nicolas (ID 578166, similarity 58%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Mitchell Weiser
  1. Michael Olise (ID 978838, similarity 77%)
  2. Michel Aebischer (ID 850891, similarity 76%)
  3. Michael Gregoritsch (ID 111483, similarity 56%)
  4. Jamie Leweling (ID 990201, similarity 52%)
  5. Mick Schmetgens (ID 1568521, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Alexander Schlager
  1. Alexander Schwolow (ID 134778, similarity 76%)
  2. András Schäfer (ID 877302, similarity 67%)
  3. Tom Alexander Rothe (ID 1210666, similarity 65%)
  4. Aleix García (ID 796047, similarity 57%)
  5. Alexis Claude-Maurice (ID 822877, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Luka Duric
  1. Lukas Ullrich (ID 1083382, similarity 76%)
  2. Laurin Curda (ID 981788, similarity 60%)
  3. Lukas Kübler (ID 142525, similarity 60%)
  4. Laurin Ulrich (ID 1152486, similarity 57%)
  5. Luca Sirch (ID 964603, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lúkas Petersson
  1. Lukas Petkov (ID 960017, similarity 72%)
  2. Lukas Kübler (ID 142525, similarity 56%)
  3. Lasse Günther (ID 997175, similarity 54%)
  4. Julian Ryerson (ID 800951, similarity 52%)
  5. Lukas Finn Pinckert (ID 990105, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Maximilian Kinzig
  1. Maximilian Beier (ID 980628, similarity 71%)
  2. Maximilian Eggestein (ID 569784, similarity 69%)
  3. Maximilian Rohr (ID 846398, similarity 67%)
  4. Maximilian Wöber (ID 794962, similarity 65%)
  5. Maximilian Mittelstädt (ID 788949, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Marius Funk
  1. Marius Wolf (ID 254119, similarity 70%)
  2. Marius Bülter (ID 378340, similarity 64%)
  3. Marc Guiu (ID 1414933, similarity 56%)
  4. Kaishu Sano (ID 1028307, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Timo Hübers
  1. Timo Becker (ID 814735, similarity 70%)
  2. Fabio Gruber (ID 1130119, similarity 57%)
  3. Timothy Chandler (ID 40239, similarity 56%)
  4. Ramon Hendriks (ID 916943, similarity 52%)
  5. Arthur (ID 1174761, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Florian Pruhs
  1. Loris Karius (ID 174135, similarity 70%)
  2. Livan Burcu (ID 1513469, similarity 55%)
  3. Florian Yves Le Joncour (ID 787816, similarity 50%)
  4. Laurin Ulrich (ID 1152486, similarity 50%)
  5. Reigan Heskey (ID 1601596, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Linus Güther
  1. Lasse Günther (ID 997175, similarity 70%)
  2. Marius Bülter (ID 378340, similarity 61%)
  3. Lucas Höler (ID 280009, similarity 57%)
  4. Kevin Stöger (ID 95381, similarity 55%)
  5. Lukas Kübler (ID 142525, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Martin Terrier
  1. Martin Adeline (ID 1158529, similarity 69%)
  2. Matthias Ginter (ID 142259, similarity 59%)
  3. Marvin Pieringer (ID 909485, similarity 57%)
  4. Maximilian Beier (ID 980628, similarity 57%)
  5. Fabian Rieder (ID 929620, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Stanley Nsoki
  1. Jan Leszczyński (ID 1823942, similarity 69%)
  2. Neil El Aynaoui (ID 1128530, similarity 56%)
  3. Daniel Svensson (ID 1021272, similarity 54%)
  4. Cajetan Lenz (ID 2077300, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Matthias Köbbing
  1. Matthias Ginter (ID 142259, similarity 69%)
  2. Mattes Hansen (ID 1083387, similarity 59%)
  3. Malik Pimpong (ID 1957761, similarity 52%)
  4. Thijs Dallinga (ID 905381, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Andrej Ilic
  1. Andrej Kramarić (ID 67647, similarity 67%)
  2. Andrija Maksimović (ID 1406171, similarity 59%)
  3. Dženan Pejčinović (ID 1127790, similarity 54%)
  4. Adil Aouchiche (ID 962877, similarity 52%)
  5. Martin Adeline (ID 1158529, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Dan-Axel Zagadou
  1. Joane Gadou (ID 1471049, similarity 67%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Justin Diehl
  1. Justin Njinmah (ID 1005343, similarity 67%)
  2. Martin Adeline (ID 1158529, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Justin Lerma
  1. Justin Njinmah (ID 1005343, similarity 67%)
  2. Jan Uwe Thielmann (ID 1010726, similarity 54%)
  3. Jamal Musiala (ID 1010231, similarity 52%)
  4. Jonah Sticker (ID 1517850, similarity 52%)
  5. Angelo Stiller (ID 901882, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Leopold Zingerle
  1. Leopold Querfeld (ID 1086547, similarity 67%)
  2. Tim Lemperle (ID 1014290, similarity 54%)
  3. Valentin Gendrey (ID 944899, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lukas Klostermann
  1. Lukas Kübler (ID 142525, similarity 67%)
  2. Lucas Höler (ID 280009, similarity 54%)
  3. Lukas Petkov (ID 960017, similarity 52%)
  4. Łukasz Poręba (ID 942336, similarity 52%)
  5. Lasse Günther (ID 997175, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Markus Kolke
  1. Marius Wolf (ID 254119, similarity 67%)
  2. Mark Flekken (ID 171919, similarity 64%)
  3. Marius Bülter (ID 378340, similarity 61%)
  4. Tim Skarke (ID 800252, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Marvin Friedrich
  1. Marvin Pieringer (ID 909485, similarity 67%)
  2. Marco Friedl (ID 825771, similarity 62%)
  3. Fabian Rieder (ID 929620, similarity 59%)
  4. Laurin Ulrich (ID 1152486, similarity 59%)
  5. Marvin Schwäbe (ID 187185, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Maxime Estève
  1. Max Moerstedt (ID 1418703, similarity 67%)
  2. Maximilian Eggestein (ID 569784, similarity 65%)
  3. Maximilian Beier (ID 980628, similarity 52%)
  4. Marius Bülter (ID 378340, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nikolas Nartey
  1. Nikola Katić (ID 831488, similarity 67%)
  2. Jan-Niklas Beste (ID 836711, similarity 59%)
  3. Nicolas Kristof (ID 1131080, similarity 59%)
  4. Bilal Nadir (ID 1129527, similarity 52%)
  5. Kauã Prates (ID 1887796, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Oliver Burke
  1. Oliver Baumann (ID 40244, similarity 67%)
  2. Olivier Deman (ID 960114, similarity 61%)
  3. Wouter Burger (ID 916946, similarity 61%)
  4. Livan Burcu (ID 1513469, similarity 57%)
  5. Oliver Batista Meier (ID 907685, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Alexander Meyer
  1. Tom Alexander Rothe (ID 1210666, similarity 65%)
  2. Alexander Schwolow (ID 134778, similarity 58%)
  3. Valentin Gendrey (ID 944899, similarity 55%)
  4. Alexis Claude-Maurice (ID 822877, similarity 55%)
  5. Julian Ryerson (ID 800951, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Alexander Prass
  1. Alexander Schwolow (ID 134778, similarity 65%)
  2. Tom Alexander Rothe (ID 1210666, similarity 65%)
  3. Aleksandar Pavlović (ID 1142251, similarity 56%)
  4. Aleix García (ID 796047, similarity 56%)
  5. Daniel Fernandes (ID 113442, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sebastian Klaas
  1. Sebastiaan Bornauw (ID 826167, similarity 65%)
  2. Satoshi Tanaka (ID 981067, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jonas Hofmann
  1. Josha Vagnoman (ID 906278, similarity 64%)
  2. Jonathan Tah (ID 227672, similarity 61%)
  3. Jan Uwe Thielmann (ID 1010726, similarity 52%)
  4. Jonathan Burkardt (ID 939830, similarity 50%)
  5. Mattes Hansen (ID 1083387, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lennard Maloney
  1. Lennart Karl (ID 1861975, similarity 64%)
  2. Kenan Karaman (ID 168943, similarity 62%)
  3. Bernardo (ID 828571, similarity 55%)
  4. Olivier Deman (ID 960114, similarity 54%)
  5. Waldemar Anton (ID 799046, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Niklas Stark
  1. Jan-Niklas Beste (ID 836711, similarity 64%)
  2. Nicolas Kristof (ID 1131080, similarity 56%)
  3. Nicolas Seiwald (ID 976575, similarity 56%)
  4. Nikola Katić (ID 831488, similarity 55%)
  5. Lasse Günther (ID 997175, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Shuto Machino
  1. Stefano Marino (ID 1167764, similarity 64%)
  2. Kaishu Sano (ID 1028307, similarity 55%)
  3. Tom Bischof (ID 1129935, similarity 55%)
  4. Linton Maina (ID 921033, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Anthony Jung
  1. Anthony Caci (ID 846471, similarity 64%)
  2. Antonio Nusa (ID 1121923, similarity 55%)
  3. Anton Kade (ID 1129365, similarity 50%)
  4. Jordan Torunarigha (ID 801003, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kevin Müller
  1. Kevin Stöger (ID 95381, similarity 64%)
  2. David Møller Wolfe (ID 1031283, similarity 54%)
  3. Angelo Stiller (ID 901882, similarity 50%)
  4. Kevin Diks (ID 583806, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Christoph Baumgartner
  1. Christopher Trimmel (ID 48557, similarity 63%)
  2. Christian Günter (ID 142231, similarity 63%)
  3. Christopher Nkunku (ID 769333, similarity 59%)
  4. Christian Kofane (ID 2029648, similarity 57%)
  5. Tristan Spranger (ID 1974432, similarity 51%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Felix Agu
  1. Felix Nmecha (ID 907463, similarity 63%)
  2. Elias Baum (ID 1403018, similarity 59%)
  3. Felix Uduokhai (ID 792142, similarity 57%)
  4. Felix Keidel (ID 1215028, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Keke Topp
  1. Keisuke Goto (ID 1391315, similarity 63%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tim Binder
  1. Timo Becker (ID 814735, similarity 63%)
  2. Tim Kleindienst (ID 228981, similarity 61%)
  3. Timothy Chandler (ID 40239, similarity 58%)
  4. Fabian Rieder (ID 929620, similarity 57%)
  5. Kim Min-jae (ID 896569, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Marcel Hoffmeier
  1. Marcel Sabitzer (ID 133908, similarity 62%)
  2. Marco Friedl (ID 825771, similarity 62%)
  3. Manuel Neuer (ID 8959, similarity 54%)
  4. Karl Hein (ID 991591, similarity 52%)
  5. András Schäfer (ID 877302, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Patrick Osterhage
  1. Patrick Wimmer (ID 987504, similarity 62%)
  2. Otto Stange (ID 1568535, similarity 54%)
  3. Arthur Chaves (ID 1122806, similarity 50%)
  4. Jonah Sticker (ID 1517850, similarity 50%)
  5. Marius Bülter (ID 378340, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kastriot Imeri
  1. Patrick Wimmer (ID 987504, similarity 62%)
  2. Mario Götze (ID 66518, similarity 52%)
  3. Fábio Vieira (ID 904835, similarity 50%)
  4. Kevin Stöger (ID 95381, similarity 50%)
  5. Marvin Pieringer (ID 909485, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Markus Schubert
  1. Marius Bülter (ID 378340, similarity 62%)
  2. András Schäfer (ID 877302, similarity 59%)
  3. Marvin Schwäbe (ID 187185, similarity 59%)
  4. Tjark Lasse Scheller (ID 1137717, similarity 56%)
  5. Arthur (ID 1174761, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Patrick Drewes
  1. Patrick Wimmer (ID 987504, similarity 62%)
  2. Patrik Schick (ID 280609, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sebastian Sebulonsen
  1. Sebastiaan Bornauw (ID 826167, similarity 61%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Finn Porath
  1. Franck Honorat (ID 280453, similarity 61%)
  2. Finn Dahmen (ID 822564, similarity 60%)
  3. Finn Jeltsch (ID 1418649, similarity 57%)
  4. Lukas Finn Pinckert (ID 990105, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Noël Aséko
  1. Nicolas Kristof (ID 1131080, similarity 61%)
  2. Lukas Petkov (ID 960017, similarity 60%)
  3. Nicholas Mickelson (ID 900264, similarity 54%)
  4. Nicolas-Gerrit Kühn (ID 877835, similarity 54%)
  5. Noel Futkeu (ID 1017574, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Ruben Müller
  1. Marius Bülter (ID 378340, similarity 61%)
  2. Robin Fellhauer (ID 860461, similarity 56%)
  3. Manuel Neuer (ID 8959, similarity 55%)
  4. Robin Zentner (ID 174345, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sven Ulreich
  1. Laurin Ulrich (ID 1152486, similarity 61%)
  2. Lukas Ullrich (ID 1083382, similarity 61%)
  3. Chris Führich (ID 891510, similarity 52%)
  4. Robert Andrich (ID 168903, similarity 50%)
  5. Samuele Inacio (ID 1861666, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tim Oermann
  1. Oliver Baumann (ID 40244, similarity 61%)
  2. Timo Becker (ID 814735, similarity 60%)
  3. Joey Veerman (ID 850816, similarity 57%)
  4. Jan Uwe Thielmann (ID 1010726, similarity 56%)
  5. Mertcan Ayhan (ID 1195798, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Florian Müller
  1. Florian Yves Le Joncour (ID 787816, similarity 61%)
  2. Laurin Ulrich (ID 1152486, similarity 56%)
  3. Angelo Stiller (ID 901882, similarity 54%)
  4. Livan Burcu (ID 1513469, similarity 52%)
  5. Christian Günter (ID 142231, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Eric Martel
  1. Eric Ebimbe (ID 904994, similarity 60%)
  2. Cédric Itten (ID 352290, similarity 57%)
  3. Tim Skarke (ID 800252, similarity 53%)
  4. Grischa Prömel (ID 253993, similarity 52%)
  5. Martin Adeline (ID 1158529, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Felix Götze
  1. Mario Götze (ID 66518, similarity 60%)
  2. Felix Keidel (ID 1215028, similarity 57%)
  3. Felix Nmecha (ID 907463, similarity 57%)
  4. Felix Uduokhai (ID 792142, similarity 52%)
  5. Marcel Sabitzer (ID 133908, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Janik Bachmann
  1. Calvin Brackelmann (ID 1128792, similarity 60%)
  2. Jan Uwe Thielmann (ID 1010726, similarity 57%)
  3. Kenan Karaman (ID 168943, similarity 56%)
  4. Oliver Baumann (ID 40244, similarity 54%)
  5. Han-Noah Massengo (ID 927340, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jens Stage
  1. Kevin Stöger (ID 95381, similarity 60%)
  2. Jae-sung Lee (ID 537552, similarity 53%)
  3. Otto Stange (ID 1568535, similarity 53%)
  4. Cajetan Lenz (ID 2077300, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Paul Nebel
  1. Manuel Neuer (ID 8959, similarity 60%)
  2. Paul Erevbenagie (ID 2160258, similarity 58%)
  3. Paul Okon-Engstler (ID 1411105, similarity 56%)
  4. Jae-sung Lee (ID 537552, similarity 53%)
  5. Nahuel Noll (ID 1048651, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jan Olschowsky
  1. Jan Leszczyński (ID 1823942, similarity 59%)
  2. Jano Ter-Horst (ID 1152342, similarity 56%)
  3. Stefan Posch (ID 355486, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kennet Eichhorn
  1. Hennes Behrens (ID 1864760, similarity 59%)
  2. Senne Lynen (ID 826171, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nediljko Labrović
  1. Nikola Katić (ID 831488, similarity 59%)
  2. Neil El Aynaoui (ID 1128530, similarity 55%)
  3. Andrija Maksimović (ID 1406171, similarity 55%)
  4. Andrej Kramarić (ID 67647, similarity 53%)
  5. Noah Darvich (ID 1469995, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Borna Sosa
  1. Bernardo (ID 828571, similarity 59%)
  2. Tom Krauß (ID 930272, similarity 56%)
  3. Edmond Tapsoba (ID 883262, similarity 55%)
  4. Antonio Nusa (ID 1121923, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Rael-Tshimbela Nakuzola
  1. Satoshi Tanaka (ID 981067, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tom Baack
  1. Robin Hack (ID 876858, similarity 59%)
  2. Timo Becker (ID 814735, similarity 56%)
  3. Tom Bischof (ID 1129935, similarity 56%)
  4. Linton Maina (ID 921033, similarity 53%)
  5. Mio Backhaus (ID 1083390, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Fabio Chiarodia
  1. Fábio Silva (ID 954076, similarity 58%)
  2. Fábio Vieira (ID 904835, similarity 56%)
  3. Albian Hajdari (ID 1000269, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Hee-Chan Hwang
  1. Ethan Nwaneri (ID 1401702, similarity 58%)
  2. Han-Noah Massengo (ID 927340, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jannik Huth
  1. Jan-Niklas Beste (ID 836711, similarity 58%)
  2. Janik Haberer (ID 168985, similarity 55%)
  3. Yannik Keitel (ID 877842, similarity 55%)
  4. Yannick Engelhardt (ID 990209, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Luca Waldschmidt
  1. Luca Sirch (ID 964603, similarity 58%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Abdoul Koné
  1. Samba Konaté (ID 2269705, similarity 57%)
  2. Paul Okon-Engstler (ID 1411105, similarity 54%)
  3. Louis Lemke (ID 1995000, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Eliesse Ben Seghir
  1. Ellyes Skhiri (ID 591706, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Frederik Schmahl
  1. Frederik Rønnow (ID 137692, similarity 57%)
  2. Farès Chaïbi (ID 1192318, similarity 54%)
  3. Alexander Schwolow (ID 134778, similarity 50%)
  4. Grischa Prömel (ID 253993, similarity 50%)
  5. Ramon Hendriks (ID 916943, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Luca Pfeiffer
  1. Luca Sirch (ID 964603, similarity 57%)
  2. Lucas Höler (ID 280009, similarity 55%)
  3. Luca Philipp (ID 943550, similarity 52%)
  4. Luca Reggiani (ID 1937833, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Rav van den Berg
  1. Ron Schallenberg (ID 872358, similarity 57%)
  2. Isac Lidberg (ID 798175, similarity 50%)
  3. Manuel Neuer (ID 8959, similarity 50%)
  4. Raphael Obermair (ID 820465, similarity 50%)
  5. Zeno Van Den Bosch (ID 1103765, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Stefan Bell
  1. Nathan Tella (ID 920379, similarity 57%)
  2. Stefan Posch (ID 355486, similarity 57%)
  3. Cole Campbell (ID 1134578, similarity 55%)
  4. Fabian Bredlow (ID 152463, similarity 52%)
  5. Stefano Marino (ID 1167764, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Atakan Karazor
  1. Kenan Karaman (ID 168943, similarity 56%)
  2. Aleksandar Pavlović (ID 1142251, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Daniel Batz
  1. Daniel Fernandes (ID 113442, similarity 56%)
  2. Natnael Abraha (ID 1861981, similarity 52%)
  3. Yannick Engelhardt (ID 990209, similarity 52%)
  4. Daniel Svensson (ID 1021272, similarity 50%)
  5. Marcel Sabitzer (ID 133908, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Dennis Seimen
  1. Hennes Behrens (ID 1864760, similarity 56%)
  2. Eric Ebimbe (ID 904994, similarity 55%)
  3. Senne Lynen (ID 826171, similarity 55%)
  4. Gideon Mensah (ID 844942, similarity 50%)
  5. Yannik Keitel (ID 877842, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Derrick Köhn
  1. Derry Scherhant (ID 1131002, similarity 56%)
  2. Dominik Kohr (ID 152206, similarity 55%)
  3. Nicolas-Gerrit Kühn (ID 877835, similarity 50%)
  4. Robert Andrich (ID 168903, similarity 50%)
  5. Robin Koch (ID 581302, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Florian Neuhaus
  1. Felix Nmecha (ID 907463, similarity 56%)
  2. Loris Karius (ID 174135, similarity 56%)
  3. Florian Yves Le Joncour (ID 787816, similarity 53%)
  4. Francis Onyeka (ID 1414916, similarity 52%)
  5. Livan Burcu (ID 1513469, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Frank Lehmann
  1. Franck Honorat (ID 280453, similarity 56%)
  2. Calvin Brackelmann (ID 1128792, similarity 55%)
  3. Rani Khedira (ID 149479, similarity 52%)
  4. Jan Uwe Thielmann (ID 1010726, similarity 52%)
  5. Bilal El Khannouss (ID 1126569, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nnamdi Collins
  1. Michael Olise (ID 978838, similarity 56%)
  2. Jamie Leweling (ID 990201, similarity 54%)
  3. Nicolas Kristof (ID 1131080, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tom Zimmerschied
  1. Tom Bischof (ID 1129935, similarity 56%)
  2. Tim Lemperle (ID 1014290, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Warmed Omari
  1. Andrej Kramarić (ID 67647, similarity 56%)
  2. Nadiem Amiri (ID 327755, similarity 55%)
  3. Ameen Al-Dakhil (ID 1979970, similarity 50%)
  4. Mert Kömür (ID 1390682, similarity 50%)
  5. Ramon Hendriks (ID 916943, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Emre Can
  1. Felix Nmecha (ID 907463, similarity 56%)
  2. Mertcan Ayhan (ID 1195798, similarity 53%)
  3. Waldemar Anton (ID 799046, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Faik Sakar
  1. Tim Skarke (ID 800252, similarity 56%)
  2. Daiki Hashioka (ID 897334, similarity 55%)
  3. Francis Onyeka (ID 1414916, similarity 55%)
  4. Fábio Silva (ID 954076, similarity 53%)
  5. Patson Daka (ID 865057, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jens Grahl
  1. Joe Scally (ID 1002920, similarity 56%)
  2. Jarell Quansah (ID 1003339, similarity 55%)
  3. Jae-sung Lee (ID 537552, similarity 53%)
  4. Brajan Gruda (ID 1198075, similarity 50%)
  5. Jan Gyamerah (ID 254411, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sima Suso
  1. Marius Wolf (ID 254119, similarity 56%)
  2. Salim Musah (ID 1864786, similarity 56%)
  3. Mats Rots (ID 1387012, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tim Boss
  1. Tidiam Gomis (ID 1426577, similarity 56%)
  2. Tim Skarke (ID 800252, similarity 50%)
  3. Tom Krauß (ID 930272, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Alexander Røssing-Lelesiit
  1. Alexander Schwolow (ID 134778, similarity 55%)
  2. Tom Alexander Rothe (ID 1210666, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Carl Klaus
  1. Jarell Quansah (ID 1003339, similarity 55%)
  2. Mio Backhaus (ID 1083390, similarity 50%)
  3. Oscar Højlund (ID 1149113, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Janis Blaswich
  1. Luca Sirch (ID 964603, similarity 55%)
  2. Adil Aouchiche (ID 962877, similarity 54%)
  3. Josip Stanišić (ID 927407, similarity 54%)
  4. Jan-Niklas Beste (ID 836711, similarity 52%)
  5. Dariusz Stalmach (ID 1141977, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jonas Urbig
  1. Jonah Sticker (ID 1517850, similarity 55%)
  2. Jordan Torunarigha (ID 801003, similarity 52%)
  3. Jae-sung Lee (ID 537552, similarity 50%)
  4. Joane Gadou (ID 1471049, similarity 50%)
  5. Josip Juranović (ID 791642, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Joël Schmied
  1. Finn Jeltsch (ID 1418649, similarity 55%)
  2. Aljoscha Kemlein (ID 1198074, similarity 54%)
  3. Joe Scally (ID 1002920, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kenny Quetant
  1. Senne Lynen (ID 826171, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Oskar Wójcik
  1. Loris Karius (ID 174135, similarity 55%)
  2. Tim Skarke (ID 800252, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sven Michel
  1. Michael Olise (ID 978838, similarity 55%)
  2. Senne Lynen (ID 826171, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Örjan Nyland
  1. Oscar Højlund (ID 1149113, similarity 55%)
  2. Mertcan Ayhan (ID 1195798, similarity 52%)
  3. Anton Kade (ID 1129365, similarity 50%)
  4. Francis Onyeka (ID 1414916, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Bara Sapoko Ndiaye
  1. Amara Condé (ID 817978, similarity 54%)
  2. Albert Sambi Lokonga (ID 901892, similarity 53%)
  3. Brajan Gruda (ID 1198075, similarity 52%)
  4. Samba Konaté (ID 2269705, similarity 52%)
  5. Raphael Onyedika (ID 1129862, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Clemens Lippmann
  1. Filippo Mané (ID 1137131, similarity 54%)
  2. Calvin Brackelmann (ID 1128792, similarity 50%)
  3. Phillipp Mwene (ID 138126, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Enzo Leopold
  1. Leopold Querfeld (ID 1086547, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Ron-Robert Zieler
  1. Gregor Kobel (ID 556866, similarity 54%)
  2. Robert Andrich (ID 168903, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jens Castrop
  1. Alessio Castro-Montes (ID 839898, similarity 53%)
  2. Bernardo (ID 828571, similarity 53%)
  3. Jonah Sticker (ID 1517850, similarity 52%)
  4. Joe Scally (ID 1002920, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Montrell Culbreath
  1. Natnael Abraha (ID 1861981, similarity 53%)
  2. Emmanuel Latte Lath (ID 848074, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Rômulo
  1. Mert Kömür (ID 1390682, similarity 53%)
  2. Marco Grüll (ID 815612, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Silas
  1. Fábio Silva (ID 954076, similarity 53%)
  2. Said El Mala (ID 1800475, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Guéla Doué
  1. Joane Gadou (ID 1471049, similarity 53%)
  2. Manuel Neuer (ID 8959, similarity 50%)
  3. Miguel Gutiérrez (ID 908716, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kofi Amoako
  1. Ko Itakura (ID 790989, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Miro Muheim
  1. Mert Kömür (ID 1390682, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Raif Adam
  1. Brajan Gruda (ID 1198075, similarity 53%)
  2. Ibrahim Maza (ID 1407524, similarity 53%)
  3. Junior Adamu (ID 902381, similarity 53%)
  4. Shafiq Nandja (ID 2204961, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Robert Skov
  1. Mert Kömür (ID 1390682, similarity 53%)
  2. Robin Koch (ID 581302, similarity 53%)
  3. Robert Andrich (ID 168903, similarity 52%)
  4. Albert Sambi Lokonga (ID 901892, similarity 50%)
  5. Rodrigo Ribeiro (ID 1215904, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Serge Gnabry
  1. Bernardo (ID 828571, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Zento Uno
  1. Zeno Van Den Bosch (ID 1103765, similarity 52%)
  2. Robin Zentner (ID 174345, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Ramy Bensebaini
  1. Samuele Inacio (ID 1861666, similarity 52%)
  2. Eren Dinkçi (ID 1067120, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sander Tangvik
  1. Andrej Kramarić (ID 67647, similarity 52%)
  2. Assan Ouédraogo (ID 1418623, similarity 52%)
  3. Aleksandar Pavlović (ID 1142251, similarity 52%)
  4. Albert Grønbæk (ID 1000263, similarity 50%)
  5. Isac Lidberg (ID 798175, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Adrian Gantenbein
  1. Christian Günter (ID 142231, similarity 52%)
  2. Maximilian Eggestein (ID 569784, similarity 51%)
  3. Reigan Heskey (ID 1601596, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nico Schlotterbeck
  1. Nicolás Capaldo (ID 973564, similarity 52%)
  2. Sheraldo Becker (ID 352544, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Johannes Simon Siebeking
  1. Jamie Leweling (ID 990201, similarity 51%)
  2. Jahmai Simpson-Pusey (ID 1402924, similarity 50%)
  3. Jan Leszczyński (ID 1823942, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Darwin Soylu
  1. Marin Ljubičić (ID 1090010, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Deniz Zeitler
  1. Yannik Keitel (ID 877842, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Fisnik Asllani
  1. Moussa Sylla (ID 861980, similarity 50%)
  2. Nikola Katić (ID 831488, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Juma Bah
  1. Jarell Quansah (ID 1003339, similarity 50%)
  2. Justin Njinmah (ID 1005343, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Koki Machida
  1. Joshua Kimmich (ID 259117, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Leonidas Stergiou
  1. Jonah Sticker (ID 1517850, similarity 50%)
  2. Lasse Günther (ID 997175, similarity 50%)
  3. Leo Sauer (ID 1150938, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lorenz Assignon
  1. Daniel Svensson (ID 1021272, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sota Kawasaki
  1. Noahkai Banks (ID 1597260, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Timur Gayret
  1. Tim Skarke (ID 800252, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tom Wisbereit
  1. Marius Bülter (ID 378340, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Uchenna Ogundu
  1. Chema Andrés (ID 1464641, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

Input summary
  Matchday: 3; ratings: team_player_average_ratings_2026-09-11_09-41-12_926998+0200.csv
  Rating recency weights (newest to oldest): 28/24/20/16/12; missing ratings excluded and weights normalized.
  Ligainsider (weight 4; current): ligainsider_bundesliga_lineups_20260911_094158.json
  Kickbase (weight 3; current): kickbase_bundesliga_lineups_20260911_095348.json
  Kicker (weight 2; current): kicker_bundesliga_lineups_20260911_094243.json
  Rotowire (weight 1; current): rotowire_bundesliga_lineups_20260911_094138.json
  Alternative starting-chance decay: 0.45
  Questionable-injury starting-chance penalty: 0.15
  Score multiplier: 10.0062
  Output: C:\kickbase project\outputs\expected_points\expected_points_20260911_094008_+0200_sofascore_overall_rating_odds_lineup_20260911_101239_+0200.csv

Team odds and expected match points

,team,provider,win_probability,draw_probability,loss_probability,expected_match_points
0,augsburg,FotMob,0.231533,0.226020,0.542448,0.920617
1,bayern,FotMob,0.814566,0.112123,0.073311,2.555822
2,bremen,FotMob,0.287507,0.249677,0.462816,1.112198
3,dortmund,FotMob,0.777826,0.131798,0.090376,2.465276
4,elversberg,FotMob,0.073311,0.112123,0.814566,0.332056
5,frankfurt,FotMob,0.263523,0.237171,0.499307,1.027739
6,freiburg,FotMob,0.573916,0.220223,0.205861,1.941970
7,gladbach,FotMob,0.205861,0.220223,0.573916,0.837806
8,hamburg,FotMob,0.141359,0.182136,0.676505,0.606214
9,hoffenheim,FotMob,0.403048,0.225515,0.371437,1.434660
10,koeln,FotMob,0.462816,0.249677,0.287507,1.638125
11,leipzig,FotMob,0.676505,0.182136,0.141359,2.211650
12,leverkusen,FotMob,0.542448,0.226020,0.231533,1.853363
13,mainz,FotMob,0.499307,0.237171,0.263523,1.735090
14,paderborn,FotMob,0.090376,0.131798,0.777826,0.402926
15,schalke,FotMob,0.326661,0.278623,0.394716,1.258607
16,stuttgart,FotMob,0.371437,0.225515,0.403048,1.339825
17,union,FotMob,0.394716,0.278623,0.326661,1.462770

Player score review (non-positive or non-exact ratings)

,name,team,rating_status,lineup_status,rating,expected_match_points,ligainsider_starting_chance,kickbase_starting_chance,kicker_starting_chance,rotowire_starting_chance,questionable_injury_penalty,starting_chance,score_multiplier,score
2,Sven Ulreich,bayern,missing_rating,ligainsider:missing; kickbase:missing; kicker:...,0.00,2.555822,0.000000,0.0,0.0,0.0,0.0,0.000000,10.0062,0.0
4,Serge Gnabry,bayern,missing_rating,ligainsider:missing; kickbase:missing; kicker:...,0.00,2.555822,0.000000,0.0,0.0,0.0,0.0,0.000000,10.0062,0.0
10,Jonas Urbig,bayern,missing_rating,ligainsider:exact; kickbase:missing; kicker:mi...,0.00,2.555822,0.310345,0.0,0.0,0.0,0.0,0.124138,10.0062,0.0
11,Hiroki Ito,bayern,exact,ligainsider:missing; kickbase:missing; kicker:...,6.60,2.555822,0.000000,0.0,0.0,0.0,0.0,0.000000,10.0062,0.0
20,Bara Sapoko Ndiaye,bayern,missing_rating,ligainsider:missing; kickbase:missing; kicker:...,0.00,2.555822,0.000000,0.0,0.0,0.0,0.0,0.000000,10.0062,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453,Adrian Gantenbein,schalke,missing_rating,ligainsider:missing; kickbase:missing; kicker:...,0.00,1.258607,0.000000,0.0,0.0,0.0,0.0,0.000000,10.0062,0.0
454,Vitalie Becker,schalke,exact,ligainsider:missing; kickbase:missing; kicker:...,6.86,1.258607,0.000000,0.0,0.0,0.0,0.0,0.000000,10.0062,0.0
455,Mert Can Ayhan,schalke,exact,ligainsider:missing; kickbase:missing; kicker:...,6.30,1.258607,0.000000,0.0,0.0,0.0,0.0,0.000000,10.0062,0.0
457,Luca Vozar,schalke,exact,ligainsider:missing; kickbase:missing; kicker:...,6.57,1.258607,0.000000,0.0,0.0,0.0,0.0,0.000000,10.0062,0.0
459,Johannes Simon Siebeking,schalke,missing_rating,ligainsider:missing; kickbase:missing; kicker:...,0.00,1.258607,0.000000,0.0,0.0,0.0,0.0,0.000000,10.0062,0.0