# Kickbase percentile rating × odds × lineup score

Run derived-analysis notebook 10 first. This notebook selects its newest export by `generated_at` and uses its one-decimal per-match ratings in the shared overall odds/lineup workflow.

Team-match weights are 28%, 24%, 20%, 16%, 12%, newest first. Missing or excluded appearances are omitted and remaining weights renormalized without shifting slots. The weighted rating is rounded half-up to one decimal before scoring. The derived notebook now exports this same weighted average; this notebook recomputes it from individual match ratings so older exports remain compatible and weights are never applied twice. Persisted fallback flags are displayed when loading ratings.

Score = multiplier × Kickbase percentile rating × expected match points × starting chance. Odds, identity matching, matchday/source confirmation, injury handling, and lineup alternatives follow the existing overall rating notebook. The export uses `kickbase_percentile_rating`, a distinct method filename, and the optimizer-compatible `score` column.

Control the blend with the variables at the top of the scoring cell: `BLEND_MEAN_POINTS = True` enables it, `False` disables it, and `None` asks via Python `input()` each run (the default). Set `CALCULATED_EXPECTED_POINTS_WEIGHT` and `MEAN_POINTS_WEIGHT` to change the split; both must be between 0 and 1 and sum to 1. Defaults are 0.8 and 0.2. When enabled, `score = CALCULATED_EXPECTED_POINTS_WEIGHT * calculated expected points + MEAN_POINTS_WEIGHT * recency-weighted mean points`. At the prompt, answer `y` or `yes` to enable the configured blend; answer `n`, `no`, or press Enter to keep the original calculation. The mean uses per-match derived points from the same eligible appearances (at least 10 minutes) as the percentile ratings, with the same 28/24/20/16/12 team-match weights and missing-slot renormalization. It is not a points-per-90 average and is not rounded before blending. Goalkeepers use the calibrated points already stored in the percentile export. The mean contribution is added after odds and lineup scoring, so it still contributes when starting chance is zero; players without matched history retain zero. Enabled exports with a positive mean-points weight also include `calculated_expected_points` and `recency_weighted_mean_points`. Rerun the scoring cell to apply the variables and create a new CSV; saved outputs below reflect the previous run.


Goalkeeper expected match points are `1.1 + raw expected match points * (0.6 / 3)`: raw 0 maps to 1.1, 1.5 maps to 1.4, and 3 maps to 1.7. Outfield players retain raw 0–3 values. The exported `expected_match_points` is the value used in the score. Rerun this notebook to generate updated scores.

Goalkeeper alternatives use decay **0.60** (relative weights **1, 0.6, 0.36, …**), with existing provider normalization and injury handling. Outfield alternatives retain their configured decay.

In [1]:
import sys
from pathlib import Path
from IPython.display import display
import pandas as pd

def locate_project_root():
    for start in (Path.cwd().resolve(), Path(globals().get('__vsc_ipynb_file__', '.')).resolve()):
        for candidate in (start, *start.parents):
            if (candidate / 'project_paths.py').is_file():
                return candidate
    raise FileNotFoundError('Run from within the project directory.')
PROJECT_ROOT = locate_project_root()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
import importlib
import sofascore_rating_odds_lineup_score as shared_scoring
import sofascore_kickbase_percentile_ratings as percentile_ratings
importlib.reload(shared_scoring)
importlib.reload(percentile_ratings)

In [2]:





































































































































































# Refresh both modules so an existing Jupyter kernel uses the latest scoring code.
import importlib
import sofascore_rating_odds_lineup_score as shared_scoring
import sofascore_kickbase_percentile_ratings as percentile_ratings
importlib.reload(shared_scoring)
importlib.reload(percentile_ratings)

QUESTIONABLE_INJURY_STARTING_CHANCE_PENALTY = 0.15
ALTERNATIVE_STARTING_CHANCE_DECAY = 0.45
GOALKEEPER_ALTERNATIVE_STARTING_CHANCE_DECAY = 0.60
LINEUP_SOURCE_WEIGHTS = {'ligainsider': 4.0, 'kickbase': 3.0, 'kicker': 2.0, 'rotowire': 1.0}
SCORE_MULTIPLIER = 10.0062
BLEND_MEAN_POINTS = None  # True: enable; False: disable; None: ask using input()
CALCULATED_EXPECTED_POINTS_WEIGHT = 0.80
MEAN_POINTS_WEIGHT = 0.20  # The two weights must sum to 1

use_mean_points_blend = BLEND_MEAN_POINTS
if use_mean_points_blend is None:
    while True:
        blend_choice = input(f'Blend expected points with recency-weighted mean points ({CALCULATED_EXPECTED_POINTS_WEIGHT:.0%}/{MEAN_POINTS_WEIGHT:.0%})? [y/N]: ').strip().lower()
        if blend_choice in {'', 'n', 'no', 'y', 'yes'}:
            use_mean_points_blend = blend_choice in {'y', 'yes'}
            break
        print('Please enter y or n.')
result = percentile_ratings.run_score_creation(
    questionable_injury_starting_chance_penalty=QUESTIONABLE_INJURY_STARTING_CHANCE_PENALTY,
    alternative_starting_chance_decay=ALTERNATIVE_STARTING_CHANCE_DECAY,
    goalkeeper_alternative_starting_chance_decay=GOALKEEPER_ALTERNATIVE_STARTING_CHANCE_DECAY,
    lineup_source_weights=LINEUP_SOURCE_WEIGHTS,
    score_multiplier=SCORE_MULTIPLIER,
    blend_mean_points=use_mean_points_blend,
    calculated_expected_points_weight=CALCULATED_EXPECTED_POINTS_WEIGHT,
    mean_points_weight=MEAN_POINTS_WEIGHT,
)

Blend expected points with recency-weighted mean points (80%/20%)? [y/N]:  y
Matchday for odds and lineups:  6
Is the Ligainsider predicted lineup snapshot (ligainsider_bundesliga_lineups_20261016_113334.json) accurate for matchday 6, or from the previous matchday? [a]ccurate/[p]revious:  a
Is the Kickbase predicted lineup snapshot (kickbase_bundesliga_lineups_20261016_120556.json) accurate for matchday 6, or from the previous matchday? [a]ccurate/[p]revious:  a
Is the Kicker predicted lineup snapshot (kicker_bundesliga_lineups_20261016_113641.json) accurate for matchday 6, or from the previous matchday? [a]ccurate/[p]revious:  a
Is the Rotowire predicted lineup snapshot (rotowire_bundesliga_lineups_20261016_113310.json) accurate for matchday 6, or from the previous matchday? [a]ccurate/[p]revious:  a

No exact match for ligainsider lineup for Lucas Höler (freiburg)
  1. Lucas Hoeler (ID 6593, similarity 95%)

Choose a candidate number, or press Enter to skip (score 0):  1

No exact match for kickbase lineup for Nicolas Kühn (gladbach)
  1. NICOLAS (displayed name, similarity 78%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Nicolas Kühn (gladbach)
  1. Nicolas (displayed name, similarity 78%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Vitalie Becker (schalke)
  1. T. Becker (displayed name, similarity 70%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Vitalie Becker (schalke)
  1. T. Becker (displayed name, similarity 70%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Juma Bah (augsburg)
  1. Abdulai Juma Bah (ID 44678, similarity 67%)

Choose a candidate number, or press Enter to skip (score 0):  1

No exact match for rotowire lineup for Lukas Kübler (freiburg)
  1. Lucas Holer (ID 25331, similarity 67%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Nicholas Mickelson (elversberg)
  1. Kristof (displayed name, similarity 65%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Nicholas Mickelson (elversberg)
  1. Nicolas Kristof (ID 26473, similarity 65%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Nicholas Mickelson (elversberg)
  1. Nicolas Kristof (ID 48713, similarity 65%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Kim Minjae (bayern)
  1. Kimmich (displayed name, similarity 64%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Lukas Kübler (freiburg)
  1. Höler (displayed name, similarity 64%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Mekhi Gray (union)
  1. KHEDIRA (displayed name, similarity 62%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Sima Suso (augsburg)
  1. MASSENGO (displayed name, similarity 62%)
  2. MATSIMA (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Sima Suso (augsburg)
  1. Massengo (displayed name, similarity 62%)
  2. Matsima (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Emre Can (dortmund)
  1. NMECHA (displayed name, similarity 62%)
  2. Veerman (displayed name, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Tim Kleindienst (gladbach)
  1. Kevin Diks (ID 11591, similarity 61%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Tim Kleindienst (gladbach)
  1. Kevin Diks (ID 21650, similarity 61%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Vitalie Becker (schalke)
  1. Timo Becker (ID 11068, similarity 61%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Vitalie Becker (schalke)
  1. Timo Becker (ID 30648, similarity 61%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Kevin Stöger (gladbach)
  1. Diks (displayed name, similarity 60%)
  2. Kleindienst (displayed name, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Kevin Stöger (gladbach)
  1. Kevin Diks (ID 21650, similarity 60%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Luka Duric (paderborn)
  1. Curda (displayed name, similarity 60%)
  2. Ulrich (displayed name, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Luka Duric (paderborn)
  1. Laurin Curda (ID 36261, similarity 60%)
  2. Laurin Ulrich (ID 27568, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Luka Duric (paderborn)
  1. Laurin Curda (ID 48704, similarity 60%)
  2. Laurin Ulrich (ID 37153, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Christoph Baumgartner (leipzig)
  1. Nkunku (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Christoph Baumgartner (leipzig)
  1. Christopher Nkunku (ID 12446, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Christoph Baumgartner (leipzig)
  1. Christopher Nkunku (ID 20544, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Jan Olschowsky (gladbach)
  1. Leszczynski (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Jan Olschowsky (gladbach)
  1. Jan Leszczynski (ID 48750, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Markus Schubert (paderborn)
  1. Scheller (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Markus Schubert (paderborn)
  1. Tjark Scheller (ID 36890, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Markus Schubert (paderborn)
  1. Tjark Scheller (ID 48700, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Isac Lidberg (gladbach)
  1. Sander (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Mekhi Gray (union)
  1. R. Khedira (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Tim Oermann (leverkusen)
  1. MOREIRA (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Tim Oermann (leverkusen)
  1. Moreira (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Jannik Huth (freiburg)
  1. Beste (displayed name, similarity 58%)
  2. Engelhardt (displayed name, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Jannik Huth (freiburg)
  1. Jan-Niklas Beste (ID 26591, similarity 58%)
  2. Yannik Engelhardt (ID 36578, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Mert Can Ayhan (schalke)
  1. Kurucay (displayed name, similarity 58%)
  2. Tanaka (displayed name, similarity 56%)
  3. Karaman (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Nicolas Kühn (gladbach)
  1. Moritz Nicolas (ID 6295, similarity 58%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Nicolas Kühn (gladbach)
  1. Moritz Nicolas (ID 25259, similarity 58%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Cédric Itten (bremen)
  1. Dinkci (displayed name, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Emre Can (dortmund)
  1. F. Nmecha (displayed name, similarity 57%)
  2. Anton (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Luca Pfeiffer (elversberg)
  1. Sirch (displayed name, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Luca Pfeiffer (elversberg)
  1. Luca Sirch (ID 26346, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Oliver Burke (union)
  1. Livan Burcu (ID 43803, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Stefan Bell (mainz)
  1. Posch (displayed name, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Stefan Bell (mainz)
  1. Stefan Posch (ID 12798, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Stefan Bell (mainz)
  1. Stefan Posch (ID 23594, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Dzenan Pejčinović (stuttgart)
  1. DEMIROVIĆ (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Dzenan Pejčinović (stuttgart)
  1. Demirovic (displayed name, similarity 56%)
  2. Seimen (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Janik Bachmann (schalke)
  1. Karaman (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Janik Bachmann (schalke)
  1. Kenan Karaman (ID 2676, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Janik Bachmann (schalke)
  1. Kenan Karaman (ID 20178, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Emre Can (dortmund)
  1. Felix Nmecha (ID 25090, similarity 56%)
  2. Waldemar Anton (ID 5837, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Emre Can (dortmund)
  1. Felix Nmecha (ID 27147, similarity 56%)
  2. Waldemar Anton (ID 20160, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Mert Can Ayhan (schalke)
  1. TANAKA (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Robert Skov (union)
  1. Rothe (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Sima Suso (augsburg)
  1. Marius Wolf (ID 5670, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Sven Michel (paderborn)
  1. SCHELLER (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Sven Michel (paderborn)
  1. Scheller (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Tiago Tomás (stuttgart)
  1. VAGNOMAN (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Tiago Tomás (stuttgart)
  1. Vagnoman (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Christian Günter (freiburg)
  1. Ginter (displayed name, similarity 55%)
  2. Scherhant (displayed name, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Christian Günter (freiburg)
  1. Matthias Ginter (ID 17592, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Giannis Konstantelias (dortmund)
  1. Konstantinos Karetsas (ID 38406, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Cajetan Lenz (hoffenheim)
  1. De Cat (displayed name, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Jan Thielmann (koeln)
  1. S. El Mala (displayed name, similarity 55%)
  2. Johannesson (displayed name, similarity 51%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jan Thielmann (koeln)
  1. Said El Mala (ID 38546, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Jan Thielmann (koeln)
  1. Said El Mala (ID 46716, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Kauã Santos (frankfurt)
  1. Knauff (displayed name, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Luca Sirch (elversberg)
  1. Lukas Pinckert (ID 48715, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Martin Terrier (leverkusen)
  1. GUTIÉRREZ (displayed name, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Reigan Heskey (koeln)
  1. Moore (displayed name, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jannik Huth (freiburg)
  1. Yannik Engelhardt (ID 20278, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Luca Schnellbacher (elversberg)
  1. Sirch (displayed name, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Luca Schnellbacher (elversberg)
  1. Luca Sirch (ID 26346, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Guéla Doué (leverkusen)
  1. Miguel (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Leonidas Stergiou (stuttgart)
  1. Lorenz Assignon (ID 25114, similarity 53%)
  2. Dennis Seimen (ID 35226, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Luka Duric (paderborn)
  1. ULRICH (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Marvin Friedrich (union)
  1. Rönnow (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Tim Binder (bayern)
  1. LAIMER (displayed name, similarity 53%)
  2. Minjae (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Tim Binder (bayern)
  1. Laimer (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Bambasé Conté (hoffenheim)
  1. Baumann (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Bernardo (hoffenheim)
  1. Hranac (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Paul Nebel (mainz)
  1. J.-S. Lee (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Paul Nebel (mainz)
  1. Jaesung Lee (ID 21202, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Ruben Müller (paderborn)
  1. SCHELLER (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Ruben Müller (paderborn)
  1. Scheller (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Adam Hložek (hoffenheim)
  1. Avdullahu (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Daniel Batz (gladbach)
  1. Nicolas (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Danny Da Costa (mainz)
  1. Anthony Caci (ID 25792, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Gideon Mensah (koeln)
  1. Maina (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Gideon Mensah (koeln)
  1. Linton Maina (ID 25597, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Sebastian Klaas (paderborn)
  1. CASTAÑEDA (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Sebastian Klaas (paderborn)
  1. Castaneda (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Alexander Meyer (dortmund)
  1. Ryerson (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Alexander Meyer (dortmund)
  1. Julian Ryerson (ID 18478, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Alexander Meyer (dortmund)
  1. Julian Ryerson (ID 28864, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Nediljko Labrović (augsburg)
  1. Ibrahimović (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Nediljko Labrović (augsburg)
  1. Ibrahimovic (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Abdoul Koné (leipzig)
  1. RÔMULO (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Abdoul Koné (leipzig)
  1. Romulo (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Abdoul Koné (leipzig)
  1. Romulo (ID 46816, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Adam Hložek (hoffenheim)
  1. Adam Daghim (ID 44189, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Albert Grønbæk (hamburg)
  1. Adeline (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Albian Hajdari (hoffenheim)
  1. Asllani (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Andrej Kramarić (hoffenheim)
  1. Adam Daghim (ID 37622, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Andrej Kramarić (hoffenheim)
  1. Adam Daghim (ID 44189, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Christian Günter (freiburg)
  1. SCHERHANT (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Elias Baum (frankfurt)
  1. Kosugi (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Elias Baum (frankfurt)
  1. Keita Kosugi (ID 47541, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Ermedin Demirović (stuttgart)
  1. Dzenan Pejcinovic (ID 37405, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Florian Pruhs (paderborn)
  1. Ulrich (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Florian Pruhs (paderborn)
  1. Laurin Ulrich (ID 27568, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Florian Pruhs (paderborn)
  1. Laurin Ulrich (ID 37153, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Franck Honorat (gladbach)
  1. Machino (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Guéla Doué (leverkusen)
  1. Miguel Gutierrez (ID 24219, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Guéla Doué (leverkusen)
  1. Miguel Gutierrez (ID 32495, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Jamal Musiala (bayern)
  1. Luis Diaz (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jamal Musiala (bayern)
  1. Luis Diaz (ID 22566, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Jamal Musiala (bayern)
  1. Luis Diaz (ID 28527, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Janik Bachmann (schalke)
  1. KARAMAN (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Janis Blaswich (leverkusen)
  1. Andrich (displayed name, similarity 50%)
  2. QUANSAH (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Janis Blaswich (leverkusen)
  1. Quansah (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jens Castrop (gladbach)
  1. Joe Scally (ID 23700, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Jens Castrop (gladbach)
  1. Joe Scally (ID 26680, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Justin Diehl (stuttgart)
  1. Stiller (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Justin Lerma (dortmund)
  1. Anton (displayed name, similarity 50%)
  2. Ryerson (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Justin Lerma (dortmund)
  1. Julian Ryerson (ID 18478, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Justin Lerma (dortmund)
  1. Julian Ryerson (ID 28864, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Leonidas Stergiou (stuttgart)
  1. Seimen (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Leonidas Stergiou (stuttgart)
  1. Dennis Seimen (ID 39573, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Linus Güther (union)
  1. AEBISCHER (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Linus Güther (union)
  1. Aebischer (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Marcel Hoffmeier (paderborn)
  1. Scheller (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Marcel Hoffmeier (paderborn)
  1. Tjark Scheller (ID 36890, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Marcel Hoffmeier (paderborn)
  1. Tjark Scheller (ID 48700, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Martin Terrier (leverkusen)
  1. Miguel (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Martin Terrier (leverkusen)
  1. Miguel Gutierrez (ID 24219, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Martin Terrier (leverkusen)
  1. Miguel Gutierrez (ID 32495, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Mekhi Gray (union)
  1. Rani Khedira (ID 2122, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Mekhi Gray (union)
  1. Rani Khedira (ID 21666, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Mert Can Ayhan (schalke)
  1. Kenan Karaman (ID 2676, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Mert Can Ayhan (schalke)
  1. Kenan Karaman (ID 20178, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Montrell Culbreath (leverkusen)
  1. MOREIRA (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Montrell Culbreath (leverkusen)
  1. Moreira (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Otávio (frankfurt)
  1. EBNOUTALIB (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Patrick Wimmer (hoffenheim)
  1. Lemperle (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Patrick Wimmer (hoffenheim)
  1. Tim Lemperle (ID 23854, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Patrick Wimmer (hoffenheim)
  1. Tim Lemperle (ID 32420, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Patson Daka (hamburg)
  1. AMOAKO (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Patson Daka (hamburg)
  1. Amoako (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Paul Nebel (mainz)
  1. LEE (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Ruben Müller (paderborn)
  1. Tjark Scheller (ID 48700, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Sota Kawasaki (mainz)
  1. POTULSKI (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Stefano Marino (paderborn)
  1. Pieringer (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Örjan Nyland (leipzig)
  1. ORBÁN (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Örjan Nyland (leipzig)
  1. Orban (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Moussa Ndiaye
  1. Moussa Diaby (ID 855817, similarity 87%)
  2. Moussa Sylla (ID 861980, similarity 61%)
  3. Luis Díaz (ID 883537, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Luca Jaquez
  1. Lucas Vázquez (ID 255239, similarity 82%)
  2. Lucas Höler (ID 280009, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Florian Pruhs
  1. Florian Neuhaus (ID 837205, similarity 77%)
  2. Loris Karius (ID 174135, similarity 70%)
  3. Livan Burcu (ID 1513469, similarity 55%)
  4. Laurin Ulrich (ID 1152486, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Alexander Schlager
  1. Alexander Schwolow (ID 134778, similarity 76%)
  2. András Schäfer (ID 877302, similarity 67%)
  3. Tom Alexander Rothe (ID 1210666, similarity 65%)
  4. Alexander Prass (ID 978062, similarity 65%)
  5. Aleix García (ID 796047, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Luka Duric
  1. Lukas Ullrich (ID 1083382, similarity 76%)
  2. Laurin Curda (ID 981788, similarity 60%)
  3. Lukas Kübler (ID 142525, similarity 60%)
  4. Laurin Ulrich (ID 1152486, similarity 57%)
  5. Luca Sirch (ID 964603, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Nathan De Cat
  1. Nathan Tella (ID 920379, similarity 73%)
  2. Jonathan Tah (ID 227672, similarity 64%)
  3. Jonathan Burkardt (ID 939830, similarity 59%)
  4. Nathaniel Brown (ID 1159759, similarity 56%)
  5. Anthony Caci (ID 846471, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Lúkas Petersson
  1. Lukas Petkov (ID 960017, similarity 72%)
  2. Lukas Kübler (ID 142525, similarity 56%)
  3. Lasse Günther (ID 997175, similarity 54%)
  4. Julian Ryerson (ID 800951, similarity 52%)
  5. Lukas Finn Pinckert (ID 990105, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Alexander Meyer
  1. Alexander Prass (ID 978062, similarity 71%)
  2. Tom Alexander Rothe (ID 1210666, similarity 65%)
  3. Alexander Schwolow (ID 134778, similarity 58%)
  4. Alexis Claude-Maurice (ID 822877, similarity 55%)
  5. Julian Ryerson (ID 800951, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Maximilian Kinzig
  1. Maximilian Beier (ID 980628, similarity 71%)
  2. Maximilian Eggestein (ID 569784, similarity 69%)
  3. Maximilian Rohr (ID 846398, similarity 67%)
  4. Maximilian Wöber (ID 794962, similarity 65%)
  5. Maximilian Rosenfelder (ID 1131337, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Kauã Santos
  1. Kaishu Sano (ID 1028307, similarity 70%)
  2. Tom Krauß (ID 930272, similarity 53%)
  3. Waldemar Anton (ID 799046, similarity 52%)
  4. Dayot Upamecano (ID 798583, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Marius Funk
  1. Marius Wolf (ID 254119, similarity 70%)
  2. Marius Bülter (ID 378340, similarity 64%)
  3. Kaishu Sano (ID 1028307, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Timo Hübers
  1. Timo Becker (ID 814735, similarity 70%)
  2. Fabio Gruber (ID 1130119, similarity 57%)
  3. Ramon Hendriks (ID 916943, similarity 52%)
  4. Arthur (ID 1174761, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Linus Güther
  1. Lasse Günther (ID 997175, similarity 70%)
  2. Marius Bülter (ID 378340, similarity 61%)
  3. Lucas Höler (ID 280009, similarity 57%)
  4. Lukas Kübler (ID 142525, similarity 55%)
  5. Christian Günter (ID 142231, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for David Herold
  1. David Møller Wolfe (ID 1031283, similarity 69%)
  2. David Raum (ID 856076, similarity 60%)
  3. David Mokwa (ID 1432398, similarity 57%)
  4. Edin Džeko (ID 14990, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Stanley Nsoki
  1. Jan Leszczyński (ID 1823942, similarity 69%)
  2. Neil El Aynaoui (ID 1128530, similarity 56%)
  3. Daniel Svensson (ID 1021272, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Matthias Köbbing
  1. Matthias Ginter (ID 142259, similarity 69%)
  2. Mattes Hansen (ID 1083387, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Andrej Ilic
  1. Andrej Kramarić (ID 67647, similarity 67%)
  2. Andrija Maksimović (ID 1406171, similarity 59%)
  3. Dženan Pejčinović (ID 1127790, similarity 54%)
  4. Adil Aouchiche (ID 962877, similarity 52%)
  5. Martin Adeline (ID 1158529, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Dan-Axel Zagadou
  1. Joane Gadou (ID 1471049, similarity 67%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Filippo Mane
  1. Philipp Sander (ID 939880, similarity 67%)
  2. Phillipp Mwene (ID 138126, similarity 67%)
  3. Willi Orbán (ID 136924, similarity 57%)
  4. Linton Maina (ID 921033, similarity 55%)
  5. Philipp Treu (ID 979820, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Josip Juranović
  1. Josip Stanišić (ID 927407, similarity 67%)
  2. Igor Matanović (ID 1019321, similarity 59%)
  3. Arijon Ibrahimović (ID 1142248, similarity 58%)
  4. Jonas Urbig (ID 1130647, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Juma Bah
  1. Abdulai Juma Bah (ID 1606792, similarity 67%)
  2. Jarell Quansah (ID 1003339, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Luca Philipp
  1. Rayan Philippe (ID 991824, similarity 67%)
  2. Philipp Treu (ID 979820, similarity 64%)
  3. Philipp Sander (ID 939880, similarity 58%)
  4. Phillipp Mwene (ID 138126, similarity 58%)
  5. Lucas Höler (ID 280009, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Luca Schnellbacher
  1. Lucas Höler (ID 280009, similarity 67%)
  2. Tjark Lasse Scheller (ID 1137717, similarity 57%)
  3. Michel Aebischer (ID 850891, similarity 56%)
  4. Luca Sirch (ID 964603, similarity 54%)
  5. Castello Lukeba (ID 976421, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Lukas Klostermann
  1. Lukas Kübler (ID 142525, similarity 67%)
  2. Lucas Höler (ID 280009, similarity 54%)
  3. Lukas Petkov (ID 960017, similarity 52%)
  4. Łukasz Poręba (ID 942336, similarity 52%)
  5. Lasse Günther (ID 997175, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Malik Pimpong
  1. Malik Tillman (ID 975798, similarity 67%)
  2. Jahmai Simpson-Pusey (ID 1402924, similarity 53%)
  3. Marvin Pieringer (ID 909485, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Marc Guiu
  1. Marco Grüll (ID 815612, similarity 67%)
  2. Marius Wolf (ID 254119, similarity 56%)
  3. Marco Friedl (ID 825771, similarity 53%)
  4. Marius Bülter (ID 378340, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Markus Kolke
  1. Marius Wolf (ID 254119, similarity 67%)
  2. Mark Flekken (ID 171919, similarity 64%)
  3. Marius Bülter (ID 378340, similarity 61%)
  4. Tim Skarke (ID 800252, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Marvin Friedrich
  1. Marvin Pieringer (ID 909485, similarity 67%)
  2. Martin Terrier (ID 846445, similarity 64%)
  3. Marco Friedl (ID 825771, similarity 62%)
  4. Fabian Rieder (ID 929620, similarity 59%)
  5. Laurin Ulrich (ID 1152486, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Maximilian Mittelstädt
  1. Maximilian Beier (ID 980628, similarity 67%)
  2. Maximilian Rosenfelder (ID 1131337, similarity 62%)
  3. Maximilian Wöber (ID 794962, similarity 61%)
  4. Maximilian Eggestein (ID 569784, similarity 60%)
  5. Maximilian Rohr (ID 846398, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Nikolas Nartey
  1. Nikola Katić (ID 831488, similarity 67%)
  2. Jan-Niklas Beste (ID 836711, similarity 59%)
  3. Nicolas Kristof (ID 1131080, similarity 59%)
  4. Noël Aséko (ID 1410926, similarity 55%)
  5. Nicolai Remberg (ID 1064305, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Oliver Burke
  1. Oliver Baumann (ID 40244, similarity 67%)
  2. Olivier Deman (ID 960114, similarity 61%)
  3. Wouter Burger (ID 916946, similarity 61%)
  4. Livan Burcu (ID 1513469, similarity 57%)
  5. Oliver Batista Meier (ID 907685, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Sebastian Klaas
  1. Sebastian Sebulonsen (ID 1020206, similarity 67%)
  2. Sebastiaan Bornauw (ID 826167, similarity 65%)
  3. Satoshi Tanaka (ID 981067, similarity 59%)
  4. Atakan Karazor (ID 801030, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Tiago Tomás
  1. Tidiam Gomis (ID 1426577, similarity 67%)
  2. Tom Krauß (ID 930272, similarity 53%)
  3. Santiago Castañeda (ID 1199101, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Alexander Røssing-Lelesiit
  1. Alexander Prass (ID 978062, similarity 65%)
  2. Alexander Schwolow (ID 134778, similarity 55%)
  3. Tom Alexander Rothe (ID 1210666, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Maxime Estève
  1. Maximilian Eggestein (ID 569784, similarity 65%)
  2. Maximilian Beier (ID 980628, similarity 52%)
  3. Marius Bülter (ID 378340, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Nicolas Kühn
  1. Nicholas Mickelson (ID 900264, similarity 64%)
  2. Niclas Füllkrug (ID 132645, similarity 64%)
  3. Nicolas Kristof (ID 1131080, similarity 64%)
  4. Noël Aséko (ID 1410926, similarity 60%)
  5. Moritz Nicolas (ID 578166, similarity 58%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Jonas Hofmann
  1. Josha Vagnoman (ID 906278, similarity 64%)
  2. Jonathan Tah (ID 227672, similarity 61%)
  3. Borna Sosa (ID 357584, similarity 57%)
  4. Jonathan Burkardt (ID 939830, similarity 50%)
  5. Mattes Hansen (ID 1083387, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Lennard Maloney
  1. Lennart Karl (ID 1861975, similarity 64%)
  2. Kenan Karaman (ID 168943, similarity 62%)
  3. Bernardo (ID 828571, similarity 55%)
  4. Olivier Deman (ID 960114, similarity 54%)
  5. Waldemar Anton (ID 799046, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Niklas Stark
  1. Jan-Niklas Beste (ID 836711, similarity 64%)
  2. Nicolas Kristof (ID 1131080, similarity 56%)
  3. Nicolas Seiwald (ID 976575, similarity 56%)
  4. Nikola Katić (ID 831488, similarity 55%)
  5. Lasse Günther (ID 997175, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Amara Condé
  1. Bambasé Conté (ID 1185359, similarity 64%)
  2. Waldemar Anton (ID 799046, similarity 61%)
  3. Ragnar Ache (ID 877544, similarity 60%)
  4. Marco Friedl (ID 825771, similarity 57%)
  5. Harry Kane (ID 108579, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Anthony Jung
  1. Anthony Caci (ID 846471, similarity 64%)
  2. Antonio Nusa (ID 1121923, similarity 55%)
  3. Jordan Torunarigha (ID 801003, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Anton Kade
  1. Patson Daka (ID 865057, similarity 63%)
  2. Anthony Caci (ID 846471, similarity 60%)
  3. Antonio Nusa (ID 1121923, similarity 60%)
  4. Francis Onyeka (ID 1414916, similarity 55%)
  5. Daniel Fernandes (ID 113442, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Christoph Baumgartner
  1. Christopher Trimmel (ID 48557, similarity 63%)
  2. Christian Günter (ID 142231, similarity 63%)
  3. Christopher Nkunku (ID 769333, similarity 59%)
  4. Christian Kofane (ID 2029648, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Felix Agu
  1. Felix Nmecha (ID 907463, similarity 63%)
  2. Elias Baum (ID 1403018, similarity 59%)
  3. Felix Uduokhai (ID 792142, similarity 57%)
  4. Felix Keidel (ID 1215028, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Keke Topp
  1. Keisuke Goto (ID 1391315, similarity 63%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Luca Vozar
  1. Lucas Höler (ID 280009, similarity 63%)
  2. Lucas Vázquez (ID 255239, similarity 57%)
  3. Luca Sirch (ID 964603, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Tim Binder
  1. Timo Becker (ID 814735, similarity 63%)
  2. Fabian Rieder (ID 929620, similarity 57%)
  3. Kim Min-jae (ID 896569, similarity 56%)
  4. Philipp Sander (ID 939880, similarity 55%)
  5. Matthias Ginter (ID 142259, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Marcel Hoffmeier
  1. Marcel Sabitzer (ID 133908, similarity 62%)
  2. Marco Friedl (ID 825771, similarity 62%)
  3. Mitchell Weiser (ID 138150, similarity 55%)
  4. Manuel Neuer (ID 8959, similarity 54%)
  5. Karl Hein (ID 991591, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Patrick Drewes
  1. Patrick Osterhage (ID 914755, similarity 62%)
  2. Patrick Wimmer (ID 987504, similarity 62%)
  3. Patrik Schick (ID 280609, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Yannik Keitel
  1. Yannick Engelhardt (ID 990209, similarity 62%)
  2. Jan-Niklas Beste (ID 836711, similarity 62%)
  3. Felix Keidel (ID 1215028, similarity 52%)
  4. Rani Khedira (ID 149479, similarity 52%)
  5. Dennis Seimen (ID 1195736, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Franck Honorat
  1. Francis Onyeka (ID 1414916, similarity 62%)
  2. Rani Khedira (ID 149479, similarity 58%)
  3. Anthony Caci (ID 846471, similarity 50%)
  4. Antonio Nusa (ID 1121923, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Joël Schmied
  1. Tom Zimmerschied (ID 887457, similarity 62%)
  2. Finn Jeltsch (ID 1418649, similarity 55%)
  3. Aljoscha Kemlein (ID 1198074, similarity 54%)
  4. Joe Scally (ID 1002920, similarity 50%)
  5. Noël Aséko (ID 1410926, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Markus Schubert
  1. Marius Bülter (ID 378340, similarity 62%)
  2. András Schäfer (ID 877302, similarity 59%)
  3. Marvin Schwäbe (ID 187185, similarity 59%)
  4. Tjark Lasse Scheller (ID 1137717, similarity 56%)
  5. Arthur (ID 1174761, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Bilal Nadir
  1. Albian Hajdari (ID 1000269, similarity 61%)
  2. Lilian Brassier (ID 988907, similarity 58%)
  3. Fabian Rieder (ID 929620, similarity 55%)
  4. Neil El Aynaoui (ID 1128530, similarity 52%)
  5. Philipp Sander (ID 939880, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Ruben Müller
  1. Marius Bülter (ID 378340, similarity 61%)
  2. Robin Fellhauer (ID 860461, similarity 56%)
  3. Manuel Neuer (ID 8959, similarity 55%)
  4. Robin Zentner (ID 174345, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Sven Ulreich
  1. Laurin Ulrich (ID 1152486, similarity 61%)
  2. Lukas Ullrich (ID 1083382, similarity 61%)
  3. Chris Führich (ID 891510, similarity 52%)
  4. Robert Andrich (ID 168903, similarity 50%)
  5. Samuele Inacio (ID 1861666, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Tim Kleindienst
  1. Kevin Diks (ID 583806, similarity 61%)
  2. Tom Alexander Rothe (ID 1210666, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Tim Oermann
  1. Oliver Baumann (ID 40244, similarity 61%)
  2. Timo Becker (ID 814735, similarity 60%)
  3. Joey Veerman (ID 850816, similarity 57%)
  4. Olivier Deman (ID 960114, similarity 55%)
  5. Igor Matanović (ID 1019321, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Vitalie Becker
  1. Timo Becker (ID 814735, similarity 61%)
  2. Sheraldo Becker (ID 352544, similarity 59%)
  3. Isac Lidberg (ID 798175, similarity 58%)
  4. Nicolai Remberg (ID 1064305, similarity 52%)
  5. Maximilian Beier (ID 980628, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Dominik Kohr
  1. Robin Koch (ID 581302, similarity 60%)
  2. Edin Džeko (ID 14990, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Felix Götze
  1. Mario Götze (ID 66518, similarity 60%)
  2. Felix Keidel (ID 1215028, similarity 57%)
  3. Felix Nmecha (ID 907463, similarity 57%)
  4. Felix Uduokhai (ID 792142, similarity 52%)
  5. Marcel Sabitzer (ID 133908, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Finn Porath
  1. Finn Dahmen (ID 822564, similarity 60%)
  2. Finn Jeltsch (ID 1418649, similarity 57%)
  3. Lukas Finn Pinckert (ID 990105, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Janik Bachmann
  1. Calvin Brackelmann (ID 1128792, similarity 60%)
  2. Kenan Karaman (ID 168943, similarity 56%)
  3. Oliver Baumann (ID 40244, similarity 54%)
  4. Han-Noah Massengo (ID 927340, similarity 50%)
  5. Mio Backhaus (ID 1083390, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Kevin Stöger
  1. Kevin Diks (ID 583806, similarity 60%)
  2. Keisuke Goto (ID 1391315, similarity 55%)
  3. Kastriot Imeri (ID 865520, similarity 50%)
  4. Vincenzo Grifo (ID 171961, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Ko Itakura
  1. Keita Kosugi (ID 1501641, similarity 60%)
  2. Satoshi Tanaka (ID 981067, similarity 55%)
  3. Koki Machida (ID 790977, similarity 50%)
  4. Lukas Kübler (ID 142525, similarity 50%)
  5. Nikola Katić (ID 831488, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Paul Nebel
  1. Manuel Neuer (ID 8959, similarity 60%)
  2. Paul Erevbenagie (ID 2160258, similarity 58%)
  3. Jae-sung Lee (ID 537552, similarity 53%)
  4. Nahuel Noll (ID 1048651, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Florian Müller
  1. Florian Neuhaus (ID 837205, similarity 59%)
  2. Laurin Ulrich (ID 1152486, similarity 56%)
  3. Angelo Stiller (ID 901882, similarity 54%)
  4. Livan Burcu (ID 1513469, similarity 52%)
  5. Christian Günter (ID 142231, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Jan Olschowsky
  1. Jan Leszczyński (ID 1823942, similarity 59%)
  2. Jano Ter-Horst (ID 1152342, similarity 56%)
  3. Stefan Posch (ID 355486, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Kennet Eichhorn
  1. Hennes Behrens (ID 1864760, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Nediljko Labrović
  1. Nikola Katić (ID 831488, similarity 59%)
  2. Neil El Aynaoui (ID 1128530, similarity 55%)
  3. Andrija Maksimović (ID 1406171, similarity 55%)
  4. Andrej Kramarić (ID 67647, similarity 53%)
  5. Noah Darvich (ID 1469995, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Rael-Tshimbela Nakuzola
  1. Satoshi Tanaka (ID 981067, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Tom Baack
  1. Robin Hack (ID 876858, similarity 59%)
  2. Timo Becker (ID 814735, similarity 56%)
  3. Tom Bischof (ID 1129935, similarity 56%)
  4. Linton Maina (ID 921033, similarity 53%)
  5. Mio Backhaus (ID 1083390, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Deniz Zeitler
  1. Dennis Seimen (ID 1195736, similarity 58%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Fabio Chiarodia
  1. Fábio Silva (ID 954076, similarity 58%)
  2. Fábio Vieira (ID 904835, similarity 56%)
  3. Albian Hajdari (ID 1000269, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Farès Chaïbi
  1. Ismael Saibari (ID 1063767, similarity 58%)
  2. Marvin Schwäbe (ID 187185, similarity 58%)
  3. Marcel Sabitzer (ID 133908, similarity 56%)
  4. Patrik Schick (ID 280609, similarity 52%)
  5. András Schäfer (ID 877302, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Hee-Chan Hwang
  1. Ethan Nwaneri (ID 1401702, similarity 58%)
  2. Hwang Hee-chan (ID 786186, similarity 58%)
  3. Han-Noah Massengo (ID 927340, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Jannik Huth
  1. Jan-Niklas Beste (ID 836711, similarity 58%)
  2. Janik Haberer (ID 168985, similarity 55%)
  3. Yannick Engelhardt (ID 990209, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Luca Waldschmidt
  1. Luca Sirch (ID 964603, similarity 58%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Silvan Widmer
  1. Fabian Rieder (ID 929620, similarity 58%)
  2. Philipp Sander (ID 939880, similarity 56%)
  3. Nicolai Remberg (ID 1064305, similarity 54%)
  4. Isac Lidberg (ID 798175, similarity 52%)
  5. Maximilian Beier (ID 980628, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Cédric Itten
  1. Eric Martel (ID 988639, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Eliesse Ben Seghir
  1. Ellyes Skhiri (ID 591706, similarity 57%)
  2. Dennis Seimen (ID 1195736, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Frederik Schmahl
  1. Frederik Rønnow (ID 137692, similarity 57%)
  2. Eric Martel (ID 988639, similarity 56%)
  3. Alexander Schwolow (ID 134778, similarity 50%)
  4. Grischa Prömel (ID 253993, similarity 50%)
  5. Ramon Hendriks (ID 916943, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Luca Pfeiffer
  1. Luca Sirch (ID 964603, similarity 57%)
  2. Lucas Höler (ID 280009, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Ron Schallenberg
  1. Marvin Schwäbe (ID 187185, similarity 57%)
  2. Isac Lidberg (ID 798175, similarity 54%)
  3. Aljoscha Kemlein (ID 1198074, similarity 53%)
  4. Robin Zentner (ID 174345, similarity 52%)
  5. András Schäfer (ID 877302, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Stefan Bell
  1. Nathan Tella (ID 920379, similarity 57%)
  2. Stefan Posch (ID 355486, similarity 57%)
  3. Cole Campbell (ID 1134578, similarity 55%)
  4. Fabian Bredlow (ID 152463, similarity 52%)
  5. Stefano Marino (ID 1167764, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Daniel Batz
  1. Daniel Fernandes (ID 113442, similarity 56%)
  2. Yannick Engelhardt (ID 990209, similarity 52%)
  3. Daniel Svensson (ID 1021272, similarity 50%)
  4. Marcel Sabitzer (ID 133908, similarity 50%)
  5. Nathaniel Brown (ID 1159759, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Derrick Köhn
  1. Derry Scherhant (ID 1131002, similarity 56%)
  2. Robert Andrich (ID 168903, similarity 50%)
  3. Robin Koch (ID 581302, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Marin Ljubičić
  1. Laurin Ulrich (ID 1152486, similarity 56%)
  2. Martin Adeline (ID 1158529, similarity 54%)
  3. Marvin Pieringer (ID 909485, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Timothy Chandler
  1. Timo Becker (ID 814735, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Emre Can
  1. Felix Nmecha (ID 907463, similarity 56%)
  2. Hwang Hee-chan (ID 786186, similarity 53%)
  3. Waldemar Anton (ID 799046, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Faik Sakar
  1. Tim Skarke (ID 800252, similarity 56%)
  2. Daiki Hashioka (ID 897334, similarity 55%)
  3. Francis Onyeka (ID 1414916, similarity 55%)
  4. Fábio Silva (ID 954076, similarity 53%)
  5. Patson Daka (ID 865057, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Jens Grahl
  1. Joe Scally (ID 1002920, similarity 56%)
  2. Jarell Quansah (ID 1003339, similarity 55%)
  3. Jae-sung Lee (ID 537552, similarity 53%)
  4. Brajan Gruda (ID 1198075, similarity 50%)
  5. Jan Gyamerah (ID 254411, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Sima Suso
  1. Marius Wolf (ID 254119, similarity 56%)
  2. Mats Rots (ID 1387012, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Tim Boss
  1. Tidiam Gomis (ID 1426577, similarity 56%)
  2. Borna Sosa (ID 357584, similarity 50%)
  3. Tim Skarke (ID 800252, similarity 50%)
  4. Tom Krauß (ID 930272, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Frank Lehmann
  1. Calvin Brackelmann (ID 1128792, similarity 55%)
  2. Rani Khedira (ID 149479, similarity 52%)
  3. Bilal El Khannouss (ID 1126569, similarity 50%)
  4. Hwang Hee-chan (ID 786186, similarity 50%)
  5. Kenan Karaman (ID 168943, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Johan Bakayoko
  1. Jonathan Burkardt (ID 939830, similarity 55%)
  2. Ozan Kabak (ID 857740, similarity 55%)
  3. Satoshi Tanaka (ID 981067, similarity 54%)
  4. Joane Gadou (ID 1471049, similarity 52%)
  5. Jonathan Tah (ID 227672, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Paul Okon-Engstler
  1. Angelo Stiller (ID 901882, similarity 55%)
  2. Manuel Neuer (ID 8959, similarity 52%)
  3. Paul Erevbenagie (ID 2160258, similarity 52%)
  4. Patrick Osterhage (ID 914755, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Giannis Konstantelias
  1. Konstantinos Karetsas (ID 1468744, similarity 55%)
  2. Nathan Tella (ID 920379, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Carl Klaus
  1. Jarell Quansah (ID 1003339, similarity 55%)
  2. Mio Backhaus (ID 1083390, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Janis Blaswich
  1. Luca Sirch (ID 964603, similarity 55%)
  2. Adil Aouchiche (ID 962877, similarity 54%)
  3. Josip Stanišić (ID 927407, similarity 54%)
  4. Jan-Niklas Beste (ID 836711, similarity 52%)
  5. Dariusz Stalmach (ID 1141977, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Senne Lynen
  1. Dennis Seimen (ID 1195736, similarity 55%)
  2. Hennes Behrens (ID 1864760, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Shafiq Nandja
  1. Finn Dahmen (ID 822564, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Sven Michel
  1. Michael Olise (ID 978838, similarity 55%)
  2. Eric Martel (ID 988639, similarity 50%)
  3. Mitchell Weiser (ID 138150, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Ameen Al Dakhil
  1. Samuele Inacio (ID 1861666, similarity 54%)
  2. Adam Daghim (ID 1180758, similarity 52%)
  3. Eren Dinkçi (ID 1067120, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Assan Ouédraogo
  1. Hasan Kuruçay (ID 852096, similarity 54%)
  2. Kaishu Sano (ID 1028307, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Kevin Müller
  1. David Møller Wolfe (ID 1031283, similarity 54%)
  2. Angelo Stiller (ID 901882, similarity 50%)
  3. Kevin Diks (ID 583806, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Leopold Zingerle
  1. Tim Lemperle (ID 1014290, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Ron-Robert Zieler
  1. Gregor Kobel (ID 556866, similarity 54%)
  2. Martin Terrier (ID 846445, similarity 50%)
  3. Robert Andrich (ID 168903, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Jens Castrop
  1. Alessio Castro-Montes (ID 839898, similarity 53%)
  2. Bernardo (ID 828571, similarity 53%)
  3. Jonah Sticker (ID 1517850, similarity 52%)
  4. Joe Scally (ID 1002920, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Silas
  1. Fábio Silva (ID 954076, similarity 53%)
  2. Said El Mala (ID 1800475, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Bara Sapoko Ndiaye
  1. Albert Sambi Lokonga (ID 901892, similarity 53%)
  2. Brajan Gruda (ID 1198075, similarity 52%)
  3. Raphael Onyedika (ID 1129862, similarity 52%)
  4. Bambasé Conté (ID 1185359, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Montrell Culbreath
  1. Emmanuel Latte Lath (ID 848074, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Bruno Ogbus
  1. Borna Sosa (ID 357584, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Fritz Fleck
  1. Ridle Baku (ID 856553, similarity 53%)
  2. Mario Götze (ID 66518, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Guéla Doué
  1. Joane Gadou (ID 1471049, similarity 53%)
  2. Manuel Neuer (ID 8959, similarity 50%)
  3. Miguel Gutiérrez (ID 908716, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Jens Stage
  1. Jae-sung Lee (ID 537552, similarity 53%)
  2. Otto Stange (ID 1568535, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Otávio
  1. Igor Matanović (ID 1019321, similarity 53%)
  2. David Mokwa (ID 1432398, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Raif Adam
  1. Brajan Gruda (ID 1198075, similarity 53%)
  2. Ibrahim Maza (ID 1407524, similarity 53%)
  3. Junior Adamu (ID 902381, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Robert Skov
  1. Mert Kömür (ID 1390682, similarity 53%)
  2. Noël Aséko (ID 1410926, similarity 53%)
  3. Robin Koch (ID 581302, similarity 53%)
  4. Robert Andrich (ID 168903, similarity 52%)
  5. Albert Sambi Lokonga (ID 901892, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Serge Gnabry
  1. Bernardo (ID 828571, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Cajetan Lenz
  1. Mattes Hansen (ID 1083387, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Imad Rondic
  1. Igor Matanović (ID 1019321, similarity 52%)
  2. Eren Dinkçi (ID 1067120, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Justin Lerma
  1. Jamal Musiala (ID 1010231, similarity 52%)
  2. Jonah Sticker (ID 1517850, similarity 52%)
  3. Angelo Stiller (ID 901882, similarity 50%)
  4. Julian Ryerson (ID 800951, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Leopold Querfeld
  1. Leo Sauer (ID 1150938, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Lorenz Assignon
  1. Borna Sosa (ID 357584, similarity 52%)
  2. Daniel Svensson (ID 1021272, similarity 50%)
  3. Jonas Urbig (ID 1130647, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Max Moerstedt
  1. Marco Friedl (ID 825771, similarity 52%)
  2. Maximilian Wöber (ID 794962, similarity 52%)
  3. Tom Zimmerschied (ID 887457, similarity 52%)
  4. Maximilian Eggestein (ID 569784, similarity 52%)
  5. Jano Ter-Horst (ID 1152342, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Mekhi Gray
  1. Serhou Guirassy (ID 328027, similarity 52%)
  2. Aleix García (ID 796047, similarity 50%)
  3. Rani Khedira (ID 149479, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Zento Uno
  1. Zeno Van Den Bosch (ID 1103765, similarity 52%)
  2. Robin Zentner (ID 174345, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Sander Tangvik
  1. Andrej Kramarić (ID 67647, similarity 52%)
  2. Aleksandar Pavlović (ID 1142251, similarity 52%)
  3. Albert Grønbæk (ID 1000263, similarity 50%)
  4. Isac Lidberg (ID 798175, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Thijs Dallinga
  1. Jobe Bellingham (ID 1134083, similarity 52%)
  2. Isac Lidberg (ID 798175, similarity 50%)
  3. Nathan Tella (ID 920379, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Tom Wisbereit
  1. Tom Zimmerschied (ID 887457, similarity 52%)
  2. Marius Bülter (ID 378340, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Yanik Spalt
  1. Yannick Engelhardt (ID 990209, similarity 52%)
  2. Jan-Niklas Beste (ID 836711, similarity 50%)
  3. Nicolás Capaldo (ID 973564, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Johannes Simon Siebeking
  1. Jamie Leweling (ID 990201, similarity 51%)
  2. Jahmai Simpson-Pusey (ID 1402924, similarity 50%)
  3. Jan Leszczyński (ID 1823942, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Abdoul Koné
  1. Rômulo (ID 1133743, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Clemens Lippmann
  1. Calvin Brackelmann (ID 1128792, similarity 50%)
  2. Phillipp Mwene (ID 138126, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Justin Diehl
  1. Martin Adeline (ID 1158529, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Kauã Prates
  1. Alexander Prass (ID 978062, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Leonidas Stergiou
  1. Dennis Seimen (ID 1195736, similarity 50%)
  2. Jonah Sticker (ID 1517850, similarity 50%)
  3. Lasse Günther (ID 997175, similarity 50%)
  4. Leo Sauer (ID 1150938, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Luca Reggiani
  1. Karl Hein (ID 991591, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Matheo Raab
  1. Arthur (ID 1174761, similarity 50%)
  2. Matthias Ginter (ID 142259, similarity 50%)
  3. Patson Daka (ID 865057, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Mathieu Nguefack
  1. Martin Adeline (ID 1158529, similarity 50%)
  2. Satoshi Tanaka (ID 981067, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Mert Can Ayhan
  1. Kenan Karaman (ID 168943, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Oscar Højlund
  1. Joe Scally (ID 1002920, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Rav van den Berg
  1. Isac Lidberg (ID 798175, similarity 50%)
  2. Manuel Neuer (ID 8959, similarity 50%)
  3. Raphael Obermair (ID 820465, similarity 50%)
  4. Zeno Van Den Bosch (ID 1103765, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Reigan Heskey
  1. Adrian Gantenbein (ID 1046188, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Sota Kawasaki
  1. Noahkai Banks (ID 1597260, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Timur Gayret
  1. Tim Skarke (ID 800252, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Valentin Gendrey
  1. Martin Adeline (ID 1158529, similarity 50%)
  2. Martin Terrier (ID 846445, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Örjan Nyland
  1. Francis Onyeka (ID 1414916, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

Input summary
  Matchday: 6; Kickbase percentile rating: sofascore_kickbase_percentile_ratings_2026-10-16_11-22-48_017318+0200.json
  Ligainsider (weight 4; current): ligainsider_bundesliga_lineups_20261016_113334.json
  Kickbase (weight 3; current): kickbase_bundesliga_lineups_20261016_120556.json
  Kicker (weight 2; current): kicker_bundesliga_lineups_20261016_113641.json
  Rotowire (weight 1; current): rotowire_bundesliga_lineups_20261016_113310.json
  Alternative starting-chance decay: 0.45
  Questionable-injury starting-chance penalty: 0.15
  Score multiplier: 10.0062
  Expected-points blend: 80% calculated + 20% recency-weighted mean.
  Output: C:\kickbase project\outputs\expected_points\expected_points_20261016_111610_+0200_sofascore_kickbase_percentile_rating_odds_lineup_20261016_122716_+0200.csv

Team odds and expected match points

,team,provider,win_probability,draw_probability,loss_probability,expected_match_points
0,augsburg,FotMob,0.357640,0.263262,0.379098,1.336181
1,bayern,FotMob,0.778612,0.115842,0.105545,2.451680
2,bremen,FotMob,0.542448,0.226020,0.231533,1.853363
3,dortmund,FotMob,0.585701,0.220659,0.193640,1.977762
4,elversberg,FotMob,0.379098,0.263262,0.357640,1.400556
5,frankfurt,FotMob,0.498437,0.230983,0.270580,1.726294
6,freiburg,FotMob,0.215710,0.225982,0.558308,0.873112
7,gladbach,FotMob,0.294118,0.235294,0.470588,1.117647
8,hamburg,FotMob,0.242843,0.230997,0.526160,0.959526
9,hoffenheim,FotMob,0.470588,0.235294,0.294118,1.647059
10,koeln,FotMob,0.270580,0.230983,0.498437,1.042723
11,leipzig,FotMob,0.105545,0.115842,0.778612,0.432478
12,leverkusen,FotMob,0.558308,0.225982,0.215710,1.900906
13,mainz,FotMob,0.421053,0.263158,0.315789,1.526316
14,paderborn,FotMob,0.231533,0.226020,0.542448,0.920617
15,schalke,FotMob,0.315789,0.263158,0.421053,1.210526
16,stuttgart,FotMob,0.526160,0.230997,0.242843,1.809477
17,union,FotMob,0.193640,0.220659,0.585701,0.801579

Player score review (non-positive or non-exact historical metric)

,name,team,metric_status,lineup_status,kickbase_percentile_rating,expected_match_points,ligainsider_starting_chance,kickbase_starting_chance,kicker_starting_chance,rotowire_starting_chance,questionable_injury_penalty,starting_chance,score_multiplier,score,calculated_expected_points,recency_weighted_mean_points
0,Jonathan Tah,bayern,missing_history,ligainsider:exact; kickbase:normalized; kicker...,8.2,2.451680,1.000000,0.689655,1.0,1.0,0.00,0.906897,10.0062,169.708673,182.433461,118.809524
1,Manuel Neuer,bayern,missing_history,ligainsider:exact; kickbase:normalized; kicker...,6.9,1.590336,0.264706,0.375000,0.0,0.0,0.15,0.218382,10.0062,39.925775,23.978647,103.714286
2,Sven Ulreich,bayern,missing_history,ligainsider:missing; kickbase:missing; kicker:...,0.0,1.590336,0.000000,0.000000,0.0,0.0,0.00,0.000000,10.0062,0.000000,0.000000,0.000000
3,Joshua Kimmich,bayern,missing_history,ligainsider:exact; kickbase:normalized; kicker...,9.3,2.451680,1.000000,1.000000,1.0,1.0,0.00,1.000000,10.0062,218.558054,228.147567,180.200000
4,Serge Gnabry,bayern,missing_history,ligainsider:exact; kickbase:normalized; kicker...,0.0,2.451680,0.689655,0.689655,1.0,0.0,0.00,0.682759,10.0062,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,Nikola Katic,schalke,missing_history,ligainsider:exact; kickbase:normalized; kicker...,8.0,1.210526,1.000000,1.000000,1.0,1.0,0.00,1.000000,10.0062,104.021718,96.902147,132.500000
461,Luca Vozar,schalke,missing_history,ligainsider:missing; kickbase:normalized; kick...,0.0,1.210526,0.000000,0.272315,0.0,0.0,0.00,0.081694,10.0062,0.000000,0.000000,0.000000
462,Satoshi Tanaka,schalke,missing_history,ligainsider:exact; kickbase:normalized; kicker...,5.4,1.210526,0.689655,0.605144,1.0,1.0,0.00,0.757405,10.0062,48.490005,49.541078,44.285714
463,Johannes Simon Siebeking,schalke,missing_history,ligainsider:missing; kickbase:missing; kicker:...,0.0,1.342105,0.000000,0.000000,0.0,0.0,0.00,0.000000,10.0062,0.000000,0.000000,0.000000
464,Adil Aouchiche,schalke,missing_history,ligainsider:exact; kickbase:normalized; kicker...,6.2,1.210526,0.689655,1.000000,1.0,1.0,0.00,0.875862,10.0062,63.978350,65.776509,56.785714