# SofaScore overall rating × odds × lineup score

Creates optimizer-ready scores from overall average ratings, expected match points from odds, and configurable-weight LigaInsider, Kickbase, and RotoWire starting chances. LigaInsider and Kickbase alternatives use configurable geometric decay before slot normalization; Kicker remains reserved until its parser exists. The exported CSV includes the provider-specific chances, the injury penalty, and the final `score` column.

Confirmed SofaScore, LigaInsider, and RotoWire name matches are stored with Transfermarkt mappings in `data/reference/player_name_cross_references.csv`. Kickbase display names resolve to a unique same-team KBStats last name, then first name; only shared-name or no-match candidates at 50% similarity or higher are shown for notebook confirmation and stored separately in `data/reference/kickbase_player_name_cross_references.csv`. Lower-similarity cases record `kickbase:missing`.

Set the notebook's QUES penalty, alternative-decay, and source-weight variables to tune scoring. A provider-level QUES reduction is applied before LigaInsider or Kickbase formation-slot alternatives are normalized.

In [2]:
import sys
from pathlib import Path

# Absolute starting-chance reduction for a `QUES` injury flag from a lineup source.
QUESTIONABLE_INJURY_STARTING_CHANCE_PENALTY = 0.15
# Each rank is 45% of the preceding alternative before its slot is normalized.
ALTERNATIVE_STARTING_CHANCE_DECAY = 0.45
# Relative trust weights for active lineup sources; use 0 to disable one.
LINEUP_SOURCE_WEIGHTS = {'ligainsider': 4.0, 'kickbase': 3.0, 'kicker': 2.0, 'rotowire': 1.0}

def locate_project_root() -> Path:
    starts = [Path.cwd().resolve()]
    notebook_path = globals().get('__vsc_ipynb_file__')
    if isinstance(notebook_path, str) and notebook_path.strip():
        starts.insert(0, Path(notebook_path).expanduser().resolve().parent)
    for start in starts:
        for candidate in (start, *start.parents):
            if (candidate / 'project_paths.py').is_file():
                return candidate
    raise FileNotFoundError('Could not locate project_paths.py.')

PROJECT_ROOT = locate_project_root()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from sofascore_rating_odds_lineup_score import run_score_creation
result = run_score_creation(
    'overall',
    questionable_injury_starting_chance_penalty=QUESTIONABLE_INJURY_STARTING_CHANCE_PENALTY,
    alternative_starting_chance_decay=ALTERNATIVE_STARTING_CHANCE_DECAY,
    lineup_source_weights=LINEUP_SOURCE_WEIGHTS,
)

Matchday for odds and lineups:  1

No exact match for rotowire lineup for Shafiq Nandja (hamburg)
  1. Shafiq Bello Nandja (ID 48225, similarity 83%)

Choose a candidate number, or press Enter to skip (score 0):  1

No exact match for SofaScore rating for Luca Jaquez
  1. Lucas Vázquez (ID 255239, similarity 82%)
  2. Cajetan Lenz (ID 2077300, similarity 57%)
  3. Luca Vozar (ID 2255221, similarity 53%)
  4. Lucas Höler (ID 280009, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nico Schlotterbeck
  1. Keven Schlotterbeck (ID 891651, similarity 80%)
  2. Nicolás Capaldo (ID 973564, similarity 52%)
  3. Sheraldo Becker (ID 352544, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Mitchell Weiser
  1. Michael Olise (ID 978838, similarity 77%)
  2. Michel Aebischer (ID 850891, similarity 76%)
  3. Michael Gregoritsch (ID 111483, similarity 56%)
  4. Mathis Albert (ID 1937835, similarity 54%)
  5. Mick Schmetgens (ID 1568521, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Alexander Schwolow
  1. Alexander Schlager (ID 282073, similarity 76%)
  2. Tom Alexander Rothe (ID 1210666, similarity 59%)
  3. Alessandro Vogt (ID 1408406, similarity 58%)
  4. Alexander Meyer (ID 138491, similarity 58%)
  5. Aleksandar Pavlović (ID 1142251, similarity 51%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Luka Duric
  1. Lukas Ullrich (ID 1083382, similarity 76%)
  2. Laurin Curda (ID 981788, similarity 60%)
  3. Lukas Kübler (ID 142525, similarity 60%)
  4. Laurin Ulrich (ID 1152486, similarity 57%)
  5. Luca Sirch (ID 964603, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lúkas Petersson
  1. Lukas Petkov (ID 960017, similarity 72%)
  2. Lukas Kübler (ID 142525, similarity 56%)
  3. Lasse Günther (ID 997175, similarity 54%)
  4. Julian Ryerson (ID 800951, similarity 52%)
  5. Amos Pieper (ID 851254, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Alexander Prass
  1. Alexander Meyer (ID 138491, similarity 71%)
  2. Alexander Schlager (ID 282073, similarity 65%)
  3. Tom Alexander Rothe (ID 1210666, similarity 65%)
  4. Aleksandar Pavlović (ID 1142251, similarity 56%)
  5. Aleix García (ID 796047, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Rihito Yamamoto
  1. Takato Yamamoto (ID 2076134, similarity 71%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Marius Funk
  1. Marius Wolf (ID 254119, similarity 70%)
  2. Marius Bülter (ID 378340, similarity 64%)
  3. Kaishu Sano (ID 1028307, similarity 50%)
  4. Markus Schubert (ID 795006, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Timo Hübers
  1. Timo Becker (ID 814735, similarity 70%)
  2. Tim Binder (ID 1925507, similarity 63%)
  3. Fabio Gruber (ID 1130119, similarity 57%)
  4. Markus Schubert (ID 795006, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Florian Pruhs
  1. Loris Karius (ID 174135, similarity 70%)
  2. Florian Müller (ID 842858, similarity 64%)
  3. Livan Burcu (ID 1513469, similarity 55%)
  4. Florian Yves Le Joncour (ID 787816, similarity 50%)
  5. Laurin Ulrich (ID 1152486, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Linus Güther
  1. Lasse Günther (ID 997175, similarity 70%)
  2. Marius Bülter (ID 378340, similarity 61%)
  3. Lucas Höler (ID 280009, similarity 57%)
  4. Kevin Stöger (ID 95381, similarity 55%)
  5. Lukas Kübler (ID 142525, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Janik Haberer
  1. Jan-Niklas Beste (ID 836711, similarity 69%)
  2. Janik Bachmann (ID 579254, similarity 56%)
  3. Jan Gyamerah (ID 254411, similarity 52%)
  4. Rani Khedira (ID 149479, similarity 52%)
  5. Raphael Obermair (ID 820465, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Stanley Nsoki
  1. Jan Leszczyński (ID 1823942, similarity 69%)
  2. Daniel Svensson (ID 1021272, similarity 54%)
  3. Cajetan Lenz (ID 2077300, similarity 52%)
  4. Sani Suleiman (ID 1894870, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Matthias Köbbing
  1. Matthias Ginter (ID 142259, similarity 69%)
  2. Mattes Hansen (ID 1083387, similarity 59%)
  3. Malik Pimpong (ID 1957761, similarity 52%)
  4. Mathis Albert (ID 1937835, similarity 52%)
  5. Thijs Dallinga (ID 905381, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Arthur
  1. Arthur Chaves (ID 1122806, similarity 67%)
  2. Arthur Theate (ID 965778, similarity 67%)
  3. Arthur Vermeeren (ID 1149127, similarity 57%)
  4. Markus Schubert (ID 795006, similarity 50%)
  5. Matheo Raab (ID 842718, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Dan-Axel Zagadou
  1. Joane Gadou (ID 1471049, similarity 67%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Jason Ceka (elversberg)
  1. ONYEKA (displayed name, similarity 67%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Justin Diehl
  1. Justin Njinmah (ID 1005343, similarity 67%)
  2. Justin Lerma (ID 1836843, similarity 64%)
  3. Martin Adeline (ID 1158529, similarity 50%)
  4. Tim Binder (ID 1925507, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kevin Müller
  1. Florian Müller (ID 842858, similarity 67%)
  2. Kevin Stöger (ID 95381, similarity 64%)
  3. Angelo Stiller (ID 901882, similarity 50%)
  4. Kevin Diks (ID 583806, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Leopold Zingerle
  1. Leopold Querfeld (ID 1086547, similarity 67%)
  2. Enzo Leopold (ID 1009161, similarity 54%)
  3. Tim Lemperle (ID 1014290, similarity 54%)
  4. Valentin Gendrey (ID 944899, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lukas Klostermann
  1. Lukas Kübler (ID 142525, similarity 67%)
  2. Lucas Höler (ID 280009, similarity 54%)
  3. Justin Lerma (ID 1836843, similarity 52%)
  4. Lukas Petkov (ID 960017, similarity 52%)
  5. Łukasz Poręba (ID 942336, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lukas Pinckert
  1. Lukas Kübler (ID 142525, similarity 67%)
  2. Lukas Petkov (ID 960017, similarity 58%)
  3. Jonah Sticker (ID 1517850, similarity 56%)
  4. Lukas Ullrich (ID 1083382, similarity 56%)
  5. Luca Sirch (ID 964603, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Marco Grüll (bremen)
  1. Marco Friedl (ID 23443, similarity 67%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Markus Kolke
  1. Marius Wolf (ID 254119, similarity 67%)
  2. Mark Flekken (ID 171919, similarity 64%)
  3. Marius Bülter (ID 378340, similarity 61%)
  4. Markus Schubert (ID 795006, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Niklas Stark
  1. Nikolas Nartey (ID 861981, similarity 67%)
  2. Jan-Niklas Beste (ID 836711, similarity 64%)
  3. Ilyas Ansah (ID 1462742, similarity 57%)
  4. Nicolas Kristof (ID 1131080, similarity 56%)
  5. Nicolas Seiwald (ID 976575, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Oliver Burke
  1. Oliver Baumann (ID 40244, similarity 67%)
  2. Olivier Deman (ID 960114, similarity 61%)
  3. Wouter Burger (ID 916946, similarity 61%)
  4. Livan Burcu (ID 1513469, similarity 57%)
  5. Oliver Batista Meier (ID 907685, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Patrice Covic
  1. Patrik Schick (ID 280609, similarity 67%)
  2. Gabriel Vidović (ID 1129940, similarity 62%)
  3. Patrick Drewes (ID 132607, similarity 56%)
  4. Patrick Wimmer (ID 987504, similarity 56%)
  5. Ermedin Demirović (ID 878081, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Ruben Müller
  1. Florian Müller (ID 842858, similarity 67%)
  2. Marius Bülter (ID 378340, similarity 61%)
  3. Robin Fellhauer (ID 860461, similarity 56%)
  4. Manuel Neuer (ID 8959, similarity 55%)
  5. Robin Zentner (ID 174345, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sebastian Klaas
  1. Bastian Assomo (ID 2361805, similarity 67%)
  2. Sebastiaan Bornauw (ID 826167, similarity 65%)
  3. Cassiano Kiala (ID 1994978, similarity 59%)
  4. Satoshi Tanaka (ID 981067, similarity 59%)
  5. Samuel Mbangula (ID 1100836, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Andrej Kramarić
  1. Andrija Maksimović (ID 1406171, similarity 65%)
  2. Nadiem Amiri (ID 327755, similarity 56%)
  3. Adam Daghim (ID 1180758, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Nicholas Mickelson (elversberg)
  1. Nicolas Kristof (ID 26473, similarity 65%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Nicholas Mickelson (elversberg)
  1. Nicolas Kristof (ID 48713, similarity 65%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Assan Ouédraogo
  1. Alessandro Vogt (ID 1408406, similarity 64%)
  2. Hasan Kuruçay (ID 852096, similarity 54%)
  3. Cassiano Kiala (ID 1994978, similarity 52%)
  4. Sander Tangvik (ID 1030355, similarity 52%)
  5. Kaishu Sano (ID 1028307, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Marvin Friedrich
  1. Martin Terrier (ID 846445, similarity 64%)
  2. Marco Friedl (ID 825771, similarity 62%)
  3. Fabian Rieder (ID 929620, similarity 59%)
  4. Laurin Ulrich (ID 1152486, similarity 59%)
  5. Marvin Schwäbe (ID 187185, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Frank Lehmann
  1. Janik Bachmann (ID 579254, similarity 64%)
  2. Sani Suleiman (ID 1894870, similarity 58%)
  3. Franck Honorat (ID 280453, similarity 56%)
  4. Rani Khedira (ID 149479, similarity 52%)
  5. Jan Uwe Thielmann (ID 1010726, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jonas Hofmann
  1. Janik Bachmann (ID 579254, similarity 64%)
  2. Josha Vagnoman (ID 906278, similarity 64%)
  3. Jonathan Tah (ID 227672, similarity 61%)
  4. Jan Uwe Thielmann (ID 1010726, similarity 52%)
  5. Jonathan Burkardt (ID 939830, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Amara Condé
  1. Bambasé Conté (ID 1185359, similarity 64%)
  2. Waldemar Anton (ID 799046, similarity 61%)
  3. Ragnar Ache (ID 877544, similarity 60%)
  4. Chema Andrés (ID 1464641, similarity 57%)
  5. Marco Friedl (ID 825771, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Anthony Jung
  1. Anthony Caci (ID 846471, similarity 64%)
  2. Antonio Nusa (ID 1121923, similarity 55%)
  3. Anton Kade (ID 1129365, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Anton Donkor
  1. Antonio Nusa (ID 1121923, similarity 64%)
  2. Anton Kade (ID 1129365, similarity 60%)
  3. Patson Daka (ID 865057, similarity 57%)
  4. Dominik Kohr (ID 152206, similarity 55%)
  5. Afonso Moreira (ID 1215906, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jason Ceka (elversberg)
  1. Francis Onyeka (ID 36948, similarity 64%)
  2. Jan Gyamerah (ID 5825, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jason Ceka
  1. Francis Onyeka (ID 1414916, similarity 64%)
  2. Patson Daka (ID 865057, similarity 63%)
  3. Anton Kade (ID 1129365, similarity 56%)
  4. Jae-sung Lee (ID 537552, similarity 53%)
  5. Anthony Caci (ID 846471, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Chema Andrés (stuttgart)
  1. Hendriks (displayed name, similarity 63%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Christoph Baumgartner
  1. Christopher Trimmel (ID 48557, similarity 63%)
  2. Christian Günter (ID 142231, similarity 63%)
  3. Christian Kofane (ID 2029648, similarity 57%)
  4. Tristan Spranger (ID 1974432, similarity 51%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Felix Agu
  1. Felix Nmecha (ID 907463, similarity 63%)
  2. Elias Baum (ID 1403018, similarity 59%)
  3. Felix Keidel (ID 1215028, similarity 53%)
  4. Felipe Chávez (ID 1482457, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Keke Topp
  1. Keisuke Goto (ID 1391315, similarity 63%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Kim Minjae (bayern)
  1. Kimmich (displayed name, similarity 62%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Sima Suso (augsburg)
  1. MASSENGO (displayed name, similarity 62%)
  2. MATSIMA (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Sima Suso (augsburg)
  1. Massengo (displayed name, similarity 62%)
  2. Matsima (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Marcel Hoffmeier
  1. Marcel Sabitzer (ID 133908, similarity 62%)
  2. Marco Friedl (ID 825771, similarity 62%)
  3. Manuel Neuer (ID 8959, similarity 54%)
  4. Roméo Ritter (ID 2266855, similarity 54%)
  5. András Schäfer (ID 877302, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Ramon Hendriks
  1. Benjamin Henrichs (ID 319857, similarity 62%)
  2. Rani Khedira (ID 149479, similarity 58%)
  3. Raphael Onyedika (ID 1129862, similarity 57%)
  4. Kevin Diks (ID 583806, similarity 55%)
  5. Chema Andrés (ID 1464641, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Emre Can (dortmund)
  1. NMECHA (displayed name, similarity 62%)
  2. VEERMAN (displayed name, similarity 57%)
  3. Mane (displayed name, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tom Zimmerschied
  1. Joel Schmied (ID 965950, similarity 62%)
  2. Tom Bischof (ID 1129935, similarity 56%)
  3. Koki Machida (ID 790977, similarity 54%)
  4. Tim Lemperle (ID 1014290, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sebastian Sebulonsen
  1. Sebastiaan Bornauw (ID 826167, similarity 61%)
  2. Bastian Assomo (ID 2361805, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Finn Porath
  1. Franck Honorat (ID 280453, similarity 61%)
  2. Finn Dahmen (ID 822564, similarity 60%)
  3. Finn Jeltsch (ID 1418649, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Noël Aséko
  1. Nicolas Kristof (ID 1131080, similarity 61%)
  2. Lukas Petkov (ID 960017, similarity 60%)
  3. Nikolas Nartey (ID 861981, similarity 55%)
  4. Nicholas Mickelson (ID 900264, similarity 54%)
  5. Daniel Svensson (ID 1021272, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sven Ulreich
  1. Laurin Ulrich (ID 1152486, similarity 61%)
  2. Lukas Ullrich (ID 1083382, similarity 61%)
  3. Chris Führich (ID 891510, similarity 52%)
  4. Sani Suleiman (ID 1894870, similarity 52%)
  5. Samuele Inacio (ID 1861666, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tim Kleindienst
  1. Kevin Diks (ID 583806, similarity 61%)
  2. Tim Binder (ID 1925507, similarity 61%)
  3. Tom Alexander Rothe (ID 1210666, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tim Oermann
  1. Oliver Baumann (ID 40244, similarity 61%)
  2. Timo Becker (ID 814735, similarity 60%)
  3. Joey Veerman (ID 850816, similarity 57%)
  4. Justin Lerma (ID 1836843, similarity 57%)
  5. Jan Uwe Thielmann (ID 1010726, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Daniel Elfadli (hamburg)
  1. Daniel Heuer Fernandes (ID 6379, similarity 61%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Daniel Elfadli (hamburg)
  1. Daniel Heuer Fernandes (ID 21877, similarity 61%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Michael Zetterer
  1. Michael Gregoritsch (ID 111483, similarity 61%)
  2. Michael Olise (ID 978838, similarity 59%)
  3. Manuel Neuer (ID 8959, similarity 54%)
  4. Michel Aebischer (ID 850891, similarity 53%)
  5. Miguel Gutiérrez (ID 908716, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Andreas Hanche-Olsen
  1. Mattes Hansen (ID 1083387, similarity 60%)
  2. András Schäfer (ID 877302, similarity 58%)
  3. Ragnar Ache (ID 877544, similarity 50%)
  4. Tjark Lasse Scheller (ID 1137717, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Calvin Brackelmann
  1. Janik Bachmann (ID 579254, similarity 60%)
  2. Malik Tillman (ID 975798, similarity 55%)
  3. Olivier Deman (ID 960114, similarity 55%)
  4. Vincent Manuba (ID 1195752, similarity 53%)
  5. Jan Uwe Thielmann (ID 1010726, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Eric Martel
  1. Eric Ebimbe (ID 904994, similarity 60%)
  2. Cédric Itten (ID 352290, similarity 57%)
  3. Grischa Prömel (ID 253993, similarity 52%)
  4. Martin Adeline (ID 1158529, similarity 52%)
  5. Enzo Duarte (ID 1957706, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Felix Götze
  1. Mario Götze (ID 66518, similarity 60%)
  2. Felix Keidel (ID 1215028, similarity 57%)
  3. Felix Nmecha (ID 907463, similarity 57%)
  4. Marcel Sabitzer (ID 133908, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Hugo Larsson
  1. Hugo Bolin (ID 1142210, similarity 60%)
  2. Julian Ryerson (ID 800951, similarity 58%)
  3. Nicholas Mickelson (ID 900264, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jens Castrop
  1. Jens Stage (ID 830142, similarity 60%)
  2. Alessio Castro-Montes (ID 839898, similarity 53%)
  3. Bernardo (ID 828571, similarity 53%)
  4. Jonah Sticker (ID 1517850, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Leo Sauer
  1. Alex Honajzer (ID 1479460, similarity 60%)
  2. Loris Karius (ID 174135, similarity 53%)
  3. Manuel Neuer (ID 8959, similarity 53%)
  4. Leopold Querfeld (ID 1086547, similarity 52%)
  5. Lasse Günther (ID 997175, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Luka Duric (paderborn)
  1. Laurin Curda (ID 36261, similarity 60%)
  2. Laurin Ulrich (ID 27568, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Luka Duric (paderborn)
  1. Laurin Curda (ID 48704, similarity 60%)
  2. Laurin Ulrich (ID 37153, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Max Grüger
  1. Fabio Gruber (ID 1130119, similarity 60%)
  2. Marius Bülter (ID 378340, similarity 57%)
  3. Max Finkgräfe (ID 1146250, similarity 57%)
  4. Marco Grüll (ID 815612, similarity 53%)
  5. Markus Schubert (ID 795006, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Paul Nebel
  1. Manuel Neuer (ID 8959, similarity 60%)
  2. Paul Erevbenagie (ID 2160258, similarity 58%)
  3. Jae-sung Lee (ID 537552, similarity 53%)
  4. Arne Wessels (ID 1649300, similarity 50%)
  5. Jeanuël Belocian (ID 1173172, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Christoph Baumgartner (leipzig)
  1. Christopher Nkunku (ID 12446, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Andrej Ilic
  1. Andrija Maksimović (ID 1406171, similarity 59%)
  2. Dženan Pejčinović (ID 1127790, similarity 54%)
  3. Adil Aouchiche (ID 962877, similarity 52%)
  4. Janis Blaswich (ID 96832, similarity 52%)
  5. Martin Adeline (ID 1158529, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Florian Neuhaus
  1. Florian Müller (ID 842858, similarity 59%)
  2. Felix Nmecha (ID 907463, similarity 56%)
  3. Loris Karius (ID 174135, similarity 56%)
  4. Florian Yves Le Joncour (ID 787816, similarity 53%)
  5. Francis Onyeka (ID 1414916, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jan Olschowsky (gladbach)
  1. Jan Leszczynski (ID 38925, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jan Olschowsky
  1. Jan Leszczyński (ID 1823942, similarity 59%)
  2. Jano Ter-Horst (ID 1152342, similarity 56%)
  3. Janis Blaswich (ID 96832, similarity 54%)
  4. Joel Schmied (ID 965950, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kennet Eichhorn
  1. Hennes Behrens (ID 1864760, similarity 59%)
  2. Senne Lynen (ID 826171, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Markus Schubert (paderborn)
  1. Tjark Scheller (ID 36890, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Markus Schubert (paderborn)
  1. Tjark Scheller (ID 48700, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nediljko Labrović
  1. Nikola Katić (ID 831488, similarity 59%)
  2. Andrija Maksimović (ID 1406171, similarity 55%)
  3. Noah Darvich (ID 1469995, similarity 52%)
  4. Ermedin Demirović (ID 878081, similarity 50%)
  5. William Bøving (ID 1021075, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Ansgar Knauff (frankfurt)
  1. Knaff (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Isac Lidberg (gladbach)
  1. SANDER (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Isac Lidberg (gladbach)
  1. Sander (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Tim Lemperle (hoffenheim)
  1. WIMMER (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Tim Lemperle (hoffenheim)
  1. Wimmer (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Tim Oermann (leverkusen)
  1. MOREIRA (displayed name, similarity 59%)
  2. TILLMAN (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Tim Oermann (leverkusen)
  1. Moreira (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tom Baack
  1. Robin Hack (ID 876858, similarity 59%)
  2. Timo Becker (ID 814735, similarity 56%)
  3. Tom Bischof (ID 1129935, similarity 56%)
  4. Linton Maina (ID 921033, similarity 53%)
  5. Mio Backhaus (ID 1083390, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Dennis Seimen
  1. Deniz Zeitler (ID 1604187, similarity 58%)
  2. Sani Suleiman (ID 1894870, similarity 58%)
  3. Hennes Behrens (ID 1864760, similarity 56%)
  4. Eric Ebimbe (ID 904994, similarity 55%)
  5. Senne Lynen (ID 826171, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Fabio Chiarodia
  1. Fábio Silva (ID 954076, similarity 58%)
  2. Albian Hajdari (ID 1000269, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Jannik Huth (freiburg)
  1. Jan-Niklas Beste (ID 26591, similarity 58%)
  2. Yannik Engelhardt (ID 36578, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jannik Huth
  1. Jan-Niklas Beste (ID 836711, similarity 58%)
  2. Yannik Keitel (ID 877842, similarity 55%)
  3. Janik Bachmann (ID 579254, similarity 52%)
  4. Yannick Engelhardt (ID 990209, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kenan Karaman
  1. Kénan Doganay (ID 2302524, similarity 58%)
  2. Janik Bachmann (ID 579254, similarity 56%)
  3. Natnael Abraha (ID 1861981, similarity 56%)
  4. Konstantinos Karetsas (ID 1468744, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Luca Waldschmidt
  1. Luca Sirch (ID 964603, similarity 58%)
  2. Joel Schmied (ID 965950, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Robert Andrich
  1. Robin Hranáč (ID 957615, similarity 58%)
  2. Benjamin Henrichs (ID 319857, similarity 55%)
  3. Robin Koch (ID 581302, similarity 55%)
  4. Raphael Obermair (ID 820465, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Stefan Posch
  1. Stefano Marino (ID 1167764, similarity 58%)
  2. Zeno Van Den Bosch (ID 1103765, similarity 54%)
  3. Josip Stanišić (ID 927407, similarity 50%)
  4. Steffen Tigges (ID 826884, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Timothy Chandler
  1. Tim Binder (ID 1925507, similarity 58%)
  2. Timo Becker (ID 814735, similarity 56%)
  3. Mathis Albert (ID 1937835, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lazar Jovanovic
  1. Arijon Ibrahimović (ID 1142248, similarity 58%)
  2. Josip Juranović (ID 791642, similarity 57%)
  3. Aleksandar Pavlović (ID 1142251, similarity 56%)
  4. Igor Matanović (ID 1019321, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Abdoul Koné
  1. Samba Konaté (ID 2269705, similarity 57%)
  2. Louis Lemke (ID 1995000, similarity 50%)
  3. Rômulo (ID 1133743, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Eliesse Ben Seghir
  1. Ellyes Skhiri (ID 591706, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Emre Can (dortmund)
  1. F. Nmecha (displayed name, similarity 57%)
  2. J. Veerman (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Eren Sami Dinkçi
  1. Ramy Bensebaini (ID 577726, similarity 57%)
  2. Samuele Inacio (ID 1861666, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jamie Leweling
  1. Jeanuël Belocian (ID 1173172, similarity 57%)
  2. Samuele Inacio (ID 1861666, similarity 54%)
  3. Thijs Dallinga (ID 905381, similarity 54%)
  4. Jae-sung Lee (ID 537552, similarity 52%)
  5. Jobe Bellingham (ID 1134083, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jeremy Arévalo
  1. Jeremiaha Maluze (ID 1886360, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Livan Burcu (union)
  1. BUCU (displayed name, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Luca Pfeiffer
  1. Luca Sirch (ID 964603, similarity 57%)
  2. Lucas Höler (ID 280009, similarity 55%)
  3. Luca Philipp (ID 943550, similarity 52%)
  4. Luca Reggiani (ID 1937833, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Malik Pimpong (frankfurt)
  1. Amaimouni (displayed name, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Maurice Krattenmacher
  1. Michel Aebischer (ID 850891, similarity 57%)
  2. Emmanuel Latte Lath (ID 848074, similarity 54%)
  3. Marcel Sabitzer (ID 133908, similarity 53%)
  4. Patrick Osterhage (ID 914755, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nahuel Noll
  1. Nathan Tella (ID 920379, similarity 57%)
  2. Angelo Stiller (ID 901882, similarity 52%)
  3. Samuele Inacio (ID 1861666, similarity 52%)
  4. Finn Dahmen (ID 822564, similarity 50%)
  5. Kaishu Sano (ID 1028307, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Oliver Burke (union)
  1. Livan Burcu (ID 36114, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Oliver Burke (union)
  1. Livan Burcu (ID 43803, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Rav van den Berg
  1. Ron Schallenberg (ID 872358, similarity 57%)
  2. Alexander Meyer (ID 138491, similarity 52%)
  3. Isac Lidberg (ID 798175, similarity 50%)
  4. Manuel Neuer (ID 8959, similarity 50%)
  5. Raphael Obermair (ID 820465, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Stefan Bell (mainz)
  1. Stefan Posch (ID 12798, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Stefan Bell
  1. Nathan Tella (ID 920379, similarity 57%)
  2. Cole Campbell (ID 1134578, similarity 55%)
  3. Fabian Bredlow (ID 152463, similarity 52%)
  4. Stefano Marino (ID 1167764, similarity 52%)
  5. Steffen Tigges (ID 826884, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Derrick Köhn
  1. Derry Scherhant (ID 1131002, similarity 56%)
  2. Dominik Kohr (ID 152206, similarity 55%)
  3. Robin Koch (ID 581302, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Janik Bachmann (schalke)
  1. Kenan Karaman (ID 2676, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Janik Bachmann (schalke)
  1. Kenan Karaman (ID 20178, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Julián Malatini
  1. Linton Maina (ID 921033, similarity 56%)
  2. Albian Hajdari (ID 1000269, similarity 52%)
  3. Ismael Saibari (ID 1063767, similarity 52%)
  4. Julian Ryerson (ID 800951, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Lukas Emanuel Petkov (elversberg)
  1. L. Petkov (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nnamdi Collins
  1. Michael Olise (ID 978838, similarity 56%)
  2. Nicolas Kristof (ID 1131080, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Alexis Claude-Maurice
  1. Alexander Schlager (ID 282073, similarity 56%)
  2. Alexander Meyer (ID 138491, similarity 55%)
  3. Adil Aouchiche (ID 962877, similarity 50%)
  4. Albian Hajdari (ID 1000269, similarity 50%)
  5. Tom Alexander Rothe (ID 1210666, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Emre Can (dortmund)
  1. Felix Nmecha (ID 25090, similarity 56%)
  2. Waldemar Anton (ID 5837, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Emre Can (dortmund)
  1. Felix Nmecha (ID 27147, similarity 56%)
  2. Waldemar Anton (ID 20160, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Emre Can
  1. Felix Nmecha (ID 907463, similarity 56%)
  2. Mertcan Ayhan (ID 1195798, similarity 53%)
  3. Waldemar Anton (ID 799046, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jens Grahl
  1. Jens Stage (ID 830142, similarity 56%)
  2. Jarell Quansah (ID 1003339, similarity 55%)
  3. Jae-sung Lee (ID 537552, similarity 53%)
  4. Brajan Gruda (ID 1198075, similarity 50%)
  5. Jan Gyamerah (ID 254411, similarity 50%)

No exact match for kicker lineup for Marco Grüll (bremen)
  1. Mbangula (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Mert Can Ayhan (schalke)
  1. Tanaka (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Nick Bätzner (paderborn)
  1. STICKER (displayed name, similarity 56%)
  2. CASTAÑEDA (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Sima Suso (augsburg)
  1. Marius Wolf (ID 5670, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Sima Suso (augsburg)
  1. Marius Wolf (ID 21031, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sima Suso
  1. Marius Wolf (ID 254119, similarity 56%)
  2. Salim Musah (ID 1864786, similarity 56%)
  3. Mats Rots (ID 1387012, similarity 50%)
  4. Tom Faust (ID 2266851, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Sven Michel (paderborn)
  1. SCHELLER (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Sven Michel (paderborn)
  1. Scheller (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Tim Binder (bayern)
  1. Kim Min-Jae (ID 34953, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tim Boss
  1. Tidiam Gomis (ID 1426577, similarity 56%)
  2. Tim Binder (ID 1925507, similarity 50%)
  3. Tom Krauß (ID 930272, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Christian Günter (freiburg)
  1. Matthias Ginter (ID 17592, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Daniel Elfadli
  1. Soufiane El-Faouzi (ID 1083338, similarity 55%)
  2. Daniel Svensson (ID 1021272, similarity 52%)
  3. David Herold (ID 997178, similarity 50%)
  4. Jeanuël Belocian (ID 1173172, similarity 50%)
  5. Nathan Tella (ID 920379, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Paul Okon-Engstler
  1. Angelo Stiller (ID 901882, similarity 55%)
  2. Manuel Neuer (ID 8959, similarity 52%)
  3. Paul Erevbenagie (ID 2160258, similarity 52%)
  4. Patrick Osterhage (ID 914755, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Salim Amani Musah (bremen)
  1. Samuel Mbangula (ID 38382, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Alexander Røssing-Lelesiit
  1. Tom Alexander Rothe (ID 1210666, similarity 55%)
  2. Alexander Meyer (ID 138491, similarity 54%)
  3. Alexander Schlager (ID 282073, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for András Schäfer (union)
  1. Aebischer (displayed name, similarity 55%)
  2. van den Bosch (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Carl Klaus
  1. Jarell Quansah (ID 1003339, similarity 55%)
  2. Mio Backhaus (ID 1083390, similarity 50%)
  3. Oscar Højlund (ID 1149113, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Faik Sakar
  1. Daiki Hashioka (ID 897334, similarity 55%)
  2. Francis Onyeka (ID 1414916, similarity 55%)
  3. Fábio Silva (ID 954076, similarity 53%)
  4. Patson Daka (ID 865057, similarity 53%)
  5. Loris Karius (ID 174135, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Julian Pauli
  1. Junior Adamu (ID 902381, similarity 55%)
  2. João Palhinha (ID 364612, similarity 52%)
  3. Soufiane El-Faouzi (ID 1083338, similarity 52%)
  4. Albian Hajdari (ID 1000269, similarity 50%)
  5. Elias Baum (ID 1403018, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Kenny Quetant (bremen)
  1. Senne Lynen (ID 35359, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Kenny Quetant (bremen)
  1. Senne Lynen (ID 37714, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kenny Quetant
  1. Senne Lynen (ID 826171, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lennard Maloney
  1. Bernardo (ID 828571, similarity 55%)
  2. Olivier Deman (ID 960114, similarity 54%)
  3. Waldemar Anton (ID 799046, similarity 52%)
  4. Adam Hložek (ID 963801, similarity 50%)
  5. Aleksandar Pavlović (ID 1142251, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Luca Sirch (elversberg)
  1. Lukas Pinckert (ID 38539, similarity 55%)
  2. Luca Schnellbacher (ID 6495, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Luca Sirch (elversberg)
  1. Lukas Pinckert (ID 48715, similarity 55%)
  2. Luca Schnellbacher (ID 48728, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Martin Terrier (leverkusen)
  1. GUTIÉRREZ (displayed name, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Noah Atubolu
  1. Nathan Tella (ID 920379, similarity 55%)
  2. Noahkai Banks (ID 1597260, similarity 52%)
  3. Sacha Boey (ID 980418, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Oskar Wójcik
  1. Loris Karius (ID 174135, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sven Michel
  1. Michael Olise (ID 978838, similarity 55%)
  2. Senne Lynen (ID 826171, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Warmed Omari
  1. Nadiem Amiri (ID 327755, similarity 55%)
  2. Roméo Ritter (ID 2266855, similarity 55%)
  3. Ameen Al-Dakhil (ID 1979970, similarity 50%)
  4. Stefano Marino (ID 1167764, similarity 50%)
  5. Wael Mohya (ID 1995809, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Örjan Nyland
  1. Oscar Højlund (ID 1149113, similarity 55%)
  2. Jan-Luca Riedl (ID 1937830, similarity 52%)
  3. Mertcan Ayhan (ID 1195798, similarity 52%)
  4. Anton Kade (ID 1129365, similarity 50%)
  5. Francis Onyeka (ID 1414916, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Ermedin Demirović (stuttgart)
  1. PEJCINOVIC (displayed name, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Ermedin Demirović (stuttgart)
  1. Pejcinovic (displayed name, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Facundo Medina (leverkusen)
  1. Afonso Moreira (ID 40418, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Frederik Schmahl
  1. Farès Chaïbi (ID 1192318, similarity 54%)
  2. Alexander Schlager (ID 282073, similarity 50%)
  3. Grischa Prömel (ID 253993, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jannik Huth (freiburg)
  1. Yannik Engelhardt (ID 20278, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Ron-Robert Zieler
  1. Gregor Kobel (ID 556866, similarity 54%)
  2. Martin Terrier (ID 846445, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Benedict Hollerbach
  1. Deniz Zeitler (ID 1604187, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Luka Duric (paderborn)
  1. ULRICH (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Luka Duric (paderborn)
  1. Ulrich (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Lukeba Castello Jr. (leipzig)
  1. Castello Lukeba (ID 34680, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Mert Kömür
  1. Rômulo (ID 1133743, similarity 53%)
  2. Keita Kosugi (ID 1501641, similarity 50%)
  3. Roméo Ritter (ID 2266855, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Montrell Culbreath
  1. Natnael Abraha (ID 1861981, similarity 53%)
  2. Emmanuel Latte Lath (ID 848074, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Silas
  1. Eljif Elmas (ID 838232, similarity 53%)
  2. Fábio Silva (ID 954076, similarity 53%)
  3. Ilyas Ansah (ID 1462742, similarity 53%)
  4. Said El Mala (ID 1800475, similarity 53%)
  5. Justin Lerma (ID 1836843, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Tim Binder (bayern)
  1. LAIMER (displayed name, similarity 53%)
  2. Minjae (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Tim Binder (bayern)
  1. Laimer (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Albert Grønbæk (hamburg)
  1. Grönbaek (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Bambasé Conté (hoffenheim)
  1. Baumann (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Justin Lerma (dortmund)
  1. J. Veerman (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Karl Hein
  1. Mark Flekken (ID 171919, similarity 53%)
  2. João Palhinha (ID 364612, similarity 50%)
  3. Luca Reggiani (ID 1937833, similarity 50%)
  4. Sani Suleiman (ID 1894870, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kofi Amoako
  1. Ko Itakura (ID 790989, similarity 53%)
  2. Takato Yamamoto (ID 2076134, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nick Bätzner
  1. Loïc Badé (ID 1006489, similarity 53%)
  2. Jonah Sticker (ID 1517850, similarity 52%)
  3. Janik Bachmann (ID 579254, similarity 50%)
  4. Natnael Abraha (ID 1861981, similarity 50%)
  5. Nikolas Nartey (ID 861981, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Paul Nebel (mainz)
  1. Jaesung Lee (ID 21202, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Raif Adam
  1. Brajan Gruda (ID 1198075, similarity 53%)
  2. Ibrahim Maza (ID 1407524, similarity 53%)
  3. Junior Adamu (ID 902381, similarity 53%)
  4. Shafiq Nandja (ID 2204961, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Robert Skov
  1. Robin Koch (ID 581302, similarity 53%)
  2. Albert Sambi Lokonga (ID 901892, similarity 50%)
  3. Rodrigo Ribeiro (ID 1215904, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Ruben Müller (paderborn)
  1. SCHELLER (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Ruben Müller (paderborn)
  1. Scheller (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Sander Tangvik (hamburg)
  1. Stange (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Serge Gnabry
  1. Bernardo (ID 828571, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tim Skarke
  1. Timo Becker (ID 814735, similarity 53%)
  2. Loris Karius (ID 174135, similarity 50%)
  3. Mark Flekken (ID 171919, similarity 50%)
  4. Tim Lemperle (ID 1014290, similarity 50%)
  5. Tristan Spranger (ID 1974432, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Amara Condé (elversberg)
  1. Francis Onyeka (ID 36948, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Daniel Batz
  1. Natnael Abraha (ID 1861981, similarity 52%)
  2. Yannick Engelhardt (ID 990209, similarity 52%)
  3. Daniel Svensson (ID 1021272, similarity 50%)
  4. Marcel Sabitzer (ID 133908, similarity 50%)
  5. Nathaniel Brown (ID 1159759, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Janik Haberer (union)
  1. Rani Khedira (ID 2122, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Janik Haberer (union)
  1. Rani Khedira (ID 21666, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Nick Bätzner (paderborn)
  1. Jonah Sticker (ID 38855, similarity 52%)
  2. Santiago Castaneda (ID 37450, similarity 50%)

No exact match for rotowire lineup for Nick Bätzner (paderborn)
  1. Jonah Sticker (ID 48705, similarity 52%)
  2. Santiago Castaneda (ID 48702, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Sebastian Klaas (paderborn)
  1. CASTAÑEDA (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Sebastian Klaas (paderborn)
  1. Castaneda (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Zento Uno
  1. Zeno Van Den Bosch (ID 1103765, similarity 52%)
  2. Robin Zentner (ID 174345, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Alexander Meyer (dortmund)
  1. Julian Ryerson (ID 18478, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Alexander Meyer (dortmund)
  1. Julian Ryerson (ID 28864, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Atakan Karazor
  1. Takato Yamamoto (ID 2076134, similarity 52%)
  2. Aleksandar Pavlović (ID 1142251, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Dariusz Stalmach
  1. Laurin Ulrich (ID 1152486, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jordan Torunarigha
  1. Jonas Urbig (ID 1130647, similarity 52%)
  2. Anthony Caci (ID 846471, similarity 50%)
  3. Jonathan Tah (ID 227672, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Samuele Inácio (dortmund)
  1. Ramy Bensebaini (ID 20296, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Adrian Gantenbein
  1. Christian Günter (ID 142231, similarity 52%)
  2. Maximilian Eggestein (ID 569784, similarity 51%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Abdoul Koné (leipzig)
  1. Rômulo (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Andrej Kramarić (hoffenheim)
  1. Adam Daghim (ID 37622, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Andrej Kramarić (hoffenheim)
  1. Adam Daghim (ID 44189, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Christian Günter (freiburg)
  1. Scherhant (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Cyriaque Irié (freiburg)
  1. Christian Guenter (ID 2153, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Darwin Soylu
  1. Marin Ljubičić (ID 1090010, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Ermedin Demirović (stuttgart)
  1. Dzenan Pejcinovic (ID 26158, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Ermedin Demirović (stuttgart)
  1. Dzenan Pejcinovic (ID 37405, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Fisnik Asllani
  1. Moussa Sylla (ID 861980, similarity 50%)
  2. Nikola Katić (ID 831488, similarity 50%)

No exact match for ligainsider lineup for Florian Pruhs (paderborn)
  1. Laurin Ulrich (ID 27568, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Florian Pruhs (paderborn)
  1. Laurin Ulrich (ID 37153, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Frank Lehmann (elversberg)
  1. Florian Le Joncour (ID 37052, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Isac Lidberg (gladbach)
  1. Philipp Sander (ID 18612, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Isac Lidberg (gladbach)
  1. Philipp Sander (ID 43368, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Jamal Musiala (bayern)
  1. Luis Diaz (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jamal Musiala (bayern)
  1. Luis Diaz (ID 22566, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Jamal Musiala (bayern)
  1. Luis Diaz (ID 28527, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Janik Bachmann (schalke)
  1. Karaman (displayed name, similarity 50%)

No exact match for kickbase lineup for Janis Blaswich (leverkusen)
  1. Quansah (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Janis Blaswich (leverkusen)
  1. Quansah (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Jason Ceka (elversberg)
  1. Jan Gyamerah (ID 48720, similarity 50%)

No exact match for SofaScore rating for Johannes Simon Siebeking
  1. Jahmai Simpson-Pusey (ID 1402924, similarity 50%)
  2. Jan Leszczyński (ID 1823942, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Justin Lerma (dortmund)
  1. Julian Ryerson (ID 18478, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Justin Lerma (dortmund)
  1. Julian Ryerson (ID 28864, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Lazar Jovanovic (stuttgart)
  1. PEJCINOVIC (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Lazar Jovanovic (stuttgart)
  1. Pejcinovic (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Leonidas Stergiou
  1. Alex Honajzer (ID 1479460, similarity 50%)
  2. Jonah Sticker (ID 1517850, similarity 50%)
  3. Lasse Günther (ID 997175, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Linus Güther (union)
  1. Aebischer (displayed name, similarity 50%)

No exact match for kicker lineup for Linus Güther (union)
  1. Aebischer (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lorenz Assignon
  1. Daniel Svensson (ID 1021272, similarity 50%)
  2. Jonas Urbig (ID 1130647, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Luca Sirch (elversberg)
  1. Darvich (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Marcel Hoffmeier (paderborn)
  1. Tjark Scheller (ID 48700, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Martin Terrier (leverkusen)
  1. Miguel Gutierrez (ID 24219, similarity 50%)

No exact match for rotowire lineup for Martin Terrier (leverkusen)
  1. Miguel Gutierrez (ID 32495, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Marvin Friedrich (union)
  1. Marin Ljubicic (ID 36465, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Marvin Friedrich (union)
  1. Marin Ljubicic (ID 40575, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Mert Can Ayhan (schalke)
  1. Kenan Karaman (ID 2676, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Mert Can Ayhan (schalke)
  1. Kenan Karaman (ID 20178, similarity 50%)

No exact match for SofaScore rating for Miro Muheim
  1. Rômulo (ID 1133743, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Mitchell Weiser (bremen)
  1. Mick Schmetgens (ID 37129, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Mitchell Weiser (bremen)
  1. Mick Schmetgens (ID 45910, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Montrell Culbreath (leverkusen)
  1. MOREIRA (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Montrell Culbreath (leverkusen)
  1. Moreira (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Nick Bätzner (paderborn)
  1. Castaneda (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Niklas Stark (bremen)
  1. Jens Stage (ID 22538, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Niklas Stark (bremen)
  1. Jens Stage (ID 30066, similarity 50%)

No exact match for SofaScore rating for Noel Futkeu
  1. Niclas Füllkrug (ID 132645, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Noël Aséko (frankfurt)
  1. LARSSON (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Noël Aséko (frankfurt)
  1. Hugo Larsson (ID 35384, similarity 50%)

No exact match for kickbase lineup for Paul Nebel (mainz)
  1. LEE (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Ruben Müller (paderborn)
  1. Tjark Scheller (ID 48700, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sota Kawasaki
  1. Noahkai Banks (ID 1597260, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Tim Lemperle (hoffenheim)
  1. Patrick Wimmer (ID 26236, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Tim Lemperle (hoffenheim)
  1. Patrick Wimmer (ID 35521, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Uchenna Ogundu
  1. Chema Andrés (ID 1464641, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Örjan Nyland (leipzig)
  1. ORBÁN (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Örjan Nyland (leipzig)
  1. Orban (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

Input summary
  Matchday: 1; ratings: team_player_average_ratings_2026-08-27_12-41-46_777583+0200.csv
  Ligainsider (weight 4): ligainsider_bundesliga_lineups_20260827_124626.json
  Kickbase (weight 3): kickbase_bundesliga_lineups_20260825_113858.json
  Kicker (weight 2): kicker_bundesliga_lineups_20260827_124652.json
  Rotowire (weight 1): rotowire_bundesliga_lineups_20260827_124203.json
  Alternative starting-chance decay: 0.45
  Questionable-injury starting-chance penalty: 0.15
  Output: C:\kickbase project\outputs\expected_points\expected_points_20260827_124042_+0200_sofascore_overall_rating_odds_lineup_20260827_124757_+0200.csv

Team odds and expected match points

,team,provider,win_probability,draw_probability,loss_probability,expected_match_points
0,augsburg,FotMob,0.440704,0.263198,0.296098,1.585310
1,bayern,FotMob,0.759036,0.135542,0.105422,2.412651
2,bremen,FotMob,0.256020,0.263131,0.480849,1.031190
3,dortmund,FotMob,0.728590,0.166170,0.105241,2.351939
4,elversberg,FotMob,0.178663,0.210425,0.610912,0.746414
5,frankfurt,FotMob,0.350701,0.270541,0.378758,1.322645
6,freiburg,FotMob,0.480849,0.263131,0.256020,1.705678
7,gladbach,FotMob,0.171996,0.205648,0.622356,0.721637
8,hamburg,FotMob,0.105241,0.166170,0.728590,0.481892
9,hoffenheim,FotMob,0.430888,0.263320,0.305792,1.555985
10,koeln,FotMob,0.305792,0.263320,0.430888,1.180695
11,leipzig,FotMob,0.622356,0.205648,0.171996,2.072715
12,leverkusen,FotMob,0.610912,0.210425,0.178663,2.043161
13,mainz,FotMob,0.574986,0.231397,0.193618,1.956354
14,paderborn,FotMob,0.193618,0.231397,0.574986,0.812250
15,schalke,FotMob,0.296098,0.263198,0.440704,1.151492
16,stuttgart,FotMob,0.105422,0.135542,0.759036,0.451807
17,union,FotMob,0.378758,0.270541,0.350701,1.406814

Player score review (non-positive or non-exact ratings)

,name,team,rating_status,lineup_status,rating,expected_match_points,ligainsider_starting_chance,kickbase_starting_chance,kicker_starting_chance,rotowire_starting_chance,questionable_injury_penalty,starting_chance,score
2,Sven Ulreich,bayern,missing_rating,not_evaluated_missing_rating,0.00,2.412651,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Serge Gnabry,bayern,missing_rating,not_evaluated_missing_rating,0.00,2.412651,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,Jamal Musiala,bayern,exact,ligainsider:missing; kickbase:missing; kicker:...,7.10,2.412651,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,Jonas Urbig,bayern,exact,ligainsider:missing; kickbase:missing; kicker:...,6.70,2.412651,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,Hiroki Ito,bayern,exact,ligainsider:missing; kickbase:missing; kicker:...,6.65,2.412651,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,Max Grüger,schalke,missing_rating,not_evaluated_missing_rating,0.00,1.151492,0.0,0.0,0.0,0.0,0.0,0.0,0.0
461,Mert Can Ayhan,schalke,exact,ligainsider:missing; kickbase:missing; kicker:...,6.05,1.151492,0.0,0.0,0.0,0.0,0.0,0.0,0.0
463,Christian Gomis,schalke,exact,ligainsider:missing; kickbase:missing; kicker:...,6.40,1.151492,0.0,0.0,0.0,0.0,0.0,0.0,0.0
464,Luca Vozar,schalke,exact,ligainsider:missing; kickbase:missing; kicker:...,6.70,1.151492,0.0,0.0,0.0,0.0,0.0,0.0,0.0
466,Johannes Simon Siebeking,schalke,missing_rating,not_evaluated_missing_rating,0.00,1.151492,0.0,0.0,0.0,0.0,0.0,0.0,0.0