# SofaScore overall rating × odds × lineup score

Creates optimizer-ready scores from overall average ratings, expected match points from odds, and configurable-weight LigaInsider, Kickbase, and RotoWire starting chances. LigaInsider and Kickbase alternatives use configurable geometric decay before slot normalization; Kicker remains reserved until its parser exists. The exported CSV includes the provider-specific chances, the injury penalty, and the final `score` column.

Confirmed SofaScore, LigaInsider, and RotoWire name matches are stored with Transfermarkt mappings in `data/reference/player_name_cross_references.csv`. Kickbase display names resolve to a unique same-team KBStats last name, then first name; only shared-name or no-match candidates at 50% similarity or higher are shown for notebook confirmation and stored separately in `data/reference/kickbase_player_name_cross_references.csv`. Lower-similarity cases record `kickbase:missing`.

Set the notebook's QUES penalty, alternative-decay, and source-weight variables to tune scoring. A provider-level QUES reduction is applied before LigaInsider or Kickbase formation-slot alternatives are normalized.

In [1]:

import sys
from pathlib import Path

# Absolute starting-chance reduction for a `QUES` injury flag from a lineup source.
QUESTIONABLE_INJURY_STARTING_CHANCE_PENALTY = 0.15
# Each rank is 45% of the preceding alternative before its slot is normalized.
ALTERNATIVE_STARTING_CHANCE_DECAY = 0.45
# Relative trust weights for active lineup sources; use 0 to disable one.
LINEUP_SOURCE_WEIGHTS = {'ligainsider': 4.0, 'kickbase': 3.0, 'rotowire': 1.0}

def locate_project_root() -> Path:
    starts = [Path.cwd().resolve()]
    notebook_path = globals().get('__vsc_ipynb_file__')
    if isinstance(notebook_path, str) and notebook_path.strip():
        starts.insert(0, Path(notebook_path).expanduser().resolve().parent)
    for start in starts:
        for candidate in (start, *start.parents):
            if (candidate / 'project_paths.py').is_file():
                return candidate
    raise FileNotFoundError('Could not locate project_paths.py.')

PROJECT_ROOT = locate_project_root()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from sofascore_rating_odds_lineup_score import run_score_creation
result = run_score_creation(
    'overall',
    questionable_injury_starting_chance_penalty=QUESTIONABLE_INJURY_STARTING_CHANCE_PENALTY,
    alternative_starting_chance_decay=ALTERNATIVE_STARTING_CHANCE_DECAY,
    lineup_source_weights=LINEUP_SOURCE_WEIGHTS,
)

Matchday for odds and lineups:  1

No exact match for ligainsider lineup for Niclas Füllkrug (bremen)
  1. Niclas Fuellkrug (ID 1867, similarity 97%)

Choose a candidate number, or press Enter to skip (score 0):  1

No exact match for SofaScore rating for Lukasz Poreba
  1. Łukasz Poręba (ID 942336, similarity 96%)
  2. Lukas Petkov (ID 960017, similarity 61%)
  3. Luca Reggiani (ID 1937833, similarity 50%)
  4. Lucas Vázquez (ID 255239, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):  1

No exact match for SofaScore rating for Florian Le Joncour
  1. Florian Yves Le Joncour (ID 787816, similarity 89%)

Choose a candidate number, or press Enter to skip (score 0):  1

No exact match for SofaScore rating for Luca Jaquez
  1. Lucas Vázquez (ID 255239, similarity 82%)
  2. Cajetan Lenz (ID 2077300, similarity 57%)
  3. Luca Vozar (ID 2255221, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nico Schlotterbeck
  1. Keven Schlotterbeck (ID 891651, similarity 80%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Robin Hack
  1. Robin Hranáč (ID 957615, similarity 80%)
  2. Robin Koch (ID 581302, similarity 67%)
  3. Robin Fellhauer (ID 860461, similarity 61%)
  4. Jobe Bellingham (ID 1134083, similarity 52%)
  5. Mio Backhaus (ID 1083390, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Mitchell Weiser
  1. Michael Olise (ID 978838, similarity 77%)
  2. Michael Gregoritsch (ID 111483, similarity 56%)
  3. Mathis Albert (ID 1937835, similarity 54%)
  4. Mick Schmetgens (ID 1568521, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Alexander Schwolow
  1. Alexander Schlager (ID 282073, similarity 76%)
  2. Alessandro Vogt (ID 1408406, similarity 58%)
  3. Alexander Meyer (ID 138491, similarity 58%)
  4. Aleksandar Pavlović (ID 1142251, similarity 51%)
  5. Aleix García (ID 796047, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lukas Emanuel Petkov
  1. Lukas Petkov (ID 960017, similarity 76%)
  2. Kauã Santos (ID 1134203, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Ayoube Amaimouni (frankfurt)
  1. Ayoube Amaimouni Echghouyab (ID 38710, similarity 75%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Christian Günter
  1. Christian Kofane (ID 2029648, similarity 73%)
  2. Christian Gomis (ID 1113440, similarity 69%)
  3. Tristan Spranger (ID 1974432, similarity 60%)
  4. Matthias Ginter (ID 142259, similarity 55%)
  5. Lasse Günther (ID 997175, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lúkas Petersson
  1. Lukas Petkov (ID 960017, similarity 72%)
  2. Lasse Günther (ID 997175, similarity 54%)
  3. Julian Ryerson (ID 800951, similarity 52%)
  4. Amos Pieper (ID 851254, similarity 50%)
  5. Daniel Svensson (ID 1021272, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Oliver Baumann
  1. Olivier Deman (ID 960114, similarity 72%)
  2. Joey Veerman (ID 850816, similarity 58%)
  3. Elias Baum (ID 1403018, similarity 55%)
  4. Janik Bachmann (ID 579254, similarity 54%)
  5. Willi Orbán (ID 136924, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Alexander Prass
  1. Alexander Meyer (ID 138491, similarity 71%)
  2. Alexander Schlager (ID 282073, similarity 65%)
  3. Aleksandar Pavlović (ID 1142251, similarity 56%)
  4. Aleix García (ID 796047, similarity 56%)
  5. Alessandro Vogt (ID 1408406, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nicolás Capaldo
  1. Nicolas Seiwald (ID 976575, similarity 71%)
  2. Nicholas Mickelson (ID 900264, similarity 65%)
  3. Nicolas Kristof (ID 1131080, similarity 57%)
  4. Cole Campbell (ID 1134578, similarity 54%)
  5. Nikolas Nartey (ID 861981, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Rihito Yamamoto
  1. Takato Yamamoto (ID 2076134, similarity 71%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Jae-Sung Lee (mainz)
  1. Lee Jae-Sung (ID 32009, similarity 70%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kaishu Sano
  1. Kauã Santos (ID 1134203, similarity 70%)
  2. Alessandro Vogt (ID 1408406, similarity 50%)
  3. Marius Wolf (ID 254119, similarity 50%)
  4. Salim Musah (ID 1864786, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Marius Funk
  1. Marius Wolf (ID 254119, similarity 70%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Timo Hübers
  1. Timo Becker (ID 814735, similarity 70%)
  2. Tim Binder (ID 1925507, similarity 63%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Vitalie Becker (schalke)
  1. T. BECKER (displayed name, similarity 70%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Florian Pruhs
  1. Loris Karius (ID 174135, similarity 70%)
  2. Florian Yves Le Joncour (ID 787816, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Laurin Ulrich (paderborn)
  1. Laurin Curda (ID 48704, similarity 70%)
  2. Luka Duric (ID 45012, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Linus Güther
  1. Lasse Günther (ID 997175, similarity 70%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Phillip Tietz
  1. Philipp Treu (ID 979820, similarity 70%)
  2. Luca Philipp (ID 943550, similarity 52%)
  3. Philipp Lienhart (ID 576266, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Janik Haberer
  1. Jan-Niklas Beste (ID 836711, similarity 69%)
  2. Janik Bachmann (ID 579254, similarity 56%)
  3. Jan Gyamerah (ID 254411, similarity 52%)
  4. Mathis Albert (ID 1937835, similarity 50%)
  5. Yannik Keitel (ID 877842, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Matthias Köbbing
  1. Matthias Ginter (ID 142259, similarity 69%)
  2. Malik Pimpong (ID 1957761, similarity 52%)
  3. Mathis Albert (ID 1937835, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for András Schäfer
  1. Alexander Schlager (ID 282073, similarity 67%)
  2. Conrad Harder (ID 1494826, similarity 56%)
  3. Derry Scherhant (ID 1131002, similarity 52%)
  4. Farès Chaïbi (ID 1192318, similarity 50%)
  5. Ron Schallenberg (ID 872358, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Arthur
  1. Arthur Chaves (ID 1122806, similarity 67%)
  2. Arthur Vermeeren (ID 1149127, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Arthur Theate
  1. Arthur Chaves (ID 1122806, similarity 67%)
  2. Arthur Vermeeren (ID 1149127, similarity 59%)
  3. Nathan De Cat (ID 1637689, similarity 52%)
  4. Nathan Tella (ID 920379, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Dan-Axel Zagadou
  1. Joane Gadou (ID 1471049, similarity 67%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Jason Ceka (elversberg)
  1. ONYEKA (displayed name, similarity 67%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Josip Juranović
  1. Josip Stanišić (ID 927407, similarity 67%)
  2. Igor Matanović (ID 1019321, similarity 59%)
  3. Arijon Ibrahimović (ID 1142248, similarity 58%)
  4. Filip Pavić (ID 2518029, similarity 50%)
  5. Jonas Urbig (ID 1130647, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Justin Diehl
  1. Justin Njinmah (ID 1005343, similarity 67%)
  2. Tim Binder (ID 1925507, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Justin Lerma
  1. Justin Njinmah (ID 1005343, similarity 67%)
  2. Jamal Musiala (ID 1010231, similarity 52%)
  3. Angelo Stiller (ID 901882, similarity 50%)
  4. Julian Ryerson (ID 800951, similarity 50%)
  5. Tim Binder (ID 1925507, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lucas Höler
  1. Luca Schnellbacher (ID 254133, similarity 67%)
  2. Luca Sirch (ID 964603, similarity 63%)
  3. Luca Vozar (ID 2255221, similarity 63%)
  4. Luca Philipp (ID 943550, similarity 57%)
  5. Lasse Günther (ID 997175, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lukas Ullrich
  1. Luca Sirch (ID 964603, similarity 67%)
  2. Luca Schnellbacher (ID 254133, similarity 55%)
  3. Niclas Füllkrug (ID 132645, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Marco Grüll (bremen)
  1. Marco Friedl (ID 23443, similarity 67%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Markus Kolke
  1. Marius Wolf (ID 254119, similarity 67%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Maxime Estève
  1. Max Moerstedt (ID 1418703, similarity 67%)
  2. Maximilian Eggestein (ID 569784, similarity 65%)
  3. Maximilian Beier (ID 980628, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Michel Aebischer
  1. Michael Gregoritsch (ID 111483, similarity 67%)
  2. Michael Olise (ID 978838, similarity 67%)
  3. Marcel Sabitzer (ID 133908, similarity 62%)
  4. Luca Schnellbacher (ID 254133, similarity 56%)
  5. Alexander Schlager (ID 282073, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Niklas Stark
  1. Nikolas Nartey (ID 861981, similarity 67%)
  2. Jan-Niklas Beste (ID 836711, similarity 64%)
  3. Nicolas Kristof (ID 1131080, similarity 56%)
  4. Nicolas Seiwald (ID 976575, similarity 56%)
  5. Nikola Katić (ID 831488, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Patrice Covic
  1. Patrik Schick (ID 280609, similarity 67%)
  2. Patrick Wimmer (ID 987504, similarity 56%)
  3. Ermedin Demirović (ID 878081, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Philipp Sander
  1. Filippo Mané (ID 1137131, similarity 67%)
  2. Philipp Treu (ID 979820, similarity 67%)
  3. Philipp Lienhart (ID 576266, similarity 64%)
  4. Luca Philipp (ID 943550, similarity 58%)
  5. Tim Binder (ID 1925507, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Raphael Obermair
  1. Raphael Onyedika (ID 1129862, similarity 67%)
  2. Mathis Albert (ID 1937835, similarity 52%)
  3. Natnael Abraha (ID 1861981, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Rayan Philippe
  1. Luca Philipp (ID 943550, similarity 67%)
  2. Philipp Treu (ID 979820, similarity 67%)
  3. Ayman Azhil (ID 990210, similarity 61%)
  4. Philipp Lienhart (ID 576266, similarity 57%)
  5. Filippo Mané (ID 1137131, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Said El Mala
  1. Samuel Mbangula (ID 1100836, similarity 67%)
  2. Waldemar Anton (ID 799046, similarity 52%)
  3. David Mokwa (ID 1432398, similarity 50%)
  4. Salim Musah (ID 1864786, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sebastian Klaas
  1. Bastian Assomo (ID 2361805, similarity 67%)
  2. Satoshi Tanaka (ID 981067, similarity 59%)
  3. Samuel Mbangula (ID 1100836, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Andrej Kramarić
  1. Andrija Maksimović (ID 1406171, similarity 65%)
  2. Adam Daghim (ID 1180758, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Nicholas Mickelson (elversberg)
  1. Nicolas Kristof (ID 26473, similarity 65%)

No exact match for rotowire lineup for Nicholas Mickelson (elversberg)
  1. Nicolas Kristof (ID 48713, similarity 65%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Assan Ouédraogo
  1. Alessandro Vogt (ID 1408406, similarity 64%)
  2. Hasan Kuruçay (ID 852096, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Frank Lehmann
  1. Janik Bachmann (ID 579254, similarity 64%)
  2. Bilal El Khannouss (ID 1126569, similarity 50%)
  3. Malik Tillman (ID 975798, similarity 50%)
  4. Mertcan Ayhan (ID 1195798, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jonas Hofmann
  1. Janik Bachmann (ID 579254, similarity 64%)
  2. Josha Vagnoman (ID 906278, similarity 64%)
  3. Jonathan Tah (ID 227672, similarity 61%)
  4. Jonathan Burkardt (ID 939830, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Amara Condé
  1. Bambasé Conté (ID 1185359, similarity 64%)
  2. Waldemar Anton (ID 799046, similarity 61%)
  3. Chema Andrés (ID 1464641, similarity 57%)
  4. Marco Friedl (ID 825771, similarity 57%)
  5. Bara Sapoko Ndiaye (ID 2427970, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Anton Donkor
  1. Antonio Nusa (ID 1121923, similarity 64%)
  2. Anton Kade (ID 1129365, similarity 60%)
  3. Afonso Moreira (ID 1215906, similarity 50%)
  4. Maycon Cardozo (ID 2236502, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jason Ceka (elversberg)
  1. Francis Onyeka (ID 36948, similarity 64%)
  2. Jan Gyamerah (ID 5825, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jason Ceka
  1. Francis Onyeka (ID 1414916, similarity 64%)
  2. Anton Kade (ID 1129365, similarity 56%)
  3. Jan Gyamerah (ID 254411, similarity 50%)
  4. Raphael Onyedika (ID 1129862, similarity 50%)
  5. Łukasz Poręba (ID 942336, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Joël Schmied (koeln)
  1. Waldschmidt (displayed name, similarity 64%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Marius Bülter
  1. Marius Wolf (ID 254119, similarity 64%)
  2. Mathis Albert (ID 1937835, similarity 58%)
  3. Mario Götze (ID 66518, similarity 55%)
  4. Marcel Sabitzer (ID 133908, similarity 54%)
  5. Matthias Ginter (ID 142259, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for William Bøving
  1. Willi Orbán (ID 136924, similarity 64%)
  2. Filip Pavić (ID 2518029, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Felix Agu
  1. Felix Nmecha (ID 907463, similarity 63%)
  2. Elias Baum (ID 1403018, similarity 59%)
  3. Felix Keidel (ID 1215028, similarity 53%)
  4. Felipe Chávez (ID 1482457, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Keke Topp
  1. Keisuke Goto (ID 1391315, similarity 63%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Patson Daka
  1. Anton Kade (ID 1129365, similarity 63%)
  2. Satoshi Tanaka (ID 981067, similarity 61%)
  3. Raphael Onyedika (ID 1129862, similarity 56%)
  4. Francis Onyeka (ID 1414916, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Kim Minjae (bayern)
  1. KIMMICH (displayed name, similarity 62%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Sima Suso (augsburg)
  1. MASSENGO (displayed name, similarity 62%)
  2. MATSIMA (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Marcel Hoffmeier
  1. Marcel Sabitzer (ID 133908, similarity 62%)
  2. Marco Friedl (ID 825771, similarity 62%)
  3. Manuel Neuer (ID 8959, similarity 54%)
  4. Roméo Ritter (ID 2266855, similarity 54%)
  5. Angelo Stiller (ID 901882, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Patrick Osterhage
  1. Patrick Wimmer (ID 987504, similarity 62%)
  2. Arthur Chaves (ID 1122806, similarity 50%)
  3. Patrik Schick (ID 280609, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Ramon Hendriks
  1. Benjamin Henrichs (ID 319857, similarity 62%)
  2. Raphael Onyedika (ID 1129862, similarity 57%)
  3. Chema Andrés (ID 1464641, similarity 50%)
  4. Ron Schallenberg (ID 872358, similarity 50%)

No exact match for kickbase lineup for Emre Can (dortmund)
  1. NMECHA (displayed name, similarity 62%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Franck Honorat
  1. Francis Onyeka (ID 1414916, similarity 62%)
  2. Antonio Nusa (ID 1121923, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Marvin Friedrich
  1. Marco Friedl (ID 825771, similarity 62%)
  2. Fabian Rieder (ID 929620, similarity 59%)
  3. Benjamin Henrichs (ID 319857, similarity 52%)

No exact match for SofaScore rating for Patrick Drewes
  1. Patrick Wimmer (ID 987504, similarity 62%)
  2. Patrik Schick (ID 280609, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Robin Zentner
  1. Robin Fellhauer (ID 860461, similarity 62%)
  2. Robin Hranáč (ID 957615, similarity 52%)
  3. Roméo Ritter (ID 2266855, similarity 52%)
  4. Ron Schallenberg (ID 872358, similarity 52%)
  5. Fabian Rieder (ID 929620, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Bilal Nadir
  1. Albian Hajdari (ID 1000269, similarity 61%)
  2. Fabian Rieder (ID 929620, similarity 55%)
  3. Tim Binder (ID 1925507, similarity 53%)
  4. Nikolas Nartey (ID 861981, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Fabio Gruber
  1. Fabian Rieder (ID 929620, similarity 61%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Isac Lidberg
  1. Mathis Albert (ID 1937835, similarity 61%)
  2. Ismael Saibari (ID 1063767, similarity 58%)
  3. Vitalie Becker (ID 1195734, similarity 58%)
  4. Ron Schallenberg (ID 872358, similarity 54%)
  5. Fabian Rieder (ID 929620, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Noël Aséko
  1. Nicolas Kristof (ID 1131080, similarity 61%)
  2. Lukas Petkov (ID 960017, similarity 60%)
  3. Nikolas Nartey (ID 861981, similarity 55%)
  4. Nicholas Mickelson (ID 900264, similarity 54%)
  5. Daniel Svensson (ID 1021272, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Oliver Burke
  1. Olivier Deman (ID 960114, similarity 61%)
  2. Wouter Burger (ID 916946, similarity 61%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tim Kleindienst
  1. Tim Binder (ID 1925507, similarity 61%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Alessio Castro-Montes
  1. Alessandro Vogt (ID 1408406, similarity 61%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Daniel Elfadli (hamburg)
  1. Daniel Heuer Fernandes (ID 6379, similarity 61%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Daniel Elfadli (hamburg)
  1. Daniel Heuer Fernandes (ID 21877, similarity 61%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Florian Müller
  1. Florian Yves Le Joncour (ID 787816, similarity 61%)
  2. Angelo Stiller (ID 901882, similarity 54%)
  3. Felix Nmecha (ID 907463, similarity 50%)
  4. Filippo Mané (ID 1137131, similarity 50%)
  5. Loris Karius (ID 174135, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Michael Zetterer
  1. Michael Gregoritsch (ID 111483, similarity 61%)
  2. Michael Olise (ID 978838, similarity 59%)
  3. Manuel Neuer (ID 8959, similarity 54%)
  4. Miguel Gutiérrez (ID 908716, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Anthony Caci
  1. Anton Kade (ID 1129365, similarity 60%)
  2. Antonio Nusa (ID 1121923, similarity 55%)
  3. Francis Onyeka (ID 1414916, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Calvin Brackelmann
  1. Janik Bachmann (ID 579254, similarity 60%)
  2. Malik Tillman (ID 975798, similarity 55%)
  3. Olivier Deman (ID 960114, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for David Herold
  1. David Raum (ID 856076, similarity 60%)
  2. David Mokwa (ID 1432398, similarity 57%)
  3. Edin Džeko (ID 14990, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Dominik Kohr
  1. Robin Koch (ID 581302, similarity 60%)
  2. Edin Džeko (ID 14990, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Felix Götze
  1. Mario Götze (ID 66518, similarity 60%)
  2. Felix Keidel (ID 1215028, similarity 57%)
  3. Felix Nmecha (ID 907463, similarity 57%)
  4. Marcel Sabitzer (ID 133908, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Finn Porath
  1. Finn Dahmen (ID 822564, similarity 60%)
  2. Finn Jeltsch (ID 1418649, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jens Castrop
  1. Jens Stage (ID 830142, similarity 60%)
  2. Bernardo (ID 828571, similarity 53%)

No exact match for SofaScore rating for Kevin Stöger
  1. Jens Stage (ID 830142, similarity 60%)
  2. Keven Schlotterbeck (ID 891651, similarity 55%)
  3. Keisuke Goto (ID 1391315, similarity 55%)
  4. Vincenzo Grifo (ID 171961, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Ko Itakura
  1. Keita Kosugi (ID 1501641, similarity 60%)
  2. Satoshi Tanaka (ID 981067, similarity 55%)
  3. Kauã Prates (ID 1887796, similarity 53%)
  4. Nikola Katić (ID 831488, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Mads Pedersen (augsburg)
  1. MASSENGO (displayed name, similarity 60%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Paul Nebel
  1. Manuel Neuer (ID 8959, similarity 60%)
  2. Paul Erevbenagie (ID 2160258, similarity 58%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Robin Gosens
  1. Robin Koch (ID 581302, similarity 60%)
  2. Robin Hranáč (ID 957615, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tim Oermann
  1. Timo Becker (ID 814735, similarity 60%)
  2. Joey Veerman (ID 850816, similarity 57%)
  3. Mertcan Ayhan (ID 1195798, similarity 55%)
  4. Olivier Deman (ID 960114, similarity 55%)
  5. Tim Binder (ID 1925507, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Andrej Ilic
  1. Andrija Maksimović (ID 1406171, similarity 59%)
  2. Dženan Pejčinović (ID 1127790, similarity 54%)
  3. Adil Aouchiche (ID 962877, similarity 52%)
  4. Janis Blaswich (ID 96832, similarity 52%)
  5. Aleksandar Pavlović (ID 1142251, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jan Olschowsky (gladbach)
  1. Jan Leszczynski (ID 38925, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kennet Eichhorn
  1. Hennes Behrens (ID 1864760, similarity 59%)
  2. Senne Lynen (ID 826171, similarity 50%)

No exact match for ligainsider lineup for Markus Schubert (paderborn)
  1. Tjark Scheller (ID 36890, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Markus Schubert (paderborn)
  1. Tjark Scheller (ID 48700, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Martin Terrier
  1. Matthias Ginter (ID 142259, similarity 59%)
  2. Maximilian Beier (ID 980628, similarity 57%)
  3. Fabian Rieder (ID 929620, similarity 56%)
  4. Arthur Vermeeren (ID 1149127, similarity 50%)
  5. Marco Friedl (ID 825771, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nediljko Labrović
  1. Nikola Katić (ID 831488, similarity 59%)
  2. Andrija Maksimović (ID 1406171, similarity 55%)
  3. Noah Darvich (ID 1469995, similarity 52%)
  4. Ermedin Demirović (ID 878081, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sheraldo Becker
  1. Vitalie Becker (ID 1195734, similarity 59%)
  2. Timo Becker (ID 814735, similarity 58%)
  3. Keven Schlotterbeck (ID 891651, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Isac Lidberg (gladbach)
  1. SANDER (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Tim Lemperle (hoffenheim)
  1. Wimmer (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Tim Oermann (leverkusen)
  1. MOREIRA (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Fabio Chiarodia
  1. Fábio Silva (ID 954076, similarity 58%)
  2. Albian Hajdari (ID 1000269, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Hugo Larsson
  1. Julian Ryerson (ID 800951, similarity 58%)
  2. Nicholas Mickelson (ID 900264, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Jannik Huth (freiburg)
  1. Jan-Niklas Beste (ID 26591, similarity 58%)
  2. Yannik Engelhardt (ID 36578, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jannik Huth
  1. Jan-Niklas Beste (ID 836711, similarity 58%)
  2. Yannik Keitel (ID 877842, similarity 55%)
  3. Janik Bachmann (ID 579254, similarity 52%)
  4. Yannick Engelhardt (ID 990209, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jean-Luc Dompé
  1. Jan-Luca Riedl (ID 1937830, similarity 58%)
  2. Cajetan Lenz (ID 2077300, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Laurin Ulrich
  1. Chris Führich (ID 891510, similarity 58%)
  2. Benjamin Henrichs (ID 319857, similarity 50%)
  3. Luca Reggiani (ID 1937833, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Luca Waldschmidt
  1. Luca Sirch (ID 964603, similarity 58%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lukas Pinckert
  1. Lukas Petkov (ID 960017, similarity 58%)
  2. Luca Sirch (ID 964603, similarity 55%)
  3. Luca Schnellbacher (ID 254133, similarity 53%)
  4. Amos Pieper (ID 851254, similarity 52%)
  5. Łukasz Poręba (ID 942336, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Martin Adeline
  1. Manuel Neuer (ID 8959, similarity 58%)
  2. Anton Kade (ID 1129365, similarity 55%)
  3. Marcel Sabitzer (ID 133908, similarity 52%)
  4. Maarten Vandevoordt (ID 934385, similarity 52%)
  5. Christian Kofane (ID 2029648, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Marvin Schwäbe
  1. Farès Chaïbi (ID 1192318, similarity 58%)
  2. Ron Schallenberg (ID 872358, similarity 57%)
  3. Mathis Albert (ID 1937835, similarity 56%)
  4. Sacha Boey (ID 980418, similarity 55%)
  5. Grischa Prömel (ID 253993, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Robert Andrich
  1. Robin Hranáč (ID 957615, similarity 58%)
  2. Benjamin Henrichs (ID 319857, similarity 55%)
  3. Robin Koch (ID 581302, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Timothy Chandler
  1. Tim Binder (ID 1925507, similarity 58%)
  2. Timo Becker (ID 814735, similarity 56%)
  3. Mathis Albert (ID 1937835, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lazar Jovanovic
  1. Arijon Ibrahimović (ID 1142248, similarity 58%)
  2. Aleksandar Pavlović (ID 1142251, similarity 56%)
  3. Igor Matanović (ID 1019321, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Christoph Baumgartner
  1. Christian Kofane (ID 2029648, similarity 57%)
  2. Tristan Spranger (ID 1974432, similarity 51%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Eren Sami Dinkçi
  1. Ramy Bensebaini (ID 577726, similarity 57%)
  2. Samuele Inacio (ID 1861666, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Eric Martel
  1. Cédric Itten (ID 352290, similarity 57%)
  2. Grischa Prömel (ID 253993, similarity 52%)
  3. Enzo Duarte (ID 1957706, similarity 50%)
  4. Mario Götze (ID 66518, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jeremy Arévalo
  1. Jeremiaha Maluze (ID 1886360, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Luca Pfeiffer
  1. Luca Sirch (ID 964603, similarity 57%)
  2. Luca Philipp (ID 943550, similarity 52%)
  3. Luca Reggiani (ID 1937833, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Max Grüger
  1. Max Finkgräfe (ID 1146250, similarity 57%)
  2. Marco Grüll (ID 815612, similarity 53%)
  3. Manuel Neuer (ID 8959, similarity 50%)
  4. Miguel Gutiérrez (ID 908716, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nahuel Noll
  1. Nathan Tella (ID 920379, similarity 57%)
  2. Angelo Stiller (ID 901882, similarity 52%)
  3. Samuele Inacio (ID 1861666, similarity 52%)
  4. Finn Dahmen (ID 822564, similarity 50%)
  5. Nathaniel Brown (ID 1159759, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Oliver Burke (union)
  1. Livan Burcu (ID 36114, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Oliver Burke (union)
  1. Livan Burcu (ID 43803, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Rav van den Berg
  1. Ron Schallenberg (ID 872358, similarity 57%)
  2. Alexander Meyer (ID 138491, similarity 52%)
  3. Manuel Neuer (ID 8959, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Stefan Bell (mainz)
  1. Stefan Posch (ID 12798, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Stefan Bell (mainz)
  1. Stefan Posch (ID 23594, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Stefan Bell
  1. Nathan Tella (ID 920379, similarity 57%)
  2. Cole Campbell (ID 1134578, similarity 55%)
  3. Fabian Bredlow (ID 152463, similarity 52%)
  4. Senne Lynen (ID 826171, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sebastian Sebulonsen
  1. Bastian Assomo (ID 2361805, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Daiki Hashioka
  1. Patrik Schick (ID 280609, similarity 56%)
  2. David Mokwa (ID 1432398, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Dennis Seimen
  1. Hennes Behrens (ID 1864760, similarity 56%)
  2. Senne Lynen (ID 826171, similarity 55%)
  3. Yannik Keitel (ID 877842, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Derrick Köhn
  1. Derry Scherhant (ID 1131002, similarity 56%)
  2. Robin Koch (ID 581302, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Florian Neuhaus
  1. Felix Nmecha (ID 907463, similarity 56%)
  2. Loris Karius (ID 174135, similarity 56%)
  3. Florian Yves Le Joncour (ID 787816, similarity 53%)
  4. Francis Onyeka (ID 1414916, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Janik Bachmann (schalke)
  1. Kenan Karaman (ID 2676, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Janik Bachmann (schalke)
  1. Kenan Karaman (ID 20178, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jonah Sticker
  1. Patrick Wimmer (ID 987504, similarity 56%)
  2. Jonas Urbig (ID 1130647, similarity 55%)
  3. Timo Becker (ID 814735, similarity 55%)
  4. Jonathan Tah (ID 227672, similarity 52%)
  5. Conrad Harder (ID 1494826, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kenan Karaman
  1. Janik Bachmann (ID 579254, similarity 56%)
  2. Natnael Abraha (ID 1861981, similarity 56%)
  3. Konstantinos Karetsas (ID 1468744, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nnamdi Collins
  1. Michael Olise (ID 978838, similarity 56%)
  2. Nicolas Kristof (ID 1131080, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Otto Stange
  1. Tristan Spranger (ID 1974432, similarity 56%)
  2. Jens Stage (ID 830142, similarity 53%)
  3. Satoshi Tanaka (ID 981067, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Ruben Müller
  1. Robin Fellhauer (ID 860461, similarity 56%)
  2. Manuel Neuer (ID 8959, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tom Zimmerschied
  1. Tom Bischof (ID 1129935, similarity 56%)
  2. Tim Lemperle (ID 1014290, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Alexis Claude-Maurice
  1. Alexander Schlager (ID 282073, similarity 56%)
  2. Alexander Meyer (ID 138491, similarity 55%)
  3. Adil Aouchiche (ID 962877, similarity 50%)
  4. Albian Hajdari (ID 1000269, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Emre Can (dortmund)
  1. Felix Nmecha (ID 25090, similarity 56%)
  2. Waldemar Anton (ID 5837, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Emre Can (dortmund)
  1. Felix Nmecha (ID 27147, similarity 56%)
  2. Waldemar Anton (ID 20160, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Emre Can
  1. Felix Nmecha (ID 907463, similarity 56%)
  2. Mertcan Ayhan (ID 1195798, similarity 53%)
  3. Waldemar Anton (ID 799046, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jens Grahl
  1. Jens Stage (ID 830142, similarity 56%)
  2. Jarell Quansah (ID 1003339, similarity 55%)
  3. Brajan Gruda (ID 1198075, similarity 50%)
  4. Jan Gyamerah (ID 254411, similarity 50%)
  5. Jeremiaha Maluze (ID 1886360, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kevin Diks
  1. Edin Džeko (ID 14990, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Luka Duric
  1. Luca Sirch (ID 964603, similarity 56%)
  2. Aleksandar Pavlović (ID 1142251, similarity 52%)
  3. Loris Karius (ID 174135, similarity 50%)
  4. Ludovit Reis (ID 893586, similarity 50%)
  5. Nikola Katić (ID 831488, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Nick Bätzner (paderborn)
  1. STICKER (displayed name, similarity 56%)
  2. CASTAÑEDA (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Sima Suso (augsburg)
  1. Marius Wolf (ID 5670, similarity 56%)

No exact match for rotowire lineup for Sima Suso (augsburg)
  1. Marius Wolf (ID 21031, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sima Suso
  1. Marius Wolf (ID 254119, similarity 56%)
  2. Salim Musah (ID 1864786, similarity 56%)
  3. Mats Rots (ID 1387012, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Sven Michel (paderborn)
  1. SCHELLER (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tim Boss
  1. Tidiam Gomis (ID 1426577, similarity 56%)
  2. Tim Binder (ID 1925507, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tom Baack
  1. Timo Becker (ID 814735, similarity 56%)
  2. Tom Bischof (ID 1129935, similarity 56%)
  3. Mio Backhaus (ID 1083390, similarity 53%)
  4. Robin Hranáč (ID 957615, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Christian Günter (freiburg)
  1. Matthias Ginter (ID 17592, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Daniel Elfadli
  1. Soufiane El-Faouzi (ID 1083338, similarity 55%)
  2. Daniel Svensson (ID 1021272, similarity 52%)
  3. Nathan Tella (ID 920379, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jean-Mattéo Bahoya
  1. Natnael Abraha (ID 1861981, similarity 55%)
  2. Jan Gyamerah (ID 254411, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nicolai Remberg
  1. Ron Schallenberg (ID 872358, similarity 55%)
  2. Cole Campbell (ID 1134578, similarity 54%)
  3. Konrad Laimer (ID 355492, similarity 54%)
  4. Nikolas Nartey (ID 861981, similarity 52%)
  5. Vitalie Becker (ID 1195734, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Paul Okon-Engstler
  1. Angelo Stiller (ID 901882, similarity 55%)
  2. Manuel Neuer (ID 8959, similarity 52%)
  3. Paul Erevbenagie (ID 2160258, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Salim Amani Musah (bremen)
  1. Samuel Mbangula (ID 38382, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Giannis Konstantelias (dortmund)
  1. Konstantinos Karetsas (ID 38406, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Giannis Konstantelias (dortmund)
  1. Konstantinos Karetsas (ID 47271, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Anthony Jung
  1. Antonio Nusa (ID 1121923, similarity 55%)
  2. Anton Kade (ID 1129365, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Carl Klaus
  1. Jarell Quansah (ID 1003339, similarity 55%)
  2. Mio Backhaus (ID 1083390, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Faik Sakar
  1. Francis Onyeka (ID 1414916, similarity 55%)
  2. Fábio Silva (ID 954076, similarity 53%)
  3. Loris Karius (ID 174135, similarity 50%)
  4. Nikola Katić (ID 831488, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Joël Schmied
  1. Finn Jeltsch (ID 1418649, similarity 55%)
  2. Jan-Luca Riedl (ID 1937830, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Julian Pauli
  1. Junior Adamu (ID 902381, similarity 55%)
  2. João Palhinha (ID 364612, similarity 52%)
  3. Soufiane El-Faouzi (ID 1083338, similarity 52%)
  4. Albian Hajdari (ID 1000269, similarity 50%)
  5. Elias Baum (ID 1403018, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Kenny Quetant (bremen)
  1. Senne Lynen (ID 35359, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Kenny Quetant (bremen)
  1. Senne Lynen (ID 37714, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kenny Quetant
  1. Senne Lynen (ID 826171, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lennard Maloney
  1. Bernardo (ID 828571, similarity 55%)
  2. Olivier Deman (ID 960114, similarity 54%)
  3. Waldemar Anton (ID 799046, similarity 52%)
  4. Adam Hložek (ID 963801, similarity 50%)
  5. Aleksandar Pavlović (ID 1142251, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Linton Maina
  1. Filippo Mané (ID 1137131, similarity 55%)
  2. Malik Tillman (ID 975798, similarity 52%)
  3. Chrislain Matsima (ID 963198, similarity 52%)
  4. Anton Kade (ID 1129365, similarity 50%)
  5. Facundo Medina (ID 860307, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Luca Sirch (elversberg)
  1. Lukas Pinckert (ID 38539, similarity 55%)
  2. Luca Schnellbacher (ID 6495, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Luca Sirch (elversberg)
  1. Lukas Pinckert (ID 48715, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lukas Kübler
  1. Lukas Petkov (ID 960017, similarity 55%)
  2. Lasse Günther (ID 997175, similarity 52%)
  3. Lucas Vázquez (ID 255239, similarity 52%)
  4. Luca Schnellbacher (ID 254133, similarity 50%)
  5. Luca Sirch (ID 964603, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Mads Pedersen
  1. Amos Pieper (ID 851254, similarity 55%)
  2. Mats Rots (ID 1387012, similarity 50%)
  3. Max Moerstedt (ID 1418703, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Martin Terrier (leverkusen)
  1. GUTIÉRREZ (displayed name, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Matheo Raab
  1. Mathis Albert (ID 1937835, similarity 55%)
  2. Natnael Abraha (ID 1861981, similarity 52%)
  3. Matthias Ginter (ID 142259, similarity 50%)

No exact match for SofaScore rating for Noah Atubolu
  1. Nathan Tella (ID 920379, similarity 55%)
  2. Noahkai Banks (ID 1597260, similarity 52%)
  3. Sacha Boey (ID 980418, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Oskar Wójcik
  1. Loris Karius (ID 174135, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Shafiq Nandja
  1. Finn Dahmen (ID 822564, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Shuto Machino
  1. Tom Bischof (ID 1129935, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sven Michel
  1. Michael Olise (ID 978838, similarity 55%)
  2. Senne Lynen (ID 826171, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Warmed Omari
  1. Roméo Ritter (ID 2266855, similarity 55%)
  2. Ameen Al-Dakhil (ID 1979970, similarity 50%)
  3. Waldemar Anton (ID 799046, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Alexander Røssing-Lelesiit
  1. Alexander Meyer (ID 138491, similarity 54%)
  2. Alexander Schlager (ID 282073, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Santiago Castañeda
  1. Giannis Konstantelias (ID 1002007, similarity 54%)
  2. Satoshi Tanaka (ID 981067, similarity 53%)
  3. Tiago Tomás (ID 983540, similarity 52%)
  4. Christian Kofane (ID 2029648, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Clemens Lippmann
  1. Filippo Mané (ID 1137131, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Facundo Medina (leverkusen)
  1. Afonso Moreira (ID 40418, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Frederik Schmahl
  1. Farès Chaïbi (ID 1192318, similarity 54%)
  2. Alexander Schlager (ID 282073, similarity 50%)
  3. Grischa Prömel (ID 253993, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jamie Leweling
  1. Samuele Inacio (ID 1861666, similarity 54%)
  2. Jobe Bellingham (ID 1134083, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jan Olschowsky
  1. Janis Blaswich (ID 96832, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jannik Huth (freiburg)
  1. Yannik Engelhardt (ID 20278, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Joël Schmied (koeln)
  1. Luca Waldschmidt (ID 2594, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Leopold Zingerle
  1. Tim Lemperle (ID 1014290, similarity 54%)
  2. Valentin Gendrey (ID 944899, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Luka Lochoshvili
  1. Luca Philipp (ID 943550, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Markus Schubert
  1. Mathis Albert (ID 1937835, similarity 54%)
  2. Derry Scherhant (ID 1131002, similarity 50%)
  3. Marcel Sabitzer (ID 133908, similarity 50%)
  4. Mick Schmetgens (ID 1568521, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Mattes Hansen
  1. Nathaniel Brown (ID 1159759, similarity 54%)
  2. Cajetan Lenz (ID 2077300, similarity 52%)
  3. Nathan De Cat (ID 1637689, similarity 52%)
  4. Nathan Tella (ID 920379, similarity 52%)
  5. Mats Rots (ID 1387012, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Rani Khedira
  1. Raphael Onyedika (ID 1129862, similarity 54%)
  2. Fabian Rieder (ID 929620, similarity 52%)
  3. Yannik Keitel (ID 877842, similarity 52%)
  4. Facundo Medina (ID 860307, similarity 50%)
  5. Francis Onyeka (ID 1414916, similarity 50%)

No exact match for SofaScore rating for Ron-Robert Zieler
  1. Gregor Kobel (ID 556866, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Stanley Nsoki
  1. Daniel Svensson (ID 1021272, similarity 54%)
  2. Cajetan Lenz (ID 2077300, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Stefano Marino
  1. Bastian Assomo (ID 2361805, similarity 54%)
  2. Facundo Medina (ID 860307, similarity 54%)
  3. Josha Vagnoman (ID 906278, similarity 54%)
  4. Christian Gomis (ID 1113440, similarity 52%)
  5. Han-Noah Massengo (ID 927340, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Aljoscha Kemlein
  1. Ron Schallenberg (ID 872358, similarity 53%)
  2. Josha Vagnoman (ID 906278, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Christopher Trimmel
  1. Chris Führich (ID 891510, similarity 53%)
  2. Christian Gomis (ID 1113440, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Gabriel Vidović
  1. Ermedin Demirović (ID 878081, similarity 53%)
  2. Andrija Maksimović (ID 1406171, similarity 52%)
  3. Arijon Ibrahimović (ID 1142248, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jahmai Simpson-Pusey
  1. Malik Pimpong (ID 1957761, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Lukeba Castello Jr. (leipzig)
  1. Castello Lukeba (ID 34680, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Montrell Culbreath
  1. Natnael Abraha (ID 1861981, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sebastiaan Bornauw
  1. Bastian Assomo (ID 2361805, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Silas
  1. Fábio Silva (ID 954076, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Tim Binder (bayern)
  1. LAIMER (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Albert Sambi Lokonga
  1. Bara Sapoko Ndiaye (ID 2427970, similarity 53%)
  2. Alessandro Vogt (ID 1408406, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Maurice Krattenmacher
  1. Marcel Sabitzer (ID 133908, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Axel Tape
  1. Cajetan Lenz (ID 2077300, similarity 53%)
  2. Max Moerstedt (ID 1418703, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Leo Sauer
  1. Loris Karius (ID 174135, similarity 53%)
  2. Manuel Neuer (ID 8959, similarity 53%)
  3. Lasse Günther (ID 997175, similarity 50%)
  4. Lucas Vázquez (ID 255239, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Livan Burcu
  1. Elias Baum (ID 1403018, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nick Bätzner
  1. Loïc Badé (ID 1006489, similarity 53%)
  2. Janik Bachmann (ID 579254, similarity 50%)
  3. Natnael Abraha (ID 1861981, similarity 50%)
  4. Nikolas Nartey (ID 861981, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Paul Nebel (mainz)
  1. Jaesung Lee (ID 21202, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Raif Adam
  1. Brajan Gruda (ID 1198075, similarity 53%)
  2. Ibrahim Maza (ID 1407524, similarity 53%)
  3. Junior Adamu (ID 902381, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Robert Skov
  1. Robin Koch (ID 581302, similarity 53%)
  2. Rodrigo Ribeiro (ID 1215904, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Ruben Müller (paderborn)
  1. SCHELLER (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Sander Tangvik (hamburg)
  1. Stange (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Serge Gnabry
  1. Bernardo (ID 828571, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tim Skarke
  1. Timo Becker (ID 814735, similarity 53%)
  2. Loris Karius (ID 174135, similarity 50%)
  3. Tim Lemperle (ID 1014290, similarity 50%)
  4. Tristan Spranger (ID 1974432, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tom Krauß
  1. Tiago Tomás (ID 983540, similarity 53%)
  2. Loris Karius (ID 174135, similarity 50%)
  3. Mio Backhaus (ID 1083390, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tom Rothe
  1. Roméo Ritter (ID 2266855, similarity 53%)
  2. Mats Rots (ID 1387012, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Albert Grønbæk
  1. Mathis Albert (ID 1937835, similarity 52%)
  2. Waldemar Anton (ID 799046, similarity 50%)

No exact match for ligainsider lineup for Amara Condé (elversberg)
  1. Francis Onyeka (ID 36948, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Daniel Batz
  1. Natnael Abraha (ID 1861981, similarity 52%)
  2. Yannick Engelhardt (ID 990209, similarity 52%)
  3. Daniel Svensson (ID 1021272, similarity 50%)
  4. Marcel Sabitzer (ID 133908, similarity 50%)
  5. Nathaniel Brown (ID 1159759, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Danny Da Costa (mainz)
  1. Anthony Caci (ID 25792, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Ilyas Ansah
  1. Jarell Quansah (ID 1003339, similarity 52%)
  2. Kauã Santos (ID 1134203, similarity 50%)
  3. Salim Musah (ID 1864786, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Janik Haberer (union)
  1. Rani Khedira (ID 2122, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Janik Haberer (union)
  1. Rani Khedira (ID 21666, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jano ter Horst
  1. Jan Gyamerah (ID 254411, similarity 52%)
  2. Benjamin Henrichs (ID 319857, similarity 50%)
  3. Max Moerstedt (ID 1418703, similarity 50%)
  4. Yan Couto (ID 1002813, similarity 50%)

No exact match for SofaScore rating for Nadiem Amiri
  1. Konrad Laimer (ID 355492, similarity 52%)
  2. Ermedin Demirović (ID 878081, similarity 52%)
  3. Albian Hajdari (ID 1000269, similarity 50%)
  4. Ismael Saibari (ID 1063767, similarity 50%)
  5. Waldemar Anton (ID 799046, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Nick Bätzner (paderborn)
  1. Jonah Sticker (ID 38855, similarity 52%)
  2. Santiago Castaneda (ID 37450, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Sebastian Klaas (paderborn)
  1. CASTAÑEDA (displayed name, similarity 52%)

No exact match for SofaScore rating for Sven Ulreich
  1. Chris Führich (ID 891510, similarity 52%)
  2. Samuele Inacio (ID 1861666, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Örjan Nyland
  1. Jan-Luca Riedl (ID 1937830, similarity 52%)
  2. Mertcan Ayhan (ID 1195798, similarity 52%)
  3. Anton Kade (ID 1129365, similarity 50%)
  4. Francis Onyeka (ID 1414916, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Alexander Meyer (dortmund)
  1. Julian Ryerson (ID 18478, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Alexander Meyer (dortmund)
  1. Julian Ryerson (ID 28864, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Atakan Karazor
  1. Takato Yamamoto (ID 2076134, similarity 52%)
  2. Aleksandar Pavlović (ID 1142251, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jordan Torunarigha
  1. Jonas Urbig (ID 1130647, similarity 52%)
  2. Jonathan Tah (ID 227672, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Julián Malatini
  1. Albian Hajdari (ID 1000269, similarity 52%)
  2. Ismael Saibari (ID 1063767, similarity 52%)
  3. Julian Ryerson (ID 800951, similarity 52%)

No exact match for SofaScore rating for Lukas Klostermann
  1. Lukas Petkov (ID 960017, similarity 52%)
  2. Łukasz Poręba (ID 942336, similarity 52%)
  3. Lasse Günther (ID 997175, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Moritz Nicolas
  1. Nicolas Kristof (ID 1131080, similarity 52%)
  2. Nicolas Seiwald (ID 976575, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Thijs Dallinga
  1. Jobe Bellingham (ID 1134083, similarity 52%)
  2. Nathan Tella (ID 920379, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sander Tangvik
  1. Aleksandar Pavlović (ID 1142251, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Youssoupha Niang
  1. Younes Ebnoutalib (ID 1474296, similarity 52%)
  2. Josha Vagnoman (ID 906278, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Zeno Van den Bosch
  1. Benjamin Henrichs (ID 319857, similarity 52%)
  2. Alexander Schlager (ID 282073, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Adrian Gantenbein
  1. Maximilian Eggestein (ID 569784, similarity 51%)

No exact match for ligainsider lineup for Andrej Kramarić (hoffenheim)
  1. Adam Daghim (ID 37622, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Andrej Kramarić (hoffenheim)
  1. Adam Daghim (ID 44189, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Chema Andrés (stuttgart)
  1. Ramon Hendriks (ID 23957, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Cyriaque Irié (freiburg)
  1. Christian Guenter (ID 2153, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Danny Da Costa
  1. Yan Couto (ID 1002813, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Dayot Upamecano
  1. Kauã Santos (ID 1134203, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Deniz Zeitler (paderborn)
  1. Ruben Mueller (ID 37563, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Deniz Zeitler
  1. Yannik Keitel (ID 877842, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Derrick Köhn (union)
  1. Friedrich (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Emmanuel Latte Lath
  1. Manuel Neuer (ID 8959, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Eren Sami Dinkçi (bremen)
  1. Erebenagie (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Ermedin Demirović (stuttgart)
  1. Dzenan Pejcinovic (ID 37405, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Fisnik Asllani
  1. Moussa Sylla (ID 861980, similarity 50%)
  2. Nikola Katić (ID 831488, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Florian Pruhs (paderborn)
  1. Laurin Ulrich (ID 27568, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Isac Lidberg (gladbach)
  1. Philipp Sander (ID 43368, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jae-Sung Lee
  1. Jonas Urbig (ID 1130647, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jamal Musiala (bayern)
  1. Luis Diaz (ID 22566, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Jamal Musiala (bayern)
  1. Luis Diaz (ID 28527, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Janik Bachmann (schalke)
  1. KARAMAN (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Janis Blaswich (leverkusen)
  1. QUANSAH (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Jason Ceka (elversberg)
  1. Jan Gyamerah (ID 48720, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jeanuël Belocian
  1. Dejan Ljubičić (ID 869883, similarity 50%)
  2. Janik Bachmann (ID 579254, similarity 50%)
  3. Samuele Inacio (ID 1861666, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Justin Lerma (dortmund)
  1. Julian Ryerson (ID 18478, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Justin Lerma (dortmund)
  1. Julian Ryerson (ID 28864, similarity 50%)

No exact match for SofaScore rating for Karl Hein
  1. João Palhinha (ID 364612, similarity 50%)
  2. Luca Reggiani (ID 1937833, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kevin Müller
  1. Angelo Stiller (ID 901882, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kofi Amoako
  1. Takato Yamamoto (ID 2076134, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Koki Machida
  1. Joshua Kimmich (ID 259117, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Lazar Jovanovic (stuttgart)
  1. Pejčinović (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Leonidas Stergiou
  1. Lasse Günther (ID 997175, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lorenz Assignon
  1. Daniel Svensson (ID 1021272, similarity 50%)
  2. Jonas Urbig (ID 1130647, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Louis Lemke
  1. Wisdom Mike (ID 1976732, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Martin Terrier (leverkusen)
  1. Miguel Gutierrez (ID 24219, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Martin Terrier (leverkusen)
  1. Miguel Gutierrez (ID 32495, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Mert Can Ayhan (schalke)
  1. Kenan Karaman (ID 20178, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Mert Kömür
  1. Keita Kosugi (ID 1501641, similarity 50%)
  2. Roméo Ritter (ID 2266855, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Mitchell Weiser (bremen)
  1. Mick Schmetgens (ID 37129, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Mitchell Weiser (bremen)
  1. Mick Schmetgens (ID 45910, similarity 50%)

No exact match for kickbase lineup for Montrell Culbreath (leverkusen)
  1. MOREIRA (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Nick Bätzner (paderborn)
  1. Santiago Castaneda (ID 48702, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Niklas Stark (bremen)
  1. Jens Stage (ID 22538, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Niklas Stark (bremen)
  1. Jens Stage (ID 30066, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Noel Futkeu
  1. Niclas Füllkrug (ID 132645, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Noël Aséko (frankfurt)
  1. LARSSON (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Noël Aséko (frankfurt)
  1. Hugo Larsson (ID 35384, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Otávio (frankfurt)
  1. EBNOUTALIB (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Paul Nebel (mainz)
  1. LEE (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Ruben Müller (paderborn)
  1. Tjark Scheller (ID 48700, similarity 50%)

No exact match for SofaScore rating for Rômulo
  1. Marco Grüll (ID 815612, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sota Kawasaki
  1. Noahkai Banks (ID 1597260, similarity 50%)

No exact match for SofaScore rating for Stefan Posch
  1. Josip Stanišić (ID 927407, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Tim Lemperle (hoffenheim)
  1. Patrick Wimmer (ID 26236, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Uchenna Ogundu
  1. Chema Andrés (ID 1464641, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Wael Mohya
  1. Felix Nmecha (ID 907463, similarity 50%)
  2. Raphael Onyedika (ID 1129862, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kickbase lineup for Örjan Nyland (leipzig)
  1. ORBÁN (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

Input summary
  Matchday: 1; ratings: team_player_average_ratings_2026-08-23_00-51-08_216063+0200.csv
  Ligainsider (weight 4): ligainsider_bundesliga_lineups_20260823_005130.json
  Kickbase (weight 3): kickbase_bundesliga_lineups_20260819_125416.json
  Rotowire (weight 1): rotowire_bundesliga_lineups_20260823_005207.json
  Alternative starting-chance decay: 0.45
  Questionable-injury starting-chance penalty: 0.15
  Output: C:\kickbase project\outputs\expected_points\expected_points_20260823_004913_+0200_sofascore_overall_rating_odds_lineup_20260823_005325_+0200.csv

Team odds and expected match points

,team,provider,win_probability,draw_probability,loss_probability,expected_match_points
0,augsburg,FotMob,0.439632,0.255462,0.304906,1.574358
1,bayern,FotMob,0.746846,0.141566,0.111588,2.382105
2,bremen,FotMob,0.270567,0.255941,0.473492,1.067642
3,dortmund,FotMob,0.728590,0.166170,0.105241,2.351939
4,elversberg,FotMob,0.182306,0.206085,0.611608,0.753004
5,frankfurt,FotMob,0.364604,0.256208,0.379188,1.350020
6,freiburg,FotMob,0.473492,0.255941,0.270567,1.676417
7,gladbach,FotMob,0.178859,0.197490,0.623652,0.734066
8,hamburg,FotMob,0.105241,0.166170,0.728590,0.481892
9,hoffenheim,FotMob,0.430888,0.263320,0.305792,1.555985
10,koeln,FotMob,0.305792,0.263320,0.430888,1.180695
11,leipzig,FotMob,0.623652,0.197490,0.178859,2.068445
12,leverkusen,FotMob,0.611608,0.206085,0.182306,2.040910
13,mainz,FotMob,0.574986,0.231397,0.193618,1.956354
14,paderborn,FotMob,0.193618,0.231397,0.574986,0.812250
15,schalke,FotMob,0.304906,0.255462,0.439632,1.170180
16,stuttgart,FotMob,0.111588,0.141566,0.746846,0.476329
17,union,FotMob,0.379188,0.256208,0.364604,1.393772

Player score review (non-positive or non-exact ratings)

,name,team,rating_status,lineup_status,rating,expected_match_points,ligainsider_starting_chance,kickbase_starting_chance,rotowire_starting_chance,questionable_injury_penalty,starting_chance,score
2,Sven Ulreich,bayern,missing_rating,not_evaluated_missing_rating,0.00,2.382105,0.0,0.0,0.0,0.0,0.0,0.0
4,Serge Gnabry,bayern,missing_rating,not_evaluated_missing_rating,0.00,2.382105,0.0,0.0,0.0,0.0,0.0,0.0
5,Dayot Upamecano,bayern,missing_rating,not_evaluated_missing_rating,0.00,2.382105,0.0,0.0,0.0,0.0,0.0,0.0
10,Jonas Urbig,bayern,exact,ligainsider:missing; kickbase:missing; rotowir...,6.70,2.382105,0.0,0.0,0.0,0.0,0.0,0.0
11,Hiroki Ito,bayern,exact,ligainsider:missing; kickbase:missing; rotowir...,6.65,2.382105,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
459,Adrian Gantenbein,schalke,missing_rating,not_evaluated_missing_rating,0.00,1.170180,0.0,0.0,0.0,0.0,0.0,0.0
461,Max Grüger,schalke,missing_rating,not_evaluated_missing_rating,0.00,1.170180,0.0,0.0,0.0,0.0,0.0,0.0
464,Christian Gomis,schalke,exact,ligainsider:missing; kickbase:missing; rotowir...,6.40,1.170180,0.0,0.0,0.0,0.0,0.0,0.0
465,Luca Vozar,schalke,exact,ligainsider:missing; kickbase:missing; rotowir...,6.70,1.170180,0.0,0.0,0.0,0.0,0.0,0.0
467,Johannes Simon Siebeking,schalke,missing_rating,not_evaluated_missing_rating,0.00,1.170180,0.0,0.0,0.0,0.0,0.0,0.0