# Kickbase percentile rating × odds × lineup score

Run derived-analysis notebook 10 first. This notebook selects its newest export by `generated_at` and uses its one-decimal per-match ratings in the shared overall odds/lineup workflow.

Team-match weights are 28%, 24%, 20%, 16%, 12%, newest first. Missing or excluded appearances are omitted and remaining weights renormalized without shifting slots. The weighted rating is rounded half-up to one decimal before scoring. The derived notebook now exports this same weighted average; this notebook recomputes it from individual match ratings so older exports remain compatible and weights are never applied twice. Persisted fallback flags are displayed when loading ratings.

Score = multiplier × Kickbase percentile rating × expected match points × starting chance. Odds, identity matching, matchday/source confirmation, injury handling, and lineup alternatives follow the existing overall rating notebook. The export uses `kickbase_percentile_rating`, a distinct method filename, and the optimizer-compatible `score` column.


Goalkeeper expected match points are `1.1 + raw expected match points * (0.6 / 3)`: raw 0 maps to 1.1, 1.5 maps to 1.4, and 3 maps to 1.7. Outfield players retain raw 0–3 values. The exported `expected_match_points` is the value used in the score. Rerun this notebook to generate updated scores.

Goalkeeper alternatives use decay **0.60** (relative weights **1, 0.6, 0.36, …**), with existing provider normalization and injury handling. Outfield alternatives retain their configured decay.

In [1]:
import sys
from pathlib import Path
from IPython.display import display
import pandas as pd

def locate_project_root():
    for start in (Path.cwd().resolve(), Path(globals().get('__vsc_ipynb_file__', '.')).resolve()):
        for candidate in (start, *start.parents):
            if (candidate / 'project_paths.py').is_file():
                return candidate
    raise FileNotFoundError('Run from within the project directory.')
PROJECT_ROOT = locate_project_root()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
import importlib
import sofascore_kickbase_percentile_ratings as percentile_ratings
importlib.reload(percentile_ratings)

In [2]:
QUESTIONABLE_INJURY_STARTING_CHANCE_PENALTY = 0.15
ALTERNATIVE_STARTING_CHANCE_DECAY = 0.45
GOALKEEPER_ALTERNATIVE_STARTING_CHANCE_DECAY = 0.60
LINEUP_SOURCE_WEIGHTS = {'ligainsider': 4.0, 'kickbase': 3.0, 'kicker': 2.0, 'rotowire': 1.0}
SCORE_MULTIPLIER = 10.0062
result = percentile_ratings.run_score_creation(
    questionable_injury_starting_chance_penalty=QUESTIONABLE_INJURY_STARTING_CHANCE_PENALTY,
    alternative_starting_chance_decay=ALTERNATIVE_STARTING_CHANCE_DECAY,
    goalkeeper_alternative_starting_chance_decay=GOALKEEPER_ALTERNATIVE_STARTING_CHANCE_DECAY,
    lineup_source_weights=LINEUP_SOURCE_WEIGHTS,
    score_multiplier=SCORE_MULTIPLIER,
)

Matchday for odds and lineups:  5
Is the Ligainsider predicted lineup snapshot (ligainsider_bundesliga_lineups_20260927_215644.json) accurate for matchday 5, or from the previous matchday? [a]ccurate/[p]revious:  p
Is the Kickbase predicted lineup snapshot (kickbase_bundesliga_lineups_20260918_171311.json) accurate for matchday 5, or from the previous matchday? [a]ccurate/[p]revious:  p
Is the Kicker predicted lineup snapshot (kicker_bundesliga_lineups_20261008_152026.json) accurate for matchday 5, or from the previous matchday? [a]ccurate/[p]revious:  a
Is the Rotowire predicted lineup snapshot (rotowire_bundesliga_lineups_20261008_151706.json) accurate for matchday 5, or from the previous matchday? [a]ccurate/[p]revious:  a

No exact match for kicker lineup for Nicolas Kühn (gladbach)
  1. Nicolas (displayed name, similarity 78%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Vitalie Becker (schalke)
  1. T. Becker (displayed name, similarity 70%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Nicholas Mickelson (elversberg)
  1. Kristof (displayed name, similarity 65%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Nicholas Mickelson (elversberg)
  1. Nicolas Kristof (ID 48713, similarity 65%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Kim Minjae (bayern)
  1. Kimmich (displayed name, similarity 64%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Sima Suso (augsburg)
  1. Massengo (displayed name, similarity 62%)
  2. Matsima (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Vitalie Becker (schalke)
  1. Timo Becker (ID 30648, similarity 61%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Kevin Stöger (gladbach)
  1. Diks (displayed name, similarity 60%)
  2. Kleindienst (displayed name, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Luka Duric (paderborn)
  1. Curda (displayed name, similarity 60%)
  2. Ulrich (displayed name, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Luka Duric (paderborn)
  1. Laurin Curda (ID 48704, similarity 60%)
  2. Laurin Ulrich (ID 37153, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Christoph Baumgartner (leipzig)
  1. Nkunku (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Christoph Baumgartner (leipzig)
  1. Christopher Nkunku (ID 20544, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Jan Olschowsky (gladbach)
  1. Leszczynski (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Jan Olschowsky (gladbach)
  1. Jan Leszczynski (ID 48750, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Markus Schubert (paderborn)
  1. Scheller (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Markus Schubert (paderborn)
  1. Tjark Scheller (ID 48700, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Isac Lidberg (gladbach)
  1. Sander (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Tim Oermann (leverkusen)
  1. Moreira (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Jannik Huth (freiburg)
  1. Beste (displayed name, similarity 58%)
  2. Engelhardt (displayed name, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Jannik Huth (freiburg)
  1. Jan-Niklas Beste (ID 26591, similarity 58%)
  2. Yannik Engelhardt (ID 36578, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Mert Can Ayhan (schalke)
  1. Kurucay (displayed name, similarity 58%)
  2. Tanaka (displayed name, similarity 56%)
  3. Karaman (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Nicolas Kühn (gladbach)
  1. Moritz Nicolas (ID 25259, similarity 58%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Cédric Itten (bremen)
  1. Dinkci (displayed name, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Emre Can (dortmund)
  1. F. Nmecha (displayed name, similarity 57%)
  2. J. Veerman (displayed name, similarity 53%)
  3. Anton (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Oliver Burke (union)
  1. Livan Burcu (ID 43803, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Stefan Bell (mainz)
  1. Posch (displayed name, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Stefan Bell (mainz)
  1. Stefan Posch (ID 23594, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Janik Bachmann (schalke)
  1. Karaman (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Janik Bachmann (schalke)
  1. Kenan Karaman (ID 20178, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Borna Sosa (koeln)
  1. Krauß (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Borna Sosa (koeln)
  1. Tom Krauss (ID 29789, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Emre Can (dortmund)
  1. Felix Nmecha (ID 27147, similarity 56%)
  2. Waldemar Anton (ID 20160, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Robert Skov (union)
  1. Rothe (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Sima Suso (augsburg)
  1. Marius Wolf (ID 21031, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Sven Michel (paderborn)
  1. Scheller (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Christian Günter (freiburg)
  1. Ginter (displayed name, similarity 55%)
  2. Scherhant (displayed name, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Christian Günter (freiburg)
  1. Matthias Ginter (ID 17592, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for András Schäfer (union)
  1. Aebischer (displayed name, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Jan Thielmann (koeln)
  1. S. El Mala (displayed name, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Jan Thielmann (koeln)
  1. Said El Mala (ID 46716, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Kastriot Imeri (union)
  1. Skarke (displayed name, similarity 55%)
  2. Trimmel (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Kauã Santos (frankfurt)
  1. Knauff (displayed name, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Luca Sirch (elversberg)
  1. Pinckert (displayed name, similarity 55%)
  2. Darvich (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Luca Sirch (elversberg)
  1. Lukas Pinckert (ID 48715, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Reigan Heskey (koeln)
  1. Moore (displayed name, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Guéla Doué (leverkusen)
  1. Miguel (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Leonidas Stergiou (stuttgart)
  1. Assignon (displayed name, similarity 53%)
  2. Seimen (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Marvin Friedrich (union)
  1. Rönnow (displayed name, similarity 53%)
  2. Ljubicic (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Tim Binder (bayern)
  1. Laimer (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Bernardo (hoffenheim)
  1. Hranac (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Justin Lerma (dortmund)
  1. J. Veerman (displayed name, similarity 53%)
  2. Anton (displayed name, similarity 50%)
  3. Ryerson (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Ruben Müller (paderborn)
  1. Scheller (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Adam Hložek (hoffenheim)
  1. Avdullahu (displayed name, similarity 52%)
  2. Daghim (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Daniel Batz (gladbach)
  1. Nicolas (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Danny Da Costa (mainz)
  1. Caci (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Danny Da Costa (mainz)
  1. Anthony Caci (ID 25792, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Janik Haberer (union)
  1. R. Khedira (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Janik Haberer (union)
  1. Rani Khedira (ID 21666, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Sebastian Klaas (paderborn)
  1. Castaneda (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Alexander Meyer (dortmund)
  1. Ryerson (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Nediljko Labrović (augsburg)
  1. Ibrahimovic (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Samuele Inácio (dortmund)
  1. Bensebaini (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Junior Adamu (schalke)
  1. Dina Ebimbe (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Abdoul Koné (leipzig)
  1. Romulo (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Abdoul Koné (leipzig)
  1. Romulo (ID 46816, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Albert Grønbæk (hamburg)
  1. Adeline (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Albian Hajdari (hoffenheim)
  1. Asllani (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Andrej Kramarić (hoffenheim)
  1. Daghim (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Andrej Kramarić (hoffenheim)
  1. Adam Daghim (ID 44189, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Brajan Gruda (leipzig)
  1. Raum (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Dzenan Pejčinović (stuttgart)
  1. Seimen (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Elias Baum (frankfurt)
  1. Kosugi (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Elias Baum (frankfurt)
  1. Keita Kosugi (ID 47541, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Ermedin Demirović (stuttgart)
  1. Seimen (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Ermedin Demirović (stuttgart)
  1. Dzenan Pejcinovic (ID 37405, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Florian Pruhs (paderborn)
  1. Ulrich (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Florian Pruhs (paderborn)
  1. Laurin Ulrich (ID 37153, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Guéla Doué (leverkusen)
  1. Miguel Gutierrez (ID 32495, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Isac Lidberg (gladbach)
  1. Philipp Sander (ID 43368, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Jamal Musiala (bayern)
  1. Luis Diaz (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Jamal Musiala (bayern)
  1. Luis Diaz (ID 28527, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Janis Blaswich (leverkusen)
  1. Quansah (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Jobe Bellingham (dortmund)
  1. Bensebaini (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Justin Diehl (stuttgart)
  1. Stiller (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Leonidas Stergiou (stuttgart)
  1. Dennis Seimen (ID 39573, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Linus Güther (union)
  1. Aebischer (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Marcel Hoffmeier (paderborn)
  1. Scheller (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Marcel Hoffmeier (paderborn)
  1. Tjark Scheller (ID 48700, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Martin Terrier (leverkusen)
  1. Miguel (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Martin Terrier (leverkusen)
  1. Miguel Gutierrez (ID 32495, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Mert Can Ayhan (schalke)
  1. Kenan Karaman (ID 20178, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Montrell Culbreath (leverkusen)
  1. Moreira (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Patrick Wimmer (hoffenheim)
  1. Lemperle (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Patrick Wimmer (hoffenheim)
  1. Tim Lemperle (ID 32420, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Ruben Müller (paderborn)
  1. Tjark Scheller (ID 48700, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Sota Kawasaki (mainz)
  1. Potulski (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Warmed Omari (hamburg)
  1. Adeline (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Örjan Nyland (leipzig)
  1. Orban (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Moussa Ndiaye
  1. Moussa Diaby (ID 855817, similarity 87%)
  2. Luis Díaz (ID 883537, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Luca Jaquez
  1. Lucas Vázquez (ID 255239, similarity 82%)
  2. Lucas Höler (ID 280009, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Robin Hranác
  1. Robin Hack (ID 876858, similarity 80%)
  2. Robin Koch (ID 581302, similarity 60%)
  3. Robert Andrich (ID 168903, similarity 58%)
  4. Robin Fellhauer (ID 860461, similarity 56%)
  5. Jonathan Tah (ID 227672, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Dejan Ljubičić
  1. Marin Ljubičić (ID 1090010, similarity 77%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Mitchell Weiser
  1. Michael Olise (ID 978838, similarity 77%)
  2. Michel Aebischer (ID 850891, similarity 76%)
  3. Michael Gregoritsch (ID 111483, similarity 56%)
  4. Jamie Leweling (ID 990201, similarity 52%)
  5. Mick Schmetgens (ID 1568521, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Alexander Schlager
  1. Alexander Schwolow (ID 134778, similarity 76%)
  2. Alexander Meyer (ID 138491, similarity 71%)
  3. András Schäfer (ID 877302, similarity 67%)
  4. Tom Alexander Rothe (ID 1210666, similarity 65%)
  5. Aleix García (ID 796047, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Christian Günter
  1. Christian Kofane (ID 2029648, similarity 73%)
  2. Christopher Nkunku (ID 769333, similarity 56%)
  3. Matthias Ginter (ID 142259, similarity 55%)
  4. Lasse Günther (ID 997175, similarity 52%)
  5. Marius Bülter (ID 378340, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Nathan Tella
  1. Jonathan Tah (ID 227672, similarity 73%)
  2. Nathaniel Brown (ID 1159759, similarity 64%)
  3. Nathan De Cat (ID 1637689, similarity 64%)
  4. Nahuel Noll (ID 1048651, similarity 57%)
  5. Matthias Ginter (ID 142259, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Lúkas Petersson
  1. Lukas Petkov (ID 960017, similarity 72%)
  2. Lukas Kübler (ID 142525, similarity 56%)
  3. Lasse Günther (ID 997175, similarity 54%)
  4. Julian Ryerson (ID 800951, similarity 52%)
  5. Lukas Finn Pinckert (ID 990105, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Alexander Prass
  1. Alexander Meyer (ID 138491, similarity 71%)
  2. Alexander Schwolow (ID 134778, similarity 65%)
  3. Tom Alexander Rothe (ID 1210666, similarity 65%)
  4. Aleksandar Pavlović (ID 1142251, similarity 56%)
  5. Aleix García (ID 796047, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Maximilian Kinzig
  1. Maximilian Beier (ID 980628, similarity 71%)
  2. Maximilian Eggestein (ID 569784, similarity 69%)
  3. Maximilian Rohr (ID 846398, similarity 67%)
  4. Maximilian Wöber (ID 794962, similarity 65%)
  5. Maximilian Mittelstädt (ID 788949, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Kauã Santos
  1. Kaishu Sano (ID 1028307, similarity 70%)
  2. Tom Krauß (ID 930272, similarity 53%)
  3. Waldemar Anton (ID 799046, similarity 52%)
  4. Dayot Upamecano (ID 798583, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Marius Funk
  1. Marius Wolf (ID 254119, similarity 70%)
  2. Marius Bülter (ID 378340, similarity 64%)
  3. Kaishu Sano (ID 1028307, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Timo Hübers
  1. Timo Becker (ID 814735, similarity 70%)
  2. Fabio Gruber (ID 1130119, similarity 57%)
  3. Arthur (ID 1174761, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Florian Pruhs
  1. Loris Karius (ID 174135, similarity 70%)
  2. Livan Burcu (ID 1513469, similarity 55%)
  3. Laurin Ulrich (ID 1152486, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Linus Güther
  1. Lasse Günther (ID 997175, similarity 70%)
  2. Marius Bülter (ID 378340, similarity 61%)
  3. Lucas Höler (ID 280009, similarity 57%)
  4. Lukas Kübler (ID 142525, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Lukas Ullrich
  1. Lukas Kübler (ID 142525, similarity 70%)
  2. Laurin Ulrich (ID 1152486, similarity 67%)
  3. Luca Sirch (ID 964603, similarity 67%)
  4. Luca Schnellbacher (ID 254133, similarity 55%)
  5. Lucas Höler (ID 280009, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for David Herold
  1. David Møller Wolfe (ID 1031283, similarity 69%)
  2. David Raum (ID 856076, similarity 60%)
  3. David Mokwa (ID 1432398, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Martin Terrier
  1. Martin Adeline (ID 1158529, similarity 69%)
  2. Matthias Ginter (ID 142259, similarity 59%)
  3. Marvin Pieringer (ID 909485, similarity 57%)
  4. Maximilian Beier (ID 980628, similarity 57%)
  5. Fabian Rieder (ID 929620, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Matthias Köbbing
  1. Matthias Ginter (ID 142259, similarity 69%)
  2. Mattes Hansen (ID 1083387, similarity 59%)
  3. Thijs Dallinga (ID 905381, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Andrej Ilic
  1. Andrej Kramarić (ID 67647, similarity 67%)
  2. Andrija Maksimović (ID 1406171, similarity 59%)
  3. Dženan Pejčinović (ID 1127790, similarity 54%)
  4. Adil Aouchiche (ID 962877, similarity 52%)
  5. Martin Adeline (ID 1158529, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Dan-Axel Zagadou
  1. Joane Gadou (ID 1471049, similarity 67%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Filippo Mane
  1. Philipp Sander (ID 939880, similarity 67%)
  2. Phillipp Mwene (ID 138126, similarity 67%)
  3. Willi Orbán (ID 136924, similarity 57%)
  4. Linton Maina (ID 921033, similarity 55%)
  5. Philipp Treu (ID 979820, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Leopold Zingerle
  1. Leopold Querfeld (ID 1086547, similarity 67%)
  2. Tim Lemperle (ID 1014290, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Luca Philipp
  1. Rayan Philippe (ID 991824, similarity 67%)
  2. Philipp Treu (ID 979820, similarity 64%)
  3. Philipp Sander (ID 939880, similarity 58%)
  4. Phillipp Mwene (ID 138126, similarity 58%)
  5. Lucas Höler (ID 280009, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Lukas Klostermann
  1. Lukas Kübler (ID 142525, similarity 67%)
  2. Lucas Höler (ID 280009, similarity 54%)
  3. Lukas Petkov (ID 960017, similarity 52%)
  4. Łukasz Poręba (ID 942336, similarity 52%)
  5. Lasse Günther (ID 997175, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Malik Pimpong
  1. Malik Tillman (ID 975798, similarity 67%)
  2. Jahmai Simpson-Pusey (ID 1402924, similarity 53%)
  3. Marvin Pieringer (ID 909485, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Marc Guiu
  1. Marco Grüll (ID 815612, similarity 67%)
  2. Marius Wolf (ID 254119, similarity 56%)
  3. Marco Friedl (ID 825771, similarity 53%)
  4. Marius Bülter (ID 378340, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Markus Kolke
  1. Marius Wolf (ID 254119, similarity 67%)
  2. Mark Flekken (ID 171919, similarity 64%)
  3. Marius Bülter (ID 378340, similarity 61%)
  4. Tim Skarke (ID 800252, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Marvin Friedrich
  1. Marvin Pieringer (ID 909485, similarity 67%)
  2. Marco Friedl (ID 825771, similarity 62%)
  3. Fabian Rieder (ID 929620, similarity 59%)
  4. Laurin Ulrich (ID 1152486, similarity 59%)
  5. Marvin Schwäbe (ID 187185, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Nikolas Nartey
  1. Nikola Katić (ID 831488, similarity 67%)
  2. Jan-Niklas Beste (ID 836711, similarity 59%)
  3. Nicolas Kristof (ID 1131080, similarity 59%)
  4. Nicolai Remberg (ID 1064305, similarity 52%)
  5. Nicolas Seiwald (ID 976575, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Oliver Burke
  1. Oliver Baumann (ID 40244, similarity 67%)
  2. Olivier Deman (ID 960114, similarity 61%)
  3. Wouter Burger (ID 916946, similarity 61%)
  4. Livan Burcu (ID 1513469, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Tiago Tomás
  1. Tidiam Gomis (ID 1426577, similarity 67%)
  2. Tom Krauß (ID 930272, similarity 53%)
  3. Santiago Castañeda (ID 1199101, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Arijon Ibrahimović
  1. Andrija Maksimović (ID 1406171, similarity 65%)
  2. Josip Juranović (ID 791642, similarity 58%)
  3. Ermedin Demirović (ID 878081, similarity 55%)
  4. Gabriel Vidović (ID 1129940, similarity 52%)
  5. Ibrahim Maza (ID 1407524, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Nicolas Kühn
  1. Nicholas Mickelson (ID 900264, similarity 64%)
  2. Niclas Füllkrug (ID 132645, similarity 64%)
  3. Nicolas Kristof (ID 1131080, similarity 64%)
  4. Moritz Nicolas (ID 578166, similarity 58%)
  5. Nicolas Seiwald (ID 976575, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Jonas Hofmann
  1. Josha Vagnoman (ID 906278, similarity 64%)
  2. Jonathan Tah (ID 227672, similarity 61%)
  3. Jonathan Burkardt (ID 939830, similarity 50%)
  4. Mattes Hansen (ID 1083387, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Lennard Maloney
  1. Lennart Karl (ID 1861975, similarity 64%)
  2. Kenan Karaman (ID 168943, similarity 62%)
  3. Olivier Deman (ID 960114, similarity 54%)
  4. Waldemar Anton (ID 799046, similarity 52%)
  5. Adam Hložek (ID 963801, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Niklas Stark
  1. Jan-Niklas Beste (ID 836711, similarity 64%)
  2. Nicolas Kristof (ID 1131080, similarity 56%)
  3. Nicolas Seiwald (ID 976575, similarity 56%)
  4. Nikola Katić (ID 831488, similarity 55%)
  5. Lasse Günther (ID 997175, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Shuto Machino
  1. Stefano Marino (ID 1167764, similarity 64%)
  2. Kaishu Sano (ID 1028307, similarity 55%)
  3. Tom Bischof (ID 1129935, similarity 55%)
  4. Koki Machida (ID 790977, similarity 52%)
  5. Linton Maina (ID 921033, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Anthony Jung
  1. Anthony Caci (ID 846471, similarity 64%)
  2. Antonio Nusa (ID 1121923, similarity 55%)
  3. Jordan Torunarigha (ID 801003, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Moussa Sylla
  1. Moussa Diaby (ID 855817, similarity 64%)
  2. Jamal Musiala (ID 1010231, similarity 52%)
  3. Fisnik Asllani (ID 1010117, similarity 50%)
  4. Joe Scally (ID 1002920, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Anton Kade
  1. Patson Daka (ID 865057, similarity 63%)
  2. Anthony Caci (ID 846471, similarity 60%)
  3. Antonio Nusa (ID 1121923, similarity 60%)
  4. Francis Onyeka (ID 1414916, similarity 55%)
  5. Amara Condé (ID 817978, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Felix Agu
  1. Felix Nmecha (ID 907463, similarity 63%)
  2. Elias Baum (ID 1403018, similarity 59%)
  3. Felix Uduokhai (ID 792142, similarity 57%)
  4. Felix Keidel (ID 1215028, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Keke Topp
  1. Keisuke Goto (ID 1391315, similarity 63%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Luca Vozar
  1. Lucas Höler (ID 280009, similarity 63%)
  2. Lucas Vázquez (ID 255239, similarity 57%)
  3. Luca Sirch (ID 964603, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Tim Binder
  1. Timo Becker (ID 814735, similarity 63%)
  2. Fabian Rieder (ID 929620, similarity 57%)
  3. Kim Min-jae (ID 896569, similarity 56%)
  4. Philipp Sander (ID 939880, similarity 55%)
  5. Matthias Ginter (ID 142259, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Christopher Trimmel
  1. Christopher Nkunku (ID 769333, similarity 63%)
  2. Chris Führich (ID 891510, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Marcel Hoffmeier
  1. Marcel Sabitzer (ID 133908, similarity 62%)
  2. Marco Friedl (ID 825771, similarity 62%)
  3. Manuel Neuer (ID 8959, similarity 54%)
  4. Karl Hein (ID 991591, similarity 52%)
  5. András Schäfer (ID 877302, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Patrick Osterhage
  1. Patrick Wimmer (ID 987504, similarity 62%)
  2. Otto Stange (ID 1568535, similarity 54%)
  3. Jonah Sticker (ID 1517850, similarity 50%)
  4. Marius Bülter (ID 378340, similarity 50%)
  5. Mattes Hansen (ID 1083387, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Ramon Hendriks
  1. Benjamin Henrichs (ID 319857, similarity 62%)
  2. Rani Khedira (ID 149479, similarity 58%)
  3. Raphael Onyedika (ID 1129862, similarity 57%)
  4. Kevin Diks (ID 583806, similarity 55%)
  5. Eren Dinkçi (ID 1067120, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Kastriot Imeri
  1. Patrick Wimmer (ID 987504, similarity 62%)
  2. Mario Götze (ID 66518, similarity 52%)
  3. Fábio Vieira (ID 904835, similarity 50%)
  4. Marvin Pieringer (ID 909485, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Markus Schubert
  1. Marius Bülter (ID 378340, similarity 62%)
  2. András Schäfer (ID 877302, similarity 59%)
  3. Marvin Schwäbe (ID 187185, similarity 59%)
  4. Tjark Lasse Scheller (ID 1137717, similarity 56%)
  5. Arthur (ID 1174761, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Patrick Drewes
  1. Patrick Wimmer (ID 987504, similarity 62%)
  2. Patrik Schick (ID 280609, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Bilal Nadir
  1. Albian Hajdari (ID 1000269, similarity 61%)
  2. Lilian Brassier (ID 988907, similarity 58%)
  3. Fabian Rieder (ID 929620, similarity 55%)
  4. Neil El Aynaoui (ID 1128530, similarity 52%)
  5. Philipp Sander (ID 939880, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Finn Porath
  1. Franck Honorat (ID 280453, similarity 61%)
  2. Finn Dahmen (ID 822564, similarity 60%)
  3. Finn Jeltsch (ID 1418649, similarity 57%)
  4. Lukas Finn Pinckert (ID 990105, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Noël Aséko
  1. Nicolas Kristof (ID 1131080, similarity 61%)
  2. Lukas Petkov (ID 960017, similarity 60%)
  3. Nicholas Mickelson (ID 900264, similarity 54%)
  4. Noel Futkeu (ID 1017574, similarity 53%)
  5. Daniel Svensson (ID 1021272, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Ruben Müller
  1. Marius Bülter (ID 378340, similarity 61%)
  2. Robin Fellhauer (ID 860461, similarity 56%)
  3. Manuel Neuer (ID 8959, similarity 55%)
  4. Robin Zentner (ID 174345, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Sven Ulreich
  1. Laurin Ulrich (ID 1152486, similarity 61%)
  2. Chris Führich (ID 891510, similarity 52%)
  3. Robert Andrich (ID 168903, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Tim Kleindienst
  1. Kevin Diks (ID 583806, similarity 61%)
  2. Tom Alexander Rothe (ID 1210666, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Tim Oermann
  1. Oliver Baumann (ID 40244, similarity 61%)
  2. Timo Becker (ID 814735, similarity 60%)
  3. Joey Veerman (ID 850816, similarity 57%)
  4. Olivier Deman (ID 960114, similarity 55%)
  5. Igor Matanović (ID 1019321, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Vitalie Becker
  1. Timo Becker (ID 814735, similarity 61%)
  2. Sheraldo Becker (ID 352544, similarity 59%)
  3. Isac Lidberg (ID 798175, similarity 58%)
  4. Nicolai Remberg (ID 1064305, similarity 52%)
  5. Maximilian Beier (ID 980628, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Dominik Kohr
  1. Robin Koch (ID 581302, similarity 60%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Eric Martel
  1. Eric Ebimbe (ID 904994, similarity 60%)
  2. Cédric Itten (ID 352290, similarity 57%)
  3. Tim Skarke (ID 800252, similarity 53%)
  4. Grischa Prömel (ID 253993, similarity 52%)
  5. Martin Adeline (ID 1158529, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Felix Götze
  1. Mario Götze (ID 66518, similarity 60%)
  2. Felix Keidel (ID 1215028, similarity 57%)
  3. Felix Nmecha (ID 907463, similarity 57%)
  4. Felix Uduokhai (ID 792142, similarity 52%)
  5. Marcel Sabitzer (ID 133908, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Imad Rondic
  1. Amara Condé (ID 817978, similarity 60%)
  2. Igor Matanović (ID 1019321, similarity 52%)
  3. Marin Ljubičić (ID 1090010, similarity 52%)
  4. Eren Dinkçi (ID 1067120, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Janik Bachmann
  1. Calvin Brackelmann (ID 1128792, similarity 60%)
  2. Kenan Karaman (ID 168943, similarity 56%)
  3. Oliver Baumann (ID 40244, similarity 54%)
  4. Han-Noah Massengo (ID 927340, similarity 50%)
  5. Mio Backhaus (ID 1083390, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Kevin Stöger
  1. Kevin Diks (ID 583806, similarity 60%)
  2. Keisuke Goto (ID 1391315, similarity 55%)
  3. Paul Okon-Engstler (ID 1411105, similarity 52%)
  4. Vincenzo Grifo (ID 171961, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Luka Duric
  1. Laurin Curda (ID 981788, similarity 60%)
  2. Lukas Kübler (ID 142525, similarity 60%)
  3. Laurin Ulrich (ID 1152486, similarity 57%)
  4. Luca Sirch (ID 964603, similarity 56%)
  5. Livan Burcu (ID 1513469, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Paul Nebel
  1. Manuel Neuer (ID 8959, similarity 60%)
  2. Paul Okon-Engstler (ID 1411105, similarity 56%)
  3. Jae-sung Lee (ID 537552, similarity 53%)
  4. Nahuel Noll (ID 1048651, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Christoph Baumgartner
  1. Christopher Nkunku (ID 769333, similarity 59%)
  2. Christian Kofane (ID 2029648, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Kennet Eichhorn
  1. Hennes Behrens (ID 1864760, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Nediljko Labrović
  1. Nikola Katić (ID 831488, similarity 59%)
  2. Neil El Aynaoui (ID 1128530, similarity 55%)
  3. Andrija Maksimović (ID 1406171, similarity 55%)
  4. Andrej Kramarić (ID 67647, similarity 53%)
  5. Noah Darvich (ID 1469995, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Sebastian Klaas
  1. Satoshi Tanaka (ID 981067, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Rael-Tshimbela Nakuzola
  1. Satoshi Tanaka (ID 981067, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Tom Baack
  1. Robin Hack (ID 876858, similarity 59%)
  2. Timo Becker (ID 814735, similarity 56%)
  3. Tom Bischof (ID 1129935, similarity 56%)
  4. Linton Maina (ID 921033, similarity 53%)
  5. Mio Backhaus (ID 1083390, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Fabio Chiarodia
  1. Fábio Silva (ID 954076, similarity 58%)
  2. Fábio Vieira (ID 904835, similarity 56%)
  3. Albian Hajdari (ID 1000269, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Farès Chaïbi
  1. Ismael Saibari (ID 1063767, similarity 58%)
  2. Marvin Schwäbe (ID 187185, similarity 58%)
  3. Marcel Sabitzer (ID 133908, similarity 56%)
  4. Patrik Schick (ID 280609, similarity 52%)
  5. András Schäfer (ID 877302, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Hee-Chan Hwang
  1. Ethan Nwaneri (ID 1401702, similarity 58%)
  2. Han-Noah Massengo (ID 927340, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Jannik Huth
  1. Jan-Niklas Beste (ID 836711, similarity 58%)
  2. Janik Haberer (ID 168985, similarity 55%)
  3. Yannik Keitel (ID 877842, similarity 55%)
  4. Yannick Engelhardt (ID 990209, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Luca Waldschmidt
  1. Luca Sirch (ID 964603, similarity 58%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Samuele Inácio
  1. Aleix García (ID 796047, similarity 58%)
  2. Jamie Leweling (ID 990201, similarity 54%)
  3. Eren Dinkçi (ID 1067120, similarity 52%)
  4. Nahuel Noll (ID 1048651, similarity 52%)
  5. Ramy Bensebaini (ID 577726, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Silvan Widmer
  1. Fabian Rieder (ID 929620, similarity 58%)
  2. Philipp Sander (ID 939880, similarity 56%)
  3. Alexander Meyer (ID 138491, similarity 54%)
  4. Nicolai Remberg (ID 1064305, similarity 54%)
  5. Isac Lidberg (ID 798175, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Oliver Batista Meier
  1. Oliver Baumann (ID 40244, similarity 58%)
  2. Lilian Brassier (ID 988907, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Eliesse Ben Seghir
  1. Ellyes Skhiri (ID 591706, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Frederik Schmahl
  1. Frederik Rønnow (ID 137692, similarity 57%)
  2. Alexander Schwolow (ID 134778, similarity 50%)
  3. Grischa Prömel (ID 253993, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Luca Pfeiffer
  1. Luca Sirch (ID 964603, similarity 57%)
  2. Lucas Höler (ID 280009, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Ron Schallenberg
  1. Marvin Schwäbe (ID 187185, similarity 57%)
  2. Isac Lidberg (ID 798175, similarity 54%)
  3. Aljoscha Kemlein (ID 1198074, similarity 53%)
  4. Robin Zentner (ID 174345, similarity 52%)
  5. András Schäfer (ID 877302, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Stefan Bell
  1. Stefan Posch (ID 355486, similarity 57%)
  2. Cole Campbell (ID 1134578, similarity 55%)
  3. Fabian Bredlow (ID 152463, similarity 52%)
  4. Stefano Marino (ID 1167764, similarity 52%)
  5. Steffen Tigges (ID 826884, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Atakan Karazor
  1. Kenan Karaman (ID 168943, similarity 56%)
  2. Aleksandar Pavlović (ID 1142251, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Daiki Hashioka
  1. Patrik Schick (ID 280609, similarity 56%)
  2. David Mokwa (ID 1432398, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Daniel Batz
  1. Daniel Fernandes (ID 113442, similarity 56%)
  2. Yannick Engelhardt (ID 990209, similarity 52%)
  3. Daniel Svensson (ID 1021272, similarity 50%)
  4. Marcel Sabitzer (ID 133908, similarity 50%)
  5. Nathaniel Brown (ID 1159759, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Dennis Seimen
  1. Hennes Behrens (ID 1864760, similarity 56%)
  2. Eric Ebimbe (ID 904994, similarity 55%)
  3. Gideon Mensah (ID 844942, similarity 50%)
  4. Yannik Keitel (ID 877842, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Derrick Köhn
  1. Derry Scherhant (ID 1131002, similarity 56%)
  2. Robert Andrich (ID 168903, similarity 50%)
  3. Robin Koch (ID 581302, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Edin Džeko
  1. Ermedin Demirović (ID 878081, similarity 56%)
  2. Kevin Diks (ID 583806, similarity 56%)
  3. Eren Dinkçi (ID 1067120, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Florian Müller
  1. Laurin Ulrich (ID 1152486, similarity 56%)
  2. Angelo Stiller (ID 901882, similarity 54%)
  3. Livan Burcu (ID 1513469, similarity 52%)
  4. Fabio Gruber (ID 1130119, similarity 50%)
  5. Felix Nmecha (ID 907463, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Florian Neuhaus
  1. Felix Nmecha (ID 907463, similarity 56%)
  2. Loris Karius (ID 174135, similarity 56%)
  3. Francis Onyeka (ID 1414916, similarity 52%)
  4. Livan Burcu (ID 1513469, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Frank Lehmann
  1. Franck Honorat (ID 280453, similarity 56%)
  2. Calvin Brackelmann (ID 1128792, similarity 55%)
  3. Rani Khedira (ID 149479, similarity 52%)
  4. Bilal El Khannouss (ID 1126569, similarity 50%)
  5. Kenan Karaman (ID 168943, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Jan Olschowsky
  1. Jano Ter-Horst (ID 1152342, similarity 56%)
  2. Stefan Posch (ID 355486, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Nnamdi Collins
  1. Michael Olise (ID 978838, similarity 56%)
  2. Jamie Leweling (ID 990201, similarity 54%)
  3. Nicolas Kristof (ID 1131080, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Stanley Nsoki
  1. Neil El Aynaoui (ID 1128530, similarity 56%)
  2. Daniel Svensson (ID 1021272, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Timothy Chandler
  1. Timo Becker (ID 814735, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Tom Zimmerschied
  1. Tom Bischof (ID 1129935, similarity 56%)
  2. Koki Machida (ID 790977, similarity 54%)
  3. Tim Lemperle (ID 1014290, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Warmed Omari
  1. Andrej Kramarić (ID 67647, similarity 56%)
  2. Nadiem Amiri (ID 327755, similarity 55%)
  3. Mert Kömür (ID 1390682, similarity 50%)
  4. Stefano Marino (ID 1167764, similarity 50%)
  5. Wael Mohya (ID 1995809, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Borna Sosa
  1. Tom Krauß (ID 930272, similarity 56%)
  2. Edmond Tapsoba (ID 883262, similarity 55%)
  3. Antonio Nusa (ID 1121923, similarity 50%)

No exact match for Kickbase percentile rating for Emre Can
  1. Felix Nmecha (ID 907463, similarity 56%)
  2. Waldemar Anton (ID 799046, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Faik Sakar
  1. Tim Skarke (ID 800252, similarity 56%)
  2. Francis Onyeka (ID 1414916, similarity 55%)
  3. Fábio Silva (ID 954076, similarity 53%)
  4. Patson Daka (ID 865057, similarity 53%)
  5. Loris Karius (ID 174135, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Jens Grahl
  1. Joe Scally (ID 1002920, similarity 56%)
  2. Jarell Quansah (ID 1003339, similarity 55%)
  3. Jae-sung Lee (ID 537552, similarity 53%)
  4. Brajan Gruda (ID 1198075, similarity 50%)
  5. Jan Gyamerah (ID 254411, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Sima Suso
  1. Marius Wolf (ID 254119, similarity 56%)
  2. Salim Musah (ID 1864786, similarity 56%)
  3. Mats Rots (ID 1387012, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Tim Boss
  1. Tidiam Gomis (ID 1426577, similarity 56%)
  2. Tim Skarke (ID 800252, similarity 50%)
  3. Tom Krauß (ID 930272, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Johan Bakayoko
  1. Jonathan Burkardt (ID 939830, similarity 55%)
  2. Ozan Kabak (ID 857740, similarity 55%)
  3. Satoshi Tanaka (ID 981067, similarity 54%)
  4. Joane Gadou (ID 1471049, similarity 52%)
  5. Jonathan Tah (ID 227672, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Valentin Gendrey
  1. Alexander Meyer (ID 138491, similarity 55%)
  2. Martin Adeline (ID 1158529, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Alexander Røssing-Lelesiit
  1. Alexander Schwolow (ID 134778, similarity 55%)
  2. Tom Alexander Rothe (ID 1210666, similarity 55%)
  3. Alexander Meyer (ID 138491, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Giannis Konstantelias
  1. Konstantinos Karetsas (ID 1468744, similarity 55%)
  2. Yannik Keitel (ID 877842, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Carl Klaus
  1. Jarell Quansah (ID 1003339, similarity 55%)
  2. Mio Backhaus (ID 1083390, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Janis Blaswich
  1. Luca Sirch (ID 964603, similarity 55%)
  2. Adil Aouchiche (ID 962877, similarity 54%)
  3. Josip Stanišić (ID 927407, similarity 54%)
  4. Jan-Niklas Beste (ID 836711, similarity 52%)
  5. Dariusz Stalmach (ID 1141977, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Joël Schmied
  1. Finn Jeltsch (ID 1418649, similarity 55%)
  2. Aljoscha Kemlein (ID 1198074, similarity 54%)
  3. Joe Scally (ID 1002920, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Oskar Wójcik
  1. Loris Karius (ID 174135, similarity 55%)
  2. Tim Skarke (ID 800252, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Shafiq Nandja
  1. Finn Dahmen (ID 822564, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Sven Michel
  1. Michael Olise (ID 978838, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Yanik Spalt
  1. Yannik Keitel (ID 877842, similarity 55%)
  2. Yannick Engelhardt (ID 990209, similarity 52%)
  3. Jan-Niklas Beste (ID 836711, similarity 50%)
  4. Nicolás Capaldo (ID 973564, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Abdoul Koné
  1. Paul Okon-Engstler (ID 1411105, similarity 54%)
  2. Louis Lemke (ID 1995000, similarity 50%)
  3. Rômulo (ID 1133743, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Assan Ouédraogo
  1. Hasan Kuruçay (ID 852096, similarity 54%)
  2. Kaishu Sano (ID 1028307, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Bara Sapoko Ndiaye
  1. Amara Condé (ID 817978, similarity 54%)
  2. Albert Sambi Lokonga (ID 901892, similarity 53%)
  3. Brajan Gruda (ID 1198075, similarity 52%)
  4. Raphael Onyedika (ID 1129862, similarity 52%)
  5. Bambasé Conté (ID 1185359, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Enzo Leopold
  1. Leopold Querfeld (ID 1086547, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Kevin Müller
  1. David Møller Wolfe (ID 1031283, similarity 54%)
  2. Angelo Stiller (ID 901882, similarity 50%)
  3. Kevin Diks (ID 583806, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Ron-Robert Zieler
  1. Gregor Kobel (ID 556866, similarity 54%)
  2. Robert Andrich (ID 168903, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Jens Castrop
  1. Alessio Castro-Montes (ID 839898, similarity 53%)
  2. Jonah Sticker (ID 1517850, similarity 52%)
  3. Joe Scally (ID 1002920, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Silas
  1. Fábio Silva (ID 954076, similarity 53%)
  2. Said El Mala (ID 1800475, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Montrell Culbreath
  1. Emmanuel Latte Lath (ID 848074, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Guéla Doué
  1. Joane Gadou (ID 1471049, similarity 53%)
  2. Manuel Neuer (ID 8959, similarity 50%)
  3. Miguel Gutiérrez (ID 908716, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Jens Stage
  1. Jae-sung Lee (ID 537552, similarity 53%)
  2. Otto Stange (ID 1568535, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Kauã Prates
  1. Ko Itakura (ID 790989, similarity 53%)
  2. Amara Condé (ID 817978, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Kofi Amoako
  1. Ko Itakura (ID 790989, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Miro Muheim
  1. Mert Kömür (ID 1390682, similarity 53%)
  2. Rômulo (ID 1133743, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Otávio
  1. Igor Matanović (ID 1019321, similarity 53%)
  2. David Mokwa (ID 1432398, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Raif Adam
  1. Brajan Gruda (ID 1198075, similarity 53%)
  2. Ibrahim Maza (ID 1407524, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Robert Skov
  1. Mert Kömür (ID 1390682, similarity 53%)
  2. Robin Koch (ID 581302, similarity 53%)
  3. Robert Andrich (ID 168903, similarity 52%)
  4. Albert Sambi Lokonga (ID 901892, similarity 50%)
  5. Rodrigo Ribeiro (ID 1215904, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Ameen Al Dakhil
  1. Adam Daghim (ID 1180758, similarity 52%)
  2. Eren Dinkçi (ID 1067120, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Ansgar Knauff
  1. Jan Gyamerah (ID 254411, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Cajetan Lenz
  1. Mattes Hansen (ID 1083387, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Junior Adamu
  1. Konrad Laimer (ID 355492, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Justin Lerma
  1. Jamal Musiala (ID 1010231, similarity 52%)
  2. Jonah Sticker (ID 1517850, similarity 52%)
  3. Angelo Stiller (ID 901882, similarity 50%)
  4. Julian Ryerson (ID 800951, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Senne Lynen
  1. Hennes Behrens (ID 1864760, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Zento Uno
  1. Zeno Van Den Bosch (ID 1103765, similarity 52%)
  2. Robin Zentner (ID 174345, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Rav van den Berg
  1. Alexander Meyer (ID 138491, similarity 52%)
  2. Isac Lidberg (ID 798175, similarity 50%)
  3. Manuel Neuer (ID 8959, similarity 50%)
  4. Raphael Obermair (ID 820465, similarity 50%)
  5. Zeno Van Den Bosch (ID 1103765, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Sander Tangvik
  1. Andrej Kramarić (ID 67647, similarity 52%)
  2. Aleksandar Pavlović (ID 1142251, similarity 52%)
  3. Albert Grønbæk (ID 1000263, similarity 50%)
  4. Isac Lidberg (ID 798175, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Adrian Gantenbein
  1. Maximilian Eggestein (ID 569784, similarity 51%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Johannes Simon Siebeking
  1. Jamie Leweling (ID 990201, similarity 51%)
  2. Jahmai Simpson-Pusey (ID 1402924, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Clemens Lippmann
  1. Calvin Brackelmann (ID 1128792, similarity 50%)
  2. Phillipp Mwene (ID 138126, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Cyriaque Irié
  1. Chris Führich (ID 891510, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Darwin Soylu
  1. Marin Ljubičić (ID 1090010, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Deniz Zeitler
  1. Yannik Keitel (ID 877842, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Juma Bah
  1. Jarell Quansah (ID 1003339, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Justin Diehl
  1. Martin Adeline (ID 1158529, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Leonidas Stergiou
  1. Jonah Sticker (ID 1517850, similarity 50%)
  2. Lasse Günther (ID 997175, similarity 50%)
  3. Leo Sauer (ID 1150938, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Lorenz Assignon
  1. Daniel Svensson (ID 1021272, similarity 50%)
  2. Jonas Urbig (ID 1130647, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Luca Reggiani
  1. Karl Hein (ID 991591, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Mathieu Nguefack
  1. Martin Adeline (ID 1158529, similarity 50%)
  2. Satoshi Tanaka (ID 981067, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Mert Can Ayhan
  1. Kenan Karaman (ID 168943, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Oscar Højlund
  1. Joe Scally (ID 1002920, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Rocco Reitz
  1. Marcel Sabitzer (ID 133908, similarity 50%)
  2. Mario Götze (ID 66518, similarity 50%)
  3. Rodrigo Ribeiro (ID 1215904, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Sota Kawasaki
  1. Noahkai Banks (ID 1597260, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Timur Gayret
  1. Tim Skarke (ID 800252, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Tom Wisbereit
  1. Marius Bülter (ID 378340, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for Kickbase percentile rating for Örjan Nyland
  1. Francis Onyeka (ID 1414916, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

Input summary
  Matchday: 5; Kickbase percentile rating: sofascore_kickbase_percentile_ratings_2026-10-08_15-15-43_201414+0200.json
  Ligainsider (weight 4; previous matchday — excluded): ligainsider_bundesliga_lineups_20260927_215644.json
  Kickbase (weight 3; previous matchday — excluded): kickbase_bundesliga_lineups_20260918_171311.json
  Kicker (weight 2; current): kicker_bundesliga_lineups_20261008_152026.json
  Rotowire (weight 1; current): rotowire_bundesliga_lineups_20261008_151706.json
  Alternative starting-chance decay: 0.45
  Questionable-injury starting-chance penalty: 0.15
  Score multiplier: 10.0062
  Output: C:\kickbase project\outputs\expected_points\expected_points_20261008_151434_+0200_sofascore_kickbase_percentile_rating_odds_lineup_20261008_152330_+0200.csv

Team odds and expected match points

,team,provider,win_probability,draw_probability,loss_probability,expected_match_points
0,augsburg,FotMob,0.086623,0.105873,0.807504,0.365742
1,bayern,FotMob,0.807504,0.105873,0.086623,2.528385
2,bremen,FotMob,0.119128,0.164314,0.716558,0.521698
3,dortmund,FotMob,0.716558,0.164314,0.119128,2.313988
4,elversberg,FotMob,0.356947,0.248924,0.394129,1.319765
5,frankfurt,FotMob,0.197755,0.189844,0.612401,0.783108
6,freiburg,FotMob,0.584893,0.225602,0.189505,1.980281
7,gladbach,FotMob,0.287356,0.231286,0.481358,1.093354
8,hamburg,FotMob,0.141359,0.182136,0.676505,0.606214
9,hoffenheim,FotMob,0.676505,0.182136,0.141359,2.211650
10,koeln,FotMob,0.481358,0.231286,0.287356,1.675359
11,leipzig,FotMob,0.612401,0.189844,0.197755,2.027048
12,leverkusen,FotMob,0.439632,0.255462,0.304906,1.574358
13,mainz,FotMob,0.304906,0.255462,0.439632,1.170180
14,paderborn,FotMob,0.189844,0.197755,0.612401,0.767288
15,schalke,FotMob,0.189505,0.225602,0.584893,0.794118
16,stuttgart,FotMob,0.612401,0.197755,0.189844,2.034958
17,union,FotMob,0.394129,0.248924,0.356947,1.431311

Player score review (non-positive or non-exact historical metric)

,name,team,metric_status,lineup_status,kickbase_percentile_rating,expected_match_points,ligainsider_starting_chance,kickbase_starting_chance,kicker_starting_chance,rotowire_starting_chance,questionable_injury_penalty,starting_chance,score_multiplier,score
0,Jonathan Tah,bayern,missing_history,kicker:normalized; rotowire:exact,9.0,2.528385,0.0,0.0,1.0,1.0,0.0,1.0,10.0062,227.695733
1,Manuel Neuer,bayern,missing_history,kicker:normalized; rotowire:exact,8.0,1.605677,0.0,0.0,1.0,1.0,0.0,1.0,10.0062,128.533801
2,Sven Ulreich,bayern,missing_history,kicker:missing; rotowire:missing,0.0,1.605677,0.0,0.0,0.0,0.0,0.0,0.0,10.0062,0.000000
3,Joshua Kimmich,bayern,missing_history,kicker:normalized; rotowire:exact,9.2,2.528385,0.0,0.0,1.0,1.0,0.0,1.0,10.0062,232.755638
4,Serge Gnabry,bayern,missing_history,kicker:missing; rotowire:missing,0.0,2.528385,0.0,0.0,0.0,0.0,0.0,0.0,10.0062,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
458,Nikola Katic,schalke,missing_history,kicker:normalized; rotowire:exact,8.2,0.794118,0.0,0.0,1.0,1.0,0.0,1.0,10.0062,65.158020
459,Luca Vozar,schalke,missing_history,kicker:missing; rotowire:missing,0.0,0.794118,0.0,0.0,0.0,0.0,0.0,0.0,10.0062,0.000000
460,Satoshi Tanaka,schalke,missing_history,kicker:normalized; rotowire:exact,6.3,0.794118,0.0,0.0,1.0,1.0,0.0,1.0,10.0062,50.060430
461,Johannes Simon Siebeking,schalke,missing_history,kicker:missing; rotowire:missing,0.0,1.258824,0.0,0.0,0.0,0.0,0.0,0.0,10.0062,0.000000
462,Adil Aouchiche,schalke,missing_history,kicker:normalized; rotowire:exact,7.9,0.794118,0.0,0.0,1.0,1.0,0.0,1.0,10.0062,62.774190