# SofaScore overall rating × odds × lineup score

Creates optimizer-ready scores from overall average ratings, expected match points from odds, and configurable-weight LigaInsider, Kickbase, Kicker, and RotoWire starting chances. LigaInsider, Kickbase, and Kicker alternatives use configurable geometric decay before slot normalization. The final score is `score multiplier × rating × expected match points × starting chance`; the exported CSV records the provider-specific chances, the injury penalty, multiplier, and final `score` column.

Confirmed SofaScore, LigaInsider, and RotoWire name matches are stored with Transfermarkt mappings in `data/reference/player_name_cross_references.csv`. Kickbase and Kicker display names resolve to a unique same-team KBStats last name, then first name; only shared-name or no-match candidates at 50% similarity or higher are shown for notebook confirmation and stored separately in `data/reference/kickbase_player_name_cross_references.csv`. Those mappings are scoped by provider, team, and KBStats player, so one provider's display label cannot override the other.

Set the notebook's QUES penalty, alternative-decay, source-weight, and score-multiplier variables to tune scoring. A provider-level QUES reduction is applied before LigaInsider or Kickbase formation-slot alternatives are normalized.

In [1]:
import sys
from pathlib import Path

# Absolute starting-chance reduction for a `QUES` injury flag from a lineup source.
QUESTIONABLE_INJURY_STARTING_CHANCE_PENALTY = 0.15
# Each rank is 45% of the preceding alternative before its slot is normalized.
ALTERNATIVE_STARTING_CHANCE_DECAY = 0.45
# Relative trust weights for active lineup sources; use 0 to disable one.
LINEUP_SOURCE_WEIGHTS = {'ligainsider': 4.0, 'kickbase': 3.0, 'kicker': 2.0, 'rotowire': 1.0}
# You will confirm whether each source is current for the selected matchday.
# Exploratory one-matchday fitted scale for rating × odds × lineup score.
SCORE_MULTIPLIER = 9.4739

def locate_project_root() -> Path:
    starts = [Path.cwd().resolve()]
    notebook_path = globals().get('__vsc_ipynb_file__')
    if isinstance(notebook_path, str) and notebook_path.strip():
        starts.insert(0, Path(notebook_path).expanduser().resolve().parent)
    for start in starts:
        for candidate in (start, *start.parents):
            if (candidate / 'project_paths.py').is_file():
                return candidate
    raise FileNotFoundError('Could not locate project_paths.py.')

PROJECT_ROOT = locate_project_root()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import importlib
import sofascore_rating_odds_lineup_score as score_creation
importlib.reload(score_creation)  # pick up local score-formula changes without restarting the kernel
from sofascore_rating_odds_lineup_score import run_score_creation
result = run_score_creation(
    'overall',
    questionable_injury_starting_chance_penalty=QUESTIONABLE_INJURY_STARTING_CHANCE_PENALTY,
    alternative_starting_chance_decay=ALTERNATIVE_STARTING_CHANCE_DECAY,
    lineup_source_weights=LINEUP_SOURCE_WEIGHTS,
    score_multiplier=SCORE_MULTIPLIER,
)

Matchday for odds and lineups:  2
Is the Ligainsider predicted lineup snapshot (ligainsider_bundesliga_lineups_20260904_105057.json) accurate for matchday 2, or from the previous matchday? [a]ccurate/[p]revious:  a
Is the Kickbase predicted lineup snapshot (kickbase_bundesliga_lineups_20260904_110452.json) accurate for matchday 2, or from the previous matchday? [a]ccurate/[p]revious:  p
Is the Kicker predicted lineup snapshot (kicker_bundesliga_lineups_20260904_105209.json) accurate for matchday 2, or from the previous matchday? [a]ccurate/[p]revious:  a
Is the Rotowire predicted lineup snapshot (rotowire_bundesliga_lineups_20260904_105027.json) accurate for matchday 2, or from the previous matchday? [a]ccurate/[p]revious:  a

No exact match for rotowire lineup for David Møller Wolfe (hamburg)
  1. David Moller Wolfe (ID 44313, similarity 97%)

Choose a candidate number, or press Enter to skip (score 0):  1

No exact match for ligainsider lineup for Mert Kömür (augsburg)
  1. Mert Koemuer (ID 27169, similarity 90%)

Choose a candidate number, or press Enter to skip (score 0):  1

No exact match for SofaScore rating for Luca Jaquez
  1. Lucas Vázquez (ID 255239, similarity 82%)
  2. Cajetan Lenz (ID 2077300, similarity 57%)
  3. Lucas Höler (ID 280009, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Mitchell Weiser
  1. Michael Olise (ID 978838, similarity 77%)
  2. Michel Aebischer (ID 850891, similarity 76%)
  3. Michael Gregoritsch (ID 111483, similarity 56%)
  4. Mathis Albert (ID 1937835, similarity 54%)
  5. Jamie Leweling (ID 990201, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Luka Duric
  1. Lukas Ullrich (ID 1083382, similarity 76%)
  2. Laurin Curda (ID 981788, similarity 60%)
  3. Lukas Kübler (ID 142525, similarity 60%)
  4. Laurin Ulrich (ID 1152486, similarity 57%)
  5. Luca Sirch (ID 964603, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lúkas Petersson
  1. Lukas Petkov (ID 960017, similarity 72%)
  2. Lukas Kübler (ID 142525, similarity 56%)
  3. Lasse Günther (ID 997175, similarity 54%)
  4. Julian Ryerson (ID 800951, similarity 52%)
  5. Lukas Finn Pinckert (ID 990105, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Alexander Prass
  1. Alexander Meyer (ID 138491, similarity 71%)
  2. Tom Alexander Rothe (ID 1210666, similarity 65%)
  3. Aleksandar Pavlović (ID 1142251, similarity 56%)
  4. Aleix García (ID 796047, similarity 56%)
  5. Daniel Fernandes (ID 113442, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Alexander Schlager
  1. Alexander Meyer (ID 138491, similarity 71%)
  2. András Schäfer (ID 877302, similarity 67%)
  3. Tom Alexander Rothe (ID 1210666, similarity 65%)
  4. Aleix García (ID 796047, similarity 57%)
  5. Alessandro Vogt (ID 1408406, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Maximilian Kinzig
  1. Maximilian Beier (ID 980628, similarity 71%)
  2. Maximilian Eggestein (ID 569784, similarity 69%)
  3. Maximilian Rohr (ID 846398, similarity 67%)
  4. Maximilian Wöber (ID 794962, similarity 65%)
  5. Maximilian Mittelstädt (ID 788949, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Marius Funk
  1. Marius Wolf (ID 254119, similarity 70%)
  2. Kaishu Sano (ID 1028307, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Timo Hübers
  1. Timo Becker (ID 814735, similarity 70%)
  2. Tim Binder (ID 1925507, similarity 63%)
  3. Fabio Gruber (ID 1130119, similarity 57%)
  4. Ramon Hendriks (ID 916943, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Vitalie Becker (schalke)
  1. T. Becker (displayed name, similarity 70%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Florian Pruhs
  1. Loris Karius (ID 174135, similarity 70%)
  2. Livan Burcu (ID 1513469, similarity 55%)
  3. Florian Yves Le Joncour (ID 787816, similarity 50%)
  4. Laurin Ulrich (ID 1152486, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Linus Güther
  1. Lasse Günther (ID 997175, similarity 70%)
  2. Lucas Höler (ID 280009, similarity 57%)
  3. Kevin Stöger (ID 95381, similarity 55%)
  4. Lukas Kübler (ID 142525, similarity 55%)
  5. Christian Günter (ID 142231, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for David Møller Wolfe
  1. David Herold (ID 997178, similarity 69%)
  2. David Mokwa (ID 1432398, similarity 56%)
  3. David Raum (ID 856076, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Martin Terrier
  1. Martin Adeline (ID 1158529, similarity 69%)
  2. Matthias Ginter (ID 142259, similarity 59%)
  3. Marvin Pieringer (ID 909485, similarity 57%)
  4. Maximilian Beier (ID 980628, similarity 57%)
  5. Fabian Rieder (ID 929620, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Matthias Köbbing
  1. Matthias Ginter (ID 142259, similarity 69%)
  2. Mattes Hansen (ID 1083387, similarity 59%)
  3. Malik Pimpong (ID 1957761, similarity 52%)
  4. Mathis Albert (ID 1937835, similarity 52%)
  5. Thijs Dallinga (ID 905381, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Andrej Ilic
  1. Andrej Kramarić (ID 67647, similarity 67%)
  2. Andrija Maksimović (ID 1406171, similarity 59%)
  3. Dženan Pejčinović (ID 1127790, similarity 54%)
  4. Adil Aouchiche (ID 962877, similarity 52%)
  5. Martin Adeline (ID 1158529, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Arthur
  1. Arthur Chaves (ID 1122806, similarity 67%)
  2. Arthur Vermeeren (ID 1149127, similarity 57%)
  3. Mert Kömür (ID 1390682, similarity 53%)
  4. Matheo Raab (ID 842718, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Dan-Axel Zagadou
  1. Joane Gadou (ID 1471049, similarity 67%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Fábio Vieira
  1. Fábio Silva (ID 954076, similarity 67%)
  2. Fabio Gruber (ID 1130119, similarity 64%)
  3. Fabian Rieder (ID 929620, similarity 61%)
  4. Rani Khedira (ID 149479, similarity 55%)
  5. Olivier Deman (ID 960114, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Justin Diehl
  1. Justin Njinmah (ID 1005343, similarity 67%)
  2. Martin Adeline (ID 1158529, similarity 50%)
  3. Tim Binder (ID 1925507, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Justin Lerma
  1. Justin Njinmah (ID 1005343, similarity 67%)
  2. Jan Uwe Thielmann (ID 1010726, similarity 54%)
  3. Jamal Musiala (ID 1010231, similarity 52%)
  4. Jonah Sticker (ID 1517850, similarity 52%)
  5. Angelo Stiller (ID 901882, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Leopold Zingerle
  1. Leopold Querfeld (ID 1086547, similarity 67%)
  2. Tim Lemperle (ID 1014290, similarity 54%)
  3. Valentin Gendrey (ID 944899, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lukas Klostermann
  1. Lukas Kübler (ID 142525, similarity 67%)
  2. Lucas Höler (ID 280009, similarity 54%)
  3. Lukas Petkov (ID 960017, similarity 52%)
  4. Łukasz Poręba (ID 942336, similarity 52%)
  5. Jonas Hofmann (ID 142390, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Markus Kolke
  1. Marius Wolf (ID 254119, similarity 67%)
  2. Mark Flekken (ID 171919, similarity 64%)
  3. Tim Skarke (ID 800252, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Marvin Friedrich
  1. Marvin Pieringer (ID 909485, similarity 67%)
  2. Marco Friedl (ID 825771, similarity 62%)
  3. Fabian Rieder (ID 929620, similarity 59%)
  4. Laurin Ulrich (ID 1152486, similarity 59%)
  5. Marvin Schwäbe (ID 187185, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Maxime Estève
  1. Max Moerstedt (ID 1418703, similarity 67%)
  2. Maximilian Eggestein (ID 569784, similarity 65%)
  3. Maximilian Beier (ID 980628, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nikolas Nartey
  1. Nikola Katić (ID 831488, similarity 67%)
  2. Jan-Niklas Beste (ID 836711, similarity 59%)
  3. Nicolas Kristof (ID 1131080, similarity 59%)
  4. Bilal Nadir (ID 1129527, similarity 52%)
  5. Kauã Prates (ID 1887796, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Oliver Burke
  1. Oliver Baumann (ID 40244, similarity 67%)
  2. Olivier Deman (ID 960114, similarity 61%)
  3. Wouter Burger (ID 916946, similarity 61%)
  4. Livan Burcu (ID 1513469, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Rayan Philippe
  1. Luca Philipp (ID 943550, similarity 67%)
  2. Philipp Treu (ID 979820, similarity 67%)
  3. Philipp Sander (ID 939880, similarity 62%)
  4. Phillipp Mwene (ID 138126, similarity 62%)
  5. Philipp Lienhart (ID 576266, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Nicholas Mickelson (elversberg)
  1. Nicolas Kristof (ID 26473, similarity 65%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Nicholas Mickelson (elversberg)
  1. Nicolas Kristof (ID 48713, similarity 65%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nicholas Mickelson
  1. Nicolas Kristof (ID 1131080, similarity 65%)
  2. Nicolás Capaldo (ID 973564, similarity 65%)
  3. Nicolas Seiwald (ID 976575, similarity 58%)
  4. Nicolai Remberg (ID 1064305, similarity 52%)
  5. Michel Aebischer (ID 850891, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sebastian Klaas
  1. Sebastiaan Bornauw (ID 826167, similarity 65%)
  2. Satoshi Tanaka (ID 981067, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Assan Ouédraogo
  1. Alessandro Vogt (ID 1408406, similarity 64%)
  2. Hasan Kuruçay (ID 852096, similarity 54%)
  3. Kaishu Sano (ID 1028307, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lennard Maloney
  1. Lennart Karl (ID 1861975, similarity 64%)
  2. Bernardo (ID 828571, similarity 55%)
  3. Olivier Deman (ID 960114, similarity 54%)
  4. Waldemar Anton (ID 799046, similarity 52%)
  5. Adam Hložek (ID 963801, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nicolas Kühn
  1. Niclas Füllkrug (ID 132645, similarity 64%)
  2. Nicolas Kristof (ID 1131080, similarity 64%)
  3. Moritz Nicolas (ID 578166, similarity 58%)
  4. Nicolas Seiwald (ID 976575, similarity 56%)
  5. Nicolás Capaldo (ID 973564, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Niklas Stark
  1. Jan-Niklas Beste (ID 836711, similarity 64%)
  2. Nicolas Kristof (ID 1131080, similarity 56%)
  3. Nicolas Seiwald (ID 976575, similarity 56%)
  4. Nikola Katić (ID 831488, similarity 55%)
  5. Lasse Günther (ID 997175, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Shuto Machino
  1. Stefano Marino (ID 1167764, similarity 64%)
  2. Kaishu Sano (ID 1028307, similarity 55%)
  3. Tom Bischof (ID 1129935, similarity 55%)
  4. Linton Maina (ID 921033, similarity 52%)
  5. Jonas Hofmann (ID 142390, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Amara Condé
  1. Bambasé Conté (ID 1185359, similarity 64%)
  2. Waldemar Anton (ID 799046, similarity 61%)
  3. Ragnar Ache (ID 877544, similarity 60%)
  4. Chema Andrés (ID 1464641, similarity 57%)
  5. Marco Friedl (ID 825771, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Anthony Jung
  1. Anthony Caci (ID 846471, similarity 64%)
  2. Antonio Nusa (ID 1121923, similarity 55%)
  3. Anton Kade (ID 1129365, similarity 50%)
  4. Jordan Torunarigha (ID 801003, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kevin Müller
  1. Kevin Stöger (ID 95381, similarity 64%)
  2. Angelo Stiller (ID 901882, similarity 50%)
  3. Kevin Diks (ID 583806, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Lucas Höler (freiburg)
  1. Lukas Kuebler (ID 1935, similarity 64%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Marius Bülter
  1. Marius Wolf (ID 254119, similarity 64%)
  2. Mathis Albert (ID 1937835, similarity 58%)
  3. Marvin Schwäbe (ID 187185, similarity 56%)
  4. Marcel Sabitzer (ID 133908, similarity 54%)
  5. Matthias Ginter (ID 142259, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Moussa Diaby
  1. Moussa Sylla (ID 861980, similarity 64%)
  2. Luis Díaz (ID 883537, similarity 53%)
  3. Sacha Boey (ID 980418, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Felix Agu
  1. Felix Nmecha (ID 907463, similarity 63%)
  2. Elias Baum (ID 1403018, similarity 59%)
  3. Felix Keidel (ID 1215028, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Keke Topp
  1. Keisuke Goto (ID 1391315, similarity 63%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Luca Vozar
  1. Lucas Höler (ID 280009, similarity 63%)
  2. Lucas Vázquez (ID 255239, similarity 57%)
  3. Luca Sirch (ID 964603, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Christoph Baumgartner
  1. Christian Günter (ID 142231, similarity 63%)
  2. Christopher Nkunku (ID 769333, similarity 59%)
  3. Christian Kofane (ID 2029648, similarity 57%)
  4. Tristan Spranger (ID 1974432, similarity 51%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Christopher Trimmel
  1. Christopher Nkunku (ID 769333, similarity 63%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Kim Minjae (bayern)
  1. Kimmich (displayed name, similarity 62%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Sima Suso (augsburg)
  1. Massengo (displayed name, similarity 62%)
  2. Matsima (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lilian Brassier
  1. Maximilian Beier (ID 980628, similarity 62%)
  2. András Schäfer (ID 877302, similarity 59%)
  3. Maximilian Wöber (ID 794962, similarity 55%)
  4. Fabian Rieder (ID 929620, similarity 54%)
  5. Silvan Widmer (ID 157377, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Marcel Hoffmeier
  1. Marcel Sabitzer (ID 133908, similarity 62%)
  2. Marco Friedl (ID 825771, similarity 62%)
  3. Manuel Neuer (ID 8959, similarity 54%)
  4. Karl Hein (ID 991591, similarity 52%)
  5. András Schäfer (ID 877302, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Patrick Drewes
  1. Patrick Osterhage (ID 914755, similarity 62%)
  2. Patrick Wimmer (ID 987504, similarity 62%)
  3. Patrice Čović (ID 1596105, similarity 56%)
  4. Patrik Schick (ID 280609, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kastriot Imeri
  1. Patrick Wimmer (ID 987504, similarity 62%)
  2. Patrick Osterhage (ID 914755, similarity 55%)
  3. Kevin Stöger (ID 95381, similarity 50%)
  4. Marvin Pieringer (ID 909485, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sebastian Sebulonsen
  1. Sebastiaan Bornauw (ID 826167, similarity 61%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Finn Porath
  1. Franck Honorat (ID 280453, similarity 61%)
  2. Finn Dahmen (ID 822564, similarity 60%)
  3. Finn Jeltsch (ID 1418649, similarity 57%)
  4. Lukas Finn Pinckert (ID 990105, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Moussa Ndiaye
  1. Moussa Sylla (ID 861980, similarity 61%)
  2. Luis Díaz (ID 883537, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Noël Aséko
  1. Nicolas Kristof (ID 1131080, similarity 61%)
  2. Lukas Petkov (ID 960017, similarity 60%)
  3. Daniel Svensson (ID 1021272, similarity 52%)
  4. Nicolas Seiwald (ID 976575, similarity 52%)
  5. Nicolás Capaldo (ID 973564, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sven Ulreich
  1. Laurin Ulrich (ID 1152486, similarity 61%)
  2. Lukas Ullrich (ID 1083382, similarity 61%)
  3. Samuele Inacio (ID 1861666, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tim Oermann
  1. Oliver Baumann (ID 40244, similarity 61%)
  2. Timo Becker (ID 814735, similarity 60%)
  3. Joey Veerman (ID 850816, similarity 57%)
  4. Jan Uwe Thielmann (ID 1010726, similarity 56%)
  5. Mertcan Ayhan (ID 1195798, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Vitalie Becker (schalke)
  1. Timo Becker (ID 30648, similarity 61%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Youri Regeer
  1. Wouter Burger (ID 916946, similarity 61%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Florian Müller
  1. Florian Yves Le Joncour (ID 787816, similarity 61%)
  2. Laurin Ulrich (ID 1152486, similarity 56%)
  3. Angelo Stiller (ID 901882, similarity 54%)
  4. Livan Burcu (ID 1513469, similarity 52%)
  5. Christian Günter (ID 142231, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Eric Martel
  1. Eric Ebimbe (ID 904994, similarity 60%)
  2. Cédric Itten (ID 352290, similarity 57%)
  3. Tim Skarke (ID 800252, similarity 53%)
  4. Grischa Prömel (ID 253993, similarity 52%)
  5. Martin Adeline (ID 1158529, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Janik Bachmann
  1. Calvin Brackelmann (ID 1128792, similarity 60%)
  2. Jan Uwe Thielmann (ID 1010726, similarity 57%)
  3. Jonas Hofmann (ID 142390, similarity 56%)
  4. Oliver Baumann (ID 40244, similarity 54%)
  5. Han-Noah Massengo (ID 927340, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jens Stage
  1. Kevin Stöger (ID 95381, similarity 60%)
  2. Jae-sung Lee (ID 537552, similarity 53%)
  3. Otto Stange (ID 1568535, similarity 53%)
  4. Cajetan Lenz (ID 2077300, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Luka Duric (paderborn)
  1. Laurin Curda (ID 36261, similarity 60%)
  2. Laurin Ulrich (ID 27568, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Luka Duric (paderborn)
  1. Laurin Curda (ID 48704, similarity 60%)
  2. Laurin Ulrich (ID 37153, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Paul Nebel
  1. Manuel Neuer (ID 8959, similarity 60%)
  2. Paul Okon-Engstler (ID 1411105, similarity 56%)
  3. Jae-sung Lee (ID 537552, similarity 53%)
  4. Nahuel Noll (ID 1048651, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Christoph Baumgartner (leipzig)
  1. Christopher Nkunku (ID 12446, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jan Olschowsky (gladbach)
  1. Jan Leszczynski (ID 38925, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kennet Eichhorn
  1. Hennes Behrens (ID 1864760, similarity 59%)
  2. Senne Lynen (ID 826171, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Markus Schubert (paderborn)
  1. Tjark Scheller (ID 36890, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Markus Schubert (paderborn)
  1. Tjark Scheller (ID 48700, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Markus Schubert
  1. András Schäfer (ID 877302, similarity 59%)
  2. Marvin Schwäbe (ID 187185, similarity 59%)
  3. Tjark Lasse Scheller (ID 1137717, similarity 56%)
  4. Mathis Albert (ID 1937835, similarity 54%)
  5. Derry Scherhant (ID 1131002, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nediljko Labrović
  1. Nikola Katić (ID 831488, similarity 59%)
  2. Andrija Maksimović (ID 1406171, similarity 55%)
  3. Andrej Kramarić (ID 67647, similarity 53%)
  4. Noah Darvich (ID 1469995, similarity 52%)
  5. Ermedin Demirović (ID 878081, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Alexander Schwolow
  1. Tom Alexander Rothe (ID 1210666, similarity 59%)
  2. Alessandro Vogt (ID 1408406, similarity 58%)
  3. Alexander Meyer (ID 138491, similarity 58%)
  4. Aleksandar Pavlović (ID 1142251, similarity 51%)
  5. Aleix García (ID 796047, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Borna Sosa
  1. Bernardo (ID 828571, similarity 59%)
  2. Jonas Hofmann (ID 142390, similarity 57%)
  3. Tom Krauß (ID 930272, similarity 56%)
  4. Edmond Tapsoba (ID 883262, similarity 55%)
  5. Antonio Nusa (ID 1121923, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Isac Lidberg (gladbach)
  1. Sander (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Rael-Tshimbela Nakuzola
  1. Satoshi Tanaka (ID 981067, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Tim Oermann (leverkusen)
  1. Moreira (displayed name, similarity 59%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Chris Führich
  1. Laurin Ulrich (ID 1152486, similarity 58%)
  2. Christian Günter (ID 142231, similarity 52%)
  3. Cyriaque Irié (ID 1508537, similarity 50%)
  4. Lukas Ullrich (ID 1083382, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Fabio Chiarodia
  1. Fábio Silva (ID 954076, similarity 58%)
  2. Albian Hajdari (ID 1000269, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Felix Uduokhai
  1. Felix Nmecha (ID 907463, similarity 58%)
  2. Felix Keidel (ID 1215028, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Jannik Huth (freiburg)
  1. Jan-Niklas Beste (ID 26591, similarity 58%)
  2. Yannik Engelhardt (ID 36578, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jannik Huth
  1. Jan-Niklas Beste (ID 836711, similarity 58%)
  2. Janik Haberer (ID 168985, similarity 55%)
  3. Yannik Keitel (ID 877842, similarity 55%)
  4. Yannick Engelhardt (ID 990209, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Luca Waldschmidt
  1. Luca Sirch (ID 964603, similarity 58%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Mario Götze
  1. Marcel Sabitzer (ID 133908, similarity 58%)
  2. Mats Rots (ID 1387012, similarity 56%)
  3. Marco Grüll (ID 815612, similarity 50%)
  4. Marius Wolf (ID 254119, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Nicolas Kühn (gladbach)
  1. Moritz Nicolas (ID 6295, similarity 58%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Nicolas Kühn (gladbach)
  1. Moritz Nicolas (ID 25259, similarity 58%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Robert Andrich
  1. Robin Hranáč (ID 957615, similarity 58%)
  2. Benjamin Henrichs (ID 319857, similarity 55%)
  3. Robin Koch (ID 581302, similarity 55%)
  4. Ramon Hendriks (ID 916943, similarity 54%)
  5. Eren Dinkçi (ID 1067120, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Stefan Posch
  1. Stefano Marino (ID 1167764, similarity 58%)
  2. Zeno Van Den Bosch (ID 1103765, similarity 54%)
  3. Josip Stanišić (ID 927407, similarity 50%)
  4. Steffen Tigges (ID 826884, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Timothy Chandler
  1. Tim Binder (ID 1925507, similarity 58%)
  2. Timo Becker (ID 814735, similarity 56%)
  3. Mathis Albert (ID 1937835, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tom Wisbereit
  1. Mathis Albert (ID 1937835, similarity 58%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Oliver Batista Meier
  1. Oliver Baumann (ID 40244, similarity 58%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Eliesse Ben Seghir
  1. Ellyes Skhiri (ID 591706, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Emre Can (dortmund)
  1. F. Nmecha (displayed name, similarity 57%)
  2. J. Veerman (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Felix Götze
  1. Felix Keidel (ID 1215028, similarity 57%)
  2. Felix Nmecha (ID 907463, similarity 57%)
  3. Marcel Sabitzer (ID 133908, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jeremy Arévalo
  1. Jeremiaha Maluze (ID 1886360, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Luca Pfeiffer
  1. Luca Sirch (ID 964603, similarity 57%)
  2. Lucas Höler (ID 280009, similarity 55%)
  3. Luca Philipp (ID 943550, similarity 52%)
  4. Luca Reggiani (ID 1937833, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Neil El Aynaoui (leipzig)
  1. Ezechiel Banzuzi (ID 46428, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Neil El Aynaoui
  1. Ezechiel Banzuzi (ID 1155383, similarity 57%)
  2. Bilal El Khannouss (ID 1126569, similarity 55%)
  3. Soufiane El-Faouzi (ID 1083338, similarity 55%)
  4. Bilal Nadir (ID 1129527, similarity 52%)
  5. Jan Uwe Thielmann (ID 1010726, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Oliver Burke (union)
  1. Livan Burcu (ID 36114, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Rav van den Berg
  1. Ron Schallenberg (ID 872358, similarity 57%)
  2. Alexander Meyer (ID 138491, similarity 52%)
  3. Isac Lidberg (ID 798175, similarity 50%)
  4. Manuel Neuer (ID 8959, similarity 50%)
  5. Raphael Obermair (ID 820465, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Stefan Bell (mainz)
  1. Stefan Posch (ID 12798, similarity 57%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Stefan Bell
  1. Nathan Tella (ID 920379, similarity 57%)
  2. Cole Campbell (ID 1134578, similarity 55%)
  3. Fabian Bredlow (ID 152463, similarity 52%)
  4. Stefano Marino (ID 1167764, similarity 52%)
  5. Steffen Tigges (ID 826884, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Young-Woo Seol
  1. Younes Ebnoutalib (ID 1474296, similarity 57%)
  2. Robin Gosens (ID 377118, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Daniel Batz
  1. Daniel Fernandes (ID 113442, similarity 56%)
  2. Natnael Abraha (ID 1861981, similarity 52%)
  3. Yannick Engelhardt (ID 990209, similarity 52%)
  4. Daniel Svensson (ID 1021272, similarity 50%)
  5. Marcel Sabitzer (ID 133908, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Dennis Seimen
  1. Hennes Behrens (ID 1864760, similarity 56%)
  2. Eric Ebimbe (ID 904994, similarity 55%)
  3. Senne Lynen (ID 826171, similarity 55%)
  4. Gideon Mensah (ID 844942, similarity 50%)
  5. Leonidas Stergiou (ID 962898, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Florian Neuhaus
  1. Felix Nmecha (ID 907463, similarity 56%)
  2. Loris Karius (ID 174135, similarity 56%)
  3. Florian Yves Le Joncour (ID 787816, similarity 53%)
  4. Francis Onyeka (ID 1414916, similarity 52%)
  5. Livan Burcu (ID 1513469, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Frank Lehmann
  1. Franck Honorat (ID 280453, similarity 56%)
  2. Calvin Brackelmann (ID 1128792, similarity 55%)
  3. Rani Khedira (ID 149479, similarity 52%)
  4. Jan Uwe Thielmann (ID 1010726, similarity 52%)
  5. Bilal El Khannouss (ID 1126569, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jan Olschowsky
  1. Jano Ter-Horst (ID 1152342, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Julián Malatini
  1. Linton Maina (ID 921033, similarity 56%)
  2. Albian Hajdari (ID 1000269, similarity 52%)
  3. Ismael Saibari (ID 1063767, similarity 52%)
  4. Julian Ryerson (ID 800951, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kenan Karaman
  1. Natnael Abraha (ID 1861981, similarity 56%)
  2. Andrej Kramarić (ID 67647, similarity 54%)
  3. Lennart Karl (ID 1861975, similarity 52%)
  4. Konstantinos Karetsas (ID 1468744, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Marius Bülter (koeln)
  1. Marvin Schwabe (ID 34845, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nnamdi Collins
  1. Michael Olise (ID 978838, similarity 56%)
  2. Jamie Leweling (ID 990201, similarity 54%)
  3. Nicolas Kristof (ID 1131080, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Ruben Müller
  1. Robin Fellhauer (ID 860461, similarity 56%)
  2. Manuel Neuer (ID 8959, similarity 55%)
  3. Robin Zentner (ID 174345, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tom Zimmerschied
  1. Tom Bischof (ID 1129935, similarity 56%)
  2. Tim Lemperle (ID 1014290, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Warmed Omari
  1. Andrej Kramarić (ID 67647, similarity 56%)
  2. Nadiem Amiri (ID 327755, similarity 55%)
  3. Mert Kömür (ID 1390682, similarity 50%)
  4. Ramon Hendriks (ID 916943, similarity 50%)
  5. Stefano Marino (ID 1167764, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Borna Sosa (koeln)
  1. Tom Krauss (ID 20244, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Borna Sosa (koeln)
  1. Tom Krauss (ID 29789, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Emre Can (dortmund)
  1. Felix Nmecha (ID 25090, similarity 56%)
  2. Waldemar Anton (ID 5837, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Emre Can (dortmund)
  1. Felix Nmecha (ID 27147, similarity 56%)
  2. Waldemar Anton (ID 20160, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Emre Can
  1. Felix Nmecha (ID 907463, similarity 56%)
  2. Mertcan Ayhan (ID 1195798, similarity 53%)
  3. Waldemar Anton (ID 799046, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Faik Sakar
  1. Tim Skarke (ID 800252, similarity 56%)
  2. Daiki Hashioka (ID 897334, similarity 55%)
  3. Francis Onyeka (ID 1414916, similarity 55%)
  4. Fábio Silva (ID 954076, similarity 53%)
  5. Patson Daka (ID 865057, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jens Grahl
  1. Joe Scally (ID 1002920, similarity 56%)
  2. Jarell Quansah (ID 1003339, similarity 55%)
  3. Jae-sung Lee (ID 537552, similarity 53%)
  4. Brajan Gruda (ID 1198075, similarity 50%)
  5. Jan Gyamerah (ID 254411, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Mert Can Ayhan (schalke)
  1. Tanaka (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Sima Suso (augsburg)
  1. Marius Wolf (ID 5670, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Sima Suso (augsburg)
  1. Marius Wolf (ID 21031, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sima Suso
  1. Marius Wolf (ID 254119, similarity 56%)
  2. Salim Musah (ID 1864786, similarity 56%)
  3. Mats Rots (ID 1387012, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Sven Michel (paderborn)
  1. Scheller (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Tiago Tomás (stuttgart)
  1. Vagnoman (displayed name, similarity 56%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Tim Boss
  1. Tidiam Gomis (ID 1426577, similarity 56%)
  2. Tim Binder (ID 1925507, similarity 50%)
  3. Tim Skarke (ID 800252, similarity 50%)
  4. Tom Krauß (ID 930272, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Christian Günter (freiburg)
  1. Matthias Ginter (ID 17592, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kristijan Jakić
  1. Christian Kofane (ID 2029648, similarity 55%)
  2. Kim Min-jae (ID 896569, similarity 52%)
  3. Andrija Maksimović (ID 1406171, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Alexander Røssing-Lelesiit
  1. Tom Alexander Rothe (ID 1210666, similarity 55%)
  2. Alexander Meyer (ID 138491, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Giannis Konstantelias (dortmund)
  1. Konstantinos Karetsas (ID 38406, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Giannis Konstantelias (dortmund)
  1. Konstantinos Karetsas (ID 47271, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Alexis Claude-Maurice
  1. Alexander Meyer (ID 138491, similarity 55%)
  2. Adil Aouchiche (ID 962877, similarity 50%)
  3. Albian Hajdari (ID 1000269, similarity 50%)
  4. Tom Alexander Rothe (ID 1210666, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for András Schäfer (union)
  1. Aebischer (displayed name, similarity 55%)
  2. van den Bosch (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Carl Klaus
  1. Jarell Quansah (ID 1003339, similarity 55%)
  2. Mio Backhaus (ID 1083390, similarity 50%)
  3. Oscar Højlund (ID 1149113, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Janis Blaswich
  1. Luca Sirch (ID 964603, similarity 55%)
  2. Adil Aouchiche (ID 962877, similarity 54%)
  3. Josip Stanišić (ID 927407, similarity 54%)
  4. Jan-Niklas Beste (ID 836711, similarity 52%)
  5. Dariusz Stalmach (ID 1141977, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Joël Schmied
  1. Finn Jeltsch (ID 1418649, similarity 55%)
  2. Aljoscha Kemlein (ID 1198074, similarity 54%)
  3. Joe Scally (ID 1002920, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Kenny Quetant (bremen)
  1. Senne Lynen (ID 35359, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Kenny Quetant (bremen)
  1. Senne Lynen (ID 37714, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kenny Quetant
  1. Senne Lynen (ID 826171, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Luca Sirch (elversberg)
  1. Lukas Pinckert (ID 38539, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Luca Sirch (elversberg)
  1. Lukas Pinckert (ID 48715, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Oskar Wójcik
  1. Loris Karius (ID 174135, similarity 55%)
  2. Tim Skarke (ID 800252, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Said El Mala (koeln)
  1. Jan Thielmann (ID 21998, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Said El Mala (koeln)
  1. Jan Thielmann (ID 30688, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Shafiq Nandja
  1. Finn Dahmen (ID 822564, similarity 55%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sven Michel
  1. Michael Olise (ID 978838, similarity 55%)
  2. Senne Lynen (ID 826171, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Örjan Nyland
  1. Oscar Højlund (ID 1149113, similarity 55%)
  2. Mertcan Ayhan (ID 1195798, similarity 52%)
  3. Anton Kade (ID 1129365, similarity 50%)
  4. Francis Onyeka (ID 1414916, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Abdoul Koné
  1. Paul Okon-Engstler (ID 1411105, similarity 54%)
  2. Louis Lemke (ID 1995000, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Ameen Al Dakhil
  1. Samuele Inacio (ID 1861666, similarity 54%)
  2. Adam Daghim (ID 1180758, similarity 52%)
  3. Eren Dinkçi (ID 1067120, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Clemens Lippmann
  1. Filippo Mané (ID 1137131, similarity 54%)
  2. Calvin Brackelmann (ID 1128792, similarity 50%)
  3. Phillipp Mwene (ID 138126, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Enzo Leopold
  1. Leopold Querfeld (ID 1086547, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Ermedin Demirović (stuttgart)
  1. Pejcinovic (displayed name, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Frederik Schmahl
  1. Farès Chaïbi (ID 1192318, similarity 54%)
  2. Grischa Prömel (ID 253993, similarity 50%)
  3. Ramon Hendriks (ID 916943, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jannik Huth (freiburg)
  1. Yannik Engelhardt (ID 20278, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Ron-Robert Zieler
  1. Gregor Kobel (ID 556866, similarity 54%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Stanley Nsoki
  1. Daniel Svensson (ID 1021272, similarity 54%)
  2. Cajetan Lenz (ID 2077300, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Borna Sosa (koeln)
  1. Krauß (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Guéla Doué (leverkusen)
  1. Miguel (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Jens Castrop
  1. Alessio Castro-Montes (ID 839898, similarity 53%)
  2. Bernardo (ID 828571, similarity 53%)
  3. Jonah Sticker (ID 1517850, similarity 52%)
  4. Leonidas Stergiou (ID 962898, similarity 52%)
  5. Joe Scally (ID 1002920, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Lorenz Assignon
  1. Leonidas Stergiou (ID 962898, similarity 53%)
  2. Daniel Svensson (ID 1021272, similarity 50%)
  3. Jonas Urbig (ID 1130647, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Luka Duric (paderborn)
  1. Ulrich (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Montrell Culbreath
  1. Natnael Abraha (ID 1861981, similarity 53%)
  2. Emmanuel Latte Lath (ID 848074, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Rômulo
  1. Mert Kömür (ID 1390682, similarity 53%)
  2. Marco Grüll (ID 815612, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Silas
  1. Fábio Silva (ID 954076, similarity 53%)
  2. Said El Mala (ID 1800475, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Tim Binder (bayern)
  1. Laimer (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Ayoube Amaimouni (frankfurt)
  1. Amaimouni-Echghouyab (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Bara Sapoko Ndiaye
  1. Albert Sambi Lokonga (ID 901892, similarity 53%)
  2. Brajan Gruda (ID 1198075, similarity 52%)
  3. Raphael Onyedika (ID 1129862, similarity 52%)
  4. Bambasé Conté (ID 1185359, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Guéla Doué
  1. Joane Gadou (ID 1471049, similarity 53%)
  2. Manuel Neuer (ID 8959, similarity 50%)
  3. Miguel Gutiérrez (ID 908716, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Justin Lerma (dortmund)
  1. J. Veerman (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Kofi Amoako
  1. Ko Itakura (ID 790989, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Leo Sauer
  1. Loris Karius (ID 174135, similarity 53%)
  2. Manuel Neuer (ID 8959, similarity 53%)
  3. Leopold Querfeld (ID 1086547, similarity 52%)
  4. Lasse Günther (ID 997175, similarity 50%)
  5. Leonidas Stergiou (ID 962898, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Miro Muheim
  1. Mert Kömür (ID 1390682, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Paul Nebel (mainz)
  1. Jaesung Lee (ID 21202, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Raif Adam
  1. Brajan Gruda (ID 1198075, similarity 53%)
  2. Ibrahim Maza (ID 1407524, similarity 53%)
  3. Junior Adamu (ID 902381, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Ritsu Dōan
  1. Kaishu Sano (ID 1028307, similarity 53%)
  2. Laurin Curda (ID 981788, similarity 50%)
  3. Linton Maina (ID 921033, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Robert Skov
  1. Mert Kömür (ID 1390682, similarity 53%)
  2. Robin Koch (ID 581302, similarity 53%)
  3. Albert Sambi Lokonga (ID 901892, similarity 50%)
  4. Rodrigo Ribeiro (ID 1215904, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Ruben Müller (paderborn)
  1. Scheller (displayed name, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Serge Gnabry
  1. Bernardo (ID 828571, similarity 53%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Amara Condé (elversberg)
  1. Francis Onyeka (ID 36948, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Amara Condé (elversberg)
  1. Francis Onyeka (ID 40979, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Janik Haberer (union)
  1. Rani Khedira (ID 2122, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Janik Haberer (union)
  1. Rani Khedira (ID 21666, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Sebastian Klaas (paderborn)
  1. Castaneda (displayed name, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Zento Uno
  1. Zeno Van Den Bosch (ID 1103765, similarity 52%)
  2. Robin Zentner (ID 174345, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Alexander Meyer (dortmund)
  1. Julian Ryerson (ID 18478, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Alexander Meyer (dortmund)
  1. Julian Ryerson (ID 28864, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Ethan Nwaneri
  1. Tristan Spranger (ID 1974432, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Hee-Chan Hwang
  1. Han-Noah Massengo (ID 927340, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Ron-Robert Zieler (koeln)
  1. Okon-Engstler (displayed name, similarity 52%)

No exact match for ligainsider lineup for Samuele Inácio (dortmund)
  1. Ramy Bensebaini (ID 7791, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sander Tangvik
  1. Andrej Kramarić (ID 67647, similarity 52%)
  2. Aleksandar Pavlović (ID 1142251, similarity 52%)
  3. Albert Grønbæk (ID 1000263, similarity 50%)
  4. Isac Lidberg (ID 798175, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Adrian Gantenbein
  1. Christian Günter (ID 142231, similarity 52%)
  2. Maximilian Eggestein (ID 569784, similarity 51%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Atakan Karazor
  1. Aleksandar Pavlović (ID 1142251, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Nico Schlotterbeck
  1. Nicolás Capaldo (ID 973564, similarity 52%)
  2. Sheraldo Becker (ID 352544, similarity 52%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Johannes Simon Siebeking
  1. Jamie Leweling (ID 990201, similarity 51%)
  2. Jahmai Simpson-Pusey (ID 1402924, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Adam Hložek (hoffenheim)
  1. Adam Daghim (ID 44189, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Andrej Kramarić (hoffenheim)
  1. Adam Daghim (ID 37622, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Andrej Kramarić (hoffenheim)
  1. Adam Daghim (ID 44189, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Christian Günter (freiburg)
  1. Scherhant (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Darwin Soylu
  1. Marin Ljubičić (ID 1090010, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Deniz Zeitler
  1. Yannik Keitel (ID 877842, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Ermedin Demirović (stuttgart)
  1. Dzenan Pejcinovic (ID 26158, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Ermedin Demirović (stuttgart)
  1. Dzenan Pejcinovic (ID 37405, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Fisnik Asllani
  1. Moussa Sylla (ID 861980, similarity 50%)
  2. Nikola Katić (ID 831488, similarity 50%)

No exact match for ligainsider lineup for Florian Pruhs (paderborn)
  1. Laurin Ulrich (ID 27568, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Florian Pruhs (paderborn)
  1. Laurin Ulrich (ID 37153, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Guéla Doué (leverkusen)
  1. Miguel Gutierrez (ID 32495, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Isac Lidberg (gladbach)
  1. Philipp Sander (ID 18612, similarity 50%)

No exact match for rotowire lineup for Isac Lidberg (gladbach)
  1. Philipp Sander (ID 43368, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Jamal Musiala (bayern)
  1. Luis Diaz (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jamal Musiala (bayern)
  1. Luis Diaz (ID 22566, similarity 50%)

No exact match for rotowire lineup for Jamal Musiala (bayern)
  1. Luis Diaz (ID 28527, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Janik Bachmann (schalke)
  1. Karaman (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Janis Blaswich (leverkusen)
  1. Quansah (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jens Castrop (gladbach)
  1. Joe Scally (ID 23700, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Jens Castrop (gladbach)
  1. Joe Scally (ID 26680, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Jens Grahl (frankfurt)
  1. Jeremiaha Maluze (ID 38581, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Jens Grahl (frankfurt)
  1. Jeremiaha Maluze (ID 49039, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Juma Bah
  1. Jarell Quansah (ID 1003339, similarity 50%)
  2. Justin Njinmah (ID 1005343, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Justin Lerma (dortmund)
  1. Julian Ryerson (ID 18478, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Justin Lerma (dortmund)
  1. Julian Ryerson (ID 28864, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Koki Machida
  1. Joshua Kimmich (ID 259117, similarity 50%)

No exact match for kicker lineup for Linus Güther (union)
  1. Aebischer (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Lucas Höler (freiburg)
  1. Kübler (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Marcel Hoffmeier (paderborn)
  1. Tjark Scheller (ID 48700, similarity 50%)

No exact match for rotowire lineup for Martin Adeline (hamburg)
  1. Zakaria El Ouahdi (ID 43675, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Martin Terrier (leverkusen)
  1. Miguel Gutierrez (ID 24219, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Martin Terrier (leverkusen)
  1. Miguel Gutierrez (ID 32495, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Marvin Friedrich (union)
  1. Marin Ljubicic (ID 36465, similarity 50%)

No exact match for rotowire lineup for Marvin Friedrich (union)
  1. Marin Ljubicic (ID 40575, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for ligainsider lineup for Mitchell Weiser (bremen)
  1. Mick Schmetgens (ID 37129, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Montrell Culbreath (leverkusen)
  1. Moreira (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Noel Futkeu
  1. Niclas Füllkrug (ID 132645, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Otávio (frankfurt)
  1. Ebnoutalib (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Paul Erevbenagie
  1. Samuele Inacio (ID 1861666, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for rotowire lineup for Ruben Müller (paderborn)
  1. Tjark Scheller (ID 48700, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Sota Kawasaki (mainz)
  1. Potulski (displayed name, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Sota Kawasaki
  1. Noahkai Banks (ID 1597260, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Timur Gayret
  1. Tim Skarke (ID 800252, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Uchenna Ogundu
  1. Chema Andrés (ID 1464641, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):

No exact match for SofaScore rating for Zakaria El Ouahdi
  1. Jarell Quansah (ID 1003339, similarity 50%)
  2. Martin Adeline (ID 1158529, similarity 50%)

Choose a candidate number, or press Enter to skip (score 0):
Choose a candidate number, or press Enter to skip (score 0):

No exact match for kicker lineup for Örjan Nyland (leipzig)
  1. Orban (displayed name, similarity 50%)
Input summary
  Matchday: 2; ratings: team_player_average_ratings_2026-09-04_10-49-29_967272+0200.csv
  Ligainsider (weight 4; current): ligainsider_bundesliga_lineups_20260904_105057.json
  Kickbase (weight 3; previous matchday — excluded): kickbase_bundesliga_lineups_20260904_110452.json
  Kicker (weight 2; current): kicker_bundesliga_lineups_20260904_105209.json
  Rotowire (weight 1; current): rotowire_bundesliga_lineups_20260904_105027.json
  Alternative starting-chance decay: 0.45
  Questionable-injury starting-chance penalty: 0.15
  Score multiplier: 9.4739
  Output: C:\kickbase project\outputs\expected_points\expected_points_20260904_104843_+0200_sofascore_overall_rating_odds_lineup_20260904_111301_+0200.csv

Team odds and expected match points

,team,provider,win_probability,draw_probability,loss_probability,expected_match_points
0,augsburg,FotMob,0.257018,0.250254,0.492728,1.021307
1,bayern,FotMob,0.836120,0.100334,0.063545,2.608696
2,bremen,FotMob,0.220646,0.237195,0.542159,0.899133
3,dortmund,FotMob,0.422303,0.250048,0.327649,1.516957
4,elversberg,FotMob,0.249598,0.243198,0.507204,0.991992
5,frankfurt,FotMob,0.492728,0.250254,0.257018,1.728439
6,freiburg,FotMob,0.480849,0.263131,0.256020,1.705678
7,gladbach,FotMob,0.507204,0.243198,0.249598,1.764811
8,hamburg,FotMob,0.357640,0.263262,0.379098,1.336181
9,hoffenheim,FotMob,0.327649,0.250048,0.422303,1.232995
10,koeln,FotMob,0.158938,0.183390,0.657673,0.660202
11,leipzig,FotMob,0.542159,0.237195,0.220646,1.863672
12,leverkusen,FotMob,0.676505,0.182136,0.141359,2.211650
13,mainz,FotMob,0.379098,0.263262,0.357640,1.400556
14,paderborn,FotMob,0.256020,0.263131,0.480849,1.031190
15,schalke,FotMob,0.063545,0.100334,0.836120,0.290970
16,stuttgart,FotMob,0.657673,0.183390,0.158938,2.156408
17,union,FotMob,0.141359,0.182136,0.676505,0.606214

Player score review (non-positive or non-exact ratings)

,name,team,rating_status,lineup_status,rating,expected_match_points,ligainsider_starting_chance,kickbase_starting_chance,kicker_starting_chance,rotowire_starting_chance,questionable_injury_penalty,starting_chance,score_multiplier,score
2,Sven Ulreich,bayern,missing_rating,not_evaluated_missing_rating,0.00,2.608696,0.000000,0.0,0.0,0.0,0.0,0.000000,9.4739,0.000000
4,Serge Gnabry,bayern,missing_rating,not_evaluated_missing_rating,0.00,2.608696,0.000000,0.0,0.0,0.0,0.0,0.000000,9.4739,0.000000
9,Jamal Musiala,bayern,exact,ligainsider:missing; kicker:missing; rotowire:...,7.10,2.608696,0.000000,0.0,0.0,0.0,0.0,0.000000,9.4739,0.000000
10,Jonas Urbig,bayern,exact,ligainsider:missing; kicker:missing; rotowire:...,6.30,2.608696,0.000000,0.0,0.0,0.0,0.0,0.000000,9.4739,0.000000
12,Tom Bischof,bayern,exact,ligainsider:missing; kicker:missing; rotowire:...,6.90,2.608696,0.000000,0.0,0.0,0.0,0.0,0.000000,9.4739,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453,Éric Dina Ebimbe,schalke,override,ligainsider:override; kicker:exact; rotowire:m...,6.20,0.290970,0.310345,0.0,1.0,0.0,0.0,0.463054,9.4739,7.914079
456,Maximilian Wöber,schalke,exact,ligainsider:missing; kicker:missing; rotowire:...,5.85,0.290970,0.000000,0.0,0.0,0.0,0.0,0.000000,9.4739,0.000000
459,Adrian Gantenbein,schalke,missing_rating,not_evaluated_missing_rating,0.00,0.290970,0.000000,0.0,0.0,0.0,0.0,0.000000,9.4739,0.000000
463,Luca Vozar,schalke,missing_rating,not_evaluated_missing_rating,0.00,0.290970,0.000000,0.0,0.0,0.0,0.0,0.000000,9.4739,0.000000
465,Johannes Simon Siebeking,schalke,missing_rating,not_evaluated_missing_rating,0.00,0.290970,0.000000,0.0,0.0,0.0,0.0,0.000000,9.4739,0.000000