# SofaScore Team Form Extractor

This is the second notebook in the team-form workflow. It reads `bundesliga_teams.json`, opens one reusable `undetected_chromedriver` Chrome instance, and retrieves up to two pages of SofaScore event history for every team.

For each team, it calculates five-match overall form and Bundesliga-only form, keeps the detailed matches used in both calculations, and orders each form from oldest to newest. Each run creates a separate, timestamped `team_form_*.json` file in `outputs/sofascore/team_form`. The execution timestamp is also retained as the JSON object's top-level key.

Run `01_extract_bundesliga_teams.ipynb` first to generate the required team input file.

In [1]:
# Resolve the project root and import authoritative data locations.
import sys
from pathlib import Path


# Handle project root for reuse in the workflow.
def _locate_project_root() -> Path:
    starts = []
    vscode_notebook = globals().get("__vsc_ipynb_file__")
    if isinstance(vscode_notebook, str) and vscode_notebook.strip():
        starts.append(Path(vscode_notebook).expanduser().resolve().parent)
    starts.append(Path.cwd().resolve())

    checked = set()
    # Process each available item while preserving the current workflow state.
    for start in starts:
        # Process each available item while preserving the current workflow state.
        for candidate in (start, *start.parents):
            if candidate in checked:
                continue
            checked.add(candidate)
            if (candidate / "project_paths.py").is_file():
                return candidate
    raise FileNotFoundError(
        "Could not locate project_paths.py. Start Jupyter from the Kickbase "
        "project root or open this notebook from within that project."
    )


# Set workflow configuration value: _PROJECT_ROOT.
_PROJECT_ROOT = _locate_project_root()
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from project_paths import (
    SOFASCORE_REFERENCE_DIR,
    SOFASCORE_TEAM_FORM_DIR,
    ensure_directory,
)

In [2]:
# 1. Imports
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# Handle expected failures with a clear, actionable message.
try:
    import pandas as pd
    import undetected_chromedriver as uc
    from bs4 import BeautifulSoup
    from IPython.display import display
    from selenium.common.exceptions import TimeoutException, WebDriverException
    from selenium.webdriver.common.by import By
    from selenium.webdriver.support import expected_conditions as EC
    from selenium.webdriver.support.ui import WebDriverWait
except ImportError as exc:
    raise ImportError(
        "Required packages are missing. Install undetected-chromedriver, "
        "selenium, beautifulsoup4, and pandas in this Jupyter kernel, "
        "then restart the kernel."
    ) from exc

from chrome_runtime import detect_chrome_major_version
CHROME_EXECUTABLE_PATH = uc.find_chrome_executable()
CHROME_MAJOR_VERSION = detect_chrome_major_version(CHROME_EXECUTABLE_PATH)

In [3]:
# 2. Parameters, Paths, and Snapshot Key
# Set workflow configuration value: HEADLESS.
HEADLESS = False
# Set workflow configuration value: PAGE_LOAD_TIMEOUT_SECONDS.
PAGE_LOAD_TIMEOUT_SECONDS = 30
# Set workflow configuration value: WAIT_TIMEOUT_SECONDS.
WAIT_TIMEOUT_SECONDS = 20
# Set workflow configuration value: MAX_PAGES.
MAX_PAGES = 1
# Set workflow configuration value: FORM_MATCH_COUNT.
FORM_MATCH_COUNT = 5
# Set workflow configuration value: BUNDESLIGA_UNIQUE_TOURNAMENT_ID.
BUNDESLIGA_UNIQUE_TOURNAMENT_ID = 35
# Set workflow configuration value: TEAM_EVENTS_URL_TEMPLATE.
TEAM_EVENTS_URL_TEMPLATE = (
    "https://www.sofascore.com/api/v1/team/{team_id}/events/last/{page}"
)

# Process each available item while preserving the current workflow state.
for setting_name, setting_value in {
    "PAGE_LOAD_TIMEOUT_SECONDS": PAGE_LOAD_TIMEOUT_SECONDS,
    "WAIT_TIMEOUT_SECONDS": WAIT_TIMEOUT_SECONDS,
    "MAX_PAGES": MAX_PAGES,
    "FORM_MATCH_COUNT": FORM_MATCH_COUNT,
}.items():
    # Validate the input before continuing with later processing.
    if not isinstance(setting_value, int) or isinstance(setting_value, bool) or setting_value < 1:
        raise ValueError(f"{setting_name} must be a positive integer.")

# Validate the input before continuing with later processing.
if FORM_MATCH_COUNT != 5:
    raise ValueError("FORM_MATCH_COUNT must remain 5 for five-match form.")

teams_path = SOFASCORE_REFERENCE_DIR / "bundesliga_teams.json"
execution_datetime = datetime.now().astimezone()
execution_timestamp = execution_datetime.isoformat(timespec="microseconds")
filename_timestamp = execution_datetime.strftime("%Y-%m-%d_%H-%M-%S_%f%z")
snapshot_output_path = ensure_directory(SOFASCORE_TEAM_FORM_DIR) / f"team_form_{filename_timestamp}.json"

print(f"Execution timestamp: {execution_timestamp}")
print(f"Team input file: {teams_path}")
print(f"Snapshot output file: {snapshot_output_path}")

Execution timestamp: 2026-10-08T15:14:18.764489+02:00
Team input file: C:\kickbase project\outputs\sofascore\reference\bundesliga_teams.json
Snapshot output file: C:\kickbase project\outputs\sofascore\team_form\team_form_2026-10-08_15-14-18_764489+0200.json

In [4]:
# 3. Load Bundesliga Teams
try:
    raw_teams = json.loads(teams_path.read_text(encoding="utf-8"))
except FileNotFoundError as exc:
    raise FileNotFoundError(
        f"Team file not found: {teams_path}. Run notebooks/01_fixtures_and_teams/03_build_bundesliga_team_reference.ipynb first."
    ) from exc
except UnicodeDecodeError as exc:
    raise ValueError(f"Team file is not valid UTF-8: {teams_path}") from exc
except json.JSONDecodeError as exc:
    raise ValueError(
        f"Team file is not valid JSON (line {exc.lineno}, column {exc.colno}): "
        f"{teams_path}"
    ) from exc
except OSError as exc:
    raise OSError(f"Could not read team file {teams_path}: {exc}") from exc

# Validate the input before continuing with later processing.
if not isinstance(raw_teams, dict):
    raise ValueError("The team JSON must be an object keyed by numeric team ID.")

teams: dict[int, dict[str, Any]] = {}
# Process each available item while preserving the current workflow state.
for team_key, team_record in raw_teams.items():
    # Validate the input before continuing with later processing.
    if not isinstance(team_record, dict):
        raise ValueError(f"Team entry {team_key!r} must be a JSON object.")

    team_id = team_record.get("team_id")
    team_name = team_record.get("team")
    # Validate the input before continuing with later processing.
    if not isinstance(team_id, int) or isinstance(team_id, bool) or team_id < 1:
        raise ValueError(f"Team entry {team_key!r} has no valid positive team_id.")
    # Validate the input before continuing with later processing.
    if str(team_id) != str(team_key):
        raise ValueError(
            f"Team key {team_key!r} does not match its team_id {team_id}."
        )
    # Validate the input before continuing with later processing.
    if not isinstance(team_name, str) or not team_name.strip():
        raise ValueError(f"Team entry {team_key!r} has no valid team name.")
    # Validate the input before continuing with later processing.
    if team_id in teams:
        raise ValueError(f"Duplicate team ID in team file: {team_id}.")

    teams[team_id] = {"team": team_name.strip()}

print(f"Loaded and validated {len(teams)} unique team(s).")

Loaded and validated 18 unique team(s).

In [5]:
# 4. Start Chrome
options = uc.ChromeOptions()
options.add_argument("--disable-gpu")
options.add_argument("--disable-dev-shm-usage")
options.add_argument("--window-size=1920,1080")
if HEADLESS:
    options.add_argument("--headless=new")

driver = None
# Handle expected failures with a clear, actionable message.
try:
    driver = uc.Chrome(options=options, use_subprocess=True, browser_executable_path=CHROME_EXECUTABLE_PATH, version_main=CHROME_MAJOR_VERSION)
    driver.set_page_load_timeout(PAGE_LOAD_TIMEOUT_SECONDS)
except Exception as exc:
    if driver is not None:
        # Handle expected failures with a clear, actionable message.
        try:
            driver.quit()
        except Exception:
            pass
        driver = None
    raise RuntimeError(
        f"Could not initialize undetected Chrome with major version "
        f"{CHROME_MAJOR_VERSION}. Adjust CHROME_MAJOR_VERSION if needed. "
        f"Original error: {exc}"
    ) from exc

print(
    f"One reusable undetected Chrome instance is ready "
    f"(major version {CHROME_MAJOR_VERSION}, headless={HEADLESS})."
)

One reusable undetected Chrome instance is ready (major version 154, headless=False).

In [6]:
# 5. SofaScore API Helper
class SofaScorePageError(Exception):
    """Raised when Chrome cannot return a usable SofaScore event page."""


# Retrieve team events page for reuse in the workflow.
def fetch_team_events_page(
    team_id: int,
    page: int,
) -> tuple[list[dict[str, Any]], bool]:
    # Validate the input before continuing with later processing.
    if driver is None:
        raise SofaScorePageError("Chrome is not initialized.")

    url = TEAM_EVENTS_URL_TEMPLATE.format(team_id=team_id, page=page)
    print(f"    Loading page {page}: {url}")
    # Handle expected failures with a clear, actionable message.
    try:
        driver.get(url)
    except TimeoutException as exc:
        raise SofaScorePageError(
            f"Timed out after {PAGE_LOAD_TIMEOUT_SECONDS} seconds loading {url}."
        ) from exc
    except WebDriverException as exc:
        raise SofaScorePageError(f"Chrome could not load {url}: {exc}") from exc

    # Handle expected failures with a clear, actionable message.
    try:
        WebDriverWait(driver, WAIT_TIMEOUT_SECONDS).until(
            EC.presence_of_element_located((By.TAG_NAME, "pre"))
        )
    except TimeoutException as exc:
        raise SofaScorePageError(
            f"No <pre> element appeared within {WAIT_TIMEOUT_SECONDS} seconds for {url}."
        ) from exc
    except WebDriverException as exc:
        raise SofaScorePageError(
            f"Chrome could not inspect the rendered response for {url}: {exc}"
        ) from exc

    soup = BeautifulSoup(driver.page_source, "html.parser")
    pre_tag = soup.find("pre")
    # Validate the input before continuing with later processing.
    if pre_tag is None:
        raise SofaScorePageError(f"Rendered page contains no <pre> element: {url}")

    response_text = pre_tag.get_text().strip()
    # Validate the input before continuing with later processing.
    if not response_text:
        raise SofaScorePageError(f"The <pre> element is empty: {url}")

    # Handle expected failures with a clear, actionable message.
    try:
        payload = json.loads(response_text)
    except json.JSONDecodeError as exc:
        raise SofaScorePageError(
            f"Invalid JSON for {url} (line {exc.lineno}, column {exc.colno})."
        ) from exc

    # Validate the input before continuing with later processing.
    if not isinstance(payload, dict):
        raise SofaScorePageError(f"SofaScore response is not a JSON object: {url}")
    events = payload.get("events")
    # Validate the input before continuing with later processing.
    if not isinstance(events, list):
        raise SofaScorePageError(
            f"SofaScore response has no valid events list: {url}"
        )

    has_next_page = payload.get("hasNextPage")
    if not isinstance(has_next_page, bool):
        print("    Warning: hasNextPage is missing or invalid; treating it as false.")
        has_next_page = False

    return events, has_next_page

In [7]:
# 6. Result Parser
def nested_get(mapping: Any, *keys: str) -> Any:
    current = mapping
    # Process each available item while preserving the current workflow state.
    for key in keys:
        if not isinstance(current, dict):
            return None
        current = current.get(key)
    return current


# Check whether number for reuse in the workflow.
def is_number(value: Any) -> bool:
    return isinstance(value, (int, float)) and not isinstance(value, bool)


# Parse and validate finished event for reuse in the workflow.
def parse_finished_event(
    event: dict[str, Any],
    team_id: int,
) -> dict[str, Any] | None:
    if not isinstance(event, dict):
        print("    Warning: skipped a non-object event.")
        return None

    event_id = event.get("id")
    if not isinstance(event_id, int) or isinstance(event_id, bool):
        print("    Warning: skipped an event with no valid numeric ID.")
        return None
    if nested_get(event, "status", "type") != "finished":
        return None

    home_team_id = nested_get(event, "homeTeam", "id")
    away_team_id = nested_get(event, "awayTeam", "id")
    if (
        not isinstance(home_team_id, int)
        or isinstance(home_team_id, bool)
        or not isinstance(away_team_id, int)
        or isinstance(away_team_id, bool)
    ):
        print(f"    Warning: skipped event {event_id}; team IDs are missing or invalid.")
        return None

    # Choose the appropriate path for the current data state.
    if team_id == home_team_id:
        analysed_team_is_home = True
    # Choose the appropriate path for the current data state.
    elif team_id == away_team_id:
        analysed_team_is_home = False
    else:
        print(
            f"    Warning: skipped event {event_id}; team ID {team_id} "
            "matches neither side."
        )
        return None

    home_score = nested_get(event, "homeScore", "normaltime")
    away_score = nested_get(event, "awayScore", "normaltime")
    if not is_number(home_score) or not is_number(away_score):
        print(
            f"    Warning: skipped event {event_id}; normal-time scores are missing."
        )
        return None

    timestamp = event.get("startTimestamp")
    if not is_number(timestamp):
        print(f"    Warning: skipped event {event_id}; startTimestamp is missing.")
        return None
    # Handle expected failures with a clear, actionable message.
    try:
        readable_date = datetime.fromtimestamp(timestamp, tz=timezone.utc).isoformat()
    except (OverflowError, OSError, ValueError) as exc:
        print(f"    Warning: skipped event {event_id}; invalid timestamp ({exc}).")
        return None

    analysed_score = home_score if analysed_team_is_home else away_score
    opponent_score = away_score if analysed_team_is_home else home_score
    # Choose the appropriate path for the current data state.
    if analysed_score > opponent_score:
        result = "W"
    # Choose the appropriate path for the current data state.
    elif analysed_score < opponent_score:
        result = "L"
    else:
        result = "D"

    return {
        "match_id": event_id,
        "date": readable_date,
        "timestamp": timestamp,
        "competition": nested_get(event, "tournament", "name"),
        "unique_tournament_id": nested_get(
            event, "tournament", "uniqueTournament", "id"
        ),
        "home_team": nested_get(event, "homeTeam", "name"),
        "home_team_id": home_team_id,
        "away_team": nested_get(event, "awayTeam", "name"),
        "away_team_id": away_team_id,
        "home_score": home_score,
        "away_score": away_score,
        "result": result,
    }

In [8]:
# 7. Team Form Function
def select_recent_matches(
    candidates: list[dict[str, Any]],
) -> tuple[list[dict[str, Any]], str]:
    latest_matches = sorted(
        candidates,
        key=lambda match: match["timestamp"],
        reverse=True,
    )[:FORM_MATCH_COUNT]
    selected_matches = sorted(
        latest_matches,
        key=lambda match: match["timestamp"],
    )
    form = "".join(match["result"] for match in selected_matches)
    return selected_matches, form


# Collect team form for reuse in the workflow.
def collect_team_form(team_id: int, team_name: str) -> dict[str, Any]:
    overall_candidates: list[dict[str, Any]] = []
    bundesliga_candidates: list[dict[str, Any]] = []
    seen_event_ids: set[int] = set()

    # Process each available item while preserving the current workflow state.
    for page in range(MAX_PAGES):
        # Handle expected failures with a clear, actionable message.
        try:
            events, has_next_page = fetch_team_events_page(team_id, page)
        except SofaScorePageError as exc:
            print(f"    Warning: stopped pagination for {team_name}: {exc}")
            break

        if not events:
            print(f"    No events returned on page {page}; history has ended.")
            break

        # Process each available item while preserving the current workflow state.
        for event in events:
            event_id = event.get("id") if isinstance(event, dict) else None
            if isinstance(event_id, int) and not isinstance(event_id, bool):
                if event_id in seen_event_ids:
                    continue
                seen_event_ids.add(event_id)

            record = parse_finished_event(event, team_id)
            if record is None:
                continue
            overall_candidates.append(record)

            if record["unique_tournament_id"] == BUNDESLIGA_UNIQUE_TOURNAMENT_ID:
                unique_tournament = nested_get(
                    event, "tournament", "uniqueTournament"
                )
                unique_name = (
                    unique_tournament.get("name")
                    if isinstance(unique_tournament, dict)
                    else None
                )
                unique_slug = (
                    unique_tournament.get("slug")
                    if isinstance(unique_tournament, dict)
                    else None
                )
                if unique_name != "Bundesliga" or unique_slug != "bundesliga":
                    print(
                        f"    Warning: event {record['match_id']} has Bundesliga ID "
                        f"{BUNDESLIGA_UNIQUE_TOURNAMENT_ID} but unexpected "
                        f"name/slug values: {unique_name!r}, {unique_slug!r}."
                    )
                bundesliga_candidates.append(record)

        if (
            len(overall_candidates) >= FORM_MATCH_COUNT
            and len(bundesliga_candidates) >= FORM_MATCH_COUNT
        ):
            break
        if not has_next_page:
            print(f"    SofaScore reports no page after page {page}.")
            break
    else:
        print(f"    Reached MAX_PAGES={MAX_PAGES} for {team_name}.")

    overall_matches, overall_form = select_recent_matches(overall_candidates)
    bundesliga_matches, bundesliga_form = select_recent_matches(
        bundesliga_candidates
    )
    if len(overall_matches) < FORM_MATCH_COUNT:
        print(
            f"    Warning: {team_name} has only {len(overall_matches)} valid "
            f"overall match(es); expected {FORM_MATCH_COUNT}."
        )
    if len(bundesliga_matches) < FORM_MATCH_COUNT:
        print(
            f"    Warning: {team_name} has only {len(bundesliga_matches)} valid "
            f"Bundesliga match(es); expected {FORM_MATCH_COUNT}."
        )

    return {
        "team": team_name,
        "overall_form": overall_form,
        "bundesliga_form": bundesliga_form,
        "overall_matches": overall_matches,
        "bundesliga_matches": bundesliga_matches,
    }

In [9]:
# 8. Process All Teams
form_results: dict[int, dict[str, Any]] = {}
total_teams = len(teams)

# Process each available item while preserving the current workflow state.
for team_number, (team_id, team_info) in enumerate(teams.items(), start=1):
    team_name = team_info["team"]
    print(f"[{team_number}/{total_teams}] {team_name} (team_id={team_id})")
    # Handle expected failures with a clear, actionable message.
    try:
        form_results[team_id] = collect_team_form(team_id, team_name)
    except Exception as exc:
        print(
            f"    Unexpected team error: {type(exc).__name__}: {exc}. "
            "Continuing with the remaining teams."
        )
        form_results[team_id] = {
            "team": team_name,
            "overall_form": "",
            "bundesliga_form": "",
            "overall_matches": [],
            "bundesliga_matches": [],
        }

print("Finished processing all teams.")

[1/18] FC Bayern München (team_id=2672)
    Loading page 0: https://www.sofascore.com/api/v1/team/2672/events/last/0
[2/18] VfB Stuttgart (team_id=2677)
    Loading page 0: https://www.sofascore.com/api/v1/team/2677/events/last/0
[3/18] 1. FC Köln (team_id=2671)
    Loading page 0: https://www.sofascore.com/api/v1/team/2671/events/last/0
[4/18] TSG Hoffenheim (team_id=2569)
    Loading page 0: https://www.sofascore.com/api/v1/team/2569/events/last/0
[5/18] 1. FC Union Berlin (team_id=2547)
    Loading page 0: https://www.sofascore.com/api/v1/team/2547/events/last/0
[6/18] Eintracht Frankfurt (team_id=2674)
    Loading page 0: https://www.sofascore.com/api/v1/team/2674/events/last/0
[7/18] 1. FSV Mainz 05 (team_id=2556)
    Loading page 0: https://www.sofascore.com/api/v1/team/2556/events/last/0
[8/18] SC Paderborn 07 (team_id=2561)
    Loading page 0: https://www.sofascore.com/api/v1/team/2561/events/last/0
[9/18] RB Leipzig (team_id=36360)
    Loading page 0: https://www.sofascore.com/api/v1/team/36360/events/last/0
[10/18] Borussia M'gladbach (team_id=2527)
    Loading page 0: https://www.sofascore.com/api/v1/team/2527/events/last/0
[11/18] SV 07 Elversberg (team_id=2598)
    Loading page 0: https://www.sofascore.com/api/v1/team/2598/events/last/0
    Reached MAX_PAGES=1 for SV 07 Elversberg.
    Warning: SV 07 Elversberg has only 4 valid Bundesliga match(es); expected 5.
[12/18] Bayer 04 Leverkusen (team_id=2681)
    Loading page 0: https://www.sofascore.com/api/v1/team/2681/events/last/0
[13/18] Borussia Dortmund (team_id=2673)
    Loading page 0: https://www.sofascore.com/api/v1/team/2673/events/last/0
[14/18] Hamburger SV (team_id=2676)
    Loading page 0: https://www.sofascore.com/api/v1/team/2676/events/last/0
[15/18] SC Freiburg (team_id=2538)
    Loading page 0: https://www.sofascore.com/api/v1/team/2538/events/last/0
[16/18] SV Werder Bremen (team_id=2534)
    Loading page 0: https://www.sofascore.com/api/v1/team/2534/events/last/0
[17/18] FC Augsburg (team_id=2600)
    Loading page 0: https://www.sofascore.com/api/v1/team/2600/events/last/0
[18/18] FC Schalke 04 (team_id=2530)
    Loading page 0: https://www.sofascore.com/api/v1/team/2530/events/last/0
    Reached MAX_PAGES=1 for FC Schalke 04.
    Warning: FC Schalke 04 has only 4 valid Bundesliga match(es); expected 5.
Finished processing all teams.

In [10]:
# 9. Final Form DataFrame
summary_rows = [
    {
        "team_id": team_id,
        "team": result["team"],
        "overall_form": result["overall_form"],
        "overall_match_count": len(result["overall_matches"]),
        "bundesliga_form": result["bundesliga_form"],
        "bundesliga_match_count": len(result["bundesliga_matches"]),
    }
    for team_id, result in form_results.items()
]
form_summary_df = pd.DataFrame(summary_rows)
display(form_summary_df)

,team_id,team,overall_form,overall_match_count,bundesliga_form,bundesliga_match_count
0,2672,FC Bayern München,WDWWW,5,WWDWW,5
1,2677,VfB Stuttgart,WLLWW,5,DLWLL,5
2,2671,1. FC Köln,WLDLD,5,LWLDL,5
3,2569,TSG Hoffenheim,LLWLL,5,LLLWL,5
4,2547,1. FC Union Berlin,DLLLW,5,WDLLL,5
5,2674,Eintracht Frankfurt,DLWDW,5,DDLWD,5
6,2556,1. FSV Mainz 05,DWLWW,5,WDWLW,5
7,2561,SC Paderborn 07,DLLWW,5,DDLLW,5
8,36360,RB Leipzig,WLLWL,5,LWLWL,5
9,2527,Borussia M'gladbach,LLLWD,5,WLLLL,5
10,2598,SV 07 Elversberg,WWWLD,5,WWLD,4
11,2681,Bayer 04 Leverkusen,LWDWW,5,DLWDW,5
12,2673,Borussia Dortmund,WWWWW,5,WWWWW,5
13,2676,Hamburger SV,LLLWW,5,DLLLW,5
14,2538,SC Freiburg,WWWDW,5,WWWWD,5
15,2534,SV Werder Bremen,LWDWL,5,LLWDW,5
16,2600,FC Augsburg,WWDLD,5,LWWDL,5
17,2530,FC Schalke 04,DWDWW,5,LDWD,4

In [11]:
# 10. Detailed Histories
history_columns = [
    "date", "competition", "home_team", "away_team",
    "home_score", "away_score", "result", "match_id",
    "timestamp", "unique_tournament_id",
]

# Process each available item while preserving the current workflow state.
for team_id, result in form_results.items():
    print(f"\n{result['team']} (team_id={team_id})")
    print(f"Overall form: {result['overall_form'] or '(no valid matches)'}")
    # Choose the appropriate path for the current data state.
    if result["overall_matches"]:
        display(pd.DataFrame(result["overall_matches"]).reindex(columns=history_columns))
    else:
        print("No valid overall matches were collected.")

    print(f"Bundesliga form: {result['bundesliga_form'] or '(no valid matches)'}")
    # Choose the appropriate path for the current data state.
    if result["bundesliga_matches"]:
        display(
            pd.DataFrame(result["bundesliga_matches"]).reindex(
                columns=history_columns
            )
        )
    else:
        print("No valid Bundesliga matches were collected.")

FC Bayern München (team_id=2672)
Overall form: WDWWW

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-09-02T18:45:00+00:00,DFB Pokal,VfL Osnabrück,FC Bayern München,1,4,W,16287047,1788374700,217
1,2026-09-05T16:30:00+00:00,Bundesliga,FC Schalke 04,FC Bayern München,0,0,D,16434032,1788625800,35
2,2026-09-10T19:00:00+00:00,UEFA Champions League,FC Bayern München,Bodø/Glimt,5,0,W,16938858,1789066800,7
3,2026-09-13T15:30:00+00:00,Bundesliga,SV 07 Elversberg,FC Bayern München,1,2,W,16434041,1789313400,35
4,2026-09-18T18:30:00+00:00,Bundesliga,FC Bayern München,1. FC Union Berlin,7,0,W,16434038,1789756200,35

Bundesliga form: WWDWW

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-05-16T13:30:00+00:00,Bundesliga,FC Bayern München,1. FC Köln,5,1,W,14065556,1778938200,35
1,2026-08-28T18:30:00+00:00,Bundesliga,FC Bayern München,VfB Stuttgart,5,1,W,16434087,1787941800,35
2,2026-09-05T16:30:00+00:00,Bundesliga,FC Schalke 04,FC Bayern München,0,0,D,16434032,1788625800,35
3,2026-09-13T15:30:00+00:00,Bundesliga,SV 07 Elversberg,FC Bayern München,1,2,W,16434041,1789313400,35
4,2026-09-18T18:30:00+00:00,Bundesliga,FC Bayern München,1. FC Union Berlin,7,0,W,16434038,1789756200,35

VfB Stuttgart (team_id=2677)
Overall form: WLLWW

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-09-09T16:45:00+00:00,UEFA Champions League,VfB Stuttgart,Viking FK,3,1,W,16939028,1788972300,7
1,2026-09-12T13:30:00+00:00,Bundesliga,TSG Hoffenheim,VfB Stuttgart,2,1,L,16434035,1789219800,35
2,2026-09-19T16:30:00+00:00,Bundesliga,VfB Stuttgart,Borussia Dortmund,0,1,L,16434034,1789835400,35
3,2026-09-25T14:30:00+00:00,Club Friendly Games,VfB Stuttgart,1. FC Heidenheim,3,0,W,17157914,1790346600,853
4,2026-10-01T15:30:00+00:00,Club Friendly Games,VfB Stuttgart,SpVgg Greuther Fürth,5,0,W,17212342,1790868600,853

Bundesliga form: DLWLL

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-05-16T13:30:00+00:00,Bundesliga,Eintracht Frankfurt,VfB Stuttgart,2,2,D,14065560,1778938200,35
1,2026-08-28T18:30:00+00:00,Bundesliga,FC Bayern München,VfB Stuttgart,5,1,L,16434087,1787941800,35
2,2026-09-04T18:30:00+00:00,Bundesliga,VfB Stuttgart,1. FC Köln,4,1,W,16434036,1788546600,35
3,2026-09-12T13:30:00+00:00,Bundesliga,TSG Hoffenheim,VfB Stuttgart,2,1,L,16434035,1789219800,35
4,2026-09-19T16:30:00+00:00,Bundesliga,VfB Stuttgart,Borussia Dortmund,0,1,L,16434034,1789835400,35

1. FC Köln (team_id=2671)
Overall form: WLDLD

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-08-29T13:30:00+00:00,Bundesliga,1. FC Köln,TSG Hoffenheim,3,2,W,16434022,1788010200,35
1,2026-09-04T18:30:00+00:00,Bundesliga,VfB Stuttgart,1. FC Köln,4,1,L,16434036,1788546600,35
2,2026-09-12T16:30:00+00:00,Bundesliga,1. FC Köln,SV Werder Bremen,1,1,D,16434027,1789230600,35
3,2026-09-19T13:30:00+00:00,Bundesliga,Hamburger SV,1. FC Köln,2,1,L,16434048,1789824600,35
4,2026-10-03T12:00:00+00:00,Club Friendly Games,FC Viktoria Köln,1. FC Köln,2,2,D,17213101,1791028800,853

Bundesliga form: LWLDL

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-05-16T13:30:00+00:00,Bundesliga,FC Bayern München,1. FC Köln,5,1,L,14065556,1778938200,35
1,2026-08-29T13:30:00+00:00,Bundesliga,1. FC Köln,TSG Hoffenheim,3,2,W,16434022,1788010200,35
2,2026-09-04T18:30:00+00:00,Bundesliga,VfB Stuttgart,1. FC Köln,4,1,L,16434036,1788546600,35
3,2026-09-12T16:30:00+00:00,Bundesliga,1. FC Köln,SV Werder Bremen,1,1,D,16434027,1789230600,35
4,2026-09-19T13:30:00+00:00,Bundesliga,Hamburger SV,1. FC Köln,2,1,L,16434048,1789824600,35

TSG Hoffenheim (team_id=2569)
Overall form: LLWLL

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-08-29T13:30:00+00:00,Bundesliga,1. FC Köln,TSG Hoffenheim,3,2,L,16434022,1788010200,35
1,2026-09-05T13:30:00+00:00,Bundesliga,TSG Hoffenheim,Borussia Dortmund,2,3,L,16434019,1788615000,35
2,2026-09-12T13:30:00+00:00,Bundesliga,TSG Hoffenheim,VfB Stuttgart,2,1,W,16434035,1789219800,35
3,2026-09-17T16:45:00+00:00,UEFA Europa League,OFI Crete,TSG Hoffenheim,2,0,L,16945561,1789663500,679
4,2026-09-20T17:30:00+00:00,Bundesliga,SC Paderborn 07,TSG Hoffenheim,3,1,L,16434052,1789925400,35

Bundesliga form: LLLWL

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-05-16T13:30:00+00:00,Bundesliga,Borussia M'gladbach,TSG Hoffenheim,4,0,L,14065559,1778938200,35
1,2026-08-29T13:30:00+00:00,Bundesliga,1. FC Köln,TSG Hoffenheim,3,2,L,16434022,1788010200,35
2,2026-09-05T13:30:00+00:00,Bundesliga,TSG Hoffenheim,Borussia Dortmund,2,3,L,16434019,1788615000,35
3,2026-09-12T13:30:00+00:00,Bundesliga,TSG Hoffenheim,VfB Stuttgart,2,1,W,16434035,1789219800,35
4,2026-09-20T17:30:00+00:00,Bundesliga,SC Paderborn 07,TSG Hoffenheim,3,1,L,16434052,1789925400,35

1. FC Union Berlin (team_id=2547)
Overall form: DLLLW

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-08-29T13:30:00+00:00,Bundesliga,1. FC Union Berlin,Eintracht Frankfurt,3,3,D,16434026,1788010200,35
1,2026-09-05T13:30:00+00:00,Bundesliga,Bayer 04 Leverkusen,1. FC Union Berlin,4,0,L,16434042,1788615000,35
2,2026-09-11T18:30:00+00:00,Bundesliga,1. FC Union Berlin,FC Schalke 04,1,3,L,16434045,1789151400,35
3,2026-09-18T18:30:00+00:00,Bundesliga,FC Bayern München,1. FC Union Berlin,7,0,L,16434038,1789756200,35
4,2026-09-26T17:15:00+00:00,Club Friendly Games,HNK Rijeka,1. FC Union Berlin,0,1,W,17184536,1790442900,853

Bundesliga form: WDLLL

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-05-16T13:30:00+00:00,Bundesliga,1. FC Union Berlin,FC Augsburg,4,0,W,14065558,1778938200,35
1,2026-08-29T13:30:00+00:00,Bundesliga,1. FC Union Berlin,Eintracht Frankfurt,3,3,D,16434026,1788010200,35
2,2026-09-05T13:30:00+00:00,Bundesliga,Bayer 04 Leverkusen,1. FC Union Berlin,4,0,L,16434042,1788615000,35
3,2026-09-11T18:30:00+00:00,Bundesliga,1. FC Union Berlin,FC Schalke 04,1,3,L,16434045,1789151400,35
4,2026-09-18T18:30:00+00:00,Bundesliga,FC Bayern München,1. FC Union Berlin,7,0,L,16434038,1789756200,35

Eintracht Frankfurt (team_id=2674)
Overall form: DLWDW

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-08-29T13:30:00+00:00,Bundesliga,1. FC Union Berlin,Eintracht Frankfurt,3,3,D,16434026,1788010200,35
1,2026-09-06T15:30:00+00:00,Bundesliga,Eintracht Frankfurt,FC Augsburg,1,4,L,16434021,1788708600,35
2,2026-09-12T13:30:00+00:00,Bundesliga,1. FSV Mainz 05,Eintracht Frankfurt,1,3,W,16434018,1789219800,35
3,2026-09-19T13:30:00+00:00,Bundesliga,Eintracht Frankfurt,SC Freiburg,2,2,D,16434046,1789824600,35
4,2026-10-02T13:30:00+00:00,Club Friendly Games,Eintracht Frankfurt,Eintracht Braunschweig,4,0,W,17212996,1790947800,853

Bundesliga form: DDLWD

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-05-16T13:30:00+00:00,Bundesliga,Eintracht Frankfurt,VfB Stuttgart,2,2,D,14065560,1778938200,35
1,2026-08-29T13:30:00+00:00,Bundesliga,1. FC Union Berlin,Eintracht Frankfurt,3,3,D,16434026,1788010200,35
2,2026-09-06T15:30:00+00:00,Bundesliga,Eintracht Frankfurt,FC Augsburg,1,4,L,16434021,1788708600,35
3,2026-09-12T13:30:00+00:00,Bundesliga,1. FSV Mainz 05,Eintracht Frankfurt,1,3,W,16434018,1789219800,35
4,2026-09-19T13:30:00+00:00,Bundesliga,Eintracht Frankfurt,SC Freiburg,2,2,D,16434046,1789824600,35

1. FSV Mainz 05 (team_id=2556)
Overall form: DWLWW

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-08-29T13:30:00+00:00,Bundesliga,1. FSV Mainz 05,SC Paderborn 07,0,0,D,16434044,1788010200,35
1,2026-09-06T13:30:00+00:00,Bundesliga,Hamburger SV,1. FSV Mainz 05,0,5,W,16434030,1788701400,35
2,2026-09-12T13:30:00+00:00,Bundesliga,1. FSV Mainz 05,Eintracht Frankfurt,1,3,L,16434018,1789219800,35
3,2026-09-19T13:30:00+00:00,Bundesliga,Borussia M'gladbach,1. FSV Mainz 05,3,4,W,16434047,1789824600,35
4,2026-10-03T11:00:00+00:00,Club Friendly Games,SV Waldhof Mannheim,1. FSV Mainz 05,0,3,W,17213068,1791025200,853

Bundesliga form: WDWLW

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-05-16T13:30:00+00:00,Bundesliga,1. FC Heidenheim,1. FSV Mainz 05,0,2,W,14065562,1778938200,35
1,2026-08-29T13:30:00+00:00,Bundesliga,1. FSV Mainz 05,SC Paderborn 07,0,0,D,16434044,1788010200,35
2,2026-09-06T13:30:00+00:00,Bundesliga,Hamburger SV,1. FSV Mainz 05,0,5,W,16434030,1788701400,35
3,2026-09-12T13:30:00+00:00,Bundesliga,1. FSV Mainz 05,Eintracht Frankfurt,1,3,L,16434018,1789219800,35
4,2026-09-19T13:30:00+00:00,Bundesliga,Borussia M'gladbach,1. FSV Mainz 05,3,4,W,16434047,1789824600,35

SC Paderborn 07 (team_id=2561)
Overall form: DLLWW

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-08-29T13:30:00+00:00,Bundesliga,1. FSV Mainz 05,SC Paderborn 07,0,0,D,16434044,1788010200,35
1,2026-09-05T13:30:00+00:00,Bundesliga,SC Paderborn 07,SC Freiburg,0,1,L,16434024,1788615000,35
2,2026-09-12T13:30:00+00:00,Bundesliga,Borussia Dortmund,SC Paderborn 07,3,0,L,16434037,1789219800,35
3,2026-09-20T17:30:00+00:00,Bundesliga,SC Paderborn 07,TSG Hoffenheim,3,1,W,16434052,1789925400,35
4,2026-09-30T23:30:00+00:00,Club Friendly Games,DC United,SC Paderborn 07,0,1,W,17059733,1790811000,853

Bundesliga form: DDLLW

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-05-25T18:30:00+00:00,"Bundesliga, Relegation/Promotion Playoffs",SC Paderborn 07,VfL Wolfsburg,1,1,D,16163444,1779733800,35
1,2026-08-29T13:30:00+00:00,Bundesliga,1. FSV Mainz 05,SC Paderborn 07,0,0,D,16434044,1788010200,35
2,2026-09-05T13:30:00+00:00,Bundesliga,SC Paderborn 07,SC Freiburg,0,1,L,16434024,1788615000,35
3,2026-09-12T13:30:00+00:00,Bundesliga,Borussia Dortmund,SC Paderborn 07,3,0,L,16434037,1789219800,35
4,2026-09-20T17:30:00+00:00,Bundesliga,SC Paderborn 07,TSG Hoffenheim,3,1,W,16434052,1789925400,35

RB Leipzig (team_id=36360)
Overall form: WLLWL

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-08-29T13:30:00+00:00,Bundesliga,RB Leipzig,Borussia M'gladbach,3,0,W,16434023,1788010200,35
1,2026-09-05T13:30:00+00:00,Bundesliga,SV Werder Bremen,RB Leipzig,3,1,L,16434101,1788615000,35
2,2026-09-10T19:00:00+00:00,UEFA Champions League,Como,RB Leipzig,4,1,L,16939034,1789066800,7
3,2026-09-13T13:30:00+00:00,Bundesliga,RB Leipzig,Hamburger SV,5,0,W,16434043,1789306200,35
4,2026-09-20T13:30:00+00:00,Bundesliga,Bayer 04 Leverkusen,RB Leipzig,2,0,L,16434033,1789911000,35

Bundesliga form: LWLWL

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-05-16T13:30:00+00:00,Bundesliga,SC Freiburg,RB Leipzig,4,1,L,14065555,1778938200,35
1,2026-08-29T13:30:00+00:00,Bundesliga,RB Leipzig,Borussia M'gladbach,3,0,W,16434023,1788010200,35
2,2026-09-05T13:30:00+00:00,Bundesliga,SV Werder Bremen,RB Leipzig,3,1,L,16434101,1788615000,35
3,2026-09-13T13:30:00+00:00,Bundesliga,RB Leipzig,Hamburger SV,5,0,W,16434043,1789306200,35
4,2026-09-20T13:30:00+00:00,Bundesliga,Bayer 04 Leverkusen,RB Leipzig,2,0,L,16434033,1789911000,35

Borussia M'gladbach (team_id=2527)
Overall form: LLLWD

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-09-05T13:30:00+00:00,Bundesliga,Borussia M'gladbach,SV 07 Elversberg,3,4,L,16434028,1788615000,35
1,2026-09-12T13:30:00+00:00,Bundesliga,SC Freiburg,Borussia M'gladbach,5,0,L,16434040,1789219800,35
2,2026-09-19T13:30:00+00:00,Bundesliga,Borussia M'gladbach,1. FSV Mainz 05,3,4,L,16434047,1789824600,35
3,2026-09-24T16:30:00+00:00,Club Friendly Games,SF Siegen,Borussia M'gladbach,0,3,W,17156906,1790267400,853
4,2026-10-03T13:30:00+00:00,Club Friendly Games,FC St. Pauli,Borussia M'gladbach,1,1,D,17226830,1791034200,853

Bundesliga form: WLLLL

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-05-16T13:30:00+00:00,Bundesliga,Borussia M'gladbach,TSG Hoffenheim,4,0,W,14065559,1778938200,35
1,2026-08-29T13:30:00+00:00,Bundesliga,RB Leipzig,Borussia M'gladbach,3,0,L,16434023,1788010200,35
2,2026-09-05T13:30:00+00:00,Bundesliga,Borussia M'gladbach,SV 07 Elversberg,3,4,L,16434028,1788615000,35
3,2026-09-12T13:30:00+00:00,Bundesliga,SC Freiburg,Borussia M'gladbach,5,0,L,16434040,1789219800,35
4,2026-09-19T13:30:00+00:00,Bundesliga,Borussia M'gladbach,1. FSV Mainz 05,3,4,L,16434047,1789824600,35

SV 07 Elversberg (team_id=2598)
Overall form: WWWLD

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-08-22T13:30:00+00:00,DFB Pokal,MSV Duisburg,SV 07 Elversberg,1,3,W,16287051,1787405400,217
1,2026-08-29T13:30:00+00:00,Bundesliga,SV 07 Elversberg,Bayer 04 Leverkusen,3,2,W,16434020,1788010200,35
2,2026-09-05T13:30:00+00:00,Bundesliga,Borussia M'gladbach,SV 07 Elversberg,3,4,W,16434028,1788615000,35
3,2026-09-13T15:30:00+00:00,Bundesliga,SV 07 Elversberg,FC Bayern München,1,2,L,16434041,1789313400,35
4,2026-09-20T15:30:00+00:00,Bundesliga,FC Schalke 04,SV 07 Elversberg,0,0,D,16434051,1789918200,35

Bundesliga form: WWLD

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-08-29T13:30:00+00:00,Bundesliga,SV 07 Elversberg,Bayer 04 Leverkusen,3,2,W,16434020,1788010200,35
1,2026-09-05T13:30:00+00:00,Bundesliga,Borussia M'gladbach,SV 07 Elversberg,3,4,W,16434028,1788615000,35
2,2026-09-13T15:30:00+00:00,Bundesliga,SV 07 Elversberg,FC Bayern München,1,2,L,16434041,1789313400,35
3,2026-09-20T15:30:00+00:00,Bundesliga,FC Schalke 04,SV 07 Elversberg,0,0,D,16434051,1789918200,35

Bayer 04 Leverkusen (team_id=2681)
Overall form: LWDWW

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-08-29T13:30:00+00:00,Bundesliga,SV 07 Elversberg,Bayer 04 Leverkusen,3,2,L,16434020,1788010200,35
1,2026-09-05T13:30:00+00:00,Bundesliga,Bayer 04 Leverkusen,1. FC Union Berlin,4,0,W,16434042,1788615000,35
2,2026-09-12T13:30:00+00:00,Bundesliga,FC Augsburg,Bayer 04 Leverkusen,2,2,D,16434031,1789219800,35
3,2026-09-16T19:00:00+00:00,UEFA Europa League,Bayer 04 Leverkusen,NK Celje,2,0,W,16943945,1789585200,679
4,2026-09-20T13:30:00+00:00,Bundesliga,Bayer 04 Leverkusen,RB Leipzig,2,0,W,16434033,1789911000,35

Bundesliga form: DLWDW

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-05-16T13:30:00+00:00,Bundesliga,Bayer 04 Leverkusen,Hamburger SV,1,1,D,14065557,1778938200,35
1,2026-08-29T13:30:00+00:00,Bundesliga,SV 07 Elversberg,Bayer 04 Leverkusen,3,2,L,16434020,1788010200,35
2,2026-09-05T13:30:00+00:00,Bundesliga,Bayer 04 Leverkusen,1. FC Union Berlin,4,0,W,16434042,1788615000,35
3,2026-09-12T13:30:00+00:00,Bundesliga,FC Augsburg,Bayer 04 Leverkusen,2,2,D,16434031,1789219800,35
4,2026-09-20T13:30:00+00:00,Bundesliga,Bayer 04 Leverkusen,RB Leipzig,2,0,W,16434033,1789911000,35

Borussia Dortmund (team_id=2673)
Overall form: WWWWW

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-09-01T18:45:00+00:00,DFB Pokal,Hamburg-Eimsbütteler Ballspiel Club 1911,Borussia Dortmund,0,5,W,16287049,1788288300,217
1,2026-09-05T13:30:00+00:00,Bundesliga,TSG Hoffenheim,Borussia Dortmund,2,3,W,16434019,1788615000,35
2,2026-09-08T19:00:00+00:00,UEFA Champions League,Borussia Dortmund,Villarreal,3,2,W,16938848,1788894000,7
3,2026-09-12T13:30:00+00:00,Bundesliga,Borussia Dortmund,SC Paderborn 07,3,0,W,16434037,1789219800,35
4,2026-09-19T16:30:00+00:00,Bundesliga,VfB Stuttgart,Borussia Dortmund,0,1,W,16434034,1789835400,35

Bundesliga form: WWWWW

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-05-16T13:30:00+00:00,Bundesliga,SV Werder Bremen,Borussia Dortmund,0,2,W,14065561,1778938200,35
1,2026-08-29T16:30:00+00:00,Bundesliga,Borussia Dortmund,Hamburger SV,2,0,W,16434025,1788021000,35
2,2026-09-05T13:30:00+00:00,Bundesliga,TSG Hoffenheim,Borussia Dortmund,2,3,W,16434019,1788615000,35
3,2026-09-12T13:30:00+00:00,Bundesliga,Borussia Dortmund,SC Paderborn 07,3,0,W,16434037,1789219800,35
4,2026-09-19T16:30:00+00:00,Bundesliga,VfB Stuttgart,Borussia Dortmund,0,1,W,16434034,1789835400,35

Hamburger SV (team_id=2676)
Overall form: LLLWW

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-08-29T16:30:00+00:00,Bundesliga,Borussia Dortmund,Hamburger SV,2,0,L,16434025,1788021000,35
1,2026-09-06T13:30:00+00:00,Bundesliga,Hamburger SV,1. FSV Mainz 05,0,5,L,16434030,1788701400,35
2,2026-09-13T13:30:00+00:00,Bundesliga,RB Leipzig,Hamburger SV,5,0,L,16434043,1789306200,35
3,2026-09-19T13:30:00+00:00,Bundesliga,Hamburger SV,1. FC Köln,2,1,W,16434048,1789824600,35
4,2026-10-04T13:30:00+00:00,Club Friendly Games,Hamburger SV,FC København,2,0,W,17213134,1791120600,853

Bundesliga form: DLLLW

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-05-16T13:30:00+00:00,Bundesliga,Bayer 04 Leverkusen,Hamburger SV,1,1,D,14065557,1778938200,35
1,2026-08-29T16:30:00+00:00,Bundesliga,Borussia Dortmund,Hamburger SV,2,0,L,16434025,1788021000,35
2,2026-09-06T13:30:00+00:00,Bundesliga,Hamburger SV,1. FSV Mainz 05,0,5,L,16434030,1788701400,35
3,2026-09-13T13:30:00+00:00,Bundesliga,RB Leipzig,Hamburger SV,5,0,L,16434043,1789306200,35
4,2026-09-19T13:30:00+00:00,Bundesliga,Hamburger SV,1. FC Köln,2,1,W,16434048,1789824600,35

SC Freiburg (team_id=2538)
Overall form: WWWDW

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-08-30T13:30:00+00:00,Bundesliga,SC Freiburg,SV Werder Bremen,4,1,W,16434029,1788096600,35
1,2026-09-05T13:30:00+00:00,Bundesliga,SC Paderborn 07,SC Freiburg,0,1,W,16434024,1788615000,35
2,2026-09-12T13:30:00+00:00,Bundesliga,SC Freiburg,Borussia M'gladbach,5,0,W,16434040,1789219800,35
3,2026-09-19T13:30:00+00:00,Bundesliga,Eintracht Frankfurt,SC Freiburg,2,2,D,16434046,1789824600,35
4,2026-10-03T11:00:00+00:00,Club Friendly Games,SC Freiburg,FC Luzern,4,2,W,17213064,1791025200,853

Bundesliga form: WWWWD

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-05-16T13:30:00+00:00,Bundesliga,SC Freiburg,RB Leipzig,4,1,W,14065555,1778938200,35
1,2026-08-30T13:30:00+00:00,Bundesliga,SC Freiburg,SV Werder Bremen,4,1,W,16434029,1788096600,35
2,2026-09-05T13:30:00+00:00,Bundesliga,SC Paderborn 07,SC Freiburg,0,1,W,16434024,1788615000,35
3,2026-09-12T13:30:00+00:00,Bundesliga,SC Freiburg,Borussia M'gladbach,5,0,W,16434040,1789219800,35
4,2026-09-19T13:30:00+00:00,Bundesliga,Eintracht Frankfurt,SC Freiburg,2,2,D,16434046,1789824600,35

SV Werder Bremen (team_id=2534)
Overall form: LWDWL

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-08-30T13:30:00+00:00,Bundesliga,SC Freiburg,SV Werder Bremen,4,1,L,16434029,1788096600,35
1,2026-09-05T13:30:00+00:00,Bundesliga,SV Werder Bremen,RB Leipzig,3,1,W,16434101,1788615000,35
2,2026-09-12T16:30:00+00:00,Bundesliga,1. FC Köln,SV Werder Bremen,1,1,D,16434027,1789230600,35
3,2026-09-19T13:30:00+00:00,Bundesliga,SV Werder Bremen,FC Augsburg,3,2,W,16434049,1789824600,35
4,2026-10-02T11:00:00+00:00,Club Friendly Games,FC Twente,SV Werder Bremen,7,0,L,17237867,1790938800,853

Bundesliga form: LLWDW

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-05-16T13:30:00+00:00,Bundesliga,SV Werder Bremen,Borussia Dortmund,0,2,L,14065561,1778938200,35
1,2026-08-30T13:30:00+00:00,Bundesliga,SC Freiburg,SV Werder Bremen,4,1,L,16434029,1788096600,35
2,2026-09-05T13:30:00+00:00,Bundesliga,SV Werder Bremen,RB Leipzig,3,1,W,16434101,1788615000,35
3,2026-09-12T16:30:00+00:00,Bundesliga,1. FC Köln,SV Werder Bremen,1,1,D,16434027,1789230600,35
4,2026-09-19T13:30:00+00:00,Bundesliga,SV Werder Bremen,FC Augsburg,3,2,W,16434049,1789824600,35

FC Augsburg (team_id=2600)
Overall form: WWDLD

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-08-30T15:30:00+00:00,Bundesliga,FC Augsburg,FC Schalke 04,3,0,W,16434039,1788103800,35
1,2026-09-06T15:30:00+00:00,Bundesliga,Eintracht Frankfurt,FC Augsburg,1,4,W,16434021,1788708600,35
2,2026-09-12T13:30:00+00:00,Bundesliga,FC Augsburg,Bayer 04 Leverkusen,2,2,D,16434031,1789219800,35
3,2026-09-19T13:30:00+00:00,Bundesliga,SV Werder Bremen,FC Augsburg,3,2,L,16434049,1789824600,35
4,2026-10-02T11:00:00+00:00,Club Friendly Games,FC Augsburg,Hertha BSC,2,2,D,17226505,1790938800,853

Bundesliga form: LWWDL

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-05-16T13:30:00+00:00,Bundesliga,1. FC Union Berlin,FC Augsburg,4,0,L,14065558,1778938200,35
1,2026-08-30T15:30:00+00:00,Bundesliga,FC Augsburg,FC Schalke 04,3,0,W,16434039,1788103800,35
2,2026-09-06T15:30:00+00:00,Bundesliga,Eintracht Frankfurt,FC Augsburg,1,4,W,16434021,1788708600,35
3,2026-09-12T13:30:00+00:00,Bundesliga,FC Augsburg,Bayer 04 Leverkusen,2,2,D,16434031,1789219800,35
4,2026-09-19T13:30:00+00:00,Bundesliga,SV Werder Bremen,FC Augsburg,3,2,L,16434049,1789824600,35

FC Schalke 04 (team_id=2530)
Overall form: DWDWW

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-09-05T16:30:00+00:00,Bundesliga,FC Schalke 04,FC Bayern München,0,0,D,16434032,1788625800,35
1,2026-09-11T18:30:00+00:00,Bundesliga,1. FC Union Berlin,FC Schalke 04,1,3,W,16434045,1789151400,35
2,2026-09-20T15:30:00+00:00,Bundesliga,FC Schalke 04,SV 07 Elversberg,0,0,D,16434051,1789918200,35
3,2026-09-24T17:00:00+00:00,Club Friendly Games,SC Rot-Weiß Oberhausen,FC Schalke 04,2,5,W,17156907,1790269200,853
4,2026-10-03T13:00:00+00:00,Club Friendly Games,SC Austria Lustenau,FC Schalke 04,0,1,W,17213102,1791032400,853

Bundesliga form: LDWD

,date,competition,home_team,away_team,home_score,away_score,result,match_id,timestamp,unique_tournament_id
0,2026-08-30T15:30:00+00:00,Bundesliga,FC Augsburg,FC Schalke 04,3,0,L,16434039,1788103800,35
1,2026-09-05T16:30:00+00:00,Bundesliga,FC Schalke 04,FC Bayern München,0,0,D,16434032,1788625800,35
2,2026-09-11T18:30:00+00:00,Bundesliga,1. FC Union Berlin,FC Schalke 04,1,3,W,16434045,1789151400,35
3,2026-09-20T15:30:00+00:00,Bundesliga,FC Schalke 04,SV 07 Elversberg,0,0,D,16434051,1789918200,35

In [12]:
# 11. Save Timestamp-Keyed JSON Snapshot
snapshot_teams = {
    str(team_id): {
        "team": result["team"],
        "overall_form": result["overall_form"],
        "bundesliga_form": result["bundesliga_form"],
        "overall_matches": result["overall_matches"],
        "bundesliga_matches": result["bundesliga_matches"],
    }
    for team_id, result in form_results.items()
}
current_snapshot = {execution_timestamp: snapshot_teams}

snapshot_json = json.dumps(current_snapshot, ensure_ascii=False, indent=2)
# Handle expected failures with a clear, actionable message.
try:
    snapshot_output_path.write_text(snapshot_json + "\n", encoding="utf-8")
except OSError as exc:
    raise OSError(
        f"Could not save snapshot file {snapshot_output_path}: {exc}"
    ) from exc

print(snapshot_json)

{
  "2026-10-08T15:14:18.764489+02:00": {
    "2672": {
      "team": "FC Bayern München",
      "overall_form": "WDWWW",
      "bundesliga_form": "WWDWW",
      "overall_matches": [
        {
          "match_id": 16287047,
          "date": "2026-09-02T18:45:00+00:00",
          "timestamp": 1788374700,
          "competition": "DFB Pokal",
          "unique_tournament_id": 217,
          "home_team": "VfL Osnabrück",
          "home_team_id": 2581,
          "away_team": "FC Bayern München",
          "away_team_id": 2672,
          "home_score": 1,
          "away_score": 4,
          "result": "W"
        },
        {
          "match_id": 16434032,
          "date": "2026-09-05T16:30:00+00:00",
          "timestamp": 1788625800,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "FC Schalke 04",
          "home_team_id": 2530,
          "away_team": "FC Bayern München",
          "away_team_id": 2672,
          "home_score": 0,
          "away_score": 0,
          "result": "D"
        },
        {
          "match_id": 16938858,
          "date": "2026-09-10T19:00:00+00:00",
          "timestamp": 1789066800,
          "competition": "UEFA Champions League",
          "unique_tournament_id": 7,
          "home_team": "FC Bayern München",
          "home_team_id": 2672,
          "away_team": "Bodø/Glimt",
          "away_team_id": 656,
          "home_score": 5,
          "away_score": 0,
          "result": "W"
        },
        {
          "match_id": 16434041,
          "date": "2026-09-13T15:30:00+00:00",
          "timestamp": 1789313400,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "SV 07 Elversberg",
          "home_team_id": 2598,
          "away_team": "FC Bayern München",
          "away_team_id": 2672,
          "home_score": 1,
          "away_score": 2,
          "result": "W"
        },
        {
          "match_id": 16434038,
          "date": "2026-09-18T18:30:00+00:00",
          "timestamp": 1789756200,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "FC Bayern München",
          "home_team_id": 2672,
          "away_team": "1. FC Union Berlin",
          "away_team_id": 2547,
          "home_score": 7,
          "away_score": 0,
          "result": "W"
        }
      ],
      "bundesliga_matches": [
        {
          "match_id": 14065556,
          "date": "2026-05-16T13:30:00+00:00",
          "timestamp": 1778938200,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "FC Bayern München",
          "home_team_id": 2672,
          "away_team": "1. FC Köln",
          "away_team_id": 2671,
          "home_score": 5,
          "away_score": 1,
          "result": "W"
        },
        {
          "match_id": 16434087,
          "date": "2026-08-28T18:30:00+00:00",
          "timestamp": 1787941800,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "FC Bayern München",
          "home_team_id": 2672,
          "away_team": "VfB Stuttgart",
          "away_team_id": 2677,
          "home_score": 5,
          "away_score": 1,
          "result": "W"
        },
        {
          "match_id": 16434032,
          "date": "2026-09-05T16:30:00+00:00",
          "timestamp": 1788625800,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "FC Schalke 04",
          "home_team_id": 2530,
          "away_team": "FC Bayern München",
          "away_team_id": 2672,
          "home_score": 0,
          "away_score": 0,
          "result": "D"
        },
        {
          "match_id": 16434041,
          "date": "2026-09-13T15:30:00+00:00",
          "timestamp": 1789313400,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "SV 07 Elversberg",
          "home_team_id": 2598,
          "away_team": "FC Bayern München",
          "away_team_id": 2672,
          "home_score": 1,
          "away_score": 2,
          "result": "W"
        },
        {
          "match_id": 16434038,
          "date": "2026-09-18T18:30:00+00:00",
          "timestamp": 1789756200,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "FC Bayern München",
          "home_team_id": 2672,
          "away_team": "1. FC Union Berlin",
          "away_team_id": 2547,
          "home_score": 7,
          "away_score": 0,
          "result": "W"
        }
      ]
    },
    "2677": {
      "team": "VfB Stuttgart",
      "overall_form": "WLLWW",
      "bundesliga_form": "DLWLL",
      "overall_matches": [
        {
          "match_id": 16939028,
          "date": "2026-09-09T16:45:00+00:00",
          "timestamp": 1788972300,
          "competition": "UEFA Champions League",
          "unique_tournament_id": 7,
          "home_team": "VfB Stuttgart",
          "home_team_id": 2677,
          "away_team": "Viking FK",
          "away_team_id": 1164,
          "home_score": 3,
          "away_score": 1,
          "result": "W"
        },
        {
          "match_id": 16434035,
          "date": "2026-09-12T13:30:00+00:00",
          "timestamp": 1789219800,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "TSG Hoffenheim",
          "home_team_id": 2569,
          "away_team": "VfB Stuttgart",
          "away_team_id": 2677,
          "home_score": 2,
          "away_score": 1,
          "result": "L"
        },
        {
          "match_id": 16434034,
          "date": "2026-09-19T16:30:00+00:00",
          "timestamp": 1789835400,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "VfB Stuttgart",
          "home_team_id": 2677,
          "away_team": "Borussia Dortmund",
          "away_team_id": 2673,
          "home_score": 0,
          "away_score": 1,
          "result": "L"
        },
        {
          "match_id": 17157914,
          "date": "2026-09-25T14:30:00+00:00",
          "timestamp": 1790346600,
          "competition": "Club Friendly Games",
          "unique_tournament_id": 853,
          "home_team": "VfB Stuttgart",
          "home_team_id": 2677,
          "away_team": "1. FC Heidenheim",
          "away_team_id": 5885,
          "home_score": 3,
          "away_score": 0,
          "result": "W"
        },
        {
          "match_id": 17212342,
          "date": "2026-10-01T15:30:00+00:00",
          "timestamp": 1790868600,
          "competition": "Club Friendly Games",
          "unique_tournament_id": 853,
          "home_team": "VfB Stuttgart",
          "home_team_id": 2677,
          "away_team": "SpVgg Greuther Fürth",
          "away_team_id": 2551,
          "home_score": 5,
          "away_score": 0,
          "result": "W"
        }
      ],
      "bundesliga_matches": [
        {
          "match_id": 14065560,
          "date": "2026-05-16T13:30:00+00:00",
          "timestamp": 1778938200,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "Eintracht Frankfurt",
          "home_team_id": 2674,
          "away_team": "VfB Stuttgart",
          "away_team_id": 2677,
          "home_score": 2,
          "away_score": 2,
          "result": "D"
        },
        {
          "match_id": 16434087,
          "date": "2026-08-28T18:30:00+00:00",
          "timestamp": 1787941800,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "FC Bayern München",
          "home_team_id": 2672,
          "away_team": "VfB Stuttgart",
          "away_team_id": 2677,
          "home_score": 5,
          "away_score": 1,
          "result": "L"
        },
        {
          "match_id": 16434036,
          "date": "2026-09-04T18:30:00+00:00",
          "timestamp": 1788546600,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "VfB Stuttgart",
          "home_team_id": 2677,
          "away_team": "1. FC Köln",
          "away_team_id": 2671,
          "home_score": 4,
          "away_score": 1,
          "result": "W"
        },
        {
          "match_id": 16434035,
          "date": "2026-09-12T13:30:00+00:00",
          "timestamp": 1789219800,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "TSG Hoffenheim",
          "home_team_id": 2569,
          "away_team": "VfB Stuttgart",
          "away_team_id": 2677,
          "home_score": 2,
          "away_score": 1,
          "result": "L"
        },
        {
          "match_id": 16434034,
          "date": "2026-09-19T16:30:00+00:00",
          "timestamp": 1789835400,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "VfB Stuttgart",
          "home_team_id": 2677,
          "away_team": "Borussia Dortmund",
          "away_team_id": 2673,
          "home_score": 0,
          "away_score": 1,
          "result": "L"
        }
      ]
    },
    "2671": {
      "team": "1. FC Köln",
      "overall_form": "WLDLD",
      "bundesliga_form": "LWLDL",
      "overall_matches": [
        {
          "match_id": 16434022,
          "date": "2026-08-29T13:30:00+00:00",
          "timestamp": 1788010200,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "1. FC Köln",
          "home_team_id": 2671,
          "away_team": "TSG Hoffenheim",
          "away_team_id": 2569,
          "home_score": 3,
          "away_score": 2,
          "result": "W"
        },
        {
          "match_id": 16434036,
          "date": "2026-09-04T18:30:00+00:00",
          "timestamp": 1788546600,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "VfB Stuttgart",
          "home_team_id": 2677,
          "away_team": "1. FC Köln",
          "away_team_id": 2671,
          "home_score": 4,
          "away_score": 1,
          "result": "L"
        },
        {
          "match_id": 16434027,
          "date": "2026-09-12T16:30:00+00:00",
          "timestamp": 1789230600,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "1. FC Köln",
          "home_team_id": 2671,
          "away_team": "SV Werder Bremen",
          "away_team_id": 2534,
          "home_score": 1,
          "away_score": 1,
          "result": "D"
        },
        {
          "match_id": 16434048,
          "date": "2026-09-19T13:30:00+00:00",
          "timestamp": 1789824600,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "Hamburger SV",
          "home_team_id": 2676,
          "away_team": "1. FC Köln",
          "away_team_id": 2671,
          "home_score": 2,
          "away_score": 1,
          "result": "L"
        },
        {
          "match_id": 17213101,
          "date": "2026-10-03T12:00:00+00:00",
          "timestamp": 1791028800,
          "competition": "Club Friendly Games",
          "unique_tournament_id": 853,
          "home_team": "FC Viktoria Köln",
          "home_team_id": 53365,
          "away_team": "1. FC Köln",
          "away_team_id": 2671,
          "home_score": 2,
          "away_score": 2,
          "result": "D"
        }
      ],
      "bundesliga_matches": [
        {
          "match_id": 14065556,
          "date": "2026-05-16T13:30:00+00:00",
          "timestamp": 1778938200,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "FC Bayern München",
          "home_team_id": 2672,
          "away_team": "1. FC Köln",
          "away_team_id": 2671,
          "home_score": 5,
          "away_score": 1,
          "result": "L"
        },
        {
          "match_id": 16434022,
          "date": "2026-08-29T13:30:00+00:00",
          "timestamp": 1788010200,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "1. FC Köln",
          "home_team_id": 2671,
          "away_team": "TSG Hoffenheim",
          "away_team_id": 2569,
          "home_score": 3,
          "away_score": 2,
          "result": "W"
        },
        {
          "match_id": 16434036,
          "date": "2026-09-04T18:30:00+00:00",
          "timestamp": 1788546600,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "VfB Stuttgart",
          "home_team_id": 2677,
          "away_team": "1. FC Köln",
          "away_team_id": 2671,
          "home_score": 4,
          "away_score": 1,
          "result": "L"
        },
        {
          "match_id": 16434027,
          "date": "2026-09-12T16:30:00+00:00",
          "timestamp": 1789230600,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "1. FC Köln",
          "home_team_id": 2671,
          "away_team": "SV Werder Bremen",
          "away_team_id": 2534,
          "home_score": 1,
          "away_score": 1,
          "result": "D"
        },
        {
          "match_id": 16434048,
          "date": "2026-09-19T13:30:00+00:00",
          "timestamp": 1789824600,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "Hamburger SV",
          "home_team_id": 2676,
          "away_team": "1. FC Köln",
          "away_team_id": 2671,
          "home_score": 2,
          "away_score": 1,
          "result": "L"
        }
      ]
    },
    "2569": {
      "team": "TSG Hoffenheim",
      "overall_form": "LLWLL",
      "bundesliga_form": "LLLWL",
      "overall_matches": [
        {
          "match_id": 16434022,
          "date": "2026-08-29T13:30:00+00:00",
          "timestamp": 1788010200,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "1. FC Köln",
          "home_team_id": 2671,
          "away_team": "TSG Hoffenheim",
          "away_team_id": 2569,
          "home_score": 3,
          "away_score": 2,
          "result": "L"
        },
        {
          "match_id": 16434019,
          "date": "2026-09-05T13:30:00+00:00",
          "timestamp": 1788615000,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "TSG Hoffenheim",
          "home_team_id": 2569,
          "away_team": "Borussia Dortmund",
          "away_team_id": 2673,
          "home_score": 2,
          "away_score": 3,
          "result": "L"
        },
        {
          "match_id": 16434035,
          "date": "2026-09-12T13:30:00+00:00",
          "timestamp": 1789219800,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "TSG Hoffenheim",
          "home_team_id": 2569,
          "away_team": "VfB Stuttgart",
          "away_team_id": 2677,
          "home_score": 2,
          "away_score": 1,
          "result": "W"
        },
        {
          "match_id": 16945561,
          "date": "2026-09-17T16:45:00+00:00",
          "timestamp": 1789663500,
          "competition": "UEFA Europa League",
          "unique_tournament_id": 679,
          "home_team": "OFI Crete",
          "home_team_id": 3241,
          "away_team": "TSG Hoffenheim",
          "away_team_id": 2569,
          "home_score": 2,
          "away_score": 0,
          "result": "L"
        },
        {
          "match_id": 16434052,
          "date": "2026-09-20T17:30:00+00:00",
          "timestamp": 1789925400,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "SC Paderborn 07",
          "home_team_id": 2561,
          "away_team": "TSG Hoffenheim",
          "away_team_id": 2569,
          "home_score": 3,
          "away_score": 1,
          "result": "L"
        }
      ],
      "bundesliga_matches": [
        {
          "match_id": 14065559,
          "date": "2026-05-16T13:30:00+00:00",
          "timestamp": 1778938200,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "Borussia M'gladbach",
          "home_team_id": 2527,
          "away_team": "TSG Hoffenheim",
          "away_team_id": 2569,
          "home_score": 4,
          "away_score": 0,
          "result": "L"
        },
        {
          "match_id": 16434022,
          "date": "2026-08-29T13:30:00+00:00",
          "timestamp": 1788010200,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "1. FC Köln",
          "home_team_id": 2671,
          "away_team": "TSG Hoffenheim",
          "away_team_id": 2569,
          "home_score": 3,
          "away_score": 2,
          "result": "L"
        },
        {
          "match_id": 16434019,
          "date": "2026-09-05T13:30:00+00:00",
          "timestamp": 1788615000,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "TSG Hoffenheim",
          "home_team_id": 2569,
          "away_team": "Borussia Dortmund",
          "away_team_id": 2673,
          "home_score": 2,
          "away_score": 3,
          "result": "L"
        },
        {
          "match_id": 16434035,
          "date": "2026-09-12T13:30:00+00:00",
          "timestamp": 1789219800,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "TSG Hoffenheim",
          "home_team_id": 2569,
          "away_team": "VfB Stuttgart",
          "away_team_id": 2677,
          "home_score": 2,
          "away_score": 1,
          "result": "W"
        },
        {
          "match_id": 16434052,
          "date": "2026-09-20T17:30:00+00:00",
          "timestamp": 1789925400,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "SC Paderborn 07",
          "home_team_id": 2561,
          "away_team": "TSG Hoffenheim",
          "away_team_id": 2569,
          "home_score": 3,
          "away_score": 1,
          "result": "L"
        }
      ]
    },
    "2547": {
      "team": "1. FC Union Berlin",
      "overall_form": "DLLLW",
      "bundesliga_form": "WDLLL",
      "overall_matches": [
        {
          "match_id": 16434026,
          "date": "2026-08-29T13:30:00+00:00",
          "timestamp": 1788010200,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "1. FC Union Berlin",
          "home_team_id": 2547,
          "away_team": "Eintracht Frankfurt",
          "away_team_id": 2674,
          "home_score": 3,
          "away_score": 3,
          "result": "D"
        },
        {
          "match_id": 16434042,
          "date": "2026-09-05T13:30:00+00:00",
          "timestamp": 1788615000,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "Bayer 04 Leverkusen",
          "home_team_id": 2681,
          "away_team": "1. FC Union Berlin",
          "away_team_id": 2547,
          "home_score": 4,
          "away_score": 0,
          "result": "L"
        },
        {
          "match_id": 16434045,
          "date": "2026-09-11T18:30:00+00:00",
          "timestamp": 1789151400,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,
          "home_team": "1. FC Union Berlin",
          "home_team_id": 2547,
          "away_team": "FC Schalke 04",
          "away_team_id": 2530,
          "home_score": 1,
          "away_score": 3,
          "result": "L"
        },
        {
          "match_id": 16434038,
          "date": "2026-09-18T18:30:00+00:00",
          "timestamp": 1789756200,
          "competition": "Bundesliga",
          "unique_tournament_id": 35,

In [13]:
# 12. Close Chrome
if driver is not None:
    # Handle expected failures with a clear, actionable message.
    try:
        driver.quit()
        print("Chrome driver closed.")
    except Exception as exc:
        print(f"Chrome driver shutdown warning: {exc}")
    finally:
        driver = None
else:
    print("Chrome driver is already closed or was not initialized.")

Chrome driver closed.

In [14]:
from project_paths import prune_timestamped_outputs

removed_outputs = prune_timestamped_outputs()
print(f"Pruned {len(removed_outputs)} expired timestamped output(s).")

Pruned 16 expired timestamped output(s).